version: "2"
linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - misspell
    - revive
  exclusions:
    paths:
      - sdk
      - examples
  settings:
    revive:
      rules:
        - name: exported
          arguments:
            - disableStutteringCheck
formatters:
  enable:
    - gofumpt
  exclusions:
    paths:
      - sdk
      - examples
