// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
	"regexp"
	"strconv"
)

// ProtocolStaticTableRoute6Interface manages a VyOS ProtocolStaticTableRoute6Interface configuration.
type ProtocolStaticTableRoute6Interface struct{}

// ProtocolStaticTableRoute6InterfaceArgs defines the inputs for the ProtocolStaticTableRoute6Interface resource.
type ProtocolStaticTableRoute6InterfaceArgs struct {
	Route6Name string  `pulumi:"route6Name"`
	Name       string  `pulumi:"name"`
	Disable    *bool   `pulumi:"disable,optional"`
	Distance   *int    `pulumi:"distance,optional"`
	Segments   *string `pulumi:"segments,optional"`
	VRF        *string `pulumi:"vrf,optional"`
}

// ProtocolStaticTableRoute6InterfaceState defines the outputs for the ProtocolStaticTableRoute6Interface resource.
type ProtocolStaticTableRoute6InterfaceState struct {
	ProtocolStaticTableRoute6InterfaceArgs
}

// Annotate provides schema metadata for the resource.
func (*ProtocolStaticTableRoute6Interface) Annotate(a infer.Annotator) {
	a.Describe(new(ProtocolStaticTableRoute6Interface), "Manages a VyOS IPv6 gateway interface name.")
}

// Annotate provides schema metadata for the inputs.
func (args *ProtocolStaticTableRoute6InterfaceArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.Route6Name, "Parent tag node key")
	a.Describe(&args.Name, "IPv6 gateway interface name")
	a.Describe(&args.Disable, "Disable instance")
	a.Describe(&args.Distance, "Distance for this route")
	a.Describe(&args.Segments, "SRv6 segments")
	a.Describe(&args.VRF, "VRF to leak route")
}

var protocolStaticTableRoute6InterfaceVRFRe = regexp.MustCompile(`^(?:` + "(default)" + `)$`)

// Check validates the ProtocolStaticTableRoute6Interface inputs.
func (ProtocolStaticTableRoute6Interface) Check(
	ctx context.Context,
	req infer.CheckRequest,
) (infer.CheckResponse[ProtocolStaticTableRoute6InterfaceArgs], error) {
	inputs, failures, err := infer.DefaultCheck[ProtocolStaticTableRoute6InterfaceArgs](ctx, req.NewInputs)
	if err != nil {
		return infer.CheckResponse[ProtocolStaticTableRoute6InterfaceArgs]{}, err
	}
	if inputs.Distance != nil {
		if f := checkIntRange(int64(*inputs.Distance), 1, 255, "distance", ""); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.VRF != nil {
		if f := checkRegex(*inputs.VRF, protocolStaticTableRoute6InterfaceVRFRe, "vrf", ""); f != nil {
			failures = append(failures, *f)
		}
	}

	return infer.CheckResponse[ProtocolStaticTableRoute6InterfaceArgs]{Inputs: inputs, Failures: failures}, nil
}

func protocolStaticTableRoute6InterfaceBasePath(route6Name, name string) []any {
	return []any{"protocols", "static", "table", "route6", route6Name, "interface", name}
}

// Create sets up the ProtocolStaticTableRoute6Interface on VyOS.
func (ProtocolStaticTableRoute6Interface) Create(
	ctx context.Context,
	req infer.CreateRequest[ProtocolStaticTableRoute6InterfaceArgs],
) (infer.CreateResponse[ProtocolStaticTableRoute6InterfaceState], error) {
	if req.DryRun {
		return infer.CreateResponse[ProtocolStaticTableRoute6InterfaceState]{
			ID:     req.Inputs.Name,
			Output: ProtocolStaticTableRoute6InterfaceState{ProtocolStaticTableRoute6InterfaceArgs: req.Inputs},
		}, nil
	}

	ops := buildProtocolStaticTableRoute6InterfaceOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[ProtocolStaticTableRoute6InterfaceState]{},
			fmt.Errorf("configure ProtocolStaticTableRoute6Interface %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[ProtocolStaticTableRoute6InterfaceState]{
		ID:     req.Inputs.Name,
		Output: ProtocolStaticTableRoute6InterfaceState{ProtocolStaticTableRoute6InterfaceArgs: req.Inputs},
	}, nil
}

// Read fetches the current ProtocolStaticTableRoute6Interface config from VyOS.
func (ProtocolStaticTableRoute6Interface) Read(
	ctx context.Context,
	req infer.ReadRequest[ProtocolStaticTableRoute6InterfaceArgs, ProtocolStaticTableRoute6InterfaceState],
) (infer.ReadResponse[ProtocolStaticTableRoute6InterfaceArgs, ProtocolStaticTableRoute6InterfaceState], error) {
	client := getClient(ctx)
	base := protocolStaticTableRoute6InterfaceBasePath(req.State.Route6Name, req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := ProtocolStaticTableRoute6InterfaceArgs{Route6Name: req.State.Route6Name, Name: req.State.Name}
			state := ProtocolStaticTableRoute6InterfaceState{ProtocolStaticTableRoute6InterfaceArgs: args}
			return infer.ReadResponse[ProtocolStaticTableRoute6InterfaceArgs, ProtocolStaticTableRoute6InterfaceState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[ProtocolStaticTableRoute6InterfaceArgs, ProtocolStaticTableRoute6InterfaceState]{},
			fmt.Errorf("read ProtocolStaticTableRoute6Interface %s: %w", req.State.Name, err)
	}

	args, err := parseProtocolStaticTableRoute6InterfaceConfig(req.State.Route6Name, req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[ProtocolStaticTableRoute6InterfaceArgs, ProtocolStaticTableRoute6InterfaceState]{},
			fmt.Errorf("parse ProtocolStaticTableRoute6Interface %s config: %w", req.State.Name, err)
	}

	state := ProtocolStaticTableRoute6InterfaceState{ProtocolStaticTableRoute6InterfaceArgs: args}
	return infer.ReadResponse[ProtocolStaticTableRoute6InterfaceArgs, ProtocolStaticTableRoute6InterfaceState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing ProtocolStaticTableRoute6Interface configuration.
func (ProtocolStaticTableRoute6Interface) Update(
	ctx context.Context,
	req infer.UpdateRequest[ProtocolStaticTableRoute6InterfaceArgs, ProtocolStaticTableRoute6InterfaceState],
) (infer.UpdateResponse[ProtocolStaticTableRoute6InterfaceState], error) {
	if req.DryRun {
		return infer.UpdateResponse[ProtocolStaticTableRoute6InterfaceState]{
			Output: ProtocolStaticTableRoute6InterfaceState{ProtocolStaticTableRoute6InterfaceArgs: req.Inputs},
		}, nil
	}

	ops := buildProtocolStaticTableRoute6InterfaceUpdateOps(req.State.ProtocolStaticTableRoute6InterfaceArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[ProtocolStaticTableRoute6InterfaceState]{},
				fmt.Errorf("update ProtocolStaticTableRoute6Interface %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[ProtocolStaticTableRoute6InterfaceState]{
		Output: ProtocolStaticTableRoute6InterfaceState{ProtocolStaticTableRoute6InterfaceArgs: req.Inputs},
	}, nil
}

// Delete removes the ProtocolStaticTableRoute6Interface configuration from VyOS.
func (ProtocolStaticTableRoute6Interface) Delete(
	ctx context.Context,
	req infer.DeleteRequest[ProtocolStaticTableRoute6InterfaceState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := protocolStaticTableRoute6InterfaceBasePath(req.State.Route6Name, req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete ProtocolStaticTableRoute6Interface %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildProtocolStaticTableRoute6InterfaceOps builds set operations for all non-nil fields.
func buildProtocolStaticTableRoute6InterfaceOps(args ProtocolStaticTableRoute6InterfaceArgs) []vyosclient.Operation {
	base := protocolStaticTableRoute6InterfaceBasePath(args.Route6Name, args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}

	if args.Disable != nil && *args.Disable {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "disable")})
	}

	if args.Distance != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "distance"), Value: strconv.Itoa(*args.Distance)})
	}

	if args.Segments != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "segments"), Value: *args.Segments})
	}

	if args.VRF != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "vrf"), Value: *args.VRF})
	}

	return ops
}

// buildProtocolStaticTableRoute6InterfaceUpdateOps computes the diff between previous and current state.
func buildProtocolStaticTableRoute6InterfaceUpdateOps(prev, cur ProtocolStaticTableRoute6InterfaceArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	base := protocolStaticTableRoute6InterfaceBasePath(cur.Route6Name, cur.Name)

	ops = append(ops, diffBoolField(base, []string{"disable"}, prev.Disable, cur.Disable)...)

	ops = append(ops, diffIntField(base, []string{"distance"}, prev.Distance, cur.Distance)...)

	ops = append(ops, diffStringField(base, []string{"segments"}, prev.Segments, cur.Segments)...)

	ops = append(ops, diffStringField(base, []string{"vrf"}, prev.VRF, cur.VRF)...)

	return ops
}

// parseProtocolStaticTableRoute6InterfaceConfig unmarshals VyOS ShowConfig JSON.
func parseProtocolStaticTableRoute6InterfaceConfig(route6Name, name string, data json.RawMessage) (ProtocolStaticTableRoute6InterfaceArgs, error) {
	args := ProtocolStaticTableRoute6InterfaceArgs{
		Route6Name: route6Name,
		Name:       name,
	}

	if _, ok := getNestedValue(data, []string{"disable"}); ok {
		t := true
		args.Disable = &t
	}

	if v, ok := getNestedValue(data, []string{"distance"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return ProtocolStaticTableRoute6InterfaceArgs{}, fmt.Errorf("parse distance: %w", err)
		}
		args.Distance = &n
	}

	if v, ok := getNestedValue(data, []string{"segments"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return ProtocolStaticTableRoute6InterfaceArgs{}, fmt.Errorf("parse segments: %w", err)
		}
		args.Segments = &s
	}

	if v, ok := getNestedValue(data, []string{"vrf"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return ProtocolStaticTableRoute6InterfaceArgs{}, fmt.Errorf("parse vrf: %w", err)
		}
		args.VRF = &s
	}

	return args, nil
}
