// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
)

// ProtocolBGPNeighborLocalAs manages a VyOS ProtocolBGPNeighborLocalAs configuration.
type ProtocolBGPNeighborLocalAs struct{}

// ProtocolBGPNeighborLocalAsArgs defines the inputs for the ProtocolBGPNeighborLocalAs resource.
type ProtocolBGPNeighborLocalAsArgs struct {
	NeighborName       string `pulumi:"neighborName"`
	Name               string `pulumi:"name"`
	NoPrependReplaceAs *bool  `pulumi:"noPrependReplaceAs,optional"`
}

// ProtocolBGPNeighborLocalAsState defines the outputs for the ProtocolBGPNeighborLocalAs resource.
type ProtocolBGPNeighborLocalAsState struct {
	ProtocolBGPNeighborLocalAsArgs
}

// Annotate provides schema metadata for the resource.
func (*ProtocolBGPNeighborLocalAs) Annotate(a infer.Annotator) {
	a.Describe(new(ProtocolBGPNeighborLocalAs), "Manages a VyOS Specify alternate ASN for this BGP process.")
}

// Annotate provides schema metadata for the inputs.
func (args *ProtocolBGPNeighborLocalAsArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.NeighborName, "Parent tag node key")
	a.Describe(&args.Name, "Specify alternate ASN for this BGP process")
	a.Describe(&args.NoPrependReplaceAs, "Prepend only local-as from/to updates for eBGP peers")
}

func protocolBGPNeighborLocalAsBasePath(neighborName, name string) []any {
	return []any{"protocols", "bgp", "neighbor", neighborName, "local-as", name}
}

// Create sets up the ProtocolBGPNeighborLocalAs on VyOS.
func (ProtocolBGPNeighborLocalAs) Create(
	ctx context.Context,
	req infer.CreateRequest[ProtocolBGPNeighborLocalAsArgs],
) (infer.CreateResponse[ProtocolBGPNeighborLocalAsState], error) {
	if req.DryRun {
		return infer.CreateResponse[ProtocolBGPNeighborLocalAsState]{
			ID:     req.Inputs.Name,
			Output: ProtocolBGPNeighborLocalAsState{ProtocolBGPNeighborLocalAsArgs: req.Inputs},
		}, nil
	}

	ops := buildProtocolBGPNeighborLocalAsOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[ProtocolBGPNeighborLocalAsState]{},
			fmt.Errorf("configure ProtocolBGPNeighborLocalAs %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[ProtocolBGPNeighborLocalAsState]{
		ID:     req.Inputs.Name,
		Output: ProtocolBGPNeighborLocalAsState{ProtocolBGPNeighborLocalAsArgs: req.Inputs},
	}, nil
}

// Read fetches the current ProtocolBGPNeighborLocalAs config from VyOS.
func (ProtocolBGPNeighborLocalAs) Read(
	ctx context.Context,
	req infer.ReadRequest[ProtocolBGPNeighborLocalAsArgs, ProtocolBGPNeighborLocalAsState],
) (infer.ReadResponse[ProtocolBGPNeighborLocalAsArgs, ProtocolBGPNeighborLocalAsState], error) {
	client := getClient(ctx)
	base := protocolBGPNeighborLocalAsBasePath(req.State.NeighborName, req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := ProtocolBGPNeighborLocalAsArgs{NeighborName: req.State.NeighborName, Name: req.State.Name}
			state := ProtocolBGPNeighborLocalAsState{ProtocolBGPNeighborLocalAsArgs: args}
			return infer.ReadResponse[ProtocolBGPNeighborLocalAsArgs, ProtocolBGPNeighborLocalAsState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[ProtocolBGPNeighborLocalAsArgs, ProtocolBGPNeighborLocalAsState]{},
			fmt.Errorf("read ProtocolBGPNeighborLocalAs %s: %w", req.State.Name, err)
	}

	args, err := parseProtocolBGPNeighborLocalAsConfig(req.State.NeighborName, req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[ProtocolBGPNeighborLocalAsArgs, ProtocolBGPNeighborLocalAsState]{},
			fmt.Errorf("parse ProtocolBGPNeighborLocalAs %s config: %w", req.State.Name, err)
	}

	state := ProtocolBGPNeighborLocalAsState{ProtocolBGPNeighborLocalAsArgs: args}
	return infer.ReadResponse[ProtocolBGPNeighborLocalAsArgs, ProtocolBGPNeighborLocalAsState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing ProtocolBGPNeighborLocalAs configuration.
func (ProtocolBGPNeighborLocalAs) Update(
	ctx context.Context,
	req infer.UpdateRequest[ProtocolBGPNeighborLocalAsArgs, ProtocolBGPNeighborLocalAsState],
) (infer.UpdateResponse[ProtocolBGPNeighborLocalAsState], error) {
	if req.DryRun {
		return infer.UpdateResponse[ProtocolBGPNeighborLocalAsState]{
			Output: ProtocolBGPNeighborLocalAsState{ProtocolBGPNeighborLocalAsArgs: req.Inputs},
		}, nil
	}

	ops := buildProtocolBGPNeighborLocalAsUpdateOps(req.State.ProtocolBGPNeighborLocalAsArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[ProtocolBGPNeighborLocalAsState]{},
				fmt.Errorf("update ProtocolBGPNeighborLocalAs %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[ProtocolBGPNeighborLocalAsState]{
		Output: ProtocolBGPNeighborLocalAsState{ProtocolBGPNeighborLocalAsArgs: req.Inputs},
	}, nil
}

// Delete removes the ProtocolBGPNeighborLocalAs configuration from VyOS.
func (ProtocolBGPNeighborLocalAs) Delete(
	ctx context.Context,
	req infer.DeleteRequest[ProtocolBGPNeighborLocalAsState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := protocolBGPNeighborLocalAsBasePath(req.State.NeighborName, req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete ProtocolBGPNeighborLocalAs %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildProtocolBGPNeighborLocalAsOps builds set operations for all non-nil fields.
func buildProtocolBGPNeighborLocalAsOps(args ProtocolBGPNeighborLocalAsArgs) []vyosclient.Operation {
	base := protocolBGPNeighborLocalAsBasePath(args.NeighborName, args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}

	if args.NoPrependReplaceAs != nil && *args.NoPrependReplaceAs {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "no-prepend", "replace-as")})
	}

	return ops
}

// buildProtocolBGPNeighborLocalAsUpdateOps computes the diff between previous and current state.
func buildProtocolBGPNeighborLocalAsUpdateOps(prev, cur ProtocolBGPNeighborLocalAsArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	base := protocolBGPNeighborLocalAsBasePath(cur.NeighborName, cur.Name)

	ops = append(ops, diffBoolField(base, []string{"no-prepend", "replace-as"}, prev.NoPrependReplaceAs, cur.NoPrependReplaceAs)...)

	return ops
}

// parseProtocolBGPNeighborLocalAsConfig unmarshals VyOS ShowConfig JSON.
func parseProtocolBGPNeighborLocalAsConfig(neighborName, name string, data json.RawMessage) (ProtocolBGPNeighborLocalAsArgs, error) {
	args := ProtocolBGPNeighborLocalAsArgs{
		NeighborName: neighborName,
		Name:         name,
	}

	if _, ok := getNestedValue(data, []string{"no-prepend", "replace-as"}); ok {
		t := true
		args.NoPrependReplaceAs = &t
	}

	return args, nil
}
