// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
	"regexp"
)

// ServiceWebproxyURLFilteringSquidguardTimePeriodDays manages a VyOS ServiceWebproxyURLFilteringSquidguardTimePeriodDays configuration.
type ServiceWebproxyURLFilteringSquidguardTimePeriodDays struct{}

// ServiceWebproxyURLFilteringSquidguardTimePeriodDaysArgs defines the inputs for the ServiceWebproxyURLFilteringSquidguardTimePeriodDays resource.
type ServiceWebproxyURLFilteringSquidguardTimePeriodDaysArgs struct {
	TimePeriodName string  `pulumi:"timePeriodName"`
	Name           string  `pulumi:"name"`
	Time           *string `pulumi:"time,optional"`
}

// ServiceWebproxyURLFilteringSquidguardTimePeriodDaysState defines the outputs for the ServiceWebproxyURLFilteringSquidguardTimePeriodDays resource.
type ServiceWebproxyURLFilteringSquidguardTimePeriodDaysState struct {
	ServiceWebproxyURLFilteringSquidguardTimePeriodDaysArgs
}

// Annotate provides schema metadata for the resource.
func (*ServiceWebproxyURLFilteringSquidguardTimePeriodDays) Annotate(a infer.Annotator) {
	a.Describe(new(ServiceWebproxyURLFilteringSquidguardTimePeriodDays), "Manages a VyOS Time-period days.")
}

// Annotate provides schema metadata for the inputs.
func (args *ServiceWebproxyURLFilteringSquidguardTimePeriodDaysArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.TimePeriodName, "Parent tag node key")
	a.Describe(&args.Name, "Time-period days")
	a.Describe(&args.Time, "Time for time-period")
}

var serviceWebproxyURLFilteringSquidguardTimePeriodDaysTimeRe = regexp.MustCompile(`^(?:` + "(\\d\\d:\\d\\d)-(\\d\\d:\\d\\d)" + `)$`)

// Check validates the ServiceWebproxyURLFilteringSquidguardTimePeriodDays inputs.
func (ServiceWebproxyURLFilteringSquidguardTimePeriodDays) Check(
	ctx context.Context,
	req infer.CheckRequest,
) (infer.CheckResponse[ServiceWebproxyURLFilteringSquidguardTimePeriodDaysArgs], error) {
	inputs, failures, err := infer.DefaultCheck[ServiceWebproxyURLFilteringSquidguardTimePeriodDaysArgs](ctx, req.NewInputs)
	if err != nil {
		return infer.CheckResponse[ServiceWebproxyURLFilteringSquidguardTimePeriodDaysArgs]{}, err
	}
	if inputs.Time != nil {
		if f := checkRegex(*inputs.Time, serviceWebproxyURLFilteringSquidguardTimePeriodDaysTimeRe, "time", "Expected time format hh:mm - hh:mm in 24hr time"); f != nil {
			failures = append(failures, *f)
		}
	}

	return infer.CheckResponse[ServiceWebproxyURLFilteringSquidguardTimePeriodDaysArgs]{Inputs: inputs, Failures: failures}, nil
}

func serviceWebproxyURLFilteringSquidguardTimePeriodDaysBasePath(timePeriodName, name string) []any {
	return []any{"service", "webproxy", "url-filtering", "squidguard", "time-period", timePeriodName, "days", name}
}

// Create sets up the ServiceWebproxyURLFilteringSquidguardTimePeriodDays on VyOS.
func (ServiceWebproxyURLFilteringSquidguardTimePeriodDays) Create(
	ctx context.Context,
	req infer.CreateRequest[ServiceWebproxyURLFilteringSquidguardTimePeriodDaysArgs],
) (infer.CreateResponse[ServiceWebproxyURLFilteringSquidguardTimePeriodDaysState], error) {
	if req.DryRun {
		return infer.CreateResponse[ServiceWebproxyURLFilteringSquidguardTimePeriodDaysState]{
			ID:     req.Inputs.Name,
			Output: ServiceWebproxyURLFilteringSquidguardTimePeriodDaysState{ServiceWebproxyURLFilteringSquidguardTimePeriodDaysArgs: req.Inputs},
		}, nil
	}

	ops := buildServiceWebproxyURLFilteringSquidguardTimePeriodDaysOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[ServiceWebproxyURLFilteringSquidguardTimePeriodDaysState]{},
			fmt.Errorf("configure ServiceWebproxyURLFilteringSquidguardTimePeriodDays %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[ServiceWebproxyURLFilteringSquidguardTimePeriodDaysState]{
		ID:     req.Inputs.Name,
		Output: ServiceWebproxyURLFilteringSquidguardTimePeriodDaysState{ServiceWebproxyURLFilteringSquidguardTimePeriodDaysArgs: req.Inputs},
	}, nil
}

// Read fetches the current ServiceWebproxyURLFilteringSquidguardTimePeriodDays config from VyOS.
func (ServiceWebproxyURLFilteringSquidguardTimePeriodDays) Read(
	ctx context.Context,
	req infer.ReadRequest[ServiceWebproxyURLFilteringSquidguardTimePeriodDaysArgs, ServiceWebproxyURLFilteringSquidguardTimePeriodDaysState],
) (infer.ReadResponse[ServiceWebproxyURLFilteringSquidguardTimePeriodDaysArgs, ServiceWebproxyURLFilteringSquidguardTimePeriodDaysState], error) {
	client := getClient(ctx)
	base := serviceWebproxyURLFilteringSquidguardTimePeriodDaysBasePath(req.State.TimePeriodName, req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := ServiceWebproxyURLFilteringSquidguardTimePeriodDaysArgs{TimePeriodName: req.State.TimePeriodName, Name: req.State.Name}
			state := ServiceWebproxyURLFilteringSquidguardTimePeriodDaysState{ServiceWebproxyURLFilteringSquidguardTimePeriodDaysArgs: args}
			return infer.ReadResponse[ServiceWebproxyURLFilteringSquidguardTimePeriodDaysArgs, ServiceWebproxyURLFilteringSquidguardTimePeriodDaysState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[ServiceWebproxyURLFilteringSquidguardTimePeriodDaysArgs, ServiceWebproxyURLFilteringSquidguardTimePeriodDaysState]{},
			fmt.Errorf("read ServiceWebproxyURLFilteringSquidguardTimePeriodDays %s: %w", req.State.Name, err)
	}

	args, err := parseServiceWebproxyURLFilteringSquidguardTimePeriodDaysConfig(req.State.TimePeriodName, req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[ServiceWebproxyURLFilteringSquidguardTimePeriodDaysArgs, ServiceWebproxyURLFilteringSquidguardTimePeriodDaysState]{},
			fmt.Errorf("parse ServiceWebproxyURLFilteringSquidguardTimePeriodDays %s config: %w", req.State.Name, err)
	}

	state := ServiceWebproxyURLFilteringSquidguardTimePeriodDaysState{ServiceWebproxyURLFilteringSquidguardTimePeriodDaysArgs: args}
	return infer.ReadResponse[ServiceWebproxyURLFilteringSquidguardTimePeriodDaysArgs, ServiceWebproxyURLFilteringSquidguardTimePeriodDaysState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing ServiceWebproxyURLFilteringSquidguardTimePeriodDays configuration.
func (ServiceWebproxyURLFilteringSquidguardTimePeriodDays) Update(
	ctx context.Context,
	req infer.UpdateRequest[ServiceWebproxyURLFilteringSquidguardTimePeriodDaysArgs, ServiceWebproxyURLFilteringSquidguardTimePeriodDaysState],
) (infer.UpdateResponse[ServiceWebproxyURLFilteringSquidguardTimePeriodDaysState], error) {
	if req.DryRun {
		return infer.UpdateResponse[ServiceWebproxyURLFilteringSquidguardTimePeriodDaysState]{
			Output: ServiceWebproxyURLFilteringSquidguardTimePeriodDaysState{ServiceWebproxyURLFilteringSquidguardTimePeriodDaysArgs: req.Inputs},
		}, nil
	}

	ops := buildServiceWebproxyURLFilteringSquidguardTimePeriodDaysUpdateOps(req.State.ServiceWebproxyURLFilteringSquidguardTimePeriodDaysArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[ServiceWebproxyURLFilteringSquidguardTimePeriodDaysState]{},
				fmt.Errorf("update ServiceWebproxyURLFilteringSquidguardTimePeriodDays %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[ServiceWebproxyURLFilteringSquidguardTimePeriodDaysState]{
		Output: ServiceWebproxyURLFilteringSquidguardTimePeriodDaysState{ServiceWebproxyURLFilteringSquidguardTimePeriodDaysArgs: req.Inputs},
	}, nil
}

// Delete removes the ServiceWebproxyURLFilteringSquidguardTimePeriodDays configuration from VyOS.
func (ServiceWebproxyURLFilteringSquidguardTimePeriodDays) Delete(
	ctx context.Context,
	req infer.DeleteRequest[ServiceWebproxyURLFilteringSquidguardTimePeriodDaysState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := serviceWebproxyURLFilteringSquidguardTimePeriodDaysBasePath(req.State.TimePeriodName, req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete ServiceWebproxyURLFilteringSquidguardTimePeriodDays %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildServiceWebproxyURLFilteringSquidguardTimePeriodDaysOps builds set operations for all non-nil fields.
func buildServiceWebproxyURLFilteringSquidguardTimePeriodDaysOps(args ServiceWebproxyURLFilteringSquidguardTimePeriodDaysArgs) []vyosclient.Operation {
	base := serviceWebproxyURLFilteringSquidguardTimePeriodDaysBasePath(args.TimePeriodName, args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}

	if args.Time != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "time"), Value: *args.Time})
	}

	return ops
}

// buildServiceWebproxyURLFilteringSquidguardTimePeriodDaysUpdateOps computes the diff between previous and current state.
func buildServiceWebproxyURLFilteringSquidguardTimePeriodDaysUpdateOps(prev, cur ServiceWebproxyURLFilteringSquidguardTimePeriodDaysArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	base := serviceWebproxyURLFilteringSquidguardTimePeriodDaysBasePath(cur.TimePeriodName, cur.Name)

	ops = append(ops, diffStringField(base, []string{"time"}, prev.Time, cur.Time)...)

	return ops
}

// parseServiceWebproxyURLFilteringSquidguardTimePeriodDaysConfig unmarshals VyOS ShowConfig JSON.
func parseServiceWebproxyURLFilteringSquidguardTimePeriodDaysConfig(timePeriodName, name string, data json.RawMessage) (ServiceWebproxyURLFilteringSquidguardTimePeriodDaysArgs, error) {
	args := ServiceWebproxyURLFilteringSquidguardTimePeriodDaysArgs{
		TimePeriodName: timePeriodName,
		Name:           name,
	}

	if v, ok := getNestedValue(data, []string{"time"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return ServiceWebproxyURLFilteringSquidguardTimePeriodDaysArgs{}, fmt.Errorf("parse time: %w", err)
		}
		args.Time = &s
	}

	return args, nil
}
