// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
	"strconv"
)

// InterfaceEthernetVifPd manages a VyOS InterfaceEthernetVifPd configuration.
type InterfaceEthernetVifPd struct{}

// InterfaceEthernetVifPdArgs defines the inputs for the InterfaceEthernetVifPd resource.
type InterfaceEthernetVifPdArgs struct {
	VifName string `pulumi:"vifName"`
	Name    string `pulumi:"name"`
	Length  *int   `pulumi:"length,optional"`
}

// InterfaceEthernetVifPdState defines the outputs for the InterfaceEthernetVifPd resource.
type InterfaceEthernetVifPdState struct {
	InterfaceEthernetVifPdArgs
}

// Annotate provides schema metadata for the resource.
func (*InterfaceEthernetVifPd) Annotate(a infer.Annotator) {
	a.Describe(new(InterfaceEthernetVifPd), "Manages a VyOS DHCPv6 prefix delegation interface statement.")
}

// Annotate provides schema metadata for the inputs.
func (args *InterfaceEthernetVifPdArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.VifName, "Parent tag node key")
	a.Describe(&args.Name, "DHCPv6 prefix delegation interface statement")
	a.Describe(&args.Length, "Request IPv6 prefix length from peer")
}

// Check validates the InterfaceEthernetVifPd inputs.
func (InterfaceEthernetVifPd) Check(
	ctx context.Context,
	req infer.CheckRequest,
) (infer.CheckResponse[InterfaceEthernetVifPdArgs], error) {
	inputs, failures, err := infer.DefaultCheck[InterfaceEthernetVifPdArgs](ctx, req.NewInputs)
	if err != nil {
		return infer.CheckResponse[InterfaceEthernetVifPdArgs]{}, err
	}
	if inputs.Length != nil {
		if f := checkIntRange(int64(*inputs.Length), 32, 64, "length", ""); f != nil {
			failures = append(failures, *f)
		}
	}

	return infer.CheckResponse[InterfaceEthernetVifPdArgs]{Inputs: inputs, Failures: failures}, nil
}

func interfaceEthernetVifPdBasePath(vifName, name string) []any {
	return []any{"interfaces", "ethernet", "vif", vifName, "pd", name}
}

// Create sets up the InterfaceEthernetVifPd on VyOS.
func (InterfaceEthernetVifPd) Create(
	ctx context.Context,
	req infer.CreateRequest[InterfaceEthernetVifPdArgs],
) (infer.CreateResponse[InterfaceEthernetVifPdState], error) {
	if req.DryRun {
		return infer.CreateResponse[InterfaceEthernetVifPdState]{
			ID:     req.Inputs.Name,
			Output: InterfaceEthernetVifPdState{InterfaceEthernetVifPdArgs: req.Inputs},
		}, nil
	}

	ops := buildInterfaceEthernetVifPdOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[InterfaceEthernetVifPdState]{},
			fmt.Errorf("configure InterfaceEthernetVifPd %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[InterfaceEthernetVifPdState]{
		ID:     req.Inputs.Name,
		Output: InterfaceEthernetVifPdState{InterfaceEthernetVifPdArgs: req.Inputs},
	}, nil
}

// Read fetches the current InterfaceEthernetVifPd config from VyOS.
func (InterfaceEthernetVifPd) Read(
	ctx context.Context,
	req infer.ReadRequest[InterfaceEthernetVifPdArgs, InterfaceEthernetVifPdState],
) (infer.ReadResponse[InterfaceEthernetVifPdArgs, InterfaceEthernetVifPdState], error) {
	client := getClient(ctx)
	base := interfaceEthernetVifPdBasePath(req.State.VifName, req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := InterfaceEthernetVifPdArgs{VifName: req.State.VifName, Name: req.State.Name}
			state := InterfaceEthernetVifPdState{InterfaceEthernetVifPdArgs: args}
			return infer.ReadResponse[InterfaceEthernetVifPdArgs, InterfaceEthernetVifPdState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[InterfaceEthernetVifPdArgs, InterfaceEthernetVifPdState]{},
			fmt.Errorf("read InterfaceEthernetVifPd %s: %w", req.State.Name, err)
	}

	args, err := parseInterfaceEthernetVifPdConfig(req.State.VifName, req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[InterfaceEthernetVifPdArgs, InterfaceEthernetVifPdState]{},
			fmt.Errorf("parse InterfaceEthernetVifPd %s config: %w", req.State.Name, err)
	}

	state := InterfaceEthernetVifPdState{InterfaceEthernetVifPdArgs: args}
	return infer.ReadResponse[InterfaceEthernetVifPdArgs, InterfaceEthernetVifPdState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing InterfaceEthernetVifPd configuration.
func (InterfaceEthernetVifPd) Update(
	ctx context.Context,
	req infer.UpdateRequest[InterfaceEthernetVifPdArgs, InterfaceEthernetVifPdState],
) (infer.UpdateResponse[InterfaceEthernetVifPdState], error) {
	if req.DryRun {
		return infer.UpdateResponse[InterfaceEthernetVifPdState]{
			Output: InterfaceEthernetVifPdState{InterfaceEthernetVifPdArgs: req.Inputs},
		}, nil
	}

	ops := buildInterfaceEthernetVifPdUpdateOps(req.State.InterfaceEthernetVifPdArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[InterfaceEthernetVifPdState]{},
				fmt.Errorf("update InterfaceEthernetVifPd %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[InterfaceEthernetVifPdState]{
		Output: InterfaceEthernetVifPdState{InterfaceEthernetVifPdArgs: req.Inputs},
	}, nil
}

// Delete removes the InterfaceEthernetVifPd configuration from VyOS.
func (InterfaceEthernetVifPd) Delete(
	ctx context.Context,
	req infer.DeleteRequest[InterfaceEthernetVifPdState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := interfaceEthernetVifPdBasePath(req.State.VifName, req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete InterfaceEthernetVifPd %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildInterfaceEthernetVifPdOps builds set operations for all non-nil fields.
func buildInterfaceEthernetVifPdOps(args InterfaceEthernetVifPdArgs) []vyosclient.Operation {
	base := interfaceEthernetVifPdBasePath(args.VifName, args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}

	if args.Length != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "length"), Value: strconv.Itoa(*args.Length)})
	}

	return ops
}

// buildInterfaceEthernetVifPdUpdateOps computes the diff between previous and current state.
func buildInterfaceEthernetVifPdUpdateOps(prev, cur InterfaceEthernetVifPdArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	base := interfaceEthernetVifPdBasePath(cur.VifName, cur.Name)

	ops = append(ops, diffIntField(base, []string{"length"}, prev.Length, cur.Length)...)

	return ops
}

// parseInterfaceEthernetVifPdConfig unmarshals VyOS ShowConfig JSON.
func parseInterfaceEthernetVifPdConfig(vifName, name string, data json.RawMessage) (InterfaceEthernetVifPdArgs, error) {
	args := InterfaceEthernetVifPdArgs{
		VifName: vifName,
		Name:    name,
	}

	if v, ok := getNestedValue(data, []string{"length"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return InterfaceEthernetVifPdArgs{}, fmt.Errorf("parse length: %w", err)
		}
		args.Length = &n
	}

	return args, nil
}
