// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
	"strconv"
)

// InterfaceWirelessPdInterface manages a VyOS InterfaceWirelessPdInterface configuration.
type InterfaceWirelessPdInterface struct{}

// InterfaceWirelessPdInterfaceArgs defines the inputs for the InterfaceWirelessPdInterface resource.
type InterfaceWirelessPdInterfaceArgs struct {
	PdName  string  `pulumi:"pdName"`
	Name    string  `pulumi:"name"`
	Address *string `pulumi:"address,optional"`
	SlaID   *int    `pulumi:"slaID,optional"`
}

// InterfaceWirelessPdInterfaceState defines the outputs for the InterfaceWirelessPdInterface resource.
type InterfaceWirelessPdInterfaceState struct {
	InterfaceWirelessPdInterfaceArgs
}

// Annotate provides schema metadata for the resource.
func (*InterfaceWirelessPdInterface) Annotate(a infer.Annotator) {
	a.Describe(new(InterfaceWirelessPdInterface), "Manages a VyOS Delegate IPv6 prefix from provider to this interface.")
}

// Annotate provides schema metadata for the inputs.
func (args *InterfaceWirelessPdInterfaceArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.PdName, "Parent tag node key")
	a.Describe(&args.Name, "Delegate IPv6 prefix from provider to this interface")
	a.Describe(&args.Address, "Local interface address assigned to interface (default: EUI-64)")
	a.Describe(&args.SlaID, "Interface site-Level aggregator (SLA)")
}

// Check validates the InterfaceWirelessPdInterface inputs.
func (InterfaceWirelessPdInterface) Check(
	ctx context.Context,
	req infer.CheckRequest,
) (infer.CheckResponse[InterfaceWirelessPdInterfaceArgs], error) {
	inputs, failures, err := infer.DefaultCheck[InterfaceWirelessPdInterfaceArgs](ctx, req.NewInputs)
	if err != nil {
		return infer.CheckResponse[InterfaceWirelessPdInterfaceArgs]{}, err
	}
	if inputs.SlaID != nil {
		if f := checkIntRange(int64(*inputs.SlaID), 0, 65535, "slaID", ""); f != nil {
			failures = append(failures, *f)
		}
	}

	return infer.CheckResponse[InterfaceWirelessPdInterfaceArgs]{Inputs: inputs, Failures: failures}, nil
}

func interfaceWirelessPdInterfaceBasePath(pdName, name string) []any {
	return []any{"interfaces", "wireless", "pd", pdName, "interface", name}
}

// Create sets up the InterfaceWirelessPdInterface on VyOS.
func (InterfaceWirelessPdInterface) Create(
	ctx context.Context,
	req infer.CreateRequest[InterfaceWirelessPdInterfaceArgs],
) (infer.CreateResponse[InterfaceWirelessPdInterfaceState], error) {
	if req.DryRun {
		return infer.CreateResponse[InterfaceWirelessPdInterfaceState]{
			ID:     req.Inputs.Name,
			Output: InterfaceWirelessPdInterfaceState{InterfaceWirelessPdInterfaceArgs: req.Inputs},
		}, nil
	}

	ops := buildInterfaceWirelessPdInterfaceOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[InterfaceWirelessPdInterfaceState]{},
			fmt.Errorf("configure InterfaceWirelessPdInterface %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[InterfaceWirelessPdInterfaceState]{
		ID:     req.Inputs.Name,
		Output: InterfaceWirelessPdInterfaceState{InterfaceWirelessPdInterfaceArgs: req.Inputs},
	}, nil
}

// Read fetches the current InterfaceWirelessPdInterface config from VyOS.
func (InterfaceWirelessPdInterface) Read(
	ctx context.Context,
	req infer.ReadRequest[InterfaceWirelessPdInterfaceArgs, InterfaceWirelessPdInterfaceState],
) (infer.ReadResponse[InterfaceWirelessPdInterfaceArgs, InterfaceWirelessPdInterfaceState], error) {
	client := getClient(ctx)
	base := interfaceWirelessPdInterfaceBasePath(req.State.PdName, req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := InterfaceWirelessPdInterfaceArgs{PdName: req.State.PdName, Name: req.State.Name}
			state := InterfaceWirelessPdInterfaceState{InterfaceWirelessPdInterfaceArgs: args}
			return infer.ReadResponse[InterfaceWirelessPdInterfaceArgs, InterfaceWirelessPdInterfaceState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[InterfaceWirelessPdInterfaceArgs, InterfaceWirelessPdInterfaceState]{},
			fmt.Errorf("read InterfaceWirelessPdInterface %s: %w", req.State.Name, err)
	}

	args, err := parseInterfaceWirelessPdInterfaceConfig(req.State.PdName, req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[InterfaceWirelessPdInterfaceArgs, InterfaceWirelessPdInterfaceState]{},
			fmt.Errorf("parse InterfaceWirelessPdInterface %s config: %w", req.State.Name, err)
	}

	state := InterfaceWirelessPdInterfaceState{InterfaceWirelessPdInterfaceArgs: args}
	return infer.ReadResponse[InterfaceWirelessPdInterfaceArgs, InterfaceWirelessPdInterfaceState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing InterfaceWirelessPdInterface configuration.
func (InterfaceWirelessPdInterface) Update(
	ctx context.Context,
	req infer.UpdateRequest[InterfaceWirelessPdInterfaceArgs, InterfaceWirelessPdInterfaceState],
) (infer.UpdateResponse[InterfaceWirelessPdInterfaceState], error) {
	if req.DryRun {
		return infer.UpdateResponse[InterfaceWirelessPdInterfaceState]{
			Output: InterfaceWirelessPdInterfaceState{InterfaceWirelessPdInterfaceArgs: req.Inputs},
		}, nil
	}

	ops := buildInterfaceWirelessPdInterfaceUpdateOps(req.State.InterfaceWirelessPdInterfaceArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[InterfaceWirelessPdInterfaceState]{},
				fmt.Errorf("update InterfaceWirelessPdInterface %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[InterfaceWirelessPdInterfaceState]{
		Output: InterfaceWirelessPdInterfaceState{InterfaceWirelessPdInterfaceArgs: req.Inputs},
	}, nil
}

// Delete removes the InterfaceWirelessPdInterface configuration from VyOS.
func (InterfaceWirelessPdInterface) Delete(
	ctx context.Context,
	req infer.DeleteRequest[InterfaceWirelessPdInterfaceState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := interfaceWirelessPdInterfaceBasePath(req.State.PdName, req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete InterfaceWirelessPdInterface %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildInterfaceWirelessPdInterfaceOps builds set operations for all non-nil fields.
func buildInterfaceWirelessPdInterfaceOps(args InterfaceWirelessPdInterfaceArgs) []vyosclient.Operation {
	base := interfaceWirelessPdInterfaceBasePath(args.PdName, args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}

	if args.Address != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "address"), Value: *args.Address})
	}

	if args.SlaID != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "sla-id"), Value: strconv.Itoa(*args.SlaID)})
	}

	return ops
}

// buildInterfaceWirelessPdInterfaceUpdateOps computes the diff between previous and current state.
func buildInterfaceWirelessPdInterfaceUpdateOps(prev, cur InterfaceWirelessPdInterfaceArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	base := interfaceWirelessPdInterfaceBasePath(cur.PdName, cur.Name)

	ops = append(ops, diffStringField(base, []string{"address"}, prev.Address, cur.Address)...)

	ops = append(ops, diffIntField(base, []string{"sla-id"}, prev.SlaID, cur.SlaID)...)

	return ops
}

// parseInterfaceWirelessPdInterfaceConfig unmarshals VyOS ShowConfig JSON.
func parseInterfaceWirelessPdInterfaceConfig(pdName, name string, data json.RawMessage) (InterfaceWirelessPdInterfaceArgs, error) {
	args := InterfaceWirelessPdInterfaceArgs{
		PdName: pdName,
		Name:   name,
	}

	if v, ok := getNestedValue(data, []string{"address"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return InterfaceWirelessPdInterfaceArgs{}, fmt.Errorf("parse address: %w", err)
		}
		args.Address = &s
	}

	if v, ok := getNestedValue(data, []string{"sla-id"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return InterfaceWirelessPdInterfaceArgs{}, fmt.Errorf("parse sla-id: %w", err)
		}
		args.SlaID = &n
	}

	return args, nil
}
