// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
	"regexp"
)

// VpnIpsecProfile manages a VyOS VpnIpsecProfile configuration.
type VpnIpsecProfile struct{}

// VpnIpsecProfileArgs defines the inputs for the VpnIpsecProfile resource.
type VpnIpsecProfileArgs struct {
	Name                          string   `pulumi:"name"`
	Disable                       *bool    `pulumi:"disable,optional"`
	EspGroup                      *string  `pulumi:"espGroup,optional"`
	IkeGroup                      *string  `pulumi:"ikeGroup,optional"`
	AuthenticationMode            *string  `pulumi:"authenticationMode,optional"`
	AuthenticationPreSharedSecret *string  `pulumi:"authenticationPreSharedSecret,optional"`
	BindTunnel                    []string `pulumi:"bindTunnel,optional"`
}

// VpnIpsecProfileState defines the outputs for the VpnIpsecProfile resource.
type VpnIpsecProfileState struct {
	VpnIpsecProfileArgs
}

// Annotate provides schema metadata for the resource.
func (*VpnIpsecProfile) Annotate(a infer.Annotator) {
	a.Describe(new(VpnIpsecProfile), "Manages a VyOS VPN IPsec profile.")
}

// Annotate provides schema metadata for the inputs.
func (args *VpnIpsecProfileArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.Name, "VPN IPsec profile")
	a.Describe(&args.Disable, "Disable instance")
	a.Describe(&args.EspGroup, "Encapsulating Security Payloads (ESP) group name")
	a.Describe(&args.IkeGroup, "Internet Key Exchange (IKE) group name")
	a.Describe(&args.AuthenticationMode, "Authentication mode")
	a.Describe(&args.AuthenticationPreSharedSecret, "Pre-shared secret key")
	a.Describe(&args.BindTunnel, "Tunnel interface associated with this profile")
}

var vpnIpsecProfileNameRe = regexp.MustCompile(`^(?:` + "[a-zA-Z][0-9a-zA-Z_-]+" + `)$`)

// Check validates the VpnIpsecProfile inputs.
func (VpnIpsecProfile) Check(
	ctx context.Context,
	req infer.CheckRequest,
) (infer.CheckResponse[VpnIpsecProfileArgs], error) {
	inputs, failures, err := infer.DefaultCheck[VpnIpsecProfileArgs](ctx, req.NewInputs)
	if err != nil {
		return infer.CheckResponse[VpnIpsecProfileArgs]{}, err
	}
	if f := checkRegex(inputs.Name, vpnIpsecProfileNameRe, "name", "Profile name must be alphanumeric and can contain hyphen(s) and underscore(s)"); f != nil {
		failures = append(failures, *f)
	}

	return infer.CheckResponse[VpnIpsecProfileArgs]{Inputs: inputs, Failures: failures}, nil
}

func vpnIpsecProfileBasePath(name string) []any {
	return []any{"vpn", "ipsec", "profile", name}
}

// Create sets up the VpnIpsecProfile on VyOS.
func (VpnIpsecProfile) Create(
	ctx context.Context,
	req infer.CreateRequest[VpnIpsecProfileArgs],
) (infer.CreateResponse[VpnIpsecProfileState], error) {
	if req.DryRun {
		return infer.CreateResponse[VpnIpsecProfileState]{
			ID:     req.Inputs.Name,
			Output: VpnIpsecProfileState{VpnIpsecProfileArgs: req.Inputs},
		}, nil
	}

	ops := buildVpnIpsecProfileOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[VpnIpsecProfileState]{},
			fmt.Errorf("configure VpnIpsecProfile %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[VpnIpsecProfileState]{
		ID:     req.Inputs.Name,
		Output: VpnIpsecProfileState{VpnIpsecProfileArgs: req.Inputs},
	}, nil
}

// Read fetches the current VpnIpsecProfile config from VyOS.
func (VpnIpsecProfile) Read(
	ctx context.Context,
	req infer.ReadRequest[VpnIpsecProfileArgs, VpnIpsecProfileState],
) (infer.ReadResponse[VpnIpsecProfileArgs, VpnIpsecProfileState], error) {
	client := getClient(ctx)
	base := vpnIpsecProfileBasePath(req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := VpnIpsecProfileArgs{Name: req.State.Name}
			state := VpnIpsecProfileState{VpnIpsecProfileArgs: args}
			return infer.ReadResponse[VpnIpsecProfileArgs, VpnIpsecProfileState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[VpnIpsecProfileArgs, VpnIpsecProfileState]{},
			fmt.Errorf("read VpnIpsecProfile %s: %w", req.State.Name, err)
	}

	args, err := parseVpnIpsecProfileConfig(req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[VpnIpsecProfileArgs, VpnIpsecProfileState]{},
			fmt.Errorf("parse VpnIpsecProfile %s config: %w", req.State.Name, err)
	}

	state := VpnIpsecProfileState{VpnIpsecProfileArgs: args}
	return infer.ReadResponse[VpnIpsecProfileArgs, VpnIpsecProfileState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing VpnIpsecProfile configuration.
func (VpnIpsecProfile) Update(
	ctx context.Context,
	req infer.UpdateRequest[VpnIpsecProfileArgs, VpnIpsecProfileState],
) (infer.UpdateResponse[VpnIpsecProfileState], error) {
	if req.DryRun {
		return infer.UpdateResponse[VpnIpsecProfileState]{
			Output: VpnIpsecProfileState{VpnIpsecProfileArgs: req.Inputs},
		}, nil
	}

	ops := buildVpnIpsecProfileUpdateOps(req.State.VpnIpsecProfileArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[VpnIpsecProfileState]{},
				fmt.Errorf("update VpnIpsecProfile %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[VpnIpsecProfileState]{
		Output: VpnIpsecProfileState{VpnIpsecProfileArgs: req.Inputs},
	}, nil
}

// Delete removes the VpnIpsecProfile configuration from VyOS.
func (VpnIpsecProfile) Delete(
	ctx context.Context,
	req infer.DeleteRequest[VpnIpsecProfileState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := vpnIpsecProfileBasePath(req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete VpnIpsecProfile %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildVpnIpsecProfileOps builds set operations for all non-nil fields.
func buildVpnIpsecProfileOps(args VpnIpsecProfileArgs) []vyosclient.Operation {
	base := vpnIpsecProfileBasePath(args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}

	if args.Disable != nil && *args.Disable {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "disable")})
	}

	if args.EspGroup != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "esp-group"), Value: *args.EspGroup})
	}

	if args.IkeGroup != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "ike-group"), Value: *args.IkeGroup})
	}

	if args.AuthenticationMode != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "authentication", "mode"), Value: *args.AuthenticationMode})
	}

	if args.AuthenticationPreSharedSecret != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "authentication", "pre-shared-secret"), Value: *args.AuthenticationPreSharedSecret})
	}

	for _, v := range args.BindTunnel {
		vp := make([]string, 0, 2+1)
		vp = append(vp, "bind")
		vp = append(vp, "tunnel")
		vp = append(vp, v)
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, vp...)})
	}

	return ops
}

// buildVpnIpsecProfileUpdateOps computes the diff between previous and current state.
func buildVpnIpsecProfileUpdateOps(prev, cur VpnIpsecProfileArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	base := vpnIpsecProfileBasePath(cur.Name)

	ops = append(ops, diffBoolField(base, []string{"disable"}, prev.Disable, cur.Disable)...)

	ops = append(ops, diffStringField(base, []string{"esp-group"}, prev.EspGroup, cur.EspGroup)...)

	ops = append(ops, diffStringField(base, []string{"ike-group"}, prev.IkeGroup, cur.IkeGroup)...)

	ops = append(ops, diffStringField(base, []string{"authentication", "mode"}, prev.AuthenticationMode, cur.AuthenticationMode)...)

	ops = append(ops, diffStringField(base, []string{"authentication", "pre-shared-secret"}, prev.AuthenticationPreSharedSecret, cur.AuthenticationPreSharedSecret)...)

	ops = append(ops, diffMultiField(base, []string{"bind", "tunnel"}, prev.BindTunnel, cur.BindTunnel)...)

	return ops
}

// parseVpnIpsecProfileConfig unmarshals VyOS ShowConfig JSON.
func parseVpnIpsecProfileConfig(name string, data json.RawMessage) (VpnIpsecProfileArgs, error) {
	args := VpnIpsecProfileArgs{
		Name: name,
	}

	if _, ok := getNestedValue(data, []string{"disable"}); ok {
		t := true
		args.Disable = &t
	}

	if v, ok := getNestedValue(data, []string{"esp-group"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return VpnIpsecProfileArgs{}, fmt.Errorf("parse esp-group: %w", err)
		}
		args.EspGroup = &s
	}

	if v, ok := getNestedValue(data, []string{"ike-group"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return VpnIpsecProfileArgs{}, fmt.Errorf("parse ike-group: %w", err)
		}
		args.IkeGroup = &s
	}

	if v, ok := getNestedValue(data, []string{"authentication", "mode"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return VpnIpsecProfileArgs{}, fmt.Errorf("parse mode: %w", err)
		}
		args.AuthenticationMode = &s
	}

	if v, ok := getNestedValue(data, []string{"authentication", "pre-shared-secret"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return VpnIpsecProfileArgs{}, fmt.Errorf("parse pre-shared-secret: %w", err)
		}
		args.AuthenticationPreSharedSecret = &s
	}

	if v, ok := getNestedValue(data, []string{"bind", "tunnel"}); ok {
		vals, err := parseMultiValue(v)
		if err != nil {
			return VpnIpsecProfileArgs{}, fmt.Errorf("parse tunnel: %w", err)
		}
		args.BindTunnel = vals
	}

	return args, nil
}
