// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
	"strconv"
)

// VpnL2tpRemoteAccessClientIPv6PoolPrefix manages a VyOS VpnL2tpRemoteAccessClientIPv6PoolPrefix configuration.
type VpnL2tpRemoteAccessClientIPv6PoolPrefix struct{}

// VpnL2tpRemoteAccessClientIPv6PoolPrefixArgs defines the inputs for the VpnL2tpRemoteAccessClientIPv6PoolPrefix resource.
type VpnL2tpRemoteAccessClientIPv6PoolPrefixArgs struct {
	ClientIPv6PoolName string `pulumi:"clientIPv6PoolName"`
	Name               string `pulumi:"name"`
	Mask               *int   `pulumi:"mask,optional"`
}

// VpnL2tpRemoteAccessClientIPv6PoolPrefixState defines the outputs for the VpnL2tpRemoteAccessClientIPv6PoolPrefix resource.
type VpnL2tpRemoteAccessClientIPv6PoolPrefixState struct {
	VpnL2tpRemoteAccessClientIPv6PoolPrefixArgs
}

// Annotate provides schema metadata for the resource.
func (*VpnL2tpRemoteAccessClientIPv6PoolPrefix) Annotate(a infer.Annotator) {
	a.Describe(new(VpnL2tpRemoteAccessClientIPv6PoolPrefix), "Manages a VyOS Pool of addresses used to assign to clients.")
}

// Annotate provides schema metadata for the inputs.
func (args *VpnL2tpRemoteAccessClientIPv6PoolPrefixArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.ClientIPv6PoolName, "Parent tag node key")
	a.Describe(&args.Name, "Pool of addresses used to assign to clients")
	a.Describe(&args.Mask, "Prefix length used for individual client")
}

// Check validates the VpnL2tpRemoteAccessClientIPv6PoolPrefix inputs.
func (VpnL2tpRemoteAccessClientIPv6PoolPrefix) Check(
	ctx context.Context,
	req infer.CheckRequest,
) (infer.CheckResponse[VpnL2tpRemoteAccessClientIPv6PoolPrefixArgs], error) {
	inputs, failures, err := infer.DefaultCheck[VpnL2tpRemoteAccessClientIPv6PoolPrefixArgs](ctx, req.NewInputs)
	if err != nil {
		return infer.CheckResponse[VpnL2tpRemoteAccessClientIPv6PoolPrefixArgs]{}, err
	}
	if inputs.Mask != nil {
		if f := checkIntRange(int64(*inputs.Mask), 48, 128, "mask", ""); f != nil {
			failures = append(failures, *f)
		}
	}

	return infer.CheckResponse[VpnL2tpRemoteAccessClientIPv6PoolPrefixArgs]{Inputs: inputs, Failures: failures}, nil
}

func vpnL2tpRemoteAccessClientIPv6PoolPrefixBasePath(clientIPv6PoolName, name string) []any {
	return []any{"vpn", "l2tp", "remote-access", "client-ipv6-pool", clientIPv6PoolName, "prefix", name}
}

// Create sets up the VpnL2tpRemoteAccessClientIPv6PoolPrefix on VyOS.
func (VpnL2tpRemoteAccessClientIPv6PoolPrefix) Create(
	ctx context.Context,
	req infer.CreateRequest[VpnL2tpRemoteAccessClientIPv6PoolPrefixArgs],
) (infer.CreateResponse[VpnL2tpRemoteAccessClientIPv6PoolPrefixState], error) {
	if req.DryRun {
		return infer.CreateResponse[VpnL2tpRemoteAccessClientIPv6PoolPrefixState]{
			ID:     req.Inputs.Name,
			Output: VpnL2tpRemoteAccessClientIPv6PoolPrefixState{VpnL2tpRemoteAccessClientIPv6PoolPrefixArgs: req.Inputs},
		}, nil
	}

	ops := buildVpnL2tpRemoteAccessClientIPv6PoolPrefixOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[VpnL2tpRemoteAccessClientIPv6PoolPrefixState]{},
			fmt.Errorf("configure VpnL2tpRemoteAccessClientIPv6PoolPrefix %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[VpnL2tpRemoteAccessClientIPv6PoolPrefixState]{
		ID:     req.Inputs.Name,
		Output: VpnL2tpRemoteAccessClientIPv6PoolPrefixState{VpnL2tpRemoteAccessClientIPv6PoolPrefixArgs: req.Inputs},
	}, nil
}

// Read fetches the current VpnL2tpRemoteAccessClientIPv6PoolPrefix config from VyOS.
func (VpnL2tpRemoteAccessClientIPv6PoolPrefix) Read(
	ctx context.Context,
	req infer.ReadRequest[VpnL2tpRemoteAccessClientIPv6PoolPrefixArgs, VpnL2tpRemoteAccessClientIPv6PoolPrefixState],
) (infer.ReadResponse[VpnL2tpRemoteAccessClientIPv6PoolPrefixArgs, VpnL2tpRemoteAccessClientIPv6PoolPrefixState], error) {
	client := getClient(ctx)
	base := vpnL2tpRemoteAccessClientIPv6PoolPrefixBasePath(req.State.ClientIPv6PoolName, req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := VpnL2tpRemoteAccessClientIPv6PoolPrefixArgs{ClientIPv6PoolName: req.State.ClientIPv6PoolName, Name: req.State.Name}
			state := VpnL2tpRemoteAccessClientIPv6PoolPrefixState{VpnL2tpRemoteAccessClientIPv6PoolPrefixArgs: args}
			return infer.ReadResponse[VpnL2tpRemoteAccessClientIPv6PoolPrefixArgs, VpnL2tpRemoteAccessClientIPv6PoolPrefixState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[VpnL2tpRemoteAccessClientIPv6PoolPrefixArgs, VpnL2tpRemoteAccessClientIPv6PoolPrefixState]{},
			fmt.Errorf("read VpnL2tpRemoteAccessClientIPv6PoolPrefix %s: %w", req.State.Name, err)
	}

	args, err := parseVpnL2tpRemoteAccessClientIPv6PoolPrefixConfig(req.State.ClientIPv6PoolName, req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[VpnL2tpRemoteAccessClientIPv6PoolPrefixArgs, VpnL2tpRemoteAccessClientIPv6PoolPrefixState]{},
			fmt.Errorf("parse VpnL2tpRemoteAccessClientIPv6PoolPrefix %s config: %w", req.State.Name, err)
	}

	state := VpnL2tpRemoteAccessClientIPv6PoolPrefixState{VpnL2tpRemoteAccessClientIPv6PoolPrefixArgs: args}
	return infer.ReadResponse[VpnL2tpRemoteAccessClientIPv6PoolPrefixArgs, VpnL2tpRemoteAccessClientIPv6PoolPrefixState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing VpnL2tpRemoteAccessClientIPv6PoolPrefix configuration.
func (VpnL2tpRemoteAccessClientIPv6PoolPrefix) Update(
	ctx context.Context,
	req infer.UpdateRequest[VpnL2tpRemoteAccessClientIPv6PoolPrefixArgs, VpnL2tpRemoteAccessClientIPv6PoolPrefixState],
) (infer.UpdateResponse[VpnL2tpRemoteAccessClientIPv6PoolPrefixState], error) {
	if req.DryRun {
		return infer.UpdateResponse[VpnL2tpRemoteAccessClientIPv6PoolPrefixState]{
			Output: VpnL2tpRemoteAccessClientIPv6PoolPrefixState{VpnL2tpRemoteAccessClientIPv6PoolPrefixArgs: req.Inputs},
		}, nil
	}

	ops := buildVpnL2tpRemoteAccessClientIPv6PoolPrefixUpdateOps(req.State.VpnL2tpRemoteAccessClientIPv6PoolPrefixArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[VpnL2tpRemoteAccessClientIPv6PoolPrefixState]{},
				fmt.Errorf("update VpnL2tpRemoteAccessClientIPv6PoolPrefix %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[VpnL2tpRemoteAccessClientIPv6PoolPrefixState]{
		Output: VpnL2tpRemoteAccessClientIPv6PoolPrefixState{VpnL2tpRemoteAccessClientIPv6PoolPrefixArgs: req.Inputs},
	}, nil
}

// Delete removes the VpnL2tpRemoteAccessClientIPv6PoolPrefix configuration from VyOS.
func (VpnL2tpRemoteAccessClientIPv6PoolPrefix) Delete(
	ctx context.Context,
	req infer.DeleteRequest[VpnL2tpRemoteAccessClientIPv6PoolPrefixState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := vpnL2tpRemoteAccessClientIPv6PoolPrefixBasePath(req.State.ClientIPv6PoolName, req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete VpnL2tpRemoteAccessClientIPv6PoolPrefix %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildVpnL2tpRemoteAccessClientIPv6PoolPrefixOps builds set operations for all non-nil fields.
func buildVpnL2tpRemoteAccessClientIPv6PoolPrefixOps(args VpnL2tpRemoteAccessClientIPv6PoolPrefixArgs) []vyosclient.Operation {
	base := vpnL2tpRemoteAccessClientIPv6PoolPrefixBasePath(args.ClientIPv6PoolName, args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}

	if args.Mask != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "mask"), Value: strconv.Itoa(*args.Mask)})
	}

	return ops
}

// buildVpnL2tpRemoteAccessClientIPv6PoolPrefixUpdateOps computes the diff between previous and current state.
func buildVpnL2tpRemoteAccessClientIPv6PoolPrefixUpdateOps(prev, cur VpnL2tpRemoteAccessClientIPv6PoolPrefixArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	base := vpnL2tpRemoteAccessClientIPv6PoolPrefixBasePath(cur.ClientIPv6PoolName, cur.Name)

	ops = append(ops, diffIntField(base, []string{"mask"}, prev.Mask, cur.Mask)...)

	return ops
}

// parseVpnL2tpRemoteAccessClientIPv6PoolPrefixConfig unmarshals VyOS ShowConfig JSON.
func parseVpnL2tpRemoteAccessClientIPv6PoolPrefixConfig(clientIPv6PoolName, name string, data json.RawMessage) (VpnL2tpRemoteAccessClientIPv6PoolPrefixArgs, error) {
	args := VpnL2tpRemoteAccessClientIPv6PoolPrefixArgs{
		ClientIPv6PoolName: clientIPv6PoolName,
		Name:               name,
	}

	if v, ok := getNestedValue(data, []string{"mask"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return VpnL2tpRemoteAccessClientIPv6PoolPrefixArgs{}, fmt.Errorf("parse mask: %w", err)
		}
		args.Mask = &n
	}

	return args, nil
}
