// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
	"strconv"
)

// InterfaceBondingVifPd manages a VyOS InterfaceBondingVifPd configuration.
type InterfaceBondingVifPd struct{}

// InterfaceBondingVifPdArgs defines the inputs for the InterfaceBondingVifPd resource.
type InterfaceBondingVifPdArgs struct {
	VifName string `pulumi:"vifName"`
	Name    string `pulumi:"name"`
	Length  *int   `pulumi:"length,optional"`
}

// InterfaceBondingVifPdState defines the outputs for the InterfaceBondingVifPd resource.
type InterfaceBondingVifPdState struct {
	InterfaceBondingVifPdArgs
}

// Annotate provides schema metadata for the resource.
func (*InterfaceBondingVifPd) Annotate(a infer.Annotator) {
	a.Describe(new(InterfaceBondingVifPd), "Manages a VyOS DHCPv6 prefix delegation interface statement.")
}

// Annotate provides schema metadata for the inputs.
func (args *InterfaceBondingVifPdArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.VifName, "Parent tag node key")
	a.Describe(&args.Name, "DHCPv6 prefix delegation interface statement")
	a.Describe(&args.Length, "Request IPv6 prefix length from peer")
}

// Check validates the InterfaceBondingVifPd inputs.
func (InterfaceBondingVifPd) Check(
	ctx context.Context,
	req infer.CheckRequest,
) (infer.CheckResponse[InterfaceBondingVifPdArgs], error) {
	inputs, failures, err := infer.DefaultCheck[InterfaceBondingVifPdArgs](ctx, req.NewInputs)
	if err != nil {
		return infer.CheckResponse[InterfaceBondingVifPdArgs]{}, err
	}
	if inputs.Length != nil {
		if f := checkIntRange(int64(*inputs.Length), 32, 64, "length", ""); f != nil {
			failures = append(failures, *f)
		}
	}

	return infer.CheckResponse[InterfaceBondingVifPdArgs]{Inputs: inputs, Failures: failures}, nil
}

func interfaceBondingVifPdBasePath(vifName, name string) []any {
	return []any{"interfaces", "bonding", "vif", vifName, "pd", name}
}

// Create sets up the InterfaceBondingVifPd on VyOS.
func (InterfaceBondingVifPd) Create(
	ctx context.Context,
	req infer.CreateRequest[InterfaceBondingVifPdArgs],
) (infer.CreateResponse[InterfaceBondingVifPdState], error) {
	if req.DryRun {
		return infer.CreateResponse[InterfaceBondingVifPdState]{
			ID:     req.Inputs.Name,
			Output: InterfaceBondingVifPdState{InterfaceBondingVifPdArgs: req.Inputs},
		}, nil
	}

	ops := buildInterfaceBondingVifPdOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[InterfaceBondingVifPdState]{},
			fmt.Errorf("configure InterfaceBondingVifPd %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[InterfaceBondingVifPdState]{
		ID:     req.Inputs.Name,
		Output: InterfaceBondingVifPdState{InterfaceBondingVifPdArgs: req.Inputs},
	}, nil
}

// Read fetches the current InterfaceBondingVifPd config from VyOS.
func (InterfaceBondingVifPd) Read(
	ctx context.Context,
	req infer.ReadRequest[InterfaceBondingVifPdArgs, InterfaceBondingVifPdState],
) (infer.ReadResponse[InterfaceBondingVifPdArgs, InterfaceBondingVifPdState], error) {
	client := getClient(ctx)
	base := interfaceBondingVifPdBasePath(req.State.VifName, req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := InterfaceBondingVifPdArgs{VifName: req.State.VifName, Name: req.State.Name}
			state := InterfaceBondingVifPdState{InterfaceBondingVifPdArgs: args}
			return infer.ReadResponse[InterfaceBondingVifPdArgs, InterfaceBondingVifPdState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[InterfaceBondingVifPdArgs, InterfaceBondingVifPdState]{},
			fmt.Errorf("read InterfaceBondingVifPd %s: %w", req.State.Name, err)
	}

	args, err := parseInterfaceBondingVifPdConfig(req.State.VifName, req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[InterfaceBondingVifPdArgs, InterfaceBondingVifPdState]{},
			fmt.Errorf("parse InterfaceBondingVifPd %s config: %w", req.State.Name, err)
	}

	state := InterfaceBondingVifPdState{InterfaceBondingVifPdArgs: args}
	return infer.ReadResponse[InterfaceBondingVifPdArgs, InterfaceBondingVifPdState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing InterfaceBondingVifPd configuration.
func (InterfaceBondingVifPd) Update(
	ctx context.Context,
	req infer.UpdateRequest[InterfaceBondingVifPdArgs, InterfaceBondingVifPdState],
) (infer.UpdateResponse[InterfaceBondingVifPdState], error) {
	if req.DryRun {
		return infer.UpdateResponse[InterfaceBondingVifPdState]{
			Output: InterfaceBondingVifPdState{InterfaceBondingVifPdArgs: req.Inputs},
		}, nil
	}

	ops := buildInterfaceBondingVifPdUpdateOps(req.State.InterfaceBondingVifPdArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[InterfaceBondingVifPdState]{},
				fmt.Errorf("update InterfaceBondingVifPd %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[InterfaceBondingVifPdState]{
		Output: InterfaceBondingVifPdState{InterfaceBondingVifPdArgs: req.Inputs},
	}, nil
}

// Delete removes the InterfaceBondingVifPd configuration from VyOS.
func (InterfaceBondingVifPd) Delete(
	ctx context.Context,
	req infer.DeleteRequest[InterfaceBondingVifPdState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := interfaceBondingVifPdBasePath(req.State.VifName, req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete InterfaceBondingVifPd %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildInterfaceBondingVifPdOps builds set operations for all non-nil fields.
func buildInterfaceBondingVifPdOps(args InterfaceBondingVifPdArgs) []vyosclient.Operation {
	base := interfaceBondingVifPdBasePath(args.VifName, args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}

	if args.Length != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "length"), Value: strconv.Itoa(*args.Length)})
	}

	return ops
}

// buildInterfaceBondingVifPdUpdateOps computes the diff between previous and current state.
func buildInterfaceBondingVifPdUpdateOps(prev, cur InterfaceBondingVifPdArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	base := interfaceBondingVifPdBasePath(cur.VifName, cur.Name)

	ops = append(ops, diffIntField(base, []string{"length"}, prev.Length, cur.Length)...)

	return ops
}

// parseInterfaceBondingVifPdConfig unmarshals VyOS ShowConfig JSON.
func parseInterfaceBondingVifPdConfig(vifName, name string, data json.RawMessage) (InterfaceBondingVifPdArgs, error) {
	args := InterfaceBondingVifPdArgs{
		VifName: vifName,
		Name:    name,
	}

	if v, ok := getNestedValue(data, []string{"length"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return InterfaceBondingVifPdArgs{}, fmt.Errorf("parse length: %w", err)
		}
		args.Length = &n
	}

	return args, nil
}
