// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
	"regexp"
)

// VpnSstpClientIPv6Pool manages a VyOS VpnSstpClientIPv6Pool configuration.
type VpnSstpClientIPv6Pool struct{}

// VpnSstpClientIPv6PoolArgs defines the inputs for the VpnSstpClientIPv6Pool resource.
type VpnSstpClientIPv6PoolArgs struct {
	Name string `pulumi:"name"`
}

// VpnSstpClientIPv6PoolState defines the outputs for the VpnSstpClientIPv6Pool resource.
type VpnSstpClientIPv6PoolState struct {
	VpnSstpClientIPv6PoolArgs
}

// Annotate provides schema metadata for the resource.
func (*VpnSstpClientIPv6Pool) Annotate(a infer.Annotator) {
	a.Describe(new(VpnSstpClientIPv6Pool), "Manages a VyOS Pool of client IPv6 addresses.")
}

// Annotate provides schema metadata for the inputs.
func (args *VpnSstpClientIPv6PoolArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.Name, "Pool of client IPv6 addresses")
}

var vpnSstpClientIPv6PoolNameRe = regexp.MustCompile(`^(?:` + "[-_a-zA-Z0-9][\\w\\-\\.\\+]*" + `)$`)

// Check validates the VpnSstpClientIPv6Pool inputs.
func (VpnSstpClientIPv6Pool) Check(
	ctx context.Context,
	req infer.CheckRequest,
) (infer.CheckResponse[VpnSstpClientIPv6PoolArgs], error) {
	inputs, failures, err := infer.DefaultCheck[VpnSstpClientIPv6PoolArgs](ctx, req.NewInputs)
	if err != nil {
		return infer.CheckResponse[VpnSstpClientIPv6PoolArgs]{}, err
	}
	if f := checkRegex(inputs.Name, vpnSstpClientIPv6PoolNameRe, "name", ""); f != nil {
		failures = append(failures, *f)
	}

	return infer.CheckResponse[VpnSstpClientIPv6PoolArgs]{Inputs: inputs, Failures: failures}, nil
}

func vpnSstpClientIPv6PoolBasePath(name string) []any {
	return []any{"vpn", "sstp", "client-ipv6-pool", name}
}

// Create sets up the VpnSstpClientIPv6Pool on VyOS.
func (VpnSstpClientIPv6Pool) Create(
	ctx context.Context,
	req infer.CreateRequest[VpnSstpClientIPv6PoolArgs],
) (infer.CreateResponse[VpnSstpClientIPv6PoolState], error) {
	if req.DryRun {
		return infer.CreateResponse[VpnSstpClientIPv6PoolState]{
			ID:     req.Inputs.Name,
			Output: VpnSstpClientIPv6PoolState{VpnSstpClientIPv6PoolArgs: req.Inputs},
		}, nil
	}

	ops := buildVpnSstpClientIPv6PoolOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[VpnSstpClientIPv6PoolState]{},
			fmt.Errorf("configure VpnSstpClientIPv6Pool %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[VpnSstpClientIPv6PoolState]{
		ID:     req.Inputs.Name,
		Output: VpnSstpClientIPv6PoolState{VpnSstpClientIPv6PoolArgs: req.Inputs},
	}, nil
}

// Read fetches the current VpnSstpClientIPv6Pool config from VyOS.
func (VpnSstpClientIPv6Pool) Read(
	ctx context.Context,
	req infer.ReadRequest[VpnSstpClientIPv6PoolArgs, VpnSstpClientIPv6PoolState],
) (infer.ReadResponse[VpnSstpClientIPv6PoolArgs, VpnSstpClientIPv6PoolState], error) {
	client := getClient(ctx)
	base := vpnSstpClientIPv6PoolBasePath(req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := VpnSstpClientIPv6PoolArgs{Name: req.State.Name}
			state := VpnSstpClientIPv6PoolState{VpnSstpClientIPv6PoolArgs: args}
			return infer.ReadResponse[VpnSstpClientIPv6PoolArgs, VpnSstpClientIPv6PoolState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[VpnSstpClientIPv6PoolArgs, VpnSstpClientIPv6PoolState]{},
			fmt.Errorf("read VpnSstpClientIPv6Pool %s: %w", req.State.Name, err)
	}

	args, err := parseVpnSstpClientIPv6PoolConfig(req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[VpnSstpClientIPv6PoolArgs, VpnSstpClientIPv6PoolState]{},
			fmt.Errorf("parse VpnSstpClientIPv6Pool %s config: %w", req.State.Name, err)
	}

	state := VpnSstpClientIPv6PoolState{VpnSstpClientIPv6PoolArgs: args}
	return infer.ReadResponse[VpnSstpClientIPv6PoolArgs, VpnSstpClientIPv6PoolState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing VpnSstpClientIPv6Pool configuration.
func (VpnSstpClientIPv6Pool) Update(
	ctx context.Context,
	req infer.UpdateRequest[VpnSstpClientIPv6PoolArgs, VpnSstpClientIPv6PoolState],
) (infer.UpdateResponse[VpnSstpClientIPv6PoolState], error) {
	if req.DryRun {
		return infer.UpdateResponse[VpnSstpClientIPv6PoolState]{
			Output: VpnSstpClientIPv6PoolState{VpnSstpClientIPv6PoolArgs: req.Inputs},
		}, nil
	}

	ops := buildVpnSstpClientIPv6PoolUpdateOps(req.State.VpnSstpClientIPv6PoolArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[VpnSstpClientIPv6PoolState]{},
				fmt.Errorf("update VpnSstpClientIPv6Pool %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[VpnSstpClientIPv6PoolState]{
		Output: VpnSstpClientIPv6PoolState{VpnSstpClientIPv6PoolArgs: req.Inputs},
	}, nil
}

// Delete removes the VpnSstpClientIPv6Pool configuration from VyOS.
func (VpnSstpClientIPv6Pool) Delete(
	ctx context.Context,
	req infer.DeleteRequest[VpnSstpClientIPv6PoolState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := vpnSstpClientIPv6PoolBasePath(req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete VpnSstpClientIPv6Pool %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildVpnSstpClientIPv6PoolOps builds set operations for all non-nil fields.
func buildVpnSstpClientIPv6PoolOps(args VpnSstpClientIPv6PoolArgs) []vyosclient.Operation {
	base := vpnSstpClientIPv6PoolBasePath(args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}
	return ops
}

// buildVpnSstpClientIPv6PoolUpdateOps computes the diff between previous and current state.
func buildVpnSstpClientIPv6PoolUpdateOps(prev, cur VpnSstpClientIPv6PoolArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	return ops
}

// parseVpnSstpClientIPv6PoolConfig unmarshals VyOS ShowConfig JSON.
func parseVpnSstpClientIPv6PoolConfig(name string, data json.RawMessage) (VpnSstpClientIPv6PoolArgs, error) {
	args := VpnSstpClientIPv6PoolArgs{
		Name: name,
	}

	return args, nil
}
