// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
	"regexp"
	"strconv"
)

// VRFNameRouteInterface manages a VyOS VRFNameRouteInterface configuration.
type VRFNameRouteInterface struct{}

// VRFNameRouteInterfaceArgs defines the inputs for the VRFNameRouteInterface resource.
type VRFNameRouteInterfaceArgs struct {
	RouteName string  `pulumi:"routeName"`
	Name      string  `pulumi:"name"`
	Disable   *bool   `pulumi:"disable,optional"`
	Distance  *int    `pulumi:"distance,optional"`
	Segments  *string `pulumi:"segments,optional"`
	VRF       *string `pulumi:"vrf,optional"`
}

// VRFNameRouteInterfaceState defines the outputs for the VRFNameRouteInterface resource.
type VRFNameRouteInterfaceState struct {
	VRFNameRouteInterfaceArgs
}

// Annotate provides schema metadata for the resource.
func (*VRFNameRouteInterface) Annotate(a infer.Annotator) {
	a.Describe(new(VRFNameRouteInterface), "Manages a VyOS Next-hop IPv4 router interface.")
}

// Annotate provides schema metadata for the inputs.
func (args *VRFNameRouteInterfaceArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.RouteName, "Parent tag node key")
	a.Describe(&args.Name, "Next-hop IPv4 router interface")
	a.Describe(&args.Disable, "Disable instance")
	a.Describe(&args.Distance, "Distance for this route")
	a.Describe(&args.Segments, "SRv6 segments")
	a.Describe(&args.VRF, "VRF to leak route")
}

var vrfNameRouteInterfaceVRFRe = regexp.MustCompile(`^(?:` + "(default)" + `)$`)

// Check validates the VRFNameRouteInterface inputs.
func (VRFNameRouteInterface) Check(
	ctx context.Context,
	req infer.CheckRequest,
) (infer.CheckResponse[VRFNameRouteInterfaceArgs], error) {
	inputs, failures, err := infer.DefaultCheck[VRFNameRouteInterfaceArgs](ctx, req.NewInputs)
	if err != nil {
		return infer.CheckResponse[VRFNameRouteInterfaceArgs]{}, err
	}
	if inputs.Distance != nil {
		if f := checkIntRange(int64(*inputs.Distance), 1, 255, "distance", ""); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.VRF != nil {
		if f := checkRegex(*inputs.VRF, vrfNameRouteInterfaceVRFRe, "vrf", ""); f != nil {
			failures = append(failures, *f)
		}
	}

	return infer.CheckResponse[VRFNameRouteInterfaceArgs]{Inputs: inputs, Failures: failures}, nil
}

func vrfNameRouteInterfaceBasePath(routeName, name string) []any {
	return []any{"vrf", "name", "route", routeName, "interface", name}
}

// Create sets up the VRFNameRouteInterface on VyOS.
func (VRFNameRouteInterface) Create(
	ctx context.Context,
	req infer.CreateRequest[VRFNameRouteInterfaceArgs],
) (infer.CreateResponse[VRFNameRouteInterfaceState], error) {
	if req.DryRun {
		return infer.CreateResponse[VRFNameRouteInterfaceState]{
			ID:     req.Inputs.Name,
			Output: VRFNameRouteInterfaceState{VRFNameRouteInterfaceArgs: req.Inputs},
		}, nil
	}

	ops := buildVRFNameRouteInterfaceOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[VRFNameRouteInterfaceState]{},
			fmt.Errorf("configure VRFNameRouteInterface %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[VRFNameRouteInterfaceState]{
		ID:     req.Inputs.Name,
		Output: VRFNameRouteInterfaceState{VRFNameRouteInterfaceArgs: req.Inputs},
	}, nil
}

// Read fetches the current VRFNameRouteInterface config from VyOS.
func (VRFNameRouteInterface) Read(
	ctx context.Context,
	req infer.ReadRequest[VRFNameRouteInterfaceArgs, VRFNameRouteInterfaceState],
) (infer.ReadResponse[VRFNameRouteInterfaceArgs, VRFNameRouteInterfaceState], error) {
	client := getClient(ctx)
	base := vrfNameRouteInterfaceBasePath(req.State.RouteName, req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := VRFNameRouteInterfaceArgs{RouteName: req.State.RouteName, Name: req.State.Name}
			state := VRFNameRouteInterfaceState{VRFNameRouteInterfaceArgs: args}
			return infer.ReadResponse[VRFNameRouteInterfaceArgs, VRFNameRouteInterfaceState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[VRFNameRouteInterfaceArgs, VRFNameRouteInterfaceState]{},
			fmt.Errorf("read VRFNameRouteInterface %s: %w", req.State.Name, err)
	}

	args, err := parseVRFNameRouteInterfaceConfig(req.State.RouteName, req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[VRFNameRouteInterfaceArgs, VRFNameRouteInterfaceState]{},
			fmt.Errorf("parse VRFNameRouteInterface %s config: %w", req.State.Name, err)
	}

	state := VRFNameRouteInterfaceState{VRFNameRouteInterfaceArgs: args}
	return infer.ReadResponse[VRFNameRouteInterfaceArgs, VRFNameRouteInterfaceState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing VRFNameRouteInterface configuration.
func (VRFNameRouteInterface) Update(
	ctx context.Context,
	req infer.UpdateRequest[VRFNameRouteInterfaceArgs, VRFNameRouteInterfaceState],
) (infer.UpdateResponse[VRFNameRouteInterfaceState], error) {
	if req.DryRun {
		return infer.UpdateResponse[VRFNameRouteInterfaceState]{
			Output: VRFNameRouteInterfaceState{VRFNameRouteInterfaceArgs: req.Inputs},
		}, nil
	}

	ops := buildVRFNameRouteInterfaceUpdateOps(req.State.VRFNameRouteInterfaceArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[VRFNameRouteInterfaceState]{},
				fmt.Errorf("update VRFNameRouteInterface %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[VRFNameRouteInterfaceState]{
		Output: VRFNameRouteInterfaceState{VRFNameRouteInterfaceArgs: req.Inputs},
	}, nil
}

// Delete removes the VRFNameRouteInterface configuration from VyOS.
func (VRFNameRouteInterface) Delete(
	ctx context.Context,
	req infer.DeleteRequest[VRFNameRouteInterfaceState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := vrfNameRouteInterfaceBasePath(req.State.RouteName, req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete VRFNameRouteInterface %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildVRFNameRouteInterfaceOps builds set operations for all non-nil fields.
func buildVRFNameRouteInterfaceOps(args VRFNameRouteInterfaceArgs) []vyosclient.Operation {
	base := vrfNameRouteInterfaceBasePath(args.RouteName, args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}

	if args.Disable != nil && *args.Disable {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "disable")})
	}

	if args.Distance != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "distance"), Value: strconv.Itoa(*args.Distance)})
	}

	if args.Segments != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "segments"), Value: *args.Segments})
	}

	if args.VRF != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "vrf"), Value: *args.VRF})
	}

	return ops
}

// buildVRFNameRouteInterfaceUpdateOps computes the diff between previous and current state.
func buildVRFNameRouteInterfaceUpdateOps(prev, cur VRFNameRouteInterfaceArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	base := vrfNameRouteInterfaceBasePath(cur.RouteName, cur.Name)

	ops = append(ops, diffBoolField(base, []string{"disable"}, prev.Disable, cur.Disable)...)

	ops = append(ops, diffIntField(base, []string{"distance"}, prev.Distance, cur.Distance)...)

	ops = append(ops, diffStringField(base, []string{"segments"}, prev.Segments, cur.Segments)...)

	ops = append(ops, diffStringField(base, []string{"vrf"}, prev.VRF, cur.VRF)...)

	return ops
}

// parseVRFNameRouteInterfaceConfig unmarshals VyOS ShowConfig JSON.
func parseVRFNameRouteInterfaceConfig(routeName, name string, data json.RawMessage) (VRFNameRouteInterfaceArgs, error) {
	args := VRFNameRouteInterfaceArgs{
		RouteName: routeName,
		Name:      name,
	}

	if _, ok := getNestedValue(data, []string{"disable"}); ok {
		t := true
		args.Disable = &t
	}

	if v, ok := getNestedValue(data, []string{"distance"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return VRFNameRouteInterfaceArgs{}, fmt.Errorf("parse distance: %w", err)
		}
		args.Distance = &n
	}

	if v, ok := getNestedValue(data, []string{"segments"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return VRFNameRouteInterfaceArgs{}, fmt.Errorf("parse segments: %w", err)
		}
		args.Segments = &s
	}

	if v, ok := getNestedValue(data, []string{"vrf"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return VRFNameRouteInterfaceArgs{}, fmt.Errorf("parse vrf: %w", err)
		}
		args.VRF = &s
	}

	return args, nil
}
