// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
	"strconv"
)

// VpnPptpRemoteAccessClientIPv6PoolDelegate manages a VyOS VpnPptpRemoteAccessClientIPv6PoolDelegate configuration.
type VpnPptpRemoteAccessClientIPv6PoolDelegate struct{}

// VpnPptpRemoteAccessClientIPv6PoolDelegateArgs defines the inputs for the VpnPptpRemoteAccessClientIPv6PoolDelegate resource.
type VpnPptpRemoteAccessClientIPv6PoolDelegateArgs struct {
	ClientIPv6PoolName string `pulumi:"clientIPv6PoolName"`
	Name               string `pulumi:"name"`
	DelegationPrefix   *int   `pulumi:"delegationPrefix,optional"`
}

// VpnPptpRemoteAccessClientIPv6PoolDelegateState defines the outputs for the VpnPptpRemoteAccessClientIPv6PoolDelegate resource.
type VpnPptpRemoteAccessClientIPv6PoolDelegateState struct {
	VpnPptpRemoteAccessClientIPv6PoolDelegateArgs
}

// Annotate provides schema metadata for the resource.
func (*VpnPptpRemoteAccessClientIPv6PoolDelegate) Annotate(a infer.Annotator) {
	a.Describe(new(VpnPptpRemoteAccessClientIPv6PoolDelegate), "Manages a VyOS Subnet used to delegate prefix through DHCPv6-PD (RFC3633).")
}

// Annotate provides schema metadata for the inputs.
func (args *VpnPptpRemoteAccessClientIPv6PoolDelegateArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.ClientIPv6PoolName, "Parent tag node key")
	a.Describe(&args.Name, "Subnet used to delegate prefix through DHCPv6-PD (RFC3633)")
	a.Describe(&args.DelegationPrefix, "Prefix length delegated to client")
}

// Check validates the VpnPptpRemoteAccessClientIPv6PoolDelegate inputs.
func (VpnPptpRemoteAccessClientIPv6PoolDelegate) Check(
	ctx context.Context,
	req infer.CheckRequest,
) (infer.CheckResponse[VpnPptpRemoteAccessClientIPv6PoolDelegateArgs], error) {
	inputs, failures, err := infer.DefaultCheck[VpnPptpRemoteAccessClientIPv6PoolDelegateArgs](ctx, req.NewInputs)
	if err != nil {
		return infer.CheckResponse[VpnPptpRemoteAccessClientIPv6PoolDelegateArgs]{}, err
	}
	if inputs.DelegationPrefix != nil {
		if f := checkIntRange(int64(*inputs.DelegationPrefix), 32, 64, "delegationPrefix", ""); f != nil {
			failures = append(failures, *f)
		}
	}

	return infer.CheckResponse[VpnPptpRemoteAccessClientIPv6PoolDelegateArgs]{Inputs: inputs, Failures: failures}, nil
}

func vpnPptpRemoteAccessClientIPv6PoolDelegateBasePath(clientIPv6PoolName, name string) []any {
	return []any{"vpn", "pptp", "remote-access", "client-ipv6-pool", clientIPv6PoolName, "delegate", name}
}

// Create sets up the VpnPptpRemoteAccessClientIPv6PoolDelegate on VyOS.
func (VpnPptpRemoteAccessClientIPv6PoolDelegate) Create(
	ctx context.Context,
	req infer.CreateRequest[VpnPptpRemoteAccessClientIPv6PoolDelegateArgs],
) (infer.CreateResponse[VpnPptpRemoteAccessClientIPv6PoolDelegateState], error) {
	if req.DryRun {
		return infer.CreateResponse[VpnPptpRemoteAccessClientIPv6PoolDelegateState]{
			ID:     req.Inputs.Name,
			Output: VpnPptpRemoteAccessClientIPv6PoolDelegateState{VpnPptpRemoteAccessClientIPv6PoolDelegateArgs: req.Inputs},
		}, nil
	}

	ops := buildVpnPptpRemoteAccessClientIPv6PoolDelegateOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[VpnPptpRemoteAccessClientIPv6PoolDelegateState]{},
			fmt.Errorf("configure VpnPptpRemoteAccessClientIPv6PoolDelegate %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[VpnPptpRemoteAccessClientIPv6PoolDelegateState]{
		ID:     req.Inputs.Name,
		Output: VpnPptpRemoteAccessClientIPv6PoolDelegateState{VpnPptpRemoteAccessClientIPv6PoolDelegateArgs: req.Inputs},
	}, nil
}

// Read fetches the current VpnPptpRemoteAccessClientIPv6PoolDelegate config from VyOS.
func (VpnPptpRemoteAccessClientIPv6PoolDelegate) Read(
	ctx context.Context,
	req infer.ReadRequest[VpnPptpRemoteAccessClientIPv6PoolDelegateArgs, VpnPptpRemoteAccessClientIPv6PoolDelegateState],
) (infer.ReadResponse[VpnPptpRemoteAccessClientIPv6PoolDelegateArgs, VpnPptpRemoteAccessClientIPv6PoolDelegateState], error) {
	client := getClient(ctx)
	base := vpnPptpRemoteAccessClientIPv6PoolDelegateBasePath(req.State.ClientIPv6PoolName, req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := VpnPptpRemoteAccessClientIPv6PoolDelegateArgs{ClientIPv6PoolName: req.State.ClientIPv6PoolName, Name: req.State.Name}
			state := VpnPptpRemoteAccessClientIPv6PoolDelegateState{VpnPptpRemoteAccessClientIPv6PoolDelegateArgs: args}
			return infer.ReadResponse[VpnPptpRemoteAccessClientIPv6PoolDelegateArgs, VpnPptpRemoteAccessClientIPv6PoolDelegateState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[VpnPptpRemoteAccessClientIPv6PoolDelegateArgs, VpnPptpRemoteAccessClientIPv6PoolDelegateState]{},
			fmt.Errorf("read VpnPptpRemoteAccessClientIPv6PoolDelegate %s: %w", req.State.Name, err)
	}

	args, err := parseVpnPptpRemoteAccessClientIPv6PoolDelegateConfig(req.State.ClientIPv6PoolName, req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[VpnPptpRemoteAccessClientIPv6PoolDelegateArgs, VpnPptpRemoteAccessClientIPv6PoolDelegateState]{},
			fmt.Errorf("parse VpnPptpRemoteAccessClientIPv6PoolDelegate %s config: %w", req.State.Name, err)
	}

	state := VpnPptpRemoteAccessClientIPv6PoolDelegateState{VpnPptpRemoteAccessClientIPv6PoolDelegateArgs: args}
	return infer.ReadResponse[VpnPptpRemoteAccessClientIPv6PoolDelegateArgs, VpnPptpRemoteAccessClientIPv6PoolDelegateState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing VpnPptpRemoteAccessClientIPv6PoolDelegate configuration.
func (VpnPptpRemoteAccessClientIPv6PoolDelegate) Update(
	ctx context.Context,
	req infer.UpdateRequest[VpnPptpRemoteAccessClientIPv6PoolDelegateArgs, VpnPptpRemoteAccessClientIPv6PoolDelegateState],
) (infer.UpdateResponse[VpnPptpRemoteAccessClientIPv6PoolDelegateState], error) {
	if req.DryRun {
		return infer.UpdateResponse[VpnPptpRemoteAccessClientIPv6PoolDelegateState]{
			Output: VpnPptpRemoteAccessClientIPv6PoolDelegateState{VpnPptpRemoteAccessClientIPv6PoolDelegateArgs: req.Inputs},
		}, nil
	}

	ops := buildVpnPptpRemoteAccessClientIPv6PoolDelegateUpdateOps(req.State.VpnPptpRemoteAccessClientIPv6PoolDelegateArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[VpnPptpRemoteAccessClientIPv6PoolDelegateState]{},
				fmt.Errorf("update VpnPptpRemoteAccessClientIPv6PoolDelegate %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[VpnPptpRemoteAccessClientIPv6PoolDelegateState]{
		Output: VpnPptpRemoteAccessClientIPv6PoolDelegateState{VpnPptpRemoteAccessClientIPv6PoolDelegateArgs: req.Inputs},
	}, nil
}

// Delete removes the VpnPptpRemoteAccessClientIPv6PoolDelegate configuration from VyOS.
func (VpnPptpRemoteAccessClientIPv6PoolDelegate) Delete(
	ctx context.Context,
	req infer.DeleteRequest[VpnPptpRemoteAccessClientIPv6PoolDelegateState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := vpnPptpRemoteAccessClientIPv6PoolDelegateBasePath(req.State.ClientIPv6PoolName, req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete VpnPptpRemoteAccessClientIPv6PoolDelegate %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildVpnPptpRemoteAccessClientIPv6PoolDelegateOps builds set operations for all non-nil fields.
func buildVpnPptpRemoteAccessClientIPv6PoolDelegateOps(args VpnPptpRemoteAccessClientIPv6PoolDelegateArgs) []vyosclient.Operation {
	base := vpnPptpRemoteAccessClientIPv6PoolDelegateBasePath(args.ClientIPv6PoolName, args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}

	if args.DelegationPrefix != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "delegation-prefix"), Value: strconv.Itoa(*args.DelegationPrefix)})
	}

	return ops
}

// buildVpnPptpRemoteAccessClientIPv6PoolDelegateUpdateOps computes the diff between previous and current state.
func buildVpnPptpRemoteAccessClientIPv6PoolDelegateUpdateOps(prev, cur VpnPptpRemoteAccessClientIPv6PoolDelegateArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	base := vpnPptpRemoteAccessClientIPv6PoolDelegateBasePath(cur.ClientIPv6PoolName, cur.Name)

	ops = append(ops, diffIntField(base, []string{"delegation-prefix"}, prev.DelegationPrefix, cur.DelegationPrefix)...)

	return ops
}

// parseVpnPptpRemoteAccessClientIPv6PoolDelegateConfig unmarshals VyOS ShowConfig JSON.
func parseVpnPptpRemoteAccessClientIPv6PoolDelegateConfig(clientIPv6PoolName, name string, data json.RawMessage) (VpnPptpRemoteAccessClientIPv6PoolDelegateArgs, error) {
	args := VpnPptpRemoteAccessClientIPv6PoolDelegateArgs{
		ClientIPv6PoolName: clientIPv6PoolName,
		Name:               name,
	}

	if v, ok := getNestedValue(data, []string{"delegation-prefix"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return VpnPptpRemoteAccessClientIPv6PoolDelegateArgs{}, fmt.Errorf("parse delegation-prefix: %w", err)
		}
		args.DelegationPrefix = &n
	}

	return args, nil
}
