// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
	"strconv"
)

// ServiceConntrackSyncInterface manages a VyOS ServiceConntrackSyncInterface configuration.
type ServiceConntrackSyncInterface struct{}

// ServiceConntrackSyncInterfaceArgs defines the inputs for the ServiceConntrackSyncInterface resource.
type ServiceConntrackSyncInterfaceArgs struct {
	Name string  `pulumi:"name"`
	Peer *string `pulumi:"peer,optional"`
	Port *int    `pulumi:"port,optional"`
}

// ServiceConntrackSyncInterfaceState defines the outputs for the ServiceConntrackSyncInterface resource.
type ServiceConntrackSyncInterfaceState struct {
	ServiceConntrackSyncInterfaceArgs
}

// Annotate provides schema metadata for the resource.
func (*ServiceConntrackSyncInterface) Annotate(a infer.Annotator) {
	a.Describe(new(ServiceConntrackSyncInterface), "Manages a VyOS Interface to use for syncing conntrack entries.")
}

// Annotate provides schema metadata for the inputs.
func (args *ServiceConntrackSyncInterfaceArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.Name, "Interface to use for syncing conntrack entries")
	a.Describe(&args.Peer, "IP address of the peer to send the UDP conntrack info too. This disable multicast.")
	a.Describe(&args.Port, "Port number used by connection")
}

// Check validates the ServiceConntrackSyncInterface inputs.
func (ServiceConntrackSyncInterface) Check(
	ctx context.Context,
	req infer.CheckRequest,
) (infer.CheckResponse[ServiceConntrackSyncInterfaceArgs], error) {
	inputs, failures, err := infer.DefaultCheck[ServiceConntrackSyncInterfaceArgs](ctx, req.NewInputs)
	if err != nil {
		return infer.CheckResponse[ServiceConntrackSyncInterfaceArgs]{}, err
	}
	if inputs.Port != nil {
		if f := checkIntRange(int64(*inputs.Port), 1, 65535, "port", "Port number must be in range 1 to 65535"); f != nil {
			failures = append(failures, *f)
		}
	}

	return infer.CheckResponse[ServiceConntrackSyncInterfaceArgs]{Inputs: inputs, Failures: failures}, nil
}

func serviceConntrackSyncInterfaceBasePath(name string) []any {
	return []any{"service", "conntrack-sync", "interface", name}
}

// Create sets up the ServiceConntrackSyncInterface on VyOS.
func (ServiceConntrackSyncInterface) Create(
	ctx context.Context,
	req infer.CreateRequest[ServiceConntrackSyncInterfaceArgs],
) (infer.CreateResponse[ServiceConntrackSyncInterfaceState], error) {
	if req.DryRun {
		return infer.CreateResponse[ServiceConntrackSyncInterfaceState]{
			ID:     req.Inputs.Name,
			Output: ServiceConntrackSyncInterfaceState{ServiceConntrackSyncInterfaceArgs: req.Inputs},
		}, nil
	}

	ops := buildServiceConntrackSyncInterfaceOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[ServiceConntrackSyncInterfaceState]{},
			fmt.Errorf("configure ServiceConntrackSyncInterface %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[ServiceConntrackSyncInterfaceState]{
		ID:     req.Inputs.Name,
		Output: ServiceConntrackSyncInterfaceState{ServiceConntrackSyncInterfaceArgs: req.Inputs},
	}, nil
}

// Read fetches the current ServiceConntrackSyncInterface config from VyOS.
func (ServiceConntrackSyncInterface) Read(
	ctx context.Context,
	req infer.ReadRequest[ServiceConntrackSyncInterfaceArgs, ServiceConntrackSyncInterfaceState],
) (infer.ReadResponse[ServiceConntrackSyncInterfaceArgs, ServiceConntrackSyncInterfaceState], error) {
	client := getClient(ctx)
	base := serviceConntrackSyncInterfaceBasePath(req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := ServiceConntrackSyncInterfaceArgs{Name: req.State.Name}
			state := ServiceConntrackSyncInterfaceState{ServiceConntrackSyncInterfaceArgs: args}
			return infer.ReadResponse[ServiceConntrackSyncInterfaceArgs, ServiceConntrackSyncInterfaceState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[ServiceConntrackSyncInterfaceArgs, ServiceConntrackSyncInterfaceState]{},
			fmt.Errorf("read ServiceConntrackSyncInterface %s: %w", req.State.Name, err)
	}

	args, err := parseServiceConntrackSyncInterfaceConfig(req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[ServiceConntrackSyncInterfaceArgs, ServiceConntrackSyncInterfaceState]{},
			fmt.Errorf("parse ServiceConntrackSyncInterface %s config: %w", req.State.Name, err)
	}

	state := ServiceConntrackSyncInterfaceState{ServiceConntrackSyncInterfaceArgs: args}
	return infer.ReadResponse[ServiceConntrackSyncInterfaceArgs, ServiceConntrackSyncInterfaceState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing ServiceConntrackSyncInterface configuration.
func (ServiceConntrackSyncInterface) Update(
	ctx context.Context,
	req infer.UpdateRequest[ServiceConntrackSyncInterfaceArgs, ServiceConntrackSyncInterfaceState],
) (infer.UpdateResponse[ServiceConntrackSyncInterfaceState], error) {
	if req.DryRun {
		return infer.UpdateResponse[ServiceConntrackSyncInterfaceState]{
			Output: ServiceConntrackSyncInterfaceState{ServiceConntrackSyncInterfaceArgs: req.Inputs},
		}, nil
	}

	ops := buildServiceConntrackSyncInterfaceUpdateOps(req.State.ServiceConntrackSyncInterfaceArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[ServiceConntrackSyncInterfaceState]{},
				fmt.Errorf("update ServiceConntrackSyncInterface %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[ServiceConntrackSyncInterfaceState]{
		Output: ServiceConntrackSyncInterfaceState{ServiceConntrackSyncInterfaceArgs: req.Inputs},
	}, nil
}

// Delete removes the ServiceConntrackSyncInterface configuration from VyOS.
func (ServiceConntrackSyncInterface) Delete(
	ctx context.Context,
	req infer.DeleteRequest[ServiceConntrackSyncInterfaceState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := serviceConntrackSyncInterfaceBasePath(req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete ServiceConntrackSyncInterface %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildServiceConntrackSyncInterfaceOps builds set operations for all non-nil fields.
func buildServiceConntrackSyncInterfaceOps(args ServiceConntrackSyncInterfaceArgs) []vyosclient.Operation {
	base := serviceConntrackSyncInterfaceBasePath(args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}

	if args.Peer != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "peer"), Value: *args.Peer})
	}

	if args.Port != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "port"), Value: strconv.Itoa(*args.Port)})
	}

	return ops
}

// buildServiceConntrackSyncInterfaceUpdateOps computes the diff between previous and current state.
func buildServiceConntrackSyncInterfaceUpdateOps(prev, cur ServiceConntrackSyncInterfaceArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	base := serviceConntrackSyncInterfaceBasePath(cur.Name)

	ops = append(ops, diffStringField(base, []string{"peer"}, prev.Peer, cur.Peer)...)

	ops = append(ops, diffIntField(base, []string{"port"}, prev.Port, cur.Port)...)

	return ops
}

// parseServiceConntrackSyncInterfaceConfig unmarshals VyOS ShowConfig JSON.
func parseServiceConntrackSyncInterfaceConfig(name string, data json.RawMessage) (ServiceConntrackSyncInterfaceArgs, error) {
	args := ServiceConntrackSyncInterfaceArgs{
		Name: name,
	}

	if v, ok := getNestedValue(data, []string{"peer"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return ServiceConntrackSyncInterfaceArgs{}, fmt.Errorf("parse peer: %w", err)
		}
		args.Peer = &s
	}

	if v, ok := getNestedValue(data, []string{"port"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return ServiceConntrackSyncInterfaceArgs{}, fmt.Errorf("parse port: %w", err)
		}
		args.Port = &n
	}

	return args, nil
}
