// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
	"strconv"
)

// InterfaceBridgeInterface manages a VyOS InterfaceBridgeInterface configuration.
type InterfaceBridgeInterface struct{}

// InterfaceBridgeInterfaceArgs defines the inputs for the InterfaceBridgeInterface resource.
type InterfaceBridgeInterfaceArgs struct {
	BridgeName  string   `pulumi:"bridgeName"`
	Name        string   `pulumi:"name"`
	NativeVLAN  *int     `pulumi:"nativeVLAN,optional"`
	AllowedVLAN []string `pulumi:"allowedVLAN,optional"`
	Cost        *int     `pulumi:"cost,optional"`
	Priority    *int     `pulumi:"priority,optional"`
	Isolated    *bool    `pulumi:"isolated,optional"`
	BpduGuard   *bool    `pulumi:"bpduGuard,optional"`
	RootGuard   *bool    `pulumi:"rootGuard,optional"`
}

// InterfaceBridgeInterfaceState defines the outputs for the InterfaceBridgeInterface resource.
type InterfaceBridgeInterfaceState struct {
	InterfaceBridgeInterfaceArgs
}

// Annotate provides schema metadata for the resource.
func (*InterfaceBridgeInterface) Annotate(a infer.Annotator) {
	a.Describe(new(InterfaceBridgeInterface), "Manages a VyOS Member interface name.")
}

// Annotate provides schema metadata for the inputs.
func (args *InterfaceBridgeInterfaceArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.BridgeName, "Parent tag node key")
	a.Describe(&args.Name, "Member interface name")
	a.Describe(&args.NativeVLAN, "Specify VLAN id which should natively be present on the link")
	a.Describe(&args.AllowedVLAN, "Specify VLAN id which is allowed in this trunk interface")
	a.Describe(&args.Cost, "Bridge port cost")
	a.Describe(&args.Priority, "Bridge port priority")
	a.Describe(&args.Isolated, "Port is isolated (also known as Private-VLAN)")
	a.Describe(&args.BpduGuard, "Enable BPDU Guard")
	a.Describe(&args.RootGuard, "Enable Root Guard")
}

// Check validates the InterfaceBridgeInterface inputs.
func (InterfaceBridgeInterface) Check(
	ctx context.Context,
	req infer.CheckRequest,
) (infer.CheckResponse[InterfaceBridgeInterfaceArgs], error) {
	inputs, failures, err := infer.DefaultCheck[InterfaceBridgeInterfaceArgs](ctx, req.NewInputs)
	if err != nil {
		return infer.CheckResponse[InterfaceBridgeInterfaceArgs]{}, err
	}
	if inputs.NativeVLAN != nil {
		if f := checkIntRange(int64(*inputs.NativeVLAN), 1, 4094, "nativeVLAN", "VLAN ID must be between 1 and 4094"); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.Cost != nil {
		if f := checkIntRange(int64(*inputs.Cost), 1, 65535, "cost", "Path cost value must be between 1 and 65535"); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.Priority != nil {
		if f := checkIntRange(int64(*inputs.Priority), 1, 63, "priority", "Port priority value must be between 0 and 63"); f != nil {
			failures = append(failures, *f)
		}
	}

	return infer.CheckResponse[InterfaceBridgeInterfaceArgs]{Inputs: inputs, Failures: failures}, nil
}

func interfaceBridgeInterfaceBasePath(bridgeName, name string) []any {
	return []any{"interfaces", "bridge", bridgeName, "interface", name}
}

// Create sets up the InterfaceBridgeInterface on VyOS.
func (InterfaceBridgeInterface) Create(
	ctx context.Context,
	req infer.CreateRequest[InterfaceBridgeInterfaceArgs],
) (infer.CreateResponse[InterfaceBridgeInterfaceState], error) {
	if req.DryRun {
		return infer.CreateResponse[InterfaceBridgeInterfaceState]{
			ID:     req.Inputs.Name,
			Output: InterfaceBridgeInterfaceState{InterfaceBridgeInterfaceArgs: req.Inputs},
		}, nil
	}

	ops := buildInterfaceBridgeInterfaceOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[InterfaceBridgeInterfaceState]{},
			fmt.Errorf("configure InterfaceBridgeInterface %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[InterfaceBridgeInterfaceState]{
		ID:     req.Inputs.Name,
		Output: InterfaceBridgeInterfaceState{InterfaceBridgeInterfaceArgs: req.Inputs},
	}, nil
}

// Read fetches the current InterfaceBridgeInterface config from VyOS.
func (InterfaceBridgeInterface) Read(
	ctx context.Context,
	req infer.ReadRequest[InterfaceBridgeInterfaceArgs, InterfaceBridgeInterfaceState],
) (infer.ReadResponse[InterfaceBridgeInterfaceArgs, InterfaceBridgeInterfaceState], error) {
	client := getClient(ctx)
	base := interfaceBridgeInterfaceBasePath(req.State.BridgeName, req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := InterfaceBridgeInterfaceArgs{BridgeName: req.State.BridgeName, Name: req.State.Name}
			state := InterfaceBridgeInterfaceState{InterfaceBridgeInterfaceArgs: args}
			return infer.ReadResponse[InterfaceBridgeInterfaceArgs, InterfaceBridgeInterfaceState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[InterfaceBridgeInterfaceArgs, InterfaceBridgeInterfaceState]{},
			fmt.Errorf("read InterfaceBridgeInterface %s: %w", req.State.Name, err)
	}

	args, err := parseInterfaceBridgeInterfaceConfig(req.State.BridgeName, req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[InterfaceBridgeInterfaceArgs, InterfaceBridgeInterfaceState]{},
			fmt.Errorf("parse InterfaceBridgeInterface %s config: %w", req.State.Name, err)
	}

	state := InterfaceBridgeInterfaceState{InterfaceBridgeInterfaceArgs: args}
	return infer.ReadResponse[InterfaceBridgeInterfaceArgs, InterfaceBridgeInterfaceState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing InterfaceBridgeInterface configuration.
func (InterfaceBridgeInterface) Update(
	ctx context.Context,
	req infer.UpdateRequest[InterfaceBridgeInterfaceArgs, InterfaceBridgeInterfaceState],
) (infer.UpdateResponse[InterfaceBridgeInterfaceState], error) {
	if req.DryRun {
		return infer.UpdateResponse[InterfaceBridgeInterfaceState]{
			Output: InterfaceBridgeInterfaceState{InterfaceBridgeInterfaceArgs: req.Inputs},
		}, nil
	}

	ops := buildInterfaceBridgeInterfaceUpdateOps(req.State.InterfaceBridgeInterfaceArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[InterfaceBridgeInterfaceState]{},
				fmt.Errorf("update InterfaceBridgeInterface %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[InterfaceBridgeInterfaceState]{
		Output: InterfaceBridgeInterfaceState{InterfaceBridgeInterfaceArgs: req.Inputs},
	}, nil
}

// Delete removes the InterfaceBridgeInterface configuration from VyOS.
func (InterfaceBridgeInterface) Delete(
	ctx context.Context,
	req infer.DeleteRequest[InterfaceBridgeInterfaceState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := interfaceBridgeInterfaceBasePath(req.State.BridgeName, req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete InterfaceBridgeInterface %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildInterfaceBridgeInterfaceOps builds set operations for all non-nil fields.
func buildInterfaceBridgeInterfaceOps(args InterfaceBridgeInterfaceArgs) []vyosclient.Operation {
	base := interfaceBridgeInterfaceBasePath(args.BridgeName, args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}

	if args.NativeVLAN != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "native-vlan"), Value: strconv.Itoa(*args.NativeVLAN)})
	}

	for _, v := range args.AllowedVLAN {
		vp := make([]string, 0, 1+1)
		vp = append(vp, "allowed-vlan")
		vp = append(vp, v)
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, vp...)})
	}

	if args.Cost != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "cost"), Value: strconv.Itoa(*args.Cost)})
	}

	if args.Priority != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "priority"), Value: strconv.Itoa(*args.Priority)})
	}

	if args.Isolated != nil && *args.Isolated {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "isolated")})
	}

	if args.BpduGuard != nil && *args.BpduGuard {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "bpdu-guard")})
	}

	if args.RootGuard != nil && *args.RootGuard {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "root-guard")})
	}

	return ops
}

// buildInterfaceBridgeInterfaceUpdateOps computes the diff between previous and current state.
func buildInterfaceBridgeInterfaceUpdateOps(prev, cur InterfaceBridgeInterfaceArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	base := interfaceBridgeInterfaceBasePath(cur.BridgeName, cur.Name)

	ops = append(ops, diffIntField(base, []string{"native-vlan"}, prev.NativeVLAN, cur.NativeVLAN)...)

	ops = append(ops, diffMultiField(base, []string{"allowed-vlan"}, prev.AllowedVLAN, cur.AllowedVLAN)...)

	ops = append(ops, diffIntField(base, []string{"cost"}, prev.Cost, cur.Cost)...)

	ops = append(ops, diffIntField(base, []string{"priority"}, prev.Priority, cur.Priority)...)

	ops = append(ops, diffBoolField(base, []string{"isolated"}, prev.Isolated, cur.Isolated)...)

	ops = append(ops, diffBoolField(base, []string{"bpdu-guard"}, prev.BpduGuard, cur.BpduGuard)...)

	ops = append(ops, diffBoolField(base, []string{"root-guard"}, prev.RootGuard, cur.RootGuard)...)

	return ops
}

// parseInterfaceBridgeInterfaceConfig unmarshals VyOS ShowConfig JSON.
func parseInterfaceBridgeInterfaceConfig(bridgeName, name string, data json.RawMessage) (InterfaceBridgeInterfaceArgs, error) {
	args := InterfaceBridgeInterfaceArgs{
		BridgeName: bridgeName,
		Name:       name,
	}

	if v, ok := getNestedValue(data, []string{"native-vlan"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return InterfaceBridgeInterfaceArgs{}, fmt.Errorf("parse native-vlan: %w", err)
		}
		args.NativeVLAN = &n
	}

	if v, ok := getNestedValue(data, []string{"allowed-vlan"}); ok {
		vals, err := parseMultiValue(v)
		if err != nil {
			return InterfaceBridgeInterfaceArgs{}, fmt.Errorf("parse allowed-vlan: %w", err)
		}
		args.AllowedVLAN = vals
	}

	if v, ok := getNestedValue(data, []string{"cost"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return InterfaceBridgeInterfaceArgs{}, fmt.Errorf("parse cost: %w", err)
		}
		args.Cost = &n
	}

	if v, ok := getNestedValue(data, []string{"priority"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return InterfaceBridgeInterfaceArgs{}, fmt.Errorf("parse priority: %w", err)
		}
		args.Priority = &n
	}

	if _, ok := getNestedValue(data, []string{"isolated"}); ok {
		t := true
		args.Isolated = &t
	}

	if _, ok := getNestedValue(data, []string{"bpdu-guard"}); ok {
		t := true
		args.BpduGuard = &t
	}

	if _, ok := getNestedValue(data, []string{"root-guard"}); ok {
		t := true
		args.RootGuard = &t
	}

	return args, nil
}
