// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
	"regexp"
	"strconv"
)

// SystemConntrackTimeoutCustomIPv4Rule manages a VyOS SystemConntrackTimeoutCustomIPv4Rule configuration.
type SystemConntrackTimeoutCustomIPv4Rule struct{}

// SystemConntrackTimeoutCustomIPv4RuleArgs defines the inputs for the SystemConntrackTimeoutCustomIPv4Rule resource.
type SystemConntrackTimeoutCustomIPv4RuleArgs struct {
	Name                   string  `pulumi:"name"`
	Description            *string `pulumi:"description,optional"`
	InboundInterface       *string `pulumi:"inboundInterface,optional"`
	DestinationAddress     *string `pulumi:"destinationAddress,optional"`
	DestinationPort        *string `pulumi:"destinationPort,optional"`
	ProtocolTCPCloseWait   *int    `pulumi:"protocolTCPCloseWait,optional"`
	ProtocolTCPClose       *int    `pulumi:"protocolTCPClose,optional"`
	ProtocolTCPEstablished *int    `pulumi:"protocolTCPEstablished,optional"`
	ProtocolTCPFinWait     *int    `pulumi:"protocolTCPFinWait,optional"`
	ProtocolTCPLastAck     *int    `pulumi:"protocolTCPLastAck,optional"`
	ProtocolTCPSynRecv     *int    `pulumi:"protocolTCPSynRecv,optional"`
	ProtocolTCPSynSent     *int    `pulumi:"protocolTCPSynSent,optional"`
	ProtocolTCPTimeWait    *int    `pulumi:"protocolTCPTimeWait,optional"`
	ProtocolUDPReplied     *int    `pulumi:"protocolUDPReplied,optional"`
	ProtocolUDPUnreplied   *int    `pulumi:"protocolUDPUnreplied,optional"`
	SourceAddress          *string `pulumi:"sourceAddress,optional"`
	SourcePort             *string `pulumi:"sourcePort,optional"`
}

// SystemConntrackTimeoutCustomIPv4RuleState defines the outputs for the SystemConntrackTimeoutCustomIPv4Rule resource.
type SystemConntrackTimeoutCustomIPv4RuleState struct {
	SystemConntrackTimeoutCustomIPv4RuleArgs
}

// Annotate provides schema metadata for the resource.
func (*SystemConntrackTimeoutCustomIPv4Rule) Annotate(a infer.Annotator) {
	a.Describe(new(SystemConntrackTimeoutCustomIPv4Rule), "Manages a VyOS Rule number.")
}

// Annotate provides schema metadata for the inputs.
func (args *SystemConntrackTimeoutCustomIPv4RuleArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.Name, "Rule number")
	a.Describe(&args.Description, "Description")
	a.Describe(&args.InboundInterface, "Interface to apply custom connection timers on")
	a.Describe(&args.DestinationAddress, "IP address, subnet, or range")
	a.Describe(&args.DestinationPort, "Port number")
	a.Describe(&args.ProtocolTCPCloseWait, "TCP CLOSE-WAIT timeout in seconds")
	a.Describe(&args.ProtocolTCPClose, "TCP CLOSE timeout in seconds")
	a.Describe(&args.ProtocolTCPEstablished, "TCP ESTABLISHED timeout in seconds")
	a.Describe(&args.ProtocolTCPFinWait, "TCP FIN-WAIT timeout in seconds")
	a.Describe(&args.ProtocolTCPLastAck, "TCP LAST-ACK timeout in seconds")
	a.Describe(&args.ProtocolTCPSynRecv, "TCP SYN-RECEIVED timeout in seconds")
	a.Describe(&args.ProtocolTCPSynSent, "TCP SYN-SENT timeout in seconds")
	a.Describe(&args.ProtocolTCPTimeWait, "TCP TIME-WAIT timeout in seconds")
	a.Describe(&args.ProtocolUDPReplied, "Timeout for UDP connection seen in both directions")
	a.Describe(&args.ProtocolUDPUnreplied, "Timeout for unreplied UDP")
	a.Describe(&args.SourceAddress, "IP address, subnet, or range")
	a.Describe(&args.SourcePort, "Port number")
}

var systemConntrackTimeoutCustomIPv4RuleDescriptionRe = regexp.MustCompile(`^(?:` + ".{0,255}" + `)$`)

// Check validates the SystemConntrackTimeoutCustomIPv4Rule inputs.
func (SystemConntrackTimeoutCustomIPv4Rule) Check(
	ctx context.Context,
	req infer.CheckRequest,
) (infer.CheckResponse[SystemConntrackTimeoutCustomIPv4RuleArgs], error) {
	inputs, failures, err := infer.DefaultCheck[SystemConntrackTimeoutCustomIPv4RuleArgs](ctx, req.NewInputs)
	if err != nil {
		return infer.CheckResponse[SystemConntrackTimeoutCustomIPv4RuleArgs]{}, err
	}
	if inputs.Description != nil {
		if f := checkRegex(*inputs.Description, systemConntrackTimeoutCustomIPv4RuleDescriptionRe, "description", "Description too long (limit 255 characters)"); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.ProtocolTCPCloseWait != nil {
		if f := checkIntRange(int64(*inputs.ProtocolTCPCloseWait), 1, 21474836, "protocolTCPCloseWait", ""); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.ProtocolTCPClose != nil {
		if f := checkIntRange(int64(*inputs.ProtocolTCPClose), 1, 21474836, "protocolTCPClose", ""); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.ProtocolTCPEstablished != nil {
		if f := checkIntRange(int64(*inputs.ProtocolTCPEstablished), 1, 21474836, "protocolTCPEstablished", ""); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.ProtocolTCPFinWait != nil {
		if f := checkIntRange(int64(*inputs.ProtocolTCPFinWait), 1, 21474836, "protocolTCPFinWait", ""); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.ProtocolTCPLastAck != nil {
		if f := checkIntRange(int64(*inputs.ProtocolTCPLastAck), 1, 21474836, "protocolTCPLastAck", ""); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.ProtocolTCPSynRecv != nil {
		if f := checkIntRange(int64(*inputs.ProtocolTCPSynRecv), 1, 21474836, "protocolTCPSynRecv", ""); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.ProtocolTCPSynSent != nil {
		if f := checkIntRange(int64(*inputs.ProtocolTCPSynSent), 1, 21474836, "protocolTCPSynSent", ""); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.ProtocolTCPTimeWait != nil {
		if f := checkIntRange(int64(*inputs.ProtocolTCPTimeWait), 1, 21474836, "protocolTCPTimeWait", ""); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.ProtocolUDPReplied != nil {
		if f := checkIntRange(int64(*inputs.ProtocolUDPReplied), 1, 21474836, "protocolUDPReplied", ""); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.ProtocolUDPUnreplied != nil {
		if f := checkIntRange(int64(*inputs.ProtocolUDPUnreplied), 1, 21474836, "protocolUDPUnreplied", ""); f != nil {
			failures = append(failures, *f)
		}
	}

	return infer.CheckResponse[SystemConntrackTimeoutCustomIPv4RuleArgs]{Inputs: inputs, Failures: failures}, nil
}

func systemConntrackTimeoutCustomIPv4RuleBasePath(name string) []any {
	return []any{"system", "conntrack", "timeout", "custom", "ipv4", "rule", name}
}

// Create sets up the SystemConntrackTimeoutCustomIPv4Rule on VyOS.
func (SystemConntrackTimeoutCustomIPv4Rule) Create(
	ctx context.Context,
	req infer.CreateRequest[SystemConntrackTimeoutCustomIPv4RuleArgs],
) (infer.CreateResponse[SystemConntrackTimeoutCustomIPv4RuleState], error) {
	if req.DryRun {
		return infer.CreateResponse[SystemConntrackTimeoutCustomIPv4RuleState]{
			ID:     req.Inputs.Name,
			Output: SystemConntrackTimeoutCustomIPv4RuleState{SystemConntrackTimeoutCustomIPv4RuleArgs: req.Inputs},
		}, nil
	}

	ops := buildSystemConntrackTimeoutCustomIPv4RuleOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[SystemConntrackTimeoutCustomIPv4RuleState]{},
			fmt.Errorf("configure SystemConntrackTimeoutCustomIPv4Rule %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[SystemConntrackTimeoutCustomIPv4RuleState]{
		ID:     req.Inputs.Name,
		Output: SystemConntrackTimeoutCustomIPv4RuleState{SystemConntrackTimeoutCustomIPv4RuleArgs: req.Inputs},
	}, nil
}

// Read fetches the current SystemConntrackTimeoutCustomIPv4Rule config from VyOS.
func (SystemConntrackTimeoutCustomIPv4Rule) Read(
	ctx context.Context,
	req infer.ReadRequest[SystemConntrackTimeoutCustomIPv4RuleArgs, SystemConntrackTimeoutCustomIPv4RuleState],
) (infer.ReadResponse[SystemConntrackTimeoutCustomIPv4RuleArgs, SystemConntrackTimeoutCustomIPv4RuleState], error) {
	client := getClient(ctx)
	base := systemConntrackTimeoutCustomIPv4RuleBasePath(req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := SystemConntrackTimeoutCustomIPv4RuleArgs{Name: req.State.Name}
			state := SystemConntrackTimeoutCustomIPv4RuleState{SystemConntrackTimeoutCustomIPv4RuleArgs: args}
			return infer.ReadResponse[SystemConntrackTimeoutCustomIPv4RuleArgs, SystemConntrackTimeoutCustomIPv4RuleState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[SystemConntrackTimeoutCustomIPv4RuleArgs, SystemConntrackTimeoutCustomIPv4RuleState]{},
			fmt.Errorf("read SystemConntrackTimeoutCustomIPv4Rule %s: %w", req.State.Name, err)
	}

	args, err := parseSystemConntrackTimeoutCustomIPv4RuleConfig(req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[SystemConntrackTimeoutCustomIPv4RuleArgs, SystemConntrackTimeoutCustomIPv4RuleState]{},
			fmt.Errorf("parse SystemConntrackTimeoutCustomIPv4Rule %s config: %w", req.State.Name, err)
	}

	state := SystemConntrackTimeoutCustomIPv4RuleState{SystemConntrackTimeoutCustomIPv4RuleArgs: args}
	return infer.ReadResponse[SystemConntrackTimeoutCustomIPv4RuleArgs, SystemConntrackTimeoutCustomIPv4RuleState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing SystemConntrackTimeoutCustomIPv4Rule configuration.
func (SystemConntrackTimeoutCustomIPv4Rule) Update(
	ctx context.Context,
	req infer.UpdateRequest[SystemConntrackTimeoutCustomIPv4RuleArgs, SystemConntrackTimeoutCustomIPv4RuleState],
) (infer.UpdateResponse[SystemConntrackTimeoutCustomIPv4RuleState], error) {
	if req.DryRun {
		return infer.UpdateResponse[SystemConntrackTimeoutCustomIPv4RuleState]{
			Output: SystemConntrackTimeoutCustomIPv4RuleState{SystemConntrackTimeoutCustomIPv4RuleArgs: req.Inputs},
		}, nil
	}

	ops := buildSystemConntrackTimeoutCustomIPv4RuleUpdateOps(req.State.SystemConntrackTimeoutCustomIPv4RuleArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[SystemConntrackTimeoutCustomIPv4RuleState]{},
				fmt.Errorf("update SystemConntrackTimeoutCustomIPv4Rule %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[SystemConntrackTimeoutCustomIPv4RuleState]{
		Output: SystemConntrackTimeoutCustomIPv4RuleState{SystemConntrackTimeoutCustomIPv4RuleArgs: req.Inputs},
	}, nil
}

// Delete removes the SystemConntrackTimeoutCustomIPv4Rule configuration from VyOS.
func (SystemConntrackTimeoutCustomIPv4Rule) Delete(
	ctx context.Context,
	req infer.DeleteRequest[SystemConntrackTimeoutCustomIPv4RuleState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := systemConntrackTimeoutCustomIPv4RuleBasePath(req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete SystemConntrackTimeoutCustomIPv4Rule %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildSystemConntrackTimeoutCustomIPv4RuleOps builds set operations for all non-nil fields.
func buildSystemConntrackTimeoutCustomIPv4RuleOps(args SystemConntrackTimeoutCustomIPv4RuleArgs) []vyosclient.Operation {
	base := systemConntrackTimeoutCustomIPv4RuleBasePath(args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}

	if args.Description != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "description"), Value: *args.Description})
	}

	if args.InboundInterface != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "inbound-interface"), Value: *args.InboundInterface})
	}

	if args.DestinationAddress != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "destination", "address"), Value: *args.DestinationAddress})
	}

	if args.DestinationPort != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "destination", "port"), Value: *args.DestinationPort})
	}

	if args.ProtocolTCPCloseWait != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "protocol", "tcp", "close-wait"), Value: strconv.Itoa(*args.ProtocolTCPCloseWait)})
	}

	if args.ProtocolTCPClose != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "protocol", "tcp", "close"), Value: strconv.Itoa(*args.ProtocolTCPClose)})
	}

	if args.ProtocolTCPEstablished != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "protocol", "tcp", "established"), Value: strconv.Itoa(*args.ProtocolTCPEstablished)})
	}

	if args.ProtocolTCPFinWait != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "protocol", "tcp", "fin-wait"), Value: strconv.Itoa(*args.ProtocolTCPFinWait)})
	}

	if args.ProtocolTCPLastAck != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "protocol", "tcp", "last-ack"), Value: strconv.Itoa(*args.ProtocolTCPLastAck)})
	}

	if args.ProtocolTCPSynRecv != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "protocol", "tcp", "syn-recv"), Value: strconv.Itoa(*args.ProtocolTCPSynRecv)})
	}

	if args.ProtocolTCPSynSent != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "protocol", "tcp", "syn-sent"), Value: strconv.Itoa(*args.ProtocolTCPSynSent)})
	}

	if args.ProtocolTCPTimeWait != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "protocol", "tcp", "time-wait"), Value: strconv.Itoa(*args.ProtocolTCPTimeWait)})
	}

	if args.ProtocolUDPReplied != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "protocol", "udp", "replied"), Value: strconv.Itoa(*args.ProtocolUDPReplied)})
	}

	if args.ProtocolUDPUnreplied != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "protocol", "udp", "unreplied"), Value: strconv.Itoa(*args.ProtocolUDPUnreplied)})
	}

	if args.SourceAddress != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "source", "address"), Value: *args.SourceAddress})
	}

	if args.SourcePort != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "source", "port"), Value: *args.SourcePort})
	}

	return ops
}

// buildSystemConntrackTimeoutCustomIPv4RuleUpdateOps computes the diff between previous and current state.
func buildSystemConntrackTimeoutCustomIPv4RuleUpdateOps(prev, cur SystemConntrackTimeoutCustomIPv4RuleArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	base := systemConntrackTimeoutCustomIPv4RuleBasePath(cur.Name)

	ops = append(ops, diffStringField(base, []string{"description"}, prev.Description, cur.Description)...)

	ops = append(ops, diffStringField(base, []string{"inbound-interface"}, prev.InboundInterface, cur.InboundInterface)...)

	ops = append(ops, diffStringField(base, []string{"destination", "address"}, prev.DestinationAddress, cur.DestinationAddress)...)

	ops = append(ops, diffStringField(base, []string{"destination", "port"}, prev.DestinationPort, cur.DestinationPort)...)

	ops = append(ops, diffIntField(base, []string{"protocol", "tcp", "close-wait"}, prev.ProtocolTCPCloseWait, cur.ProtocolTCPCloseWait)...)

	ops = append(ops, diffIntField(base, []string{"protocol", "tcp", "close"}, prev.ProtocolTCPClose, cur.ProtocolTCPClose)...)

	ops = append(ops, diffIntField(base, []string{"protocol", "tcp", "established"}, prev.ProtocolTCPEstablished, cur.ProtocolTCPEstablished)...)

	ops = append(ops, diffIntField(base, []string{"protocol", "tcp", "fin-wait"}, prev.ProtocolTCPFinWait, cur.ProtocolTCPFinWait)...)

	ops = append(ops, diffIntField(base, []string{"protocol", "tcp", "last-ack"}, prev.ProtocolTCPLastAck, cur.ProtocolTCPLastAck)...)

	ops = append(ops, diffIntField(base, []string{"protocol", "tcp", "syn-recv"}, prev.ProtocolTCPSynRecv, cur.ProtocolTCPSynRecv)...)

	ops = append(ops, diffIntField(base, []string{"protocol", "tcp", "syn-sent"}, prev.ProtocolTCPSynSent, cur.ProtocolTCPSynSent)...)

	ops = append(ops, diffIntField(base, []string{"protocol", "tcp", "time-wait"}, prev.ProtocolTCPTimeWait, cur.ProtocolTCPTimeWait)...)

	ops = append(ops, diffIntField(base, []string{"protocol", "udp", "replied"}, prev.ProtocolUDPReplied, cur.ProtocolUDPReplied)...)

	ops = append(ops, diffIntField(base, []string{"protocol", "udp", "unreplied"}, prev.ProtocolUDPUnreplied, cur.ProtocolUDPUnreplied)...)

	ops = append(ops, diffStringField(base, []string{"source", "address"}, prev.SourceAddress, cur.SourceAddress)...)

	ops = append(ops, diffStringField(base, []string{"source", "port"}, prev.SourcePort, cur.SourcePort)...)

	return ops
}

// parseSystemConntrackTimeoutCustomIPv4RuleConfig unmarshals VyOS ShowConfig JSON.
func parseSystemConntrackTimeoutCustomIPv4RuleConfig(name string, data json.RawMessage) (SystemConntrackTimeoutCustomIPv4RuleArgs, error) {
	args := SystemConntrackTimeoutCustomIPv4RuleArgs{
		Name: name,
	}

	if v, ok := getNestedValue(data, []string{"description"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return SystemConntrackTimeoutCustomIPv4RuleArgs{}, fmt.Errorf("parse description: %w", err)
		}
		args.Description = &s
	}

	if v, ok := getNestedValue(data, []string{"inbound-interface"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return SystemConntrackTimeoutCustomIPv4RuleArgs{}, fmt.Errorf("parse inbound-interface: %w", err)
		}
		args.InboundInterface = &s
	}

	if v, ok := getNestedValue(data, []string{"destination", "address"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return SystemConntrackTimeoutCustomIPv4RuleArgs{}, fmt.Errorf("parse address: %w", err)
		}
		args.DestinationAddress = &s
	}

	if v, ok := getNestedValue(data, []string{"destination", "port"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return SystemConntrackTimeoutCustomIPv4RuleArgs{}, fmt.Errorf("parse port: %w", err)
		}
		args.DestinationPort = &s
	}

	if v, ok := getNestedValue(data, []string{"protocol", "tcp", "close-wait"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return SystemConntrackTimeoutCustomIPv4RuleArgs{}, fmt.Errorf("parse close-wait: %w", err)
		}
		args.ProtocolTCPCloseWait = &n
	}

	if v, ok := getNestedValue(data, []string{"protocol", "tcp", "close"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return SystemConntrackTimeoutCustomIPv4RuleArgs{}, fmt.Errorf("parse close: %w", err)
		}
		args.ProtocolTCPClose = &n
	}

	if v, ok := getNestedValue(data, []string{"protocol", "tcp", "established"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return SystemConntrackTimeoutCustomIPv4RuleArgs{}, fmt.Errorf("parse established: %w", err)
		}
		args.ProtocolTCPEstablished = &n
	}

	if v, ok := getNestedValue(data, []string{"protocol", "tcp", "fin-wait"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return SystemConntrackTimeoutCustomIPv4RuleArgs{}, fmt.Errorf("parse fin-wait: %w", err)
		}
		args.ProtocolTCPFinWait = &n
	}

	if v, ok := getNestedValue(data, []string{"protocol", "tcp", "last-ack"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return SystemConntrackTimeoutCustomIPv4RuleArgs{}, fmt.Errorf("parse last-ack: %w", err)
		}
		args.ProtocolTCPLastAck = &n
	}

	if v, ok := getNestedValue(data, []string{"protocol", "tcp", "syn-recv"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return SystemConntrackTimeoutCustomIPv4RuleArgs{}, fmt.Errorf("parse syn-recv: %w", err)
		}
		args.ProtocolTCPSynRecv = &n
	}

	if v, ok := getNestedValue(data, []string{"protocol", "tcp", "syn-sent"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return SystemConntrackTimeoutCustomIPv4RuleArgs{}, fmt.Errorf("parse syn-sent: %w", err)
		}
		args.ProtocolTCPSynSent = &n
	}

	if v, ok := getNestedValue(data, []string{"protocol", "tcp", "time-wait"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return SystemConntrackTimeoutCustomIPv4RuleArgs{}, fmt.Errorf("parse time-wait: %w", err)
		}
		args.ProtocolTCPTimeWait = &n
	}

	if v, ok := getNestedValue(data, []string{"protocol", "udp", "replied"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return SystemConntrackTimeoutCustomIPv4RuleArgs{}, fmt.Errorf("parse replied: %w", err)
		}
		args.ProtocolUDPReplied = &n
	}

	if v, ok := getNestedValue(data, []string{"protocol", "udp", "unreplied"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return SystemConntrackTimeoutCustomIPv4RuleArgs{}, fmt.Errorf("parse unreplied: %w", err)
		}
		args.ProtocolUDPUnreplied = &n
	}

	if v, ok := getNestedValue(data, []string{"source", "address"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return SystemConntrackTimeoutCustomIPv4RuleArgs{}, fmt.Errorf("parse address: %w", err)
		}
		args.SourceAddress = &s
	}

	if v, ok := getNestedValue(data, []string{"source", "port"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return SystemConntrackTimeoutCustomIPv4RuleArgs{}, fmt.Errorf("parse port: %w", err)
		}
		args.SourcePort = &s
	}

	return args, nil
}
