// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
	"strconv"
)

// VRFNameTarget manages a VyOS VRFNameTarget configuration.
type VRFNameTarget struct{}

// VRFNameTargetArgs defines the inputs for the VRFNameTarget resource.
type VRFNameTargetArgs struct {
	NameName                     string  `pulumi:"nameName"`
	Name                         string  `pulumi:"name"`
	Address                      *string `pulumi:"address,optional"`
	Port                         *int    `pulumi:"port,optional"`
	MinRetry                     *int    `pulumi:"minRetry,optional"`
	MaxRetry                     *int    `pulumi:"maxRetry,optional"`
	Mirror                       *bool   `pulumi:"mirror,optional"`
	MonitorIPv4UnicastLocalRib   *bool   `pulumi:"monitorIPv4UnicastLocalRib,optional"`
	MonitorIPv4UnicastPrePolicy  *bool   `pulumi:"monitorIPv4UnicastPrePolicy,optional"`
	MonitorIPv4UnicastPostPolicy *bool   `pulumi:"monitorIPv4UnicastPostPolicy,optional"`
	MonitorIPv6UnicastLocalRib   *bool   `pulumi:"monitorIPv6UnicastLocalRib,optional"`
	MonitorIPv6UnicastPrePolicy  *bool   `pulumi:"monitorIPv6UnicastPrePolicy,optional"`
	MonitorIPv6UnicastPostPolicy *bool   `pulumi:"monitorIPv6UnicastPostPolicy,optional"`
}

// VRFNameTargetState defines the outputs for the VRFNameTarget resource.
type VRFNameTargetState struct {
	VRFNameTargetArgs
}

// Annotate provides schema metadata for the resource.
func (*VRFNameTarget) Annotate(a infer.Annotator) {
	a.Describe(new(VRFNameTarget), "Manages a VyOS BMP target.")
}

// Annotate provides schema metadata for the inputs.
func (args *VRFNameTargetArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.NameName, "Parent tag node key")
	a.Describe(&args.Name, "BMP target")
	a.Describe(&args.Address, "IP address")
	a.Describe(&args.Port, "Port number used by connection")
	a.Describe(&args.MinRetry, "Minimum connection retry interval (in milliseconds)")
	a.Describe(&args.MaxRetry, "Maximum connection retry interval")
	a.Describe(&args.Mirror, "Send BMP route mirroring messages")
	a.Describe(&args.MonitorIPv4UnicastLocalRib, "Enable BMP monitoring of local RIB")
	a.Describe(&args.MonitorIPv4UnicastPrePolicy, "Send state before policy and filter processing")
	a.Describe(&args.MonitorIPv4UnicastPostPolicy, "Send state with policy and filters applied")
	a.Describe(&args.MonitorIPv6UnicastLocalRib, "Enable BMP monitoring of local RIB")
	a.Describe(&args.MonitorIPv6UnicastPrePolicy, "Send state before policy and filter processing")
	a.Describe(&args.MonitorIPv6UnicastPostPolicy, "Send state with policy and filters applied")
}

// Check validates the VRFNameTarget inputs.
func (VRFNameTarget) Check(
	ctx context.Context,
	req infer.CheckRequest,
) (infer.CheckResponse[VRFNameTargetArgs], error) {
	inputs, failures, err := infer.DefaultCheck[VRFNameTargetArgs](ctx, req.NewInputs)
	if err != nil {
		return infer.CheckResponse[VRFNameTargetArgs]{}, err
	}
	if inputs.Port != nil {
		if f := checkIntRange(int64(*inputs.Port), 1, 65535, "port", "Port number must be in range 1 to 65535"); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.MinRetry != nil {
		if f := checkIntRange(int64(*inputs.MinRetry), 100, 86400000, "minRetry", ""); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.MaxRetry != nil {
		if f := checkIntRange(int64(*inputs.MaxRetry), 100, 86400000, "maxRetry", ""); f != nil {
			failures = append(failures, *f)
		}
	}

	return infer.CheckResponse[VRFNameTargetArgs]{Inputs: inputs, Failures: failures}, nil
}

func vrfNameTargetBasePath(nameName, name string) []any {
	return []any{"vrf", "name", nameName, "target", name}
}

// Create sets up the VRFNameTarget on VyOS.
func (VRFNameTarget) Create(
	ctx context.Context,
	req infer.CreateRequest[VRFNameTargetArgs],
) (infer.CreateResponse[VRFNameTargetState], error) {
	if req.DryRun {
		return infer.CreateResponse[VRFNameTargetState]{
			ID:     req.Inputs.Name,
			Output: VRFNameTargetState{VRFNameTargetArgs: req.Inputs},
		}, nil
	}

	ops := buildVRFNameTargetOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[VRFNameTargetState]{},
			fmt.Errorf("configure VRFNameTarget %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[VRFNameTargetState]{
		ID:     req.Inputs.Name,
		Output: VRFNameTargetState{VRFNameTargetArgs: req.Inputs},
	}, nil
}

// Read fetches the current VRFNameTarget config from VyOS.
func (VRFNameTarget) Read(
	ctx context.Context,
	req infer.ReadRequest[VRFNameTargetArgs, VRFNameTargetState],
) (infer.ReadResponse[VRFNameTargetArgs, VRFNameTargetState], error) {
	client := getClient(ctx)
	base := vrfNameTargetBasePath(req.State.NameName, req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := VRFNameTargetArgs{NameName: req.State.NameName, Name: req.State.Name}
			state := VRFNameTargetState{VRFNameTargetArgs: args}
			return infer.ReadResponse[VRFNameTargetArgs, VRFNameTargetState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[VRFNameTargetArgs, VRFNameTargetState]{},
			fmt.Errorf("read VRFNameTarget %s: %w", req.State.Name, err)
	}

	args, err := parseVRFNameTargetConfig(req.State.NameName, req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[VRFNameTargetArgs, VRFNameTargetState]{},
			fmt.Errorf("parse VRFNameTarget %s config: %w", req.State.Name, err)
	}

	state := VRFNameTargetState{VRFNameTargetArgs: args}
	return infer.ReadResponse[VRFNameTargetArgs, VRFNameTargetState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing VRFNameTarget configuration.
func (VRFNameTarget) Update(
	ctx context.Context,
	req infer.UpdateRequest[VRFNameTargetArgs, VRFNameTargetState],
) (infer.UpdateResponse[VRFNameTargetState], error) {
	if req.DryRun {
		return infer.UpdateResponse[VRFNameTargetState]{
			Output: VRFNameTargetState{VRFNameTargetArgs: req.Inputs},
		}, nil
	}

	ops := buildVRFNameTargetUpdateOps(req.State.VRFNameTargetArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[VRFNameTargetState]{},
				fmt.Errorf("update VRFNameTarget %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[VRFNameTargetState]{
		Output: VRFNameTargetState{VRFNameTargetArgs: req.Inputs},
	}, nil
}

// Delete removes the VRFNameTarget configuration from VyOS.
func (VRFNameTarget) Delete(
	ctx context.Context,
	req infer.DeleteRequest[VRFNameTargetState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := vrfNameTargetBasePath(req.State.NameName, req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete VRFNameTarget %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildVRFNameTargetOps builds set operations for all non-nil fields.
func buildVRFNameTargetOps(args VRFNameTargetArgs) []vyosclient.Operation {
	base := vrfNameTargetBasePath(args.NameName, args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}

	if args.Address != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "address"), Value: *args.Address})
	}

	if args.Port != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "port"), Value: strconv.Itoa(*args.Port)})
	}

	if args.MinRetry != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "min-retry"), Value: strconv.Itoa(*args.MinRetry)})
	}

	if args.MaxRetry != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "max-retry"), Value: strconv.Itoa(*args.MaxRetry)})
	}

	if args.Mirror != nil && *args.Mirror {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "mirror")})
	}

	if args.MonitorIPv4UnicastLocalRib != nil && *args.MonitorIPv4UnicastLocalRib {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "monitor", "ipv4-unicast", "local-rib")})
	}

	if args.MonitorIPv4UnicastPrePolicy != nil && *args.MonitorIPv4UnicastPrePolicy {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "monitor", "ipv4-unicast", "pre-policy")})
	}

	if args.MonitorIPv4UnicastPostPolicy != nil && *args.MonitorIPv4UnicastPostPolicy {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "monitor", "ipv4-unicast", "post-policy")})
	}

	if args.MonitorIPv6UnicastLocalRib != nil && *args.MonitorIPv6UnicastLocalRib {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "monitor", "ipv6-unicast", "local-rib")})
	}

	if args.MonitorIPv6UnicastPrePolicy != nil && *args.MonitorIPv6UnicastPrePolicy {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "monitor", "ipv6-unicast", "pre-policy")})
	}

	if args.MonitorIPv6UnicastPostPolicy != nil && *args.MonitorIPv6UnicastPostPolicy {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "monitor", "ipv6-unicast", "post-policy")})
	}

	return ops
}

// buildVRFNameTargetUpdateOps computes the diff between previous and current state.
func buildVRFNameTargetUpdateOps(prev, cur VRFNameTargetArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	base := vrfNameTargetBasePath(cur.NameName, cur.Name)

	ops = append(ops, diffStringField(base, []string{"address"}, prev.Address, cur.Address)...)

	ops = append(ops, diffIntField(base, []string{"port"}, prev.Port, cur.Port)...)

	ops = append(ops, diffIntField(base, []string{"min-retry"}, prev.MinRetry, cur.MinRetry)...)

	ops = append(ops, diffIntField(base, []string{"max-retry"}, prev.MaxRetry, cur.MaxRetry)...)

	ops = append(ops, diffBoolField(base, []string{"mirror"}, prev.Mirror, cur.Mirror)...)

	ops = append(ops, diffBoolField(base, []string{"monitor", "ipv4-unicast", "local-rib"}, prev.MonitorIPv4UnicastLocalRib, cur.MonitorIPv4UnicastLocalRib)...)

	ops = append(ops, diffBoolField(base, []string{"monitor", "ipv4-unicast", "pre-policy"}, prev.MonitorIPv4UnicastPrePolicy, cur.MonitorIPv4UnicastPrePolicy)...)

	ops = append(ops, diffBoolField(base, []string{"monitor", "ipv4-unicast", "post-policy"}, prev.MonitorIPv4UnicastPostPolicy, cur.MonitorIPv4UnicastPostPolicy)...)

	ops = append(ops, diffBoolField(base, []string{"monitor", "ipv6-unicast", "local-rib"}, prev.MonitorIPv6UnicastLocalRib, cur.MonitorIPv6UnicastLocalRib)...)

	ops = append(ops, diffBoolField(base, []string{"monitor", "ipv6-unicast", "pre-policy"}, prev.MonitorIPv6UnicastPrePolicy, cur.MonitorIPv6UnicastPrePolicy)...)

	ops = append(ops, diffBoolField(base, []string{"monitor", "ipv6-unicast", "post-policy"}, prev.MonitorIPv6UnicastPostPolicy, cur.MonitorIPv6UnicastPostPolicy)...)

	return ops
}

// parseVRFNameTargetConfig unmarshals VyOS ShowConfig JSON.
func parseVRFNameTargetConfig(nameName, name string, data json.RawMessage) (VRFNameTargetArgs, error) {
	args := VRFNameTargetArgs{
		NameName: nameName,
		Name:     name,
	}

	if v, ok := getNestedValue(data, []string{"address"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return VRFNameTargetArgs{}, fmt.Errorf("parse address: %w", err)
		}
		args.Address = &s
	}

	if v, ok := getNestedValue(data, []string{"port"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return VRFNameTargetArgs{}, fmt.Errorf("parse port: %w", err)
		}
		args.Port = &n
	}

	if v, ok := getNestedValue(data, []string{"min-retry"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return VRFNameTargetArgs{}, fmt.Errorf("parse min-retry: %w", err)
		}
		args.MinRetry = &n
	}

	if v, ok := getNestedValue(data, []string{"max-retry"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return VRFNameTargetArgs{}, fmt.Errorf("parse max-retry: %w", err)
		}
		args.MaxRetry = &n
	}

	if _, ok := getNestedValue(data, []string{"mirror"}); ok {
		t := true
		args.Mirror = &t
	}

	if _, ok := getNestedValue(data, []string{"monitor", "ipv4-unicast", "local-rib"}); ok {
		t := true
		args.MonitorIPv4UnicastLocalRib = &t
	}

	if _, ok := getNestedValue(data, []string{"monitor", "ipv4-unicast", "pre-policy"}); ok {
		t := true
		args.MonitorIPv4UnicastPrePolicy = &t
	}

	if _, ok := getNestedValue(data, []string{"monitor", "ipv4-unicast", "post-policy"}); ok {
		t := true
		args.MonitorIPv4UnicastPostPolicy = &t
	}

	if _, ok := getNestedValue(data, []string{"monitor", "ipv6-unicast", "local-rib"}); ok {
		t := true
		args.MonitorIPv6UnicastLocalRib = &t
	}

	if _, ok := getNestedValue(data, []string{"monitor", "ipv6-unicast", "pre-policy"}); ok {
		t := true
		args.MonitorIPv6UnicastPrePolicy = &t
	}

	if _, ok := getNestedValue(data, []string{"monitor", "ipv6-unicast", "post-policy"}); ok {
		t := true
		args.MonitorIPv6UnicastPostPolicy = &t
	}

	return args, nil
}
