// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
	"regexp"
)

// SystemConsoleDevice manages a VyOS SystemConsoleDevice configuration.
type SystemConsoleDevice struct{}

// SystemConsoleDeviceArgs defines the inputs for the SystemConsoleDevice resource.
type SystemConsoleDeviceArgs struct {
	Name  string  `pulumi:"name"`
	Speed *string `pulumi:"speed,optional"`
}

// SystemConsoleDeviceState defines the outputs for the SystemConsoleDevice resource.
type SystemConsoleDeviceState struct {
	SystemConsoleDeviceArgs
}

// Annotate provides schema metadata for the resource.
func (*SystemConsoleDevice) Annotate(a infer.Annotator) {
	a.Describe(new(SystemConsoleDevice), "Manages a VyOS Serial console device name.")
}

// Annotate provides schema metadata for the inputs.
func (args *SystemConsoleDeviceArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.Name, "Serial console device name")
	a.Describe(&args.Speed, "Console baud rate")
}

var systemConsoleDeviceNameRe = regexp.MustCompile(`^(?:` + "(ttyS[0-9]+|hvc[0-9]+|usb[0-9]+b.*)" + `)$`)
var systemConsoleDeviceSpeedRe = regexp.MustCompile(`^(?:` + "(1200|2400|4800|9600|19200|38400|57600|115200)" + `)$`)

// Check validates the SystemConsoleDevice inputs.
func (SystemConsoleDevice) Check(
	ctx context.Context,
	req infer.CheckRequest,
) (infer.CheckResponse[SystemConsoleDeviceArgs], error) {
	inputs, failures, err := infer.DefaultCheck[SystemConsoleDeviceArgs](ctx, req.NewInputs)
	if err != nil {
		return infer.CheckResponse[SystemConsoleDeviceArgs]{}, err
	}
	if f := checkRegex(inputs.Name, systemConsoleDeviceNameRe, "name", ""); f != nil {
		failures = append(failures, *f)
	}
	if inputs.Speed != nil {
		if f := checkRegex(*inputs.Speed, systemConsoleDeviceSpeedRe, "speed", ""); f != nil {
			failures = append(failures, *f)
		}
	}

	return infer.CheckResponse[SystemConsoleDeviceArgs]{Inputs: inputs, Failures: failures}, nil
}

func systemConsoleDeviceBasePath(name string) []any {
	return []any{"system", "console", "device", name}
}

// Create sets up the SystemConsoleDevice on VyOS.
func (SystemConsoleDevice) Create(
	ctx context.Context,
	req infer.CreateRequest[SystemConsoleDeviceArgs],
) (infer.CreateResponse[SystemConsoleDeviceState], error) {
	if req.DryRun {
		return infer.CreateResponse[SystemConsoleDeviceState]{
			ID:     req.Inputs.Name,
			Output: SystemConsoleDeviceState{SystemConsoleDeviceArgs: req.Inputs},
		}, nil
	}

	ops := buildSystemConsoleDeviceOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[SystemConsoleDeviceState]{},
			fmt.Errorf("configure SystemConsoleDevice %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[SystemConsoleDeviceState]{
		ID:     req.Inputs.Name,
		Output: SystemConsoleDeviceState{SystemConsoleDeviceArgs: req.Inputs},
	}, nil
}

// Read fetches the current SystemConsoleDevice config from VyOS.
func (SystemConsoleDevice) Read(
	ctx context.Context,
	req infer.ReadRequest[SystemConsoleDeviceArgs, SystemConsoleDeviceState],
) (infer.ReadResponse[SystemConsoleDeviceArgs, SystemConsoleDeviceState], error) {
	client := getClient(ctx)
	base := systemConsoleDeviceBasePath(req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := SystemConsoleDeviceArgs{Name: req.State.Name}
			state := SystemConsoleDeviceState{SystemConsoleDeviceArgs: args}
			return infer.ReadResponse[SystemConsoleDeviceArgs, SystemConsoleDeviceState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[SystemConsoleDeviceArgs, SystemConsoleDeviceState]{},
			fmt.Errorf("read SystemConsoleDevice %s: %w", req.State.Name, err)
	}

	args, err := parseSystemConsoleDeviceConfig(req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[SystemConsoleDeviceArgs, SystemConsoleDeviceState]{},
			fmt.Errorf("parse SystemConsoleDevice %s config: %w", req.State.Name, err)
	}

	state := SystemConsoleDeviceState{SystemConsoleDeviceArgs: args}
	return infer.ReadResponse[SystemConsoleDeviceArgs, SystemConsoleDeviceState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing SystemConsoleDevice configuration.
func (SystemConsoleDevice) Update(
	ctx context.Context,
	req infer.UpdateRequest[SystemConsoleDeviceArgs, SystemConsoleDeviceState],
) (infer.UpdateResponse[SystemConsoleDeviceState], error) {
	if req.DryRun {
		return infer.UpdateResponse[SystemConsoleDeviceState]{
			Output: SystemConsoleDeviceState{SystemConsoleDeviceArgs: req.Inputs},
		}, nil
	}

	ops := buildSystemConsoleDeviceUpdateOps(req.State.SystemConsoleDeviceArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[SystemConsoleDeviceState]{},
				fmt.Errorf("update SystemConsoleDevice %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[SystemConsoleDeviceState]{
		Output: SystemConsoleDeviceState{SystemConsoleDeviceArgs: req.Inputs},
	}, nil
}

// Delete removes the SystemConsoleDevice configuration from VyOS.
func (SystemConsoleDevice) Delete(
	ctx context.Context,
	req infer.DeleteRequest[SystemConsoleDeviceState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := systemConsoleDeviceBasePath(req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete SystemConsoleDevice %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildSystemConsoleDeviceOps builds set operations for all non-nil fields.
func buildSystemConsoleDeviceOps(args SystemConsoleDeviceArgs) []vyosclient.Operation {
	base := systemConsoleDeviceBasePath(args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}

	if args.Speed != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "speed"), Value: *args.Speed})
	}

	return ops
}

// buildSystemConsoleDeviceUpdateOps computes the diff between previous and current state.
func buildSystemConsoleDeviceUpdateOps(prev, cur SystemConsoleDeviceArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	base := systemConsoleDeviceBasePath(cur.Name)

	ops = append(ops, diffStringField(base, []string{"speed"}, prev.Speed, cur.Speed)...)

	return ops
}

// parseSystemConsoleDeviceConfig unmarshals VyOS ShowConfig JSON.
func parseSystemConsoleDeviceConfig(name string, data json.RawMessage) (SystemConsoleDeviceArgs, error) {
	args := SystemConsoleDeviceArgs{
		Name: name,
	}

	if v, ok := getNestedValue(data, []string{"speed"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return SystemConsoleDeviceArgs{}, fmt.Errorf("parse speed: %w", err)
		}
		args.Speed = &s
	}

	return args, nil
}
