// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
	"regexp"
	"strconv"
)

// VpnIpsecRemoteAccessConnection manages a VyOS VpnIpsecRemoteAccessConnection configuration.
type VpnIpsecRemoteAccessConnection struct{}

// VpnIpsecRemoteAccessConnectionArgs defines the inputs for the VpnIpsecRemoteAccessConnection resource.
type VpnIpsecRemoteAccessConnectionArgs struct {
	Name                            string   `pulumi:"name"`
	Description                     *string  `pulumi:"description,optional"`
	Disable                         *bool    `pulumi:"disable,optional"`
	EspGroup                        *string  `pulumi:"espGroup,optional"`
	IkeGroup                        *string  `pulumi:"ikeGroup,optional"`
	LocalAddress                    *string  `pulumi:"localAddress,optional"`
	DHCPInterface                   *string  `pulumi:"dhcpInterface,optional"`
	ReplayWindow                    *int     `pulumi:"replayWindow,optional"`
	Bind                            *string  `pulumi:"bind,optional"`
	Timeout                         *int     `pulumi:"timeout,optional"`
	Pool                            []string `pulumi:"pool,optional"`
	Unique                          *string  `pulumi:"unique,optional"`
	AuthenticationLocalID           *string  `pulumi:"authenticationLocalID,optional"`
	AuthenticationEapID             *string  `pulumi:"authenticationEapID,optional"`
	AuthenticationClientMode        *string  `pulumi:"authenticationClientMode,optional"`
	AuthenticationAlwaysSendCert    *bool    `pulumi:"authenticationAlwaysSendCert,optional"`
	AuthenticationServerMode        *string  `pulumi:"authenticationServerMode,optional"`
	AuthenticationPreSharedSecret   *string  `pulumi:"authenticationPreSharedSecret,optional"`
	AuthenticationX509Certificate   *string  `pulumi:"authenticationX509Certificate,optional"`
	AuthenticationX509Passphrase    *string  `pulumi:"authenticationX509Passphrase,optional"`
	AuthenticationX509CaCertificate []string `pulumi:"authenticationX509CaCertificate,optional"`
	LocalPort                       *int     `pulumi:"localPort,optional"`
	LocalPrefix                     []string `pulumi:"localPrefix,optional"`
}

// VpnIpsecRemoteAccessConnectionState defines the outputs for the VpnIpsecRemoteAccessConnection resource.
type VpnIpsecRemoteAccessConnectionState struct {
	VpnIpsecRemoteAccessConnectionArgs
}

// Annotate provides schema metadata for the resource.
func (*VpnIpsecRemoteAccessConnection) Annotate(a infer.Annotator) {
	a.Describe(new(VpnIpsecRemoteAccessConnection), "Manages a VyOS IKEv2 VPN connection name.")
}

// Annotate provides schema metadata for the inputs.
func (args *VpnIpsecRemoteAccessConnectionArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.Name, "IKEv2 VPN connection name")
	a.Describe(&args.Description, "Description")
	a.Describe(&args.Disable, "Disable instance")
	a.Describe(&args.EspGroup, "Encapsulating Security Payloads (ESP) group name")
	a.Describe(&args.IkeGroup, "Internet Key Exchange (IKE) group name")
	a.Describe(&args.LocalAddress, "IPv4 or IPv6 address of a local interface to use for VPN")
	a.Describe(&args.DHCPInterface, "DHCP interface supplying next-hop IP address")
	a.Describe(&args.ReplayWindow, "IPsec replay window to configure for this CHILD_SA")
	a.Describe(&args.Bind, "VTI tunnel interface associated with this configuration")
	a.Describe(&args.Timeout, "Timeout to close connection if no data is transmitted")
	a.Describe(&args.Pool, "IP address pool")
	a.Describe(&args.Unique, "Connection uniqueness enforcement policy")
	a.Describe(&args.AuthenticationLocalID, "Local ID for peer authentication")
	a.Describe(&args.AuthenticationEapID, "Remote EAP ID for client authentication")
	a.Describe(&args.AuthenticationClientMode, "Client authentication mode")
	a.Describe(&args.AuthenticationAlwaysSendCert, "Always send local certificate for this connection")
	a.Describe(&args.AuthenticationServerMode, "Server authentication mode")
	a.Describe(&args.AuthenticationPreSharedSecret, "Pre-shared secret key")
	a.Describe(&args.AuthenticationX509Certificate, "Certificate in PKI configuration")
	a.Describe(&args.AuthenticationX509Passphrase, "Private key passphrase")
	a.Describe(&args.AuthenticationX509CaCertificate, "Certificate Authority chain in PKI configuration")
	a.Describe(&args.LocalPort, "Port number used by connection")
	a.Describe(&args.LocalPrefix, "Local IPv4 or IPv6 prefix")
}

var vpnIpsecRemoteAccessConnectionNameRe = regexp.MustCompile(`^(?:` + "[a-zA-Z][0-9a-zA-Z_-]+" + `)$`)
var vpnIpsecRemoteAccessConnectionDescriptionRe = regexp.MustCompile(`^(?:` + ".{0,255}" + `)$`)
var vpnIpsecRemoteAccessConnectionLocalAddressRe = regexp.MustCompile(`^(?:` + "(any)" + `)$`)
var vpnIpsecRemoteAccessConnectionDHCPInterfaceRe = regexp.MustCompile(`^(?:` + "(bond|br|dum|en|ersp|eth|gnv|ifb|ipoe|lan|l2tp|l2tpeth|macsec|peth|ppp|pppoe|pptp|sstp|sstpc|tun|veth|vpptap|vpptun|vti|vtun|vxlan|wg|wlan|wwan)[0-9]+(.\\d+)?|pod-[-_a-zA-Z0-9]{1,11}|lo" + `)$`)
var vpnIpsecRemoteAccessConnectionUniqueRe = regexp.MustCompile(`^(?:` + "(never|keep|replace)" + `)$`)
var vpnIpsecRemoteAccessConnectionAuthenticationEapIDRe = regexp.MustCompile(`^(?:` + "[[:ascii:]]{1,64}" + `)$`)
var vpnIpsecRemoteAccessConnectionAuthenticationClientModeRe = regexp.MustCompile(`^(?:` + "(x509|eap-tls|eap-mschapv2|eap-radius)" + `)$`)
var vpnIpsecRemoteAccessConnectionAuthenticationServerModeRe = regexp.MustCompile(`^(?:` + "(pre-shared-secret|x509)" + `)$`)

// Check validates the VpnIpsecRemoteAccessConnection inputs.
func (VpnIpsecRemoteAccessConnection) Check(
	ctx context.Context,
	req infer.CheckRequest,
) (infer.CheckResponse[VpnIpsecRemoteAccessConnectionArgs], error) {
	inputs, failures, err := infer.DefaultCheck[VpnIpsecRemoteAccessConnectionArgs](ctx, req.NewInputs)
	if err != nil {
		return infer.CheckResponse[VpnIpsecRemoteAccessConnectionArgs]{}, err
	}
	if f := checkRegex(inputs.Name, vpnIpsecRemoteAccessConnectionNameRe, "name", "Profile name must be alphanumeric and can contain hyphen(s) and underscore(s)"); f != nil {
		failures = append(failures, *f)
	}
	if inputs.Description != nil {
		if f := checkRegex(*inputs.Description, vpnIpsecRemoteAccessConnectionDescriptionRe, "description", "Description too long (limit 255 characters)"); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.LocalAddress != nil {
		if f := checkRegex(*inputs.LocalAddress, vpnIpsecRemoteAccessConnectionLocalAddressRe, "localAddress", ""); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.DHCPInterface != nil {
		if f := checkRegex(*inputs.DHCPInterface, vpnIpsecRemoteAccessConnectionDHCPInterfaceRe, "dhcpInterface", ""); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.ReplayWindow != nil {
		if f := checkIntRange(int64(*inputs.ReplayWindow), 0, 2040, "replayWindow", ""); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.Timeout != nil {
		if f := checkIntRange(int64(*inputs.Timeout), 0, 86400, "timeout", ""); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.Unique != nil {
		if f := checkRegex(*inputs.Unique, vpnIpsecRemoteAccessConnectionUniqueRe, "unique", ""); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.AuthenticationEapID != nil {
		if f := checkRegex(*inputs.AuthenticationEapID, vpnIpsecRemoteAccessConnectionAuthenticationEapIDRe, "authenticationEapID", ""); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.AuthenticationClientMode != nil {
		if f := checkRegex(*inputs.AuthenticationClientMode, vpnIpsecRemoteAccessConnectionAuthenticationClientModeRe, "authenticationClientMode", ""); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.AuthenticationServerMode != nil {
		if f := checkRegex(*inputs.AuthenticationServerMode, vpnIpsecRemoteAccessConnectionAuthenticationServerModeRe, "authenticationServerMode", ""); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.LocalPort != nil {
		if f := checkIntRange(int64(*inputs.LocalPort), 1, 65535, "localPort", "Port number must be in range 1 to 65535"); f != nil {
			failures = append(failures, *f)
		}
	}

	return infer.CheckResponse[VpnIpsecRemoteAccessConnectionArgs]{Inputs: inputs, Failures: failures}, nil
}

func vpnIpsecRemoteAccessConnectionBasePath(name string) []any {
	return []any{"vpn", "ipsec", "remote-access", "connection", name}
}

// Create sets up the VpnIpsecRemoteAccessConnection on VyOS.
func (VpnIpsecRemoteAccessConnection) Create(
	ctx context.Context,
	req infer.CreateRequest[VpnIpsecRemoteAccessConnectionArgs],
) (infer.CreateResponse[VpnIpsecRemoteAccessConnectionState], error) {
	if req.DryRun {
		return infer.CreateResponse[VpnIpsecRemoteAccessConnectionState]{
			ID:     req.Inputs.Name,
			Output: VpnIpsecRemoteAccessConnectionState{VpnIpsecRemoteAccessConnectionArgs: req.Inputs},
		}, nil
	}

	ops := buildVpnIpsecRemoteAccessConnectionOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[VpnIpsecRemoteAccessConnectionState]{},
			fmt.Errorf("configure VpnIpsecRemoteAccessConnection %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[VpnIpsecRemoteAccessConnectionState]{
		ID:     req.Inputs.Name,
		Output: VpnIpsecRemoteAccessConnectionState{VpnIpsecRemoteAccessConnectionArgs: req.Inputs},
	}, nil
}

// Read fetches the current VpnIpsecRemoteAccessConnection config from VyOS.
func (VpnIpsecRemoteAccessConnection) Read(
	ctx context.Context,
	req infer.ReadRequest[VpnIpsecRemoteAccessConnectionArgs, VpnIpsecRemoteAccessConnectionState],
) (infer.ReadResponse[VpnIpsecRemoteAccessConnectionArgs, VpnIpsecRemoteAccessConnectionState], error) {
	client := getClient(ctx)
	base := vpnIpsecRemoteAccessConnectionBasePath(req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := VpnIpsecRemoteAccessConnectionArgs{Name: req.State.Name}
			state := VpnIpsecRemoteAccessConnectionState{VpnIpsecRemoteAccessConnectionArgs: args}
			return infer.ReadResponse[VpnIpsecRemoteAccessConnectionArgs, VpnIpsecRemoteAccessConnectionState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[VpnIpsecRemoteAccessConnectionArgs, VpnIpsecRemoteAccessConnectionState]{},
			fmt.Errorf("read VpnIpsecRemoteAccessConnection %s: %w", req.State.Name, err)
	}

	args, err := parseVpnIpsecRemoteAccessConnectionConfig(req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[VpnIpsecRemoteAccessConnectionArgs, VpnIpsecRemoteAccessConnectionState]{},
			fmt.Errorf("parse VpnIpsecRemoteAccessConnection %s config: %w", req.State.Name, err)
	}

	state := VpnIpsecRemoteAccessConnectionState{VpnIpsecRemoteAccessConnectionArgs: args}
	return infer.ReadResponse[VpnIpsecRemoteAccessConnectionArgs, VpnIpsecRemoteAccessConnectionState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing VpnIpsecRemoteAccessConnection configuration.
func (VpnIpsecRemoteAccessConnection) Update(
	ctx context.Context,
	req infer.UpdateRequest[VpnIpsecRemoteAccessConnectionArgs, VpnIpsecRemoteAccessConnectionState],
) (infer.UpdateResponse[VpnIpsecRemoteAccessConnectionState], error) {
	if req.DryRun {
		return infer.UpdateResponse[VpnIpsecRemoteAccessConnectionState]{
			Output: VpnIpsecRemoteAccessConnectionState{VpnIpsecRemoteAccessConnectionArgs: req.Inputs},
		}, nil
	}

	ops := buildVpnIpsecRemoteAccessConnectionUpdateOps(req.State.VpnIpsecRemoteAccessConnectionArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[VpnIpsecRemoteAccessConnectionState]{},
				fmt.Errorf("update VpnIpsecRemoteAccessConnection %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[VpnIpsecRemoteAccessConnectionState]{
		Output: VpnIpsecRemoteAccessConnectionState{VpnIpsecRemoteAccessConnectionArgs: req.Inputs},
	}, nil
}

// Delete removes the VpnIpsecRemoteAccessConnection configuration from VyOS.
func (VpnIpsecRemoteAccessConnection) Delete(
	ctx context.Context,
	req infer.DeleteRequest[VpnIpsecRemoteAccessConnectionState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := vpnIpsecRemoteAccessConnectionBasePath(req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete VpnIpsecRemoteAccessConnection %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildVpnIpsecRemoteAccessConnectionOps builds set operations for all non-nil fields.
func buildVpnIpsecRemoteAccessConnectionOps(args VpnIpsecRemoteAccessConnectionArgs) []vyosclient.Operation {
	base := vpnIpsecRemoteAccessConnectionBasePath(args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}

	if args.Description != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "description"), Value: *args.Description})
	}

	if args.Disable != nil && *args.Disable {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "disable")})
	}

	if args.EspGroup != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "esp-group"), Value: *args.EspGroup})
	}

	if args.IkeGroup != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "ike-group"), Value: *args.IkeGroup})
	}

	if args.LocalAddress != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "local-address"), Value: *args.LocalAddress})
	}

	if args.DHCPInterface != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "dhcp-interface"), Value: *args.DHCPInterface})
	}

	if args.ReplayWindow != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "replay-window"), Value: strconv.Itoa(*args.ReplayWindow)})
	}

	if args.Bind != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "bind"), Value: *args.Bind})
	}

	if args.Timeout != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "timeout"), Value: strconv.Itoa(*args.Timeout)})
	}

	for _, v := range args.Pool {
		vp := make([]string, 0, 1+1)
		vp = append(vp, "pool")
		vp = append(vp, v)
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, vp...)})
	}

	if args.Unique != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "unique"), Value: *args.Unique})
	}

	if args.AuthenticationLocalID != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "authentication", "local-id"), Value: *args.AuthenticationLocalID})
	}

	if args.AuthenticationEapID != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "authentication", "eap-id"), Value: *args.AuthenticationEapID})
	}

	if args.AuthenticationClientMode != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "authentication", "client-mode"), Value: *args.AuthenticationClientMode})
	}

	if args.AuthenticationAlwaysSendCert != nil && *args.AuthenticationAlwaysSendCert {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "authentication", "always-send-cert")})
	}

	if args.AuthenticationServerMode != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "authentication", "server-mode"), Value: *args.AuthenticationServerMode})
	}

	if args.AuthenticationPreSharedSecret != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "authentication", "pre-shared-secret"), Value: *args.AuthenticationPreSharedSecret})
	}

	if args.AuthenticationX509Certificate != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "authentication", "x509", "certificate"), Value: *args.AuthenticationX509Certificate})
	}

	if args.AuthenticationX509Passphrase != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "authentication", "x509", "passphrase"), Value: *args.AuthenticationX509Passphrase})
	}

	for _, v := range args.AuthenticationX509CaCertificate {
		vp := make([]string, 0, 3+1)
		vp = append(vp, "authentication")
		vp = append(vp, "x509")
		vp = append(vp, "ca-certificate")
		vp = append(vp, v)
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, vp...)})
	}

	if args.LocalPort != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "local", "port"), Value: strconv.Itoa(*args.LocalPort)})
	}

	for _, v := range args.LocalPrefix {
		vp := make([]string, 0, 2+1)
		vp = append(vp, "local")
		vp = append(vp, "prefix")
		vp = append(vp, v)
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, vp...)})
	}

	return ops
}

// buildVpnIpsecRemoteAccessConnectionUpdateOps computes the diff between previous and current state.
func buildVpnIpsecRemoteAccessConnectionUpdateOps(prev, cur VpnIpsecRemoteAccessConnectionArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	base := vpnIpsecRemoteAccessConnectionBasePath(cur.Name)

	ops = append(ops, diffStringField(base, []string{"description"}, prev.Description, cur.Description)...)

	ops = append(ops, diffBoolField(base, []string{"disable"}, prev.Disable, cur.Disable)...)

	ops = append(ops, diffStringField(base, []string{"esp-group"}, prev.EspGroup, cur.EspGroup)...)

	ops = append(ops, diffStringField(base, []string{"ike-group"}, prev.IkeGroup, cur.IkeGroup)...)

	ops = append(ops, diffStringField(base, []string{"local-address"}, prev.LocalAddress, cur.LocalAddress)...)

	ops = append(ops, diffStringField(base, []string{"dhcp-interface"}, prev.DHCPInterface, cur.DHCPInterface)...)

	ops = append(ops, diffIntField(base, []string{"replay-window"}, prev.ReplayWindow, cur.ReplayWindow)...)

	ops = append(ops, diffStringField(base, []string{"bind"}, prev.Bind, cur.Bind)...)

	ops = append(ops, diffIntField(base, []string{"timeout"}, prev.Timeout, cur.Timeout)...)

	ops = append(ops, diffMultiField(base, []string{"pool"}, prev.Pool, cur.Pool)...)

	ops = append(ops, diffStringField(base, []string{"unique"}, prev.Unique, cur.Unique)...)

	ops = append(ops, diffStringField(base, []string{"authentication", "local-id"}, prev.AuthenticationLocalID, cur.AuthenticationLocalID)...)

	ops = append(ops, diffStringField(base, []string{"authentication", "eap-id"}, prev.AuthenticationEapID, cur.AuthenticationEapID)...)

	ops = append(ops, diffStringField(base, []string{"authentication", "client-mode"}, prev.AuthenticationClientMode, cur.AuthenticationClientMode)...)

	ops = append(ops, diffBoolField(base, []string{"authentication", "always-send-cert"}, prev.AuthenticationAlwaysSendCert, cur.AuthenticationAlwaysSendCert)...)

	ops = append(ops, diffStringField(base, []string{"authentication", "server-mode"}, prev.AuthenticationServerMode, cur.AuthenticationServerMode)...)

	ops = append(ops, diffStringField(base, []string{"authentication", "pre-shared-secret"}, prev.AuthenticationPreSharedSecret, cur.AuthenticationPreSharedSecret)...)

	ops = append(ops, diffStringField(base, []string{"authentication", "x509", "certificate"}, prev.AuthenticationX509Certificate, cur.AuthenticationX509Certificate)...)

	ops = append(ops, diffStringField(base, []string{"authentication", "x509", "passphrase"}, prev.AuthenticationX509Passphrase, cur.AuthenticationX509Passphrase)...)

	ops = append(ops, diffMultiField(base, []string{"authentication", "x509", "ca-certificate"}, prev.AuthenticationX509CaCertificate, cur.AuthenticationX509CaCertificate)...)

	ops = append(ops, diffIntField(base, []string{"local", "port"}, prev.LocalPort, cur.LocalPort)...)

	ops = append(ops, diffMultiField(base, []string{"local", "prefix"}, prev.LocalPrefix, cur.LocalPrefix)...)

	return ops
}

// parseVpnIpsecRemoteAccessConnectionConfig unmarshals VyOS ShowConfig JSON.
func parseVpnIpsecRemoteAccessConnectionConfig(name string, data json.RawMessage) (VpnIpsecRemoteAccessConnectionArgs, error) {
	args := VpnIpsecRemoteAccessConnectionArgs{
		Name: name,
	}

	if v, ok := getNestedValue(data, []string{"description"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return VpnIpsecRemoteAccessConnectionArgs{}, fmt.Errorf("parse description: %w", err)
		}
		args.Description = &s
	}

	if _, ok := getNestedValue(data, []string{"disable"}); ok {
		t := true
		args.Disable = &t
	}

	if v, ok := getNestedValue(data, []string{"esp-group"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return VpnIpsecRemoteAccessConnectionArgs{}, fmt.Errorf("parse esp-group: %w", err)
		}
		args.EspGroup = &s
	}

	if v, ok := getNestedValue(data, []string{"ike-group"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return VpnIpsecRemoteAccessConnectionArgs{}, fmt.Errorf("parse ike-group: %w", err)
		}
		args.IkeGroup = &s
	}

	if v, ok := getNestedValue(data, []string{"local-address"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return VpnIpsecRemoteAccessConnectionArgs{}, fmt.Errorf("parse local-address: %w", err)
		}
		args.LocalAddress = &s
	}

	if v, ok := getNestedValue(data, []string{"dhcp-interface"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return VpnIpsecRemoteAccessConnectionArgs{}, fmt.Errorf("parse dhcp-interface: %w", err)
		}
		args.DHCPInterface = &s
	}

	if v, ok := getNestedValue(data, []string{"replay-window"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return VpnIpsecRemoteAccessConnectionArgs{}, fmt.Errorf("parse replay-window: %w", err)
		}
		args.ReplayWindow = &n
	}

	if v, ok := getNestedValue(data, []string{"bind"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return VpnIpsecRemoteAccessConnectionArgs{}, fmt.Errorf("parse bind: %w", err)
		}
		args.Bind = &s
	}

	if v, ok := getNestedValue(data, []string{"timeout"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return VpnIpsecRemoteAccessConnectionArgs{}, fmt.Errorf("parse timeout: %w", err)
		}
		args.Timeout = &n
	}

	if v, ok := getNestedValue(data, []string{"pool"}); ok {
		vals, err := parseMultiValue(v)
		if err != nil {
			return VpnIpsecRemoteAccessConnectionArgs{}, fmt.Errorf("parse pool: %w", err)
		}
		args.Pool = vals
	}

	if v, ok := getNestedValue(data, []string{"unique"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return VpnIpsecRemoteAccessConnectionArgs{}, fmt.Errorf("parse unique: %w", err)
		}
		args.Unique = &s
	}

	if v, ok := getNestedValue(data, []string{"authentication", "local-id"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return VpnIpsecRemoteAccessConnectionArgs{}, fmt.Errorf("parse local-id: %w", err)
		}
		args.AuthenticationLocalID = &s
	}

	if v, ok := getNestedValue(data, []string{"authentication", "eap-id"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return VpnIpsecRemoteAccessConnectionArgs{}, fmt.Errorf("parse eap-id: %w", err)
		}
		args.AuthenticationEapID = &s
	}

	if v, ok := getNestedValue(data, []string{"authentication", "client-mode"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return VpnIpsecRemoteAccessConnectionArgs{}, fmt.Errorf("parse client-mode: %w", err)
		}
		args.AuthenticationClientMode = &s
	}

	if _, ok := getNestedValue(data, []string{"authentication", "always-send-cert"}); ok {
		t := true
		args.AuthenticationAlwaysSendCert = &t
	}

	if v, ok := getNestedValue(data, []string{"authentication", "server-mode"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return VpnIpsecRemoteAccessConnectionArgs{}, fmt.Errorf("parse server-mode: %w", err)
		}
		args.AuthenticationServerMode = &s
	}

	if v, ok := getNestedValue(data, []string{"authentication", "pre-shared-secret"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return VpnIpsecRemoteAccessConnectionArgs{}, fmt.Errorf("parse pre-shared-secret: %w", err)
		}
		args.AuthenticationPreSharedSecret = &s
	}

	if v, ok := getNestedValue(data, []string{"authentication", "x509", "certificate"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return VpnIpsecRemoteAccessConnectionArgs{}, fmt.Errorf("parse certificate: %w", err)
		}
		args.AuthenticationX509Certificate = &s
	}

	if v, ok := getNestedValue(data, []string{"authentication", "x509", "passphrase"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return VpnIpsecRemoteAccessConnectionArgs{}, fmt.Errorf("parse passphrase: %w", err)
		}
		args.AuthenticationX509Passphrase = &s
	}

	if v, ok := getNestedValue(data, []string{"authentication", "x509", "ca-certificate"}); ok {
		vals, err := parseMultiValue(v)
		if err != nil {
			return VpnIpsecRemoteAccessConnectionArgs{}, fmt.Errorf("parse ca-certificate: %w", err)
		}
		args.AuthenticationX509CaCertificate = vals
	}

	if v, ok := getNestedValue(data, []string{"local", "port"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return VpnIpsecRemoteAccessConnectionArgs{}, fmt.Errorf("parse port: %w", err)
		}
		args.LocalPort = &n
	}

	if v, ok := getNestedValue(data, []string{"local", "prefix"}); ok {
		vals, err := parseMultiValue(v)
		if err != nil {
			return VpnIpsecRemoteAccessConnectionArgs{}, fmt.Errorf("parse prefix: %w", err)
		}
		args.LocalPrefix = vals
	}

	return args, nil
}
