// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
	"regexp"
	"strconv"
)

// NATCgnatPoolExternal manages a VyOS NATCgnatPoolExternal configuration.
type NATCgnatPoolExternal struct{}

// NATCgnatPoolExternalArgs defines the inputs for the NATCgnatPoolExternal resource.
type NATCgnatPoolExternalArgs struct {
	Name              string  `pulumi:"name"`
	ExternalPortRange *string `pulumi:"externalPortRange,optional"`
	PerUserLimitPort  *int    `pulumi:"perUserLimitPort,optional"`
}

// NATCgnatPoolExternalState defines the outputs for the NATCgnatPoolExternal resource.
type NATCgnatPoolExternalState struct {
	NATCgnatPoolExternalArgs
}

// Annotate provides schema metadata for the resource.
func (*NATCgnatPoolExternal) Annotate(a infer.Annotator) {
	a.Describe(new(NATCgnatPoolExternal), "Manages a VyOS External pool name.")
}

// Annotate provides schema metadata for the inputs.
func (args *NATCgnatPoolExternalArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.Name, "External pool name")
	a.Describe(&args.ExternalPortRange, "Port range")
	a.Describe(&args.PerUserLimitPort, "Ports per user")
}

var natCgnatPoolExternalNameRe = regexp.MustCompile(`^(?:` + "[-_a-zA-Z0-9][\\w\\-\\.\\+]*" + `)$`)

// Check validates the NATCgnatPoolExternal inputs.
func (NATCgnatPoolExternal) Check(
	ctx context.Context,
	req infer.CheckRequest,
) (infer.CheckResponse[NATCgnatPoolExternalArgs], error) {
	inputs, failures, err := infer.DefaultCheck[NATCgnatPoolExternalArgs](ctx, req.NewInputs)
	if err != nil {
		return infer.CheckResponse[NATCgnatPoolExternalArgs]{}, err
	}
	if f := checkRegex(inputs.Name, natCgnatPoolExternalNameRe, "name", "Name of pool can only contain alpha-numeric letters, hyphen and underscores"); f != nil {
		failures = append(failures, *f)
	}
	if inputs.PerUserLimitPort != nil {
		if f := checkIntRange(int64(*inputs.PerUserLimitPort), 1, 65535, "perUserLimitPort", ""); f != nil {
			failures = append(failures, *f)
		}
	}

	return infer.CheckResponse[NATCgnatPoolExternalArgs]{Inputs: inputs, Failures: failures}, nil
}

func natCgnatPoolExternalBasePath(name string) []any {
	return []any{"nat", "cgnat", "pool", "external", name}
}

// Create sets up the NATCgnatPoolExternal on VyOS.
func (NATCgnatPoolExternal) Create(
	ctx context.Context,
	req infer.CreateRequest[NATCgnatPoolExternalArgs],
) (infer.CreateResponse[NATCgnatPoolExternalState], error) {
	if req.DryRun {
		return infer.CreateResponse[NATCgnatPoolExternalState]{
			ID:     req.Inputs.Name,
			Output: NATCgnatPoolExternalState{NATCgnatPoolExternalArgs: req.Inputs},
		}, nil
	}

	ops := buildNATCgnatPoolExternalOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[NATCgnatPoolExternalState]{},
			fmt.Errorf("configure NATCgnatPoolExternal %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[NATCgnatPoolExternalState]{
		ID:     req.Inputs.Name,
		Output: NATCgnatPoolExternalState{NATCgnatPoolExternalArgs: req.Inputs},
	}, nil
}

// Read fetches the current NATCgnatPoolExternal config from VyOS.
func (NATCgnatPoolExternal) Read(
	ctx context.Context,
	req infer.ReadRequest[NATCgnatPoolExternalArgs, NATCgnatPoolExternalState],
) (infer.ReadResponse[NATCgnatPoolExternalArgs, NATCgnatPoolExternalState], error) {
	client := getClient(ctx)
	base := natCgnatPoolExternalBasePath(req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := NATCgnatPoolExternalArgs{Name: req.State.Name}
			state := NATCgnatPoolExternalState{NATCgnatPoolExternalArgs: args}
			return infer.ReadResponse[NATCgnatPoolExternalArgs, NATCgnatPoolExternalState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[NATCgnatPoolExternalArgs, NATCgnatPoolExternalState]{},
			fmt.Errorf("read NATCgnatPoolExternal %s: %w", req.State.Name, err)
	}

	args, err := parseNATCgnatPoolExternalConfig(req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[NATCgnatPoolExternalArgs, NATCgnatPoolExternalState]{},
			fmt.Errorf("parse NATCgnatPoolExternal %s config: %w", req.State.Name, err)
	}

	state := NATCgnatPoolExternalState{NATCgnatPoolExternalArgs: args}
	return infer.ReadResponse[NATCgnatPoolExternalArgs, NATCgnatPoolExternalState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing NATCgnatPoolExternal configuration.
func (NATCgnatPoolExternal) Update(
	ctx context.Context,
	req infer.UpdateRequest[NATCgnatPoolExternalArgs, NATCgnatPoolExternalState],
) (infer.UpdateResponse[NATCgnatPoolExternalState], error) {
	if req.DryRun {
		return infer.UpdateResponse[NATCgnatPoolExternalState]{
			Output: NATCgnatPoolExternalState{NATCgnatPoolExternalArgs: req.Inputs},
		}, nil
	}

	ops := buildNATCgnatPoolExternalUpdateOps(req.State.NATCgnatPoolExternalArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[NATCgnatPoolExternalState]{},
				fmt.Errorf("update NATCgnatPoolExternal %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[NATCgnatPoolExternalState]{
		Output: NATCgnatPoolExternalState{NATCgnatPoolExternalArgs: req.Inputs},
	}, nil
}

// Delete removes the NATCgnatPoolExternal configuration from VyOS.
func (NATCgnatPoolExternal) Delete(
	ctx context.Context,
	req infer.DeleteRequest[NATCgnatPoolExternalState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := natCgnatPoolExternalBasePath(req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete NATCgnatPoolExternal %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildNATCgnatPoolExternalOps builds set operations for all non-nil fields.
func buildNATCgnatPoolExternalOps(args NATCgnatPoolExternalArgs) []vyosclient.Operation {
	base := natCgnatPoolExternalBasePath(args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}

	if args.ExternalPortRange != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "external-port-range"), Value: *args.ExternalPortRange})
	}

	if args.PerUserLimitPort != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "per-user-limit", "port"), Value: strconv.Itoa(*args.PerUserLimitPort)})
	}

	return ops
}

// buildNATCgnatPoolExternalUpdateOps computes the diff between previous and current state.
func buildNATCgnatPoolExternalUpdateOps(prev, cur NATCgnatPoolExternalArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	base := natCgnatPoolExternalBasePath(cur.Name)

	ops = append(ops, diffStringField(base, []string{"external-port-range"}, prev.ExternalPortRange, cur.ExternalPortRange)...)

	ops = append(ops, diffIntField(base, []string{"per-user-limit", "port"}, prev.PerUserLimitPort, cur.PerUserLimitPort)...)

	return ops
}

// parseNATCgnatPoolExternalConfig unmarshals VyOS ShowConfig JSON.
func parseNATCgnatPoolExternalConfig(name string, data json.RawMessage) (NATCgnatPoolExternalArgs, error) {
	args := NATCgnatPoolExternalArgs{
		Name: name,
	}

	if v, ok := getNestedValue(data, []string{"external-port-range"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return NATCgnatPoolExternalArgs{}, fmt.Errorf("parse external-port-range: %w", err)
		}
		args.ExternalPortRange = &s
	}

	if v, ok := getNestedValue(data, []string{"per-user-limit", "port"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return NATCgnatPoolExternalArgs{}, fmt.Errorf("parse port: %w", err)
		}
		args.PerUserLimitPort = &n
	}

	return args, nil
}
