// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
	"regexp"
	"strconv"
)

// InterfaceGeneve manages a VyOS InterfaceGeneve configuration.
type InterfaceGeneve struct{}

// InterfaceGeneveArgs defines the inputs for the InterfaceGeneve resource.
type InterfaceGeneveArgs struct {
	Name                           string   `pulumi:"name"`
	Address                        []string `pulumi:"address,optional"`
	Description                    *string  `pulumi:"description,optional"`
	Disable                        *bool    `pulumi:"disable,optional"`
	MAC                            *string  `pulumi:"mac,optional"`
	MTU                            *int     `pulumi:"mtu,optional"`
	Port                           *int     `pulumi:"port,optional"`
	Redirect                       *string  `pulumi:"redirect,optional"`
	Remote                         *string  `pulumi:"remote,optional"`
	VRF                            *string  `pulumi:"vrf,optional"`
	VNI                            *int     `pulumi:"vni,optional"`
	IPAdjustMss                    *string  `pulumi:"ipAdjustMss,optional"`
	IPARPCacheTimeout              *int     `pulumi:"iparpCacheTimeout,optional"`
	IPDisableARPFilter             *bool    `pulumi:"ipDisableARPFilter,optional"`
	IPDisableForwarding            *bool    `pulumi:"ipDisableForwarding,optional"`
	IPEnableDirectedBroadcast      *bool    `pulumi:"ipEnableDirectedBroadcast,optional"`
	IPEnableARPAccept              *bool    `pulumi:"ipEnableARPAccept,optional"`
	IPEnableARPAnnounce            *bool    `pulumi:"ipEnableARPAnnounce,optional"`
	IPEnableARPIgnore              *bool    `pulumi:"ipEnableARPIgnore,optional"`
	IPEnableProxyARP               *bool    `pulumi:"ipEnableProxyARP,optional"`
	IPProxyARPPvlan                *bool    `pulumi:"ipProxyARPPvlan,optional"`
	IPSourceValidation             *string  `pulumi:"ipSourceValidation,optional"`
	IPv6AdjustMss                  *string  `pulumi:"iPv6AdjustMss,optional"`
	IPv6BaseReachableTime          *int     `pulumi:"iPv6BaseReachableTime,optional"`
	IPv6DisableForwarding          *bool    `pulumi:"iPv6DisableForwarding,optional"`
	IPv6AcceptDad                  *string  `pulumi:"iPv6AcceptDad,optional"`
	IPv6DupAddrDetectTransmits     *int     `pulumi:"iPv6DupAddrDetectTransmits,optional"`
	IPv6SourceValidation           *string  `pulumi:"iPv6SourceValidation,optional"`
	IPv6AddressAutoconf            *bool    `pulumi:"iPv6AddressAutoconf,optional"`
	IPv6AddressEui64               []string `pulumi:"iPv6AddressEui64,optional"`
	IPv6AddressNoDefaultLinkLocal  *bool    `pulumi:"iPv6AddressNoDefaultLinkLocal,optional"`
	IPv6AddressInterfaceIdentifier *string  `pulumi:"iPv6AddressInterfaceIdentifier,optional"`
	ParametersIPDf                 *string  `pulumi:"parametersIPDf,optional"`
	ParametersIPTos                *int     `pulumi:"parametersIPTos,optional"`
	ParametersIPTTL                *int     `pulumi:"parametersIPTTL,optional"`
	ParametersIPInnerproto         *bool    `pulumi:"parametersIPInnerproto,optional"`
	ParametersIPv6Flowlabel        *string  `pulumi:"parametersIPv6Flowlabel,optional"`
	MirrorIngress                  *string  `pulumi:"mirrorIngress,optional"`
	MirrorEgress                   *string  `pulumi:"mirrorEgress,optional"`
}

// InterfaceGeneveState defines the outputs for the InterfaceGeneve resource.
type InterfaceGeneveState struct {
	InterfaceGeneveArgs
}

// Annotate provides schema metadata for the resource.
func (*InterfaceGeneve) Annotate(a infer.Annotator) {
	a.Describe(new(InterfaceGeneve), "Manages a VyOS Generic Network Virtualization Encapsulation (GENEVE) Interface.")
}

// Annotate provides schema metadata for the inputs.
func (args *InterfaceGeneveArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.Name, "Generic Network Virtualization Encapsulation (GENEVE) Interface")
	a.Describe(&args.Address, "IP address")
	a.Describe(&args.Description, "Description")
	a.Describe(&args.Disable, "Administratively disable interface")
	a.Describe(&args.MAC, "Media Access Control (MAC) address")
	a.Describe(&args.MTU, "Maximum Transmission Unit (MTU)")
	a.Describe(&args.Port, "Port number used by connection")
	a.Describe(&args.Redirect, "Redirect incoming packet to destination")
	a.Describe(&args.Remote, "Tunnel remote address")
	a.Describe(&args.VRF, "VRF instance name")
	a.Describe(&args.VNI, "Virtual Network Identifier")
	a.Describe(&args.IPAdjustMss, "Adjust TCP MSS value")
	a.Describe(&args.IPARPCacheTimeout, "ARP cache entry timeout in seconds")
	a.Describe(&args.IPDisableARPFilter, "Disable ARP filter on this interface")
	a.Describe(&args.IPDisableForwarding, "Disable IP forwarding on this interface")
	a.Describe(&args.IPEnableDirectedBroadcast, "Enable directed broadcast forwarding on this interface")
	a.Describe(&args.IPEnableARPAccept, "Enable ARP accept on this interface")
	a.Describe(&args.IPEnableARPAnnounce, "Enable ARP announce on this interface")
	a.Describe(&args.IPEnableARPIgnore, "Enable ARP ignore on this interface")
	a.Describe(&args.IPEnableProxyARP, "Enable proxy-arp on this interface")
	a.Describe(&args.IPProxyARPPvlan, "Enable private VLAN proxy ARP on this interface")
	a.Describe(&args.IPSourceValidation, "Source validation by reversed path (RFC3704)")
	a.Describe(&args.IPv6AdjustMss, "Adjust TCP MSS value")
	a.Describe(&args.IPv6BaseReachableTime, "Base reachable time in seconds")
	a.Describe(&args.IPv6DisableForwarding, "Disable IP forwarding on this interface")
	a.Describe(&args.IPv6AcceptDad, "Accept Duplicate Address Detection")
	a.Describe(&args.IPv6DupAddrDetectTransmits, "Number of NS messages to send while performing DAD")
	a.Describe(&args.IPv6SourceValidation, "Source validation by reversed path (RFC3704)")
	a.Describe(&args.IPv6AddressAutoconf, "Enable acquisition of IPv6 address using stateless autoconfig (SLAAC)")
	a.Describe(&args.IPv6AddressEui64, "Prefix for IPv6 address with MAC-based EUI-64")
	a.Describe(&args.IPv6AddressNoDefaultLinkLocal, "Remove the default link-local address from the interface")
	a.Describe(&args.IPv6AddressInterfaceIdentifier, "SLAAC interface identifier")
	a.Describe(&args.ParametersIPDf, "Usage of the DF (don't Fragment) bit in outgoing packets")
	a.Describe(&args.ParametersIPTos, "Specifies TOS value to use in outgoing packets")
	a.Describe(&args.ParametersIPTTL, "Specifies TTL value to use in outgoing packets")
	a.Describe(&args.ParametersIPInnerproto, "Use IPv4 as inner protocol instead of Ethernet")
	a.Describe(&args.ParametersIPv6Flowlabel, "Specifies the flow label to use in outgoing packets")
	a.Describe(&args.MirrorIngress, "Mirror ingress traffic to destination interface")
	a.Describe(&args.MirrorEgress, "Mirror egress traffic to destination interface")
}

var interfaceGeneveNameRe = regexp.MustCompile(`^(?:` + "gnv[0-9]+" + `)$`)
var interfaceGeneveDescriptionRe = regexp.MustCompile(`^(?:` + ".{0,255}" + `)$`)
var interfaceGeneveRedirectRe = regexp.MustCompile(`^(?:` + "(bond|br|dum|en|ersp|eth|gnv|ifb|ipoe|lan|l2tp|l2tpeth|macsec|peth|ppp|pppoe|pptp|sstp|sstpc|tun|veth|vpptap|vpptun|vti|vtun|vxlan|wg|wlan|wwan)[0-9]+(.\\d+)?|pod-[-_a-zA-Z0-9]{1,11}|lo" + `)$`)
var interfaceGeneveIPAdjustMssRe = regexp.MustCompile(`^(?:` + "(clamp-mss-to-pmtu)" + `)$`)
var interfaceGeneveIPSourceValidationRe = regexp.MustCompile(`^(?:` + "(strict|loose|disable)" + `)$`)
var interfaceGeneveIPv6AdjustMssRe = regexp.MustCompile(`^(?:` + "(clamp-mss-to-pmtu)" + `)$`)
var interfaceGeneveIPv6SourceValidationRe = regexp.MustCompile(`^(?:` + "(strict|loose|disable)" + `)$`)
var interfaceGeneveIPv6AddressInterfaceIdentifierRe = regexp.MustCompile(`^(?:` + "::([0-9a-fA-F]{1,4}(:[0-9a-fA-F]{1,4}){0,3})" + `)$`)
var interfaceGeneveParametersIPDfRe = regexp.MustCompile(`^(?:` + "(set|unset|inherit)" + `)$`)
var interfaceGeneveParametersIPv6FlowlabelRe = regexp.MustCompile(`^(?:` + "((0x){0,1}(0?[0-9A-Fa-f]{1,5})|inherit)" + `)$`)

// Check validates the InterfaceGeneve inputs.
func (InterfaceGeneve) Check(
	ctx context.Context,
	req infer.CheckRequest,
) (infer.CheckResponse[InterfaceGeneveArgs], error) {
	inputs, failures, err := infer.DefaultCheck[InterfaceGeneveArgs](ctx, req.NewInputs)
	if err != nil {
		return infer.CheckResponse[InterfaceGeneveArgs]{}, err
	}
	if f := checkRegex(inputs.Name, interfaceGeneveNameRe, "name", "GENEVE interface must be named gnvN"); f != nil {
		failures = append(failures, *f)
	}
	if inputs.Description != nil {
		if f := checkRegex(*inputs.Description, interfaceGeneveDescriptionRe, "description", "Description too long (limit 255 characters)"); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.MTU != nil {
		if f := checkIntRange(int64(*inputs.MTU), 1200, 16000, "mtu", "MTU must be between 1200 and 16000"); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.Port != nil {
		if f := checkIntRange(int64(*inputs.Port), 1, 65535, "port", "Port number must be in range 1 to 65535"); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.Redirect != nil {
		if f := checkRegex(*inputs.Redirect, interfaceGeneveRedirectRe, "redirect", ""); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.VNI != nil {
		if f := checkIntRange(int64(*inputs.VNI), 0, 16777214, "vni", ""); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.IPAdjustMss != nil {
		if f := checkRegex(*inputs.IPAdjustMss, interfaceGeneveIPAdjustMssRe, "ipAdjustMss", ""); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.IPARPCacheTimeout != nil {
		if f := checkIntRange(int64(*inputs.IPARPCacheTimeout), 1, 86400, "iparpCacheTimeout", "ARP cache entry timeout must be between 1 and 86400 seconds"); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.IPSourceValidation != nil {
		if f := checkRegex(*inputs.IPSourceValidation, interfaceGeneveIPSourceValidationRe, "ipSourceValidation", ""); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.IPv6AdjustMss != nil {
		if f := checkRegex(*inputs.IPv6AdjustMss, interfaceGeneveIPv6AdjustMssRe, "iPv6AdjustMss", ""); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.IPv6BaseReachableTime != nil {
		if f := checkIntRange(int64(*inputs.IPv6BaseReachableTime), 1, 86400, "iPv6BaseReachableTime", "Base reachable time must be between 1 and 86400 seconds"); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.IPv6SourceValidation != nil {
		if f := checkRegex(*inputs.IPv6SourceValidation, interfaceGeneveIPv6SourceValidationRe, "iPv6SourceValidation", ""); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.IPv6AddressInterfaceIdentifier != nil {
		if f := checkRegex(*inputs.IPv6AddressInterfaceIdentifier, interfaceGeneveIPv6AddressInterfaceIdentifierRe, "iPv6AddressInterfaceIdentifier", "Interface identifier format must start with :: and may contain up four hextets (::h:h:h:h)"); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.ParametersIPDf != nil {
		if f := checkRegex(*inputs.ParametersIPDf, interfaceGeneveParametersIPDfRe, "parametersIPDf", ""); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.ParametersIPTos != nil {
		if f := checkIntRange(int64(*inputs.ParametersIPTos), 0, 99, "parametersIPTos", "TOS must be between 0 and 99"); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.ParametersIPTTL != nil {
		if f := checkIntRange(int64(*inputs.ParametersIPTTL), 0, 255, "parametersIPTTL", "TTL must be between 0 and 255"); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.ParametersIPv6Flowlabel != nil {
		if f := checkRegex(*inputs.ParametersIPv6Flowlabel, interfaceGeneveParametersIPv6FlowlabelRe, "parametersIPv6Flowlabel", "Must be 'inherit' or a number"); f != nil {
			failures = append(failures, *f)
		}
	}

	return infer.CheckResponse[InterfaceGeneveArgs]{Inputs: inputs, Failures: failures}, nil
}

func interfaceGeneveBasePath(name string) []any {
	return []any{"interfaces", "geneve", name}
}

// Create sets up the InterfaceGeneve on VyOS.
func (InterfaceGeneve) Create(
	ctx context.Context,
	req infer.CreateRequest[InterfaceGeneveArgs],
) (infer.CreateResponse[InterfaceGeneveState], error) {
	if req.DryRun {
		return infer.CreateResponse[InterfaceGeneveState]{
			ID:     req.Inputs.Name,
			Output: InterfaceGeneveState{InterfaceGeneveArgs: req.Inputs},
		}, nil
	}

	ops := buildInterfaceGeneveOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[InterfaceGeneveState]{},
			fmt.Errorf("configure InterfaceGeneve %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[InterfaceGeneveState]{
		ID:     req.Inputs.Name,
		Output: InterfaceGeneveState{InterfaceGeneveArgs: req.Inputs},
	}, nil
}

// Read fetches the current InterfaceGeneve config from VyOS.
func (InterfaceGeneve) Read(
	ctx context.Context,
	req infer.ReadRequest[InterfaceGeneveArgs, InterfaceGeneveState],
) (infer.ReadResponse[InterfaceGeneveArgs, InterfaceGeneveState], error) {
	client := getClient(ctx)
	base := interfaceGeneveBasePath(req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := InterfaceGeneveArgs{Name: req.State.Name}
			state := InterfaceGeneveState{InterfaceGeneveArgs: args}
			return infer.ReadResponse[InterfaceGeneveArgs, InterfaceGeneveState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[InterfaceGeneveArgs, InterfaceGeneveState]{},
			fmt.Errorf("read InterfaceGeneve %s: %w", req.State.Name, err)
	}

	args, err := parseInterfaceGeneveConfig(req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[InterfaceGeneveArgs, InterfaceGeneveState]{},
			fmt.Errorf("parse InterfaceGeneve %s config: %w", req.State.Name, err)
	}

	state := InterfaceGeneveState{InterfaceGeneveArgs: args}
	return infer.ReadResponse[InterfaceGeneveArgs, InterfaceGeneveState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing InterfaceGeneve configuration.
func (InterfaceGeneve) Update(
	ctx context.Context,
	req infer.UpdateRequest[InterfaceGeneveArgs, InterfaceGeneveState],
) (infer.UpdateResponse[InterfaceGeneveState], error) {
	if req.DryRun {
		return infer.UpdateResponse[InterfaceGeneveState]{
			Output: InterfaceGeneveState{InterfaceGeneveArgs: req.Inputs},
		}, nil
	}

	ops := buildInterfaceGeneveUpdateOps(req.State.InterfaceGeneveArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[InterfaceGeneveState]{},
				fmt.Errorf("update InterfaceGeneve %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[InterfaceGeneveState]{
		Output: InterfaceGeneveState{InterfaceGeneveArgs: req.Inputs},
	}, nil
}

// Delete removes the InterfaceGeneve configuration from VyOS.
func (InterfaceGeneve) Delete(
	ctx context.Context,
	req infer.DeleteRequest[InterfaceGeneveState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := interfaceGeneveBasePath(req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete InterfaceGeneve %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildInterfaceGeneveOps builds set operations for all non-nil fields.
func buildInterfaceGeneveOps(args InterfaceGeneveArgs) []vyosclient.Operation {
	base := interfaceGeneveBasePath(args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}

	for _, v := range args.Address {
		vp := make([]string, 0, 1+1)
		vp = append(vp, "address")
		vp = append(vp, v)
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, vp...)})
	}

	if args.Description != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "description"), Value: *args.Description})
	}

	if args.Disable != nil && *args.Disable {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "disable")})
	}

	if args.MAC != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "mac"), Value: *args.MAC})
	}

	if args.MTU != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "mtu"), Value: strconv.Itoa(*args.MTU)})
	}

	if args.Port != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "port"), Value: strconv.Itoa(*args.Port)})
	}

	if args.Redirect != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "redirect"), Value: *args.Redirect})
	}

	if args.Remote != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "remote"), Value: *args.Remote})
	}

	if args.VRF != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "vrf"), Value: *args.VRF})
	}

	if args.VNI != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "vni"), Value: strconv.Itoa(*args.VNI)})
	}

	if args.IPAdjustMss != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "ip", "adjust-mss"), Value: *args.IPAdjustMss})
	}

	if args.IPARPCacheTimeout != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "ip", "arp-cache-timeout"), Value: strconv.Itoa(*args.IPARPCacheTimeout)})
	}

	if args.IPDisableARPFilter != nil && *args.IPDisableARPFilter {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "ip", "disable-arp-filter")})
	}

	if args.IPDisableForwarding != nil && *args.IPDisableForwarding {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "ip", "disable-forwarding")})
	}

	if args.IPEnableDirectedBroadcast != nil && *args.IPEnableDirectedBroadcast {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "ip", "enable-directed-broadcast")})
	}

	if args.IPEnableARPAccept != nil && *args.IPEnableARPAccept {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "ip", "enable-arp-accept")})
	}

	if args.IPEnableARPAnnounce != nil && *args.IPEnableARPAnnounce {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "ip", "enable-arp-announce")})
	}

	if args.IPEnableARPIgnore != nil && *args.IPEnableARPIgnore {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "ip", "enable-arp-ignore")})
	}

	if args.IPEnableProxyARP != nil && *args.IPEnableProxyARP {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "ip", "enable-proxy-arp")})
	}

	if args.IPProxyARPPvlan != nil && *args.IPProxyARPPvlan {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "ip", "proxy-arp-pvlan")})
	}

	if args.IPSourceValidation != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "ip", "source-validation"), Value: *args.IPSourceValidation})
	}

	if args.IPv6AdjustMss != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "ipv6", "adjust-mss"), Value: *args.IPv6AdjustMss})
	}

	if args.IPv6BaseReachableTime != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "ipv6", "base-reachable-time"), Value: strconv.Itoa(*args.IPv6BaseReachableTime)})
	}

	if args.IPv6DisableForwarding != nil && *args.IPv6DisableForwarding {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "ipv6", "disable-forwarding")})
	}

	if args.IPv6AcceptDad != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "ipv6", "accept-dad"), Value: *args.IPv6AcceptDad})
	}

	if args.IPv6DupAddrDetectTransmits != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "ipv6", "dup-addr-detect-transmits"), Value: strconv.Itoa(*args.IPv6DupAddrDetectTransmits)})
	}

	if args.IPv6SourceValidation != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "ipv6", "source-validation"), Value: *args.IPv6SourceValidation})
	}

	if args.IPv6AddressAutoconf != nil && *args.IPv6AddressAutoconf {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "ipv6", "address", "autoconf")})
	}

	for _, v := range args.IPv6AddressEui64 {
		vp := make([]string, 0, 3+1)
		vp = append(vp, "ipv6")
		vp = append(vp, "address")
		vp = append(vp, "eui64")
		vp = append(vp, v)
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, vp...)})
	}

	if args.IPv6AddressNoDefaultLinkLocal != nil && *args.IPv6AddressNoDefaultLinkLocal {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "ipv6", "address", "no-default-link-local")})
	}

	if args.IPv6AddressInterfaceIdentifier != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "ipv6", "address", "interface-identifier"), Value: *args.IPv6AddressInterfaceIdentifier})
	}

	if args.ParametersIPDf != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "parameters", "ip", "df"), Value: *args.ParametersIPDf})
	}

	if args.ParametersIPTos != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "parameters", "ip", "tos"), Value: strconv.Itoa(*args.ParametersIPTos)})
	}

	if args.ParametersIPTTL != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "parameters", "ip", "ttl"), Value: strconv.Itoa(*args.ParametersIPTTL)})
	}

	if args.ParametersIPInnerproto != nil && *args.ParametersIPInnerproto {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "parameters", "ip", "innerproto")})
	}

	if args.ParametersIPv6Flowlabel != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "parameters", "ipv6", "flowlabel"), Value: *args.ParametersIPv6Flowlabel})
	}

	if args.MirrorIngress != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "mirror", "ingress"), Value: *args.MirrorIngress})
	}

	if args.MirrorEgress != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "mirror", "egress"), Value: *args.MirrorEgress})
	}

	return ops
}

// buildInterfaceGeneveUpdateOps computes the diff between previous and current state.
func buildInterfaceGeneveUpdateOps(prev, cur InterfaceGeneveArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	base := interfaceGeneveBasePath(cur.Name)

	ops = append(ops, diffMultiField(base, []string{"address"}, prev.Address, cur.Address)...)

	ops = append(ops, diffStringField(base, []string{"description"}, prev.Description, cur.Description)...)

	ops = append(ops, diffBoolField(base, []string{"disable"}, prev.Disable, cur.Disable)...)

	ops = append(ops, diffStringField(base, []string{"mac"}, prev.MAC, cur.MAC)...)

	ops = append(ops, diffIntField(base, []string{"mtu"}, prev.MTU, cur.MTU)...)

	ops = append(ops, diffIntField(base, []string{"port"}, prev.Port, cur.Port)...)

	ops = append(ops, diffStringField(base, []string{"redirect"}, prev.Redirect, cur.Redirect)...)

	ops = append(ops, diffStringField(base, []string{"remote"}, prev.Remote, cur.Remote)...)

	ops = append(ops, diffStringField(base, []string{"vrf"}, prev.VRF, cur.VRF)...)

	ops = append(ops, diffIntField(base, []string{"vni"}, prev.VNI, cur.VNI)...)

	ops = append(ops, diffStringField(base, []string{"ip", "adjust-mss"}, prev.IPAdjustMss, cur.IPAdjustMss)...)

	ops = append(ops, diffIntField(base, []string{"ip", "arp-cache-timeout"}, prev.IPARPCacheTimeout, cur.IPARPCacheTimeout)...)

	ops = append(ops, diffBoolField(base, []string{"ip", "disable-arp-filter"}, prev.IPDisableARPFilter, cur.IPDisableARPFilter)...)

	ops = append(ops, diffBoolField(base, []string{"ip", "disable-forwarding"}, prev.IPDisableForwarding, cur.IPDisableForwarding)...)

	ops = append(ops, diffBoolField(base, []string{"ip", "enable-directed-broadcast"}, prev.IPEnableDirectedBroadcast, cur.IPEnableDirectedBroadcast)...)

	ops = append(ops, diffBoolField(base, []string{"ip", "enable-arp-accept"}, prev.IPEnableARPAccept, cur.IPEnableARPAccept)...)

	ops = append(ops, diffBoolField(base, []string{"ip", "enable-arp-announce"}, prev.IPEnableARPAnnounce, cur.IPEnableARPAnnounce)...)

	ops = append(ops, diffBoolField(base, []string{"ip", "enable-arp-ignore"}, prev.IPEnableARPIgnore, cur.IPEnableARPIgnore)...)

	ops = append(ops, diffBoolField(base, []string{"ip", "enable-proxy-arp"}, prev.IPEnableProxyARP, cur.IPEnableProxyARP)...)

	ops = append(ops, diffBoolField(base, []string{"ip", "proxy-arp-pvlan"}, prev.IPProxyARPPvlan, cur.IPProxyARPPvlan)...)

	ops = append(ops, diffStringField(base, []string{"ip", "source-validation"}, prev.IPSourceValidation, cur.IPSourceValidation)...)

	ops = append(ops, diffStringField(base, []string{"ipv6", "adjust-mss"}, prev.IPv6AdjustMss, cur.IPv6AdjustMss)...)

	ops = append(ops, diffIntField(base, []string{"ipv6", "base-reachable-time"}, prev.IPv6BaseReachableTime, cur.IPv6BaseReachableTime)...)

	ops = append(ops, diffBoolField(base, []string{"ipv6", "disable-forwarding"}, prev.IPv6DisableForwarding, cur.IPv6DisableForwarding)...)

	ops = append(ops, diffStringField(base, []string{"ipv6", "accept-dad"}, prev.IPv6AcceptDad, cur.IPv6AcceptDad)...)

	ops = append(ops, diffIntField(base, []string{"ipv6", "dup-addr-detect-transmits"}, prev.IPv6DupAddrDetectTransmits, cur.IPv6DupAddrDetectTransmits)...)

	ops = append(ops, diffStringField(base, []string{"ipv6", "source-validation"}, prev.IPv6SourceValidation, cur.IPv6SourceValidation)...)

	ops = append(ops, diffBoolField(base, []string{"ipv6", "address", "autoconf"}, prev.IPv6AddressAutoconf, cur.IPv6AddressAutoconf)...)

	ops = append(ops, diffMultiField(base, []string{"ipv6", "address", "eui64"}, prev.IPv6AddressEui64, cur.IPv6AddressEui64)...)

	ops = append(ops, diffBoolField(base, []string{"ipv6", "address", "no-default-link-local"}, prev.IPv6AddressNoDefaultLinkLocal, cur.IPv6AddressNoDefaultLinkLocal)...)

	ops = append(ops, diffStringField(base, []string{"ipv6", "address", "interface-identifier"}, prev.IPv6AddressInterfaceIdentifier, cur.IPv6AddressInterfaceIdentifier)...)

	ops = append(ops, diffStringField(base, []string{"parameters", "ip", "df"}, prev.ParametersIPDf, cur.ParametersIPDf)...)

	ops = append(ops, diffIntField(base, []string{"parameters", "ip", "tos"}, prev.ParametersIPTos, cur.ParametersIPTos)...)

	ops = append(ops, diffIntField(base, []string{"parameters", "ip", "ttl"}, prev.ParametersIPTTL, cur.ParametersIPTTL)...)

	ops = append(ops, diffBoolField(base, []string{"parameters", "ip", "innerproto"}, prev.ParametersIPInnerproto, cur.ParametersIPInnerproto)...)

	ops = append(ops, diffStringField(base, []string{"parameters", "ipv6", "flowlabel"}, prev.ParametersIPv6Flowlabel, cur.ParametersIPv6Flowlabel)...)

	ops = append(ops, diffStringField(base, []string{"mirror", "ingress"}, prev.MirrorIngress, cur.MirrorIngress)...)

	ops = append(ops, diffStringField(base, []string{"mirror", "egress"}, prev.MirrorEgress, cur.MirrorEgress)...)

	return ops
}

// parseInterfaceGeneveConfig unmarshals VyOS ShowConfig JSON.
func parseInterfaceGeneveConfig(name string, data json.RawMessage) (InterfaceGeneveArgs, error) {
	args := InterfaceGeneveArgs{
		Name: name,
	}

	if v, ok := getNestedValue(data, []string{"address"}); ok {
		vals, err := parseMultiValue(v)
		if err != nil {
			return InterfaceGeneveArgs{}, fmt.Errorf("parse address: %w", err)
		}
		args.Address = vals
	}

	if v, ok := getNestedValue(data, []string{"description"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return InterfaceGeneveArgs{}, fmt.Errorf("parse description: %w", err)
		}
		args.Description = &s
	}

	if _, ok := getNestedValue(data, []string{"disable"}); ok {
		t := true
		args.Disable = &t
	}

	if v, ok := getNestedValue(data, []string{"mac"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return InterfaceGeneveArgs{}, fmt.Errorf("parse mac: %w", err)
		}
		args.MAC = &s
	}

	if v, ok := getNestedValue(data, []string{"mtu"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return InterfaceGeneveArgs{}, fmt.Errorf("parse mtu: %w", err)
		}
		args.MTU = &n
	}

	if v, ok := getNestedValue(data, []string{"port"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return InterfaceGeneveArgs{}, fmt.Errorf("parse port: %w", err)
		}
		args.Port = &n
	}

	if v, ok := getNestedValue(data, []string{"redirect"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return InterfaceGeneveArgs{}, fmt.Errorf("parse redirect: %w", err)
		}
		args.Redirect = &s
	}

	if v, ok := getNestedValue(data, []string{"remote"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return InterfaceGeneveArgs{}, fmt.Errorf("parse remote: %w", err)
		}
		args.Remote = &s
	}

	if v, ok := getNestedValue(data, []string{"vrf"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return InterfaceGeneveArgs{}, fmt.Errorf("parse vrf: %w", err)
		}
		args.VRF = &s
	}

	if v, ok := getNestedValue(data, []string{"vni"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return InterfaceGeneveArgs{}, fmt.Errorf("parse vni: %w", err)
		}
		args.VNI = &n
	}

	if v, ok := getNestedValue(data, []string{"ip", "adjust-mss"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return InterfaceGeneveArgs{}, fmt.Errorf("parse adjust-mss: %w", err)
		}
		args.IPAdjustMss = &s
	}

	if v, ok := getNestedValue(data, []string{"ip", "arp-cache-timeout"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return InterfaceGeneveArgs{}, fmt.Errorf("parse arp-cache-timeout: %w", err)
		}
		args.IPARPCacheTimeout = &n
	}

	if _, ok := getNestedValue(data, []string{"ip", "disable-arp-filter"}); ok {
		t := true
		args.IPDisableARPFilter = &t
	}

	if _, ok := getNestedValue(data, []string{"ip", "disable-forwarding"}); ok {
		t := true
		args.IPDisableForwarding = &t
	}

	if _, ok := getNestedValue(data, []string{"ip", "enable-directed-broadcast"}); ok {
		t := true
		args.IPEnableDirectedBroadcast = &t
	}

	if _, ok := getNestedValue(data, []string{"ip", "enable-arp-accept"}); ok {
		t := true
		args.IPEnableARPAccept = &t
	}

	if _, ok := getNestedValue(data, []string{"ip", "enable-arp-announce"}); ok {
		t := true
		args.IPEnableARPAnnounce = &t
	}

	if _, ok := getNestedValue(data, []string{"ip", "enable-arp-ignore"}); ok {
		t := true
		args.IPEnableARPIgnore = &t
	}

	if _, ok := getNestedValue(data, []string{"ip", "enable-proxy-arp"}); ok {
		t := true
		args.IPEnableProxyARP = &t
	}

	if _, ok := getNestedValue(data, []string{"ip", "proxy-arp-pvlan"}); ok {
		t := true
		args.IPProxyARPPvlan = &t
	}

	if v, ok := getNestedValue(data, []string{"ip", "source-validation"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return InterfaceGeneveArgs{}, fmt.Errorf("parse source-validation: %w", err)
		}
		args.IPSourceValidation = &s
	}

	if v, ok := getNestedValue(data, []string{"ipv6", "adjust-mss"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return InterfaceGeneveArgs{}, fmt.Errorf("parse adjust-mss: %w", err)
		}
		args.IPv6AdjustMss = &s
	}

	if v, ok := getNestedValue(data, []string{"ipv6", "base-reachable-time"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return InterfaceGeneveArgs{}, fmt.Errorf("parse base-reachable-time: %w", err)
		}
		args.IPv6BaseReachableTime = &n
	}

	if _, ok := getNestedValue(data, []string{"ipv6", "disable-forwarding"}); ok {
		t := true
		args.IPv6DisableForwarding = &t
	}

	if v, ok := getNestedValue(data, []string{"ipv6", "accept-dad"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return InterfaceGeneveArgs{}, fmt.Errorf("parse accept-dad: %w", err)
		}
		args.IPv6AcceptDad = &s
	}

	if v, ok := getNestedValue(data, []string{"ipv6", "dup-addr-detect-transmits"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return InterfaceGeneveArgs{}, fmt.Errorf("parse dup-addr-detect-transmits: %w", err)
		}
		args.IPv6DupAddrDetectTransmits = &n
	}

	if v, ok := getNestedValue(data, []string{"ipv6", "source-validation"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return InterfaceGeneveArgs{}, fmt.Errorf("parse source-validation: %w", err)
		}
		args.IPv6SourceValidation = &s
	}

	if _, ok := getNestedValue(data, []string{"ipv6", "address", "autoconf"}); ok {
		t := true
		args.IPv6AddressAutoconf = &t
	}

	if v, ok := getNestedValue(data, []string{"ipv6", "address", "eui64"}); ok {
		vals, err := parseMultiValue(v)
		if err != nil {
			return InterfaceGeneveArgs{}, fmt.Errorf("parse eui64: %w", err)
		}
		args.IPv6AddressEui64 = vals
	}

	if _, ok := getNestedValue(data, []string{"ipv6", "address", "no-default-link-local"}); ok {
		t := true
		args.IPv6AddressNoDefaultLinkLocal = &t
	}

	if v, ok := getNestedValue(data, []string{"ipv6", "address", "interface-identifier"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return InterfaceGeneveArgs{}, fmt.Errorf("parse interface-identifier: %w", err)
		}
		args.IPv6AddressInterfaceIdentifier = &s
	}

	if v, ok := getNestedValue(data, []string{"parameters", "ip", "df"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return InterfaceGeneveArgs{}, fmt.Errorf("parse df: %w", err)
		}
		args.ParametersIPDf = &s
	}

	if v, ok := getNestedValue(data, []string{"parameters", "ip", "tos"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return InterfaceGeneveArgs{}, fmt.Errorf("parse tos: %w", err)
		}
		args.ParametersIPTos = &n
	}

	if v, ok := getNestedValue(data, []string{"parameters", "ip", "ttl"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return InterfaceGeneveArgs{}, fmt.Errorf("parse ttl: %w", err)
		}
		args.ParametersIPTTL = &n
	}

	if _, ok := getNestedValue(data, []string{"parameters", "ip", "innerproto"}); ok {
		t := true
		args.ParametersIPInnerproto = &t
	}

	if v, ok := getNestedValue(data, []string{"parameters", "ipv6", "flowlabel"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return InterfaceGeneveArgs{}, fmt.Errorf("parse flowlabel: %w", err)
		}
		args.ParametersIPv6Flowlabel = &s
	}

	if v, ok := getNestedValue(data, []string{"mirror", "ingress"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return InterfaceGeneveArgs{}, fmt.Errorf("parse ingress: %w", err)
		}
		args.MirrorIngress = &s
	}

	if v, ok := getNestedValue(data, []string{"mirror", "egress"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return InterfaceGeneveArgs{}, fmt.Errorf("parse egress: %w", err)
		}
		args.MirrorEgress = &s
	}

	return args, nil
}
