// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
)

// ProtocolPimInterfaceJoin manages a VyOS ProtocolPimInterfaceJoin configuration.
type ProtocolPimInterfaceJoin struct{}

// ProtocolPimInterfaceJoinArgs defines the inputs for the ProtocolPimInterfaceJoin resource.
type ProtocolPimInterfaceJoinArgs struct {
	InterfaceName string   `pulumi:"interfaceName"`
	Name          string   `pulumi:"name"`
	SourceAddress []string `pulumi:"sourceAddress,optional"`
}

// ProtocolPimInterfaceJoinState defines the outputs for the ProtocolPimInterfaceJoin resource.
type ProtocolPimInterfaceJoinState struct {
	ProtocolPimInterfaceJoinArgs
}

// Annotate provides schema metadata for the resource.
func (*ProtocolPimInterfaceJoin) Annotate(a infer.Annotator) {
	a.Describe(new(ProtocolPimInterfaceJoin), "Manages a VyOS IGMP join multicast group.")
}

// Annotate provides schema metadata for the inputs.
func (args *ProtocolPimInterfaceJoinArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.InterfaceName, "Parent tag node key")
	a.Describe(&args.Name, "IGMP join multicast group")
	a.Describe(&args.SourceAddress, "IPv4 source address used to initiate connection")
}

func protocolPimInterfaceJoinBasePath(interfaceName, name string) []any {
	return []any{"protocols", "pim", "interface", interfaceName, "join", name}
}

// Create sets up the ProtocolPimInterfaceJoin on VyOS.
func (ProtocolPimInterfaceJoin) Create(
	ctx context.Context,
	req infer.CreateRequest[ProtocolPimInterfaceJoinArgs],
) (infer.CreateResponse[ProtocolPimInterfaceJoinState], error) {
	if req.DryRun {
		return infer.CreateResponse[ProtocolPimInterfaceJoinState]{
			ID:     req.Inputs.Name,
			Output: ProtocolPimInterfaceJoinState{ProtocolPimInterfaceJoinArgs: req.Inputs},
		}, nil
	}

	ops := buildProtocolPimInterfaceJoinOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[ProtocolPimInterfaceJoinState]{},
			fmt.Errorf("configure ProtocolPimInterfaceJoin %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[ProtocolPimInterfaceJoinState]{
		ID:     req.Inputs.Name,
		Output: ProtocolPimInterfaceJoinState{ProtocolPimInterfaceJoinArgs: req.Inputs},
	}, nil
}

// Read fetches the current ProtocolPimInterfaceJoin config from VyOS.
func (ProtocolPimInterfaceJoin) Read(
	ctx context.Context,
	req infer.ReadRequest[ProtocolPimInterfaceJoinArgs, ProtocolPimInterfaceJoinState],
) (infer.ReadResponse[ProtocolPimInterfaceJoinArgs, ProtocolPimInterfaceJoinState], error) {
	client := getClient(ctx)
	base := protocolPimInterfaceJoinBasePath(req.State.InterfaceName, req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := ProtocolPimInterfaceJoinArgs{InterfaceName: req.State.InterfaceName, Name: req.State.Name}
			state := ProtocolPimInterfaceJoinState{ProtocolPimInterfaceJoinArgs: args}
			return infer.ReadResponse[ProtocolPimInterfaceJoinArgs, ProtocolPimInterfaceJoinState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[ProtocolPimInterfaceJoinArgs, ProtocolPimInterfaceJoinState]{},
			fmt.Errorf("read ProtocolPimInterfaceJoin %s: %w", req.State.Name, err)
	}

	args, err := parseProtocolPimInterfaceJoinConfig(req.State.InterfaceName, req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[ProtocolPimInterfaceJoinArgs, ProtocolPimInterfaceJoinState]{},
			fmt.Errorf("parse ProtocolPimInterfaceJoin %s config: %w", req.State.Name, err)
	}

	state := ProtocolPimInterfaceJoinState{ProtocolPimInterfaceJoinArgs: args}
	return infer.ReadResponse[ProtocolPimInterfaceJoinArgs, ProtocolPimInterfaceJoinState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing ProtocolPimInterfaceJoin configuration.
func (ProtocolPimInterfaceJoin) Update(
	ctx context.Context,
	req infer.UpdateRequest[ProtocolPimInterfaceJoinArgs, ProtocolPimInterfaceJoinState],
) (infer.UpdateResponse[ProtocolPimInterfaceJoinState], error) {
	if req.DryRun {
		return infer.UpdateResponse[ProtocolPimInterfaceJoinState]{
			Output: ProtocolPimInterfaceJoinState{ProtocolPimInterfaceJoinArgs: req.Inputs},
		}, nil
	}

	ops := buildProtocolPimInterfaceJoinUpdateOps(req.State.ProtocolPimInterfaceJoinArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[ProtocolPimInterfaceJoinState]{},
				fmt.Errorf("update ProtocolPimInterfaceJoin %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[ProtocolPimInterfaceJoinState]{
		Output: ProtocolPimInterfaceJoinState{ProtocolPimInterfaceJoinArgs: req.Inputs},
	}, nil
}

// Delete removes the ProtocolPimInterfaceJoin configuration from VyOS.
func (ProtocolPimInterfaceJoin) Delete(
	ctx context.Context,
	req infer.DeleteRequest[ProtocolPimInterfaceJoinState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := protocolPimInterfaceJoinBasePath(req.State.InterfaceName, req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete ProtocolPimInterfaceJoin %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildProtocolPimInterfaceJoinOps builds set operations for all non-nil fields.
func buildProtocolPimInterfaceJoinOps(args ProtocolPimInterfaceJoinArgs) []vyosclient.Operation {
	base := protocolPimInterfaceJoinBasePath(args.InterfaceName, args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}

	for _, v := range args.SourceAddress {
		vp := make([]string, 0, 1+1)
		vp = append(vp, "source-address")
		vp = append(vp, v)
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, vp...)})
	}

	return ops
}

// buildProtocolPimInterfaceJoinUpdateOps computes the diff between previous and current state.
func buildProtocolPimInterfaceJoinUpdateOps(prev, cur ProtocolPimInterfaceJoinArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	base := protocolPimInterfaceJoinBasePath(cur.InterfaceName, cur.Name)

	ops = append(ops, diffMultiField(base, []string{"source-address"}, prev.SourceAddress, cur.SourceAddress)...)

	return ops
}

// parseProtocolPimInterfaceJoinConfig unmarshals VyOS ShowConfig JSON.
func parseProtocolPimInterfaceJoinConfig(interfaceName, name string, data json.RawMessage) (ProtocolPimInterfaceJoinArgs, error) {
	args := ProtocolPimInterfaceJoinArgs{
		InterfaceName: interfaceName,
		Name:          name,
	}

	if v, ok := getNestedValue(data, []string{"source-address"}); ok {
		vals, err := parseMultiValue(v)
		if err != nil {
			return ProtocolPimInterfaceJoinArgs{}, fmt.Errorf("parse source-address: %w", err)
		}
		args.SourceAddress = vals
	}

	return args, nil
}
