// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
	"regexp"
)

// FirewallGroupDynamicGroupIPv6AddressGroup manages a VyOS FirewallGroupDynamicGroupIPv6AddressGroup configuration.
type FirewallGroupDynamicGroupIPv6AddressGroup struct{}

// FirewallGroupDynamicGroupIPv6AddressGroupArgs defines the inputs for the FirewallGroupDynamicGroupIPv6AddressGroup resource.
type FirewallGroupDynamicGroupIPv6AddressGroupArgs struct {
	Name        string  `pulumi:"name"`
	Description *string `pulumi:"description,optional"`
}

// FirewallGroupDynamicGroupIPv6AddressGroupState defines the outputs for the FirewallGroupDynamicGroupIPv6AddressGroup resource.
type FirewallGroupDynamicGroupIPv6AddressGroupState struct {
	FirewallGroupDynamicGroupIPv6AddressGroupArgs
}

// Annotate provides schema metadata for the resource.
func (*FirewallGroupDynamicGroupIPv6AddressGroup) Annotate(a infer.Annotator) {
	a.Describe(new(FirewallGroupDynamicGroupIPv6AddressGroup), "Manages a VyOS Firewall dynamic IPv6 address group.")
}

// Annotate provides schema metadata for the inputs.
func (args *FirewallGroupDynamicGroupIPv6AddressGroupArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.Name, "Firewall dynamic IPv6 address group")
	a.Describe(&args.Description, "Description")
}

var firewallGroupDynamicGroupIPv6AddressGroupNameRe = regexp.MustCompile(`^(?:` + "[a-zA-Z0-9][\\w\\-\\.]*" + `)$`)
var firewallGroupDynamicGroupIPv6AddressGroupDescriptionRe = regexp.MustCompile(`^(?:` + ".{0,255}" + `)$`)

// Check validates the FirewallGroupDynamicGroupIPv6AddressGroup inputs.
func (FirewallGroupDynamicGroupIPv6AddressGroup) Check(
	ctx context.Context,
	req infer.CheckRequest,
) (infer.CheckResponse[FirewallGroupDynamicGroupIPv6AddressGroupArgs], error) {
	inputs, failures, err := infer.DefaultCheck[FirewallGroupDynamicGroupIPv6AddressGroupArgs](ctx, req.NewInputs)
	if err != nil {
		return infer.CheckResponse[FirewallGroupDynamicGroupIPv6AddressGroupArgs]{}, err
	}
	if f := checkRegex(inputs.Name, firewallGroupDynamicGroupIPv6AddressGroupNameRe, "name", ""); f != nil {
		failures = append(failures, *f)
	}
	if inputs.Description != nil {
		if f := checkRegex(*inputs.Description, firewallGroupDynamicGroupIPv6AddressGroupDescriptionRe, "description", "Description too long (limit 255 characters)"); f != nil {
			failures = append(failures, *f)
		}
	}

	return infer.CheckResponse[FirewallGroupDynamicGroupIPv6AddressGroupArgs]{Inputs: inputs, Failures: failures}, nil
}

func firewallGroupDynamicGroupIPv6AddressGroupBasePath(name string) []any {
	return []any{"firewall", "group", "dynamic-group", "ipv6-address-group", name}
}

// Create sets up the FirewallGroupDynamicGroupIPv6AddressGroup on VyOS.
func (FirewallGroupDynamicGroupIPv6AddressGroup) Create(
	ctx context.Context,
	req infer.CreateRequest[FirewallGroupDynamicGroupIPv6AddressGroupArgs],
) (infer.CreateResponse[FirewallGroupDynamicGroupIPv6AddressGroupState], error) {
	if req.DryRun {
		return infer.CreateResponse[FirewallGroupDynamicGroupIPv6AddressGroupState]{
			ID:     req.Inputs.Name,
			Output: FirewallGroupDynamicGroupIPv6AddressGroupState{FirewallGroupDynamicGroupIPv6AddressGroupArgs: req.Inputs},
		}, nil
	}

	ops := buildFirewallGroupDynamicGroupIPv6AddressGroupOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[FirewallGroupDynamicGroupIPv6AddressGroupState]{},
			fmt.Errorf("configure FirewallGroupDynamicGroupIPv6AddressGroup %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[FirewallGroupDynamicGroupIPv6AddressGroupState]{
		ID:     req.Inputs.Name,
		Output: FirewallGroupDynamicGroupIPv6AddressGroupState{FirewallGroupDynamicGroupIPv6AddressGroupArgs: req.Inputs},
	}, nil
}

// Read fetches the current FirewallGroupDynamicGroupIPv6AddressGroup config from VyOS.
func (FirewallGroupDynamicGroupIPv6AddressGroup) Read(
	ctx context.Context,
	req infer.ReadRequest[FirewallGroupDynamicGroupIPv6AddressGroupArgs, FirewallGroupDynamicGroupIPv6AddressGroupState],
) (infer.ReadResponse[FirewallGroupDynamicGroupIPv6AddressGroupArgs, FirewallGroupDynamicGroupIPv6AddressGroupState], error) {
	client := getClient(ctx)
	base := firewallGroupDynamicGroupIPv6AddressGroupBasePath(req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := FirewallGroupDynamicGroupIPv6AddressGroupArgs{Name: req.State.Name}
			state := FirewallGroupDynamicGroupIPv6AddressGroupState{FirewallGroupDynamicGroupIPv6AddressGroupArgs: args}
			return infer.ReadResponse[FirewallGroupDynamicGroupIPv6AddressGroupArgs, FirewallGroupDynamicGroupIPv6AddressGroupState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[FirewallGroupDynamicGroupIPv6AddressGroupArgs, FirewallGroupDynamicGroupIPv6AddressGroupState]{},
			fmt.Errorf("read FirewallGroupDynamicGroupIPv6AddressGroup %s: %w", req.State.Name, err)
	}

	args, err := parseFirewallGroupDynamicGroupIPv6AddressGroupConfig(req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[FirewallGroupDynamicGroupIPv6AddressGroupArgs, FirewallGroupDynamicGroupIPv6AddressGroupState]{},
			fmt.Errorf("parse FirewallGroupDynamicGroupIPv6AddressGroup %s config: %w", req.State.Name, err)
	}

	state := FirewallGroupDynamicGroupIPv6AddressGroupState{FirewallGroupDynamicGroupIPv6AddressGroupArgs: args}
	return infer.ReadResponse[FirewallGroupDynamicGroupIPv6AddressGroupArgs, FirewallGroupDynamicGroupIPv6AddressGroupState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing FirewallGroupDynamicGroupIPv6AddressGroup configuration.
func (FirewallGroupDynamicGroupIPv6AddressGroup) Update(
	ctx context.Context,
	req infer.UpdateRequest[FirewallGroupDynamicGroupIPv6AddressGroupArgs, FirewallGroupDynamicGroupIPv6AddressGroupState],
) (infer.UpdateResponse[FirewallGroupDynamicGroupIPv6AddressGroupState], error) {
	if req.DryRun {
		return infer.UpdateResponse[FirewallGroupDynamicGroupIPv6AddressGroupState]{
			Output: FirewallGroupDynamicGroupIPv6AddressGroupState{FirewallGroupDynamicGroupIPv6AddressGroupArgs: req.Inputs},
		}, nil
	}

	ops := buildFirewallGroupDynamicGroupIPv6AddressGroupUpdateOps(req.State.FirewallGroupDynamicGroupIPv6AddressGroupArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[FirewallGroupDynamicGroupIPv6AddressGroupState]{},
				fmt.Errorf("update FirewallGroupDynamicGroupIPv6AddressGroup %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[FirewallGroupDynamicGroupIPv6AddressGroupState]{
		Output: FirewallGroupDynamicGroupIPv6AddressGroupState{FirewallGroupDynamicGroupIPv6AddressGroupArgs: req.Inputs},
	}, nil
}

// Delete removes the FirewallGroupDynamicGroupIPv6AddressGroup configuration from VyOS.
func (FirewallGroupDynamicGroupIPv6AddressGroup) Delete(
	ctx context.Context,
	req infer.DeleteRequest[FirewallGroupDynamicGroupIPv6AddressGroupState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := firewallGroupDynamicGroupIPv6AddressGroupBasePath(req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete FirewallGroupDynamicGroupIPv6AddressGroup %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildFirewallGroupDynamicGroupIPv6AddressGroupOps builds set operations for all non-nil fields.
func buildFirewallGroupDynamicGroupIPv6AddressGroupOps(args FirewallGroupDynamicGroupIPv6AddressGroupArgs) []vyosclient.Operation {
	base := firewallGroupDynamicGroupIPv6AddressGroupBasePath(args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}

	if args.Description != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "description"), Value: *args.Description})
	}

	return ops
}

// buildFirewallGroupDynamicGroupIPv6AddressGroupUpdateOps computes the diff between previous and current state.
func buildFirewallGroupDynamicGroupIPv6AddressGroupUpdateOps(prev, cur FirewallGroupDynamicGroupIPv6AddressGroupArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	base := firewallGroupDynamicGroupIPv6AddressGroupBasePath(cur.Name)

	ops = append(ops, diffStringField(base, []string{"description"}, prev.Description, cur.Description)...)

	return ops
}

// parseFirewallGroupDynamicGroupIPv6AddressGroupConfig unmarshals VyOS ShowConfig JSON.
func parseFirewallGroupDynamicGroupIPv6AddressGroupConfig(name string, data json.RawMessage) (FirewallGroupDynamicGroupIPv6AddressGroupArgs, error) {
	args := FirewallGroupDynamicGroupIPv6AddressGroupArgs{
		Name: name,
	}

	if v, ok := getNestedValue(data, []string{"description"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return FirewallGroupDynamicGroupIPv6AddressGroupArgs{}, fmt.Errorf("parse description: %w", err)
		}
		args.Description = &s
	}

	return args, nil
}
