// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
	"regexp"
	"strconv"
)

// VRFNameArea manages a VyOS VRFNameArea configuration.
type VRFNameArea struct{}

// VRFNameAreaArgs defines the inputs for the VRFNameArea resource.
type VRFNameAreaArgs struct {
	NameName                string   `pulumi:"nameName"`
	Name                    string   `pulumi:"name"`
	Authentication          *string  `pulumi:"authentication,optional"`
	Network                 []string `pulumi:"network,optional"`
	Shortcut                *string  `pulumi:"shortcut,optional"`
	ExportList              *int     `pulumi:"exportList,optional"`
	ImportList              *int     `pulumi:"importList,optional"`
	AreaTypeNormal          *bool    `pulumi:"areaTypeNormal,optional"`
	AreaTypeNssaDefaultCost *int     `pulumi:"areaTypeNssaDefaultCost,optional"`
	AreaTypeNssaNoSummary   *bool    `pulumi:"areaTypeNssaNoSummary,optional"`
	AreaTypeNssaTranslate   *string  `pulumi:"areaTypeNssaTranslate,optional"`
	AreaTypeStubDefaultCost *int     `pulumi:"areaTypeStubDefaultCost,optional"`
	AreaTypeStubNoSummary   *bool    `pulumi:"areaTypeStubNoSummary,optional"`
}

// VRFNameAreaState defines the outputs for the VRFNameArea resource.
type VRFNameAreaState struct {
	VRFNameAreaArgs
}

// Annotate provides schema metadata for the resource.
func (*VRFNameArea) Annotate(a infer.Annotator) {
	a.Describe(new(VRFNameArea), "Manages a VyOS OSPF area settings.")
}

// Annotate provides schema metadata for the inputs.
func (args *VRFNameAreaArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.NameName, "Parent tag node key")
	a.Describe(&args.Name, "OSPF area settings")
	a.Describe(&args.Authentication, "OSPF area authentication type")
	a.Describe(&args.Network, "OSPF network")
	a.Describe(&args.Shortcut, "Area shortcut mode")
	a.Describe(&args.ExportList, "Set the filter for networks announced to other areas")
	a.Describe(&args.ImportList, "Set the filter for networks from other areas announced")
	a.Describe(&args.AreaTypeNormal, "Normal OSPF area")
	a.Describe(&args.AreaTypeNssaDefaultCost, "Summary-default cost of an NSSA area")
	a.Describe(&args.AreaTypeNssaNoSummary, "Do not inject inter-area routes into stub")
	a.Describe(&args.AreaTypeNssaTranslate, "Configure NSSA-ABR")
	a.Describe(&args.AreaTypeStubDefaultCost, "Summary-default cost")
	a.Describe(&args.AreaTypeStubNoSummary, "Do not inject inter-area routes into the stub")
}

var vrfNameAreaAuthenticationRe = regexp.MustCompile(`^(?:` + "(plaintext-password|md5)" + `)$`)
var vrfNameAreaShortcutRe = regexp.MustCompile(`^(?:` + "(default|disable|enable)" + `)$`)
var vrfNameAreaAreaTypeNssaTranslateRe = regexp.MustCompile(`^(?:` + "(always|candidate|never)" + `)$`)

// Check validates the VRFNameArea inputs.
func (VRFNameArea) Check(
	ctx context.Context,
	req infer.CheckRequest,
) (infer.CheckResponse[VRFNameAreaArgs], error) {
	inputs, failures, err := infer.DefaultCheck[VRFNameAreaArgs](ctx, req.NewInputs)
	if err != nil {
		return infer.CheckResponse[VRFNameAreaArgs]{}, err
	}
	if inputs.Authentication != nil {
		if f := checkRegex(*inputs.Authentication, vrfNameAreaAuthenticationRe, "authentication", ""); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.Shortcut != nil {
		if f := checkRegex(*inputs.Shortcut, vrfNameAreaShortcutRe, "shortcut", ""); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.ExportList != nil {
		if f := checkIntRange(int64(*inputs.ExportList), 0, 4294967295, "exportList", ""); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.ImportList != nil {
		if f := checkIntRange(int64(*inputs.ImportList), 0, 4294967295, "importList", ""); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.AreaTypeNssaDefaultCost != nil {
		if f := checkIntRange(int64(*inputs.AreaTypeNssaDefaultCost), 0, 16777215, "areaTypeNssaDefaultCost", ""); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.AreaTypeNssaTranslate != nil {
		if f := checkRegex(*inputs.AreaTypeNssaTranslate, vrfNameAreaAreaTypeNssaTranslateRe, "areaTypeNssaTranslate", ""); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.AreaTypeStubDefaultCost != nil {
		if f := checkIntRange(int64(*inputs.AreaTypeStubDefaultCost), 0, 16777215, "areaTypeStubDefaultCost", ""); f != nil {
			failures = append(failures, *f)
		}
	}

	return infer.CheckResponse[VRFNameAreaArgs]{Inputs: inputs, Failures: failures}, nil
}

func vrfNameAreaBasePath(nameName, name string) []any {
	return []any{"vrf", "name", nameName, "area", name}
}

// Create sets up the VRFNameArea on VyOS.
func (VRFNameArea) Create(
	ctx context.Context,
	req infer.CreateRequest[VRFNameAreaArgs],
) (infer.CreateResponse[VRFNameAreaState], error) {
	if req.DryRun {
		return infer.CreateResponse[VRFNameAreaState]{
			ID:     req.Inputs.Name,
			Output: VRFNameAreaState{VRFNameAreaArgs: req.Inputs},
		}, nil
	}

	ops := buildVRFNameAreaOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[VRFNameAreaState]{},
			fmt.Errorf("configure VRFNameArea %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[VRFNameAreaState]{
		ID:     req.Inputs.Name,
		Output: VRFNameAreaState{VRFNameAreaArgs: req.Inputs},
	}, nil
}

// Read fetches the current VRFNameArea config from VyOS.
func (VRFNameArea) Read(
	ctx context.Context,
	req infer.ReadRequest[VRFNameAreaArgs, VRFNameAreaState],
) (infer.ReadResponse[VRFNameAreaArgs, VRFNameAreaState], error) {
	client := getClient(ctx)
	base := vrfNameAreaBasePath(req.State.NameName, req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := VRFNameAreaArgs{NameName: req.State.NameName, Name: req.State.Name}
			state := VRFNameAreaState{VRFNameAreaArgs: args}
			return infer.ReadResponse[VRFNameAreaArgs, VRFNameAreaState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[VRFNameAreaArgs, VRFNameAreaState]{},
			fmt.Errorf("read VRFNameArea %s: %w", req.State.Name, err)
	}

	args, err := parseVRFNameAreaConfig(req.State.NameName, req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[VRFNameAreaArgs, VRFNameAreaState]{},
			fmt.Errorf("parse VRFNameArea %s config: %w", req.State.Name, err)
	}

	state := VRFNameAreaState{VRFNameAreaArgs: args}
	return infer.ReadResponse[VRFNameAreaArgs, VRFNameAreaState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing VRFNameArea configuration.
func (VRFNameArea) Update(
	ctx context.Context,
	req infer.UpdateRequest[VRFNameAreaArgs, VRFNameAreaState],
) (infer.UpdateResponse[VRFNameAreaState], error) {
	if req.DryRun {
		return infer.UpdateResponse[VRFNameAreaState]{
			Output: VRFNameAreaState{VRFNameAreaArgs: req.Inputs},
		}, nil
	}

	ops := buildVRFNameAreaUpdateOps(req.State.VRFNameAreaArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[VRFNameAreaState]{},
				fmt.Errorf("update VRFNameArea %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[VRFNameAreaState]{
		Output: VRFNameAreaState{VRFNameAreaArgs: req.Inputs},
	}, nil
}

// Delete removes the VRFNameArea configuration from VyOS.
func (VRFNameArea) Delete(
	ctx context.Context,
	req infer.DeleteRequest[VRFNameAreaState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := vrfNameAreaBasePath(req.State.NameName, req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete VRFNameArea %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildVRFNameAreaOps builds set operations for all non-nil fields.
func buildVRFNameAreaOps(args VRFNameAreaArgs) []vyosclient.Operation {
	base := vrfNameAreaBasePath(args.NameName, args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}

	if args.Authentication != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "authentication"), Value: *args.Authentication})
	}

	for _, v := range args.Network {
		vp := make([]string, 0, 1+1)
		vp = append(vp, "network")
		vp = append(vp, v)
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, vp...)})
	}

	if args.Shortcut != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "shortcut"), Value: *args.Shortcut})
	}

	if args.ExportList != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "export-list"), Value: strconv.Itoa(*args.ExportList)})
	}

	if args.ImportList != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "import-list"), Value: strconv.Itoa(*args.ImportList)})
	}

	if args.AreaTypeNormal != nil && *args.AreaTypeNormal {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "area-type", "normal")})
	}

	if args.AreaTypeNssaDefaultCost != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "area-type", "nssa", "default-cost"), Value: strconv.Itoa(*args.AreaTypeNssaDefaultCost)})
	}

	if args.AreaTypeNssaNoSummary != nil && *args.AreaTypeNssaNoSummary {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "area-type", "nssa", "no-summary")})
	}

	if args.AreaTypeNssaTranslate != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "area-type", "nssa", "translate"), Value: *args.AreaTypeNssaTranslate})
	}

	if args.AreaTypeStubDefaultCost != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "area-type", "stub", "default-cost"), Value: strconv.Itoa(*args.AreaTypeStubDefaultCost)})
	}

	if args.AreaTypeStubNoSummary != nil && *args.AreaTypeStubNoSummary {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "area-type", "stub", "no-summary")})
	}

	return ops
}

// buildVRFNameAreaUpdateOps computes the diff between previous and current state.
func buildVRFNameAreaUpdateOps(prev, cur VRFNameAreaArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	base := vrfNameAreaBasePath(cur.NameName, cur.Name)

	ops = append(ops, diffStringField(base, []string{"authentication"}, prev.Authentication, cur.Authentication)...)

	ops = append(ops, diffMultiField(base, []string{"network"}, prev.Network, cur.Network)...)

	ops = append(ops, diffStringField(base, []string{"shortcut"}, prev.Shortcut, cur.Shortcut)...)

	ops = append(ops, diffIntField(base, []string{"export-list"}, prev.ExportList, cur.ExportList)...)

	ops = append(ops, diffIntField(base, []string{"import-list"}, prev.ImportList, cur.ImportList)...)

	ops = append(ops, diffBoolField(base, []string{"area-type", "normal"}, prev.AreaTypeNormal, cur.AreaTypeNormal)...)

	ops = append(ops, diffIntField(base, []string{"area-type", "nssa", "default-cost"}, prev.AreaTypeNssaDefaultCost, cur.AreaTypeNssaDefaultCost)...)

	ops = append(ops, diffBoolField(base, []string{"area-type", "nssa", "no-summary"}, prev.AreaTypeNssaNoSummary, cur.AreaTypeNssaNoSummary)...)

	ops = append(ops, diffStringField(base, []string{"area-type", "nssa", "translate"}, prev.AreaTypeNssaTranslate, cur.AreaTypeNssaTranslate)...)

	ops = append(ops, diffIntField(base, []string{"area-type", "stub", "default-cost"}, prev.AreaTypeStubDefaultCost, cur.AreaTypeStubDefaultCost)...)

	ops = append(ops, diffBoolField(base, []string{"area-type", "stub", "no-summary"}, prev.AreaTypeStubNoSummary, cur.AreaTypeStubNoSummary)...)

	return ops
}

// parseVRFNameAreaConfig unmarshals VyOS ShowConfig JSON.
func parseVRFNameAreaConfig(nameName, name string, data json.RawMessage) (VRFNameAreaArgs, error) {
	args := VRFNameAreaArgs{
		NameName: nameName,
		Name:     name,
	}

	if v, ok := getNestedValue(data, []string{"authentication"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return VRFNameAreaArgs{}, fmt.Errorf("parse authentication: %w", err)
		}
		args.Authentication = &s
	}

	if v, ok := getNestedValue(data, []string{"network"}); ok {
		vals, err := parseMultiValue(v)
		if err != nil {
			return VRFNameAreaArgs{}, fmt.Errorf("parse network: %w", err)
		}
		args.Network = vals
	}

	if v, ok := getNestedValue(data, []string{"shortcut"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return VRFNameAreaArgs{}, fmt.Errorf("parse shortcut: %w", err)
		}
		args.Shortcut = &s
	}

	if v, ok := getNestedValue(data, []string{"export-list"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return VRFNameAreaArgs{}, fmt.Errorf("parse export-list: %w", err)
		}
		args.ExportList = &n
	}

	if v, ok := getNestedValue(data, []string{"import-list"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return VRFNameAreaArgs{}, fmt.Errorf("parse import-list: %w", err)
		}
		args.ImportList = &n
	}

	if _, ok := getNestedValue(data, []string{"area-type", "normal"}); ok {
		t := true
		args.AreaTypeNormal = &t
	}

	if v, ok := getNestedValue(data, []string{"area-type", "nssa", "default-cost"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return VRFNameAreaArgs{}, fmt.Errorf("parse default-cost: %w", err)
		}
		args.AreaTypeNssaDefaultCost = &n
	}

	if _, ok := getNestedValue(data, []string{"area-type", "nssa", "no-summary"}); ok {
		t := true
		args.AreaTypeNssaNoSummary = &t
	}

	if v, ok := getNestedValue(data, []string{"area-type", "nssa", "translate"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return VRFNameAreaArgs{}, fmt.Errorf("parse translate: %w", err)
		}
		args.AreaTypeNssaTranslate = &s
	}

	if v, ok := getNestedValue(data, []string{"area-type", "stub", "default-cost"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return VRFNameAreaArgs{}, fmt.Errorf("parse default-cost: %w", err)
		}
		args.AreaTypeStubDefaultCost = &n
	}

	if _, ok := getNestedValue(data, []string{"area-type", "stub", "no-summary"}); ok {
		t := true
		args.AreaTypeStubNoSummary = &t
	}

	return args, nil
}
