// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
	"regexp"
	"strconv"
)

// InterfaceWireguardPeer manages a VyOS InterfaceWireguardPeer configuration.
type InterfaceWireguardPeer struct{}

// InterfaceWireguardPeerArgs defines the inputs for the InterfaceWireguardPeer resource.
type InterfaceWireguardPeerArgs struct {
	WireguardName       string   `pulumi:"wireguardName"`
	Name                string   `pulumi:"name"`
	Disable             *bool    `pulumi:"disable,optional"`
	Description         *string  `pulumi:"description,optional"`
	PublicKey           *string  `pulumi:"publicKey,optional"`
	PresharedKey        *string  `pulumi:"presharedKey,optional"`
	AllowedIps          []string `pulumi:"allowedIps,optional"`
	Address             *string  `pulumi:"address,optional"`
	HostName            *string  `pulumi:"hostName,optional"`
	Port                *int     `pulumi:"port,optional"`
	PersistentKeepalive *int     `pulumi:"persistentKeepalive,optional"`
}

// InterfaceWireguardPeerState defines the outputs for the InterfaceWireguardPeer resource.
type InterfaceWireguardPeerState struct {
	InterfaceWireguardPeerArgs
}

// Annotate provides schema metadata for the resource.
func (*InterfaceWireguardPeer) Annotate(a infer.Annotator) {
	a.Describe(new(InterfaceWireguardPeer), "Manages a VyOS peer alias.")
}

// Annotate provides schema metadata for the inputs.
func (args *InterfaceWireguardPeerArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.WireguardName, "Parent tag node key")
	a.Describe(&args.Name, "peer alias")
	a.Describe(&args.Disable, "Disable instance")
	a.Describe(&args.Description, "Description")
	a.Describe(&args.PublicKey, "Base64 encoded public key")
	a.Describe(&args.PresharedKey, "Base64 encoded preshared key")
	a.Describe(&args.AllowedIps, "IP addresses allowed to traverse the peer")
	a.Describe(&args.Address, "IP address of tunnel endpoint")
	a.Describe(&args.HostName, "Hostname of tunnel endpoint")
	a.Describe(&args.Port, "Port number used by connection")
	a.Describe(&args.PersistentKeepalive, "Interval to send keepalive messages")
}

var interfaceWireguardPeerDescriptionRe = regexp.MustCompile(`^(?:` + ".{0,255}" + `)$`)

// Check validates the InterfaceWireguardPeer inputs.
func (InterfaceWireguardPeer) Check(
	ctx context.Context,
	req infer.CheckRequest,
) (infer.CheckResponse[InterfaceWireguardPeerArgs], error) {
	inputs, failures, err := infer.DefaultCheck[InterfaceWireguardPeerArgs](ctx, req.NewInputs)
	if err != nil {
		return infer.CheckResponse[InterfaceWireguardPeerArgs]{}, err
	}
	if inputs.Description != nil {
		if f := checkRegex(*inputs.Description, interfaceWireguardPeerDescriptionRe, "description", "Description too long (limit 255 characters)"); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.Port != nil {
		if f := checkIntRange(int64(*inputs.Port), 1, 65535, "port", "Port number must be in range 1 to 65535"); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.PersistentKeepalive != nil {
		if f := checkIntRange(int64(*inputs.PersistentKeepalive), 1, 65535, "persistentKeepalive", ""); f != nil {
			failures = append(failures, *f)
		}
	}

	return infer.CheckResponse[InterfaceWireguardPeerArgs]{Inputs: inputs, Failures: failures}, nil
}

func interfaceWireguardPeerBasePath(wireguardName, name string) []any {
	return []any{"interfaces", "wireguard", wireguardName, "peer", name}
}

// Create sets up the InterfaceWireguardPeer on VyOS.
func (InterfaceWireguardPeer) Create(
	ctx context.Context,
	req infer.CreateRequest[InterfaceWireguardPeerArgs],
) (infer.CreateResponse[InterfaceWireguardPeerState], error) {
	if req.DryRun {
		return infer.CreateResponse[InterfaceWireguardPeerState]{
			ID:     req.Inputs.Name,
			Output: InterfaceWireguardPeerState{InterfaceWireguardPeerArgs: req.Inputs},
		}, nil
	}

	ops := buildInterfaceWireguardPeerOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[InterfaceWireguardPeerState]{},
			fmt.Errorf("configure InterfaceWireguardPeer %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[InterfaceWireguardPeerState]{
		ID:     req.Inputs.Name,
		Output: InterfaceWireguardPeerState{InterfaceWireguardPeerArgs: req.Inputs},
	}, nil
}

// Read fetches the current InterfaceWireguardPeer config from VyOS.
func (InterfaceWireguardPeer) Read(
	ctx context.Context,
	req infer.ReadRequest[InterfaceWireguardPeerArgs, InterfaceWireguardPeerState],
) (infer.ReadResponse[InterfaceWireguardPeerArgs, InterfaceWireguardPeerState], error) {
	client := getClient(ctx)
	base := interfaceWireguardPeerBasePath(req.State.WireguardName, req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := InterfaceWireguardPeerArgs{WireguardName: req.State.WireguardName, Name: req.State.Name}
			state := InterfaceWireguardPeerState{InterfaceWireguardPeerArgs: args}
			return infer.ReadResponse[InterfaceWireguardPeerArgs, InterfaceWireguardPeerState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[InterfaceWireguardPeerArgs, InterfaceWireguardPeerState]{},
			fmt.Errorf("read InterfaceWireguardPeer %s: %w", req.State.Name, err)
	}

	args, err := parseInterfaceWireguardPeerConfig(req.State.WireguardName, req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[InterfaceWireguardPeerArgs, InterfaceWireguardPeerState]{},
			fmt.Errorf("parse InterfaceWireguardPeer %s config: %w", req.State.Name, err)
	}

	state := InterfaceWireguardPeerState{InterfaceWireguardPeerArgs: args}
	return infer.ReadResponse[InterfaceWireguardPeerArgs, InterfaceWireguardPeerState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing InterfaceWireguardPeer configuration.
func (InterfaceWireguardPeer) Update(
	ctx context.Context,
	req infer.UpdateRequest[InterfaceWireguardPeerArgs, InterfaceWireguardPeerState],
) (infer.UpdateResponse[InterfaceWireguardPeerState], error) {
	if req.DryRun {
		return infer.UpdateResponse[InterfaceWireguardPeerState]{
			Output: InterfaceWireguardPeerState{InterfaceWireguardPeerArgs: req.Inputs},
		}, nil
	}

	ops := buildInterfaceWireguardPeerUpdateOps(req.State.InterfaceWireguardPeerArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[InterfaceWireguardPeerState]{},
				fmt.Errorf("update InterfaceWireguardPeer %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[InterfaceWireguardPeerState]{
		Output: InterfaceWireguardPeerState{InterfaceWireguardPeerArgs: req.Inputs},
	}, nil
}

// Delete removes the InterfaceWireguardPeer configuration from VyOS.
func (InterfaceWireguardPeer) Delete(
	ctx context.Context,
	req infer.DeleteRequest[InterfaceWireguardPeerState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := interfaceWireguardPeerBasePath(req.State.WireguardName, req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete InterfaceWireguardPeer %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildInterfaceWireguardPeerOps builds set operations for all non-nil fields.
func buildInterfaceWireguardPeerOps(args InterfaceWireguardPeerArgs) []vyosclient.Operation {
	base := interfaceWireguardPeerBasePath(args.WireguardName, args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}

	if args.Disable != nil && *args.Disable {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "disable")})
	}

	if args.Description != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "description"), Value: *args.Description})
	}

	if args.PublicKey != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "public-key"), Value: *args.PublicKey})
	}

	if args.PresharedKey != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "preshared-key"), Value: *args.PresharedKey})
	}

	for _, v := range args.AllowedIps {
		vp := make([]string, 0, 1+1)
		vp = append(vp, "allowed-ips")
		vp = append(vp, v)
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, vp...)})
	}

	if args.Address != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "address"), Value: *args.Address})
	}

	if args.HostName != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "host-name"), Value: *args.HostName})
	}

	if args.Port != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "port"), Value: strconv.Itoa(*args.Port)})
	}

	if args.PersistentKeepalive != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "persistent-keepalive"), Value: strconv.Itoa(*args.PersistentKeepalive)})
	}

	return ops
}

// buildInterfaceWireguardPeerUpdateOps computes the diff between previous and current state.
func buildInterfaceWireguardPeerUpdateOps(prev, cur InterfaceWireguardPeerArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	base := interfaceWireguardPeerBasePath(cur.WireguardName, cur.Name)

	ops = append(ops, diffBoolField(base, []string{"disable"}, prev.Disable, cur.Disable)...)

	ops = append(ops, diffStringField(base, []string{"description"}, prev.Description, cur.Description)...)

	ops = append(ops, diffStringField(base, []string{"public-key"}, prev.PublicKey, cur.PublicKey)...)

	ops = append(ops, diffStringField(base, []string{"preshared-key"}, prev.PresharedKey, cur.PresharedKey)...)

	ops = append(ops, diffMultiField(base, []string{"allowed-ips"}, prev.AllowedIps, cur.AllowedIps)...)

	ops = append(ops, diffStringField(base, []string{"address"}, prev.Address, cur.Address)...)

	ops = append(ops, diffStringField(base, []string{"host-name"}, prev.HostName, cur.HostName)...)

	ops = append(ops, diffIntField(base, []string{"port"}, prev.Port, cur.Port)...)

	ops = append(ops, diffIntField(base, []string{"persistent-keepalive"}, prev.PersistentKeepalive, cur.PersistentKeepalive)...)

	return ops
}

// parseInterfaceWireguardPeerConfig unmarshals VyOS ShowConfig JSON.
func parseInterfaceWireguardPeerConfig(wireguardName, name string, data json.RawMessage) (InterfaceWireguardPeerArgs, error) {
	args := InterfaceWireguardPeerArgs{
		WireguardName: wireguardName,
		Name:          name,
	}

	if _, ok := getNestedValue(data, []string{"disable"}); ok {
		t := true
		args.Disable = &t
	}

	if v, ok := getNestedValue(data, []string{"description"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return InterfaceWireguardPeerArgs{}, fmt.Errorf("parse description: %w", err)
		}
		args.Description = &s
	}

	if v, ok := getNestedValue(data, []string{"public-key"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return InterfaceWireguardPeerArgs{}, fmt.Errorf("parse public-key: %w", err)
		}
		args.PublicKey = &s
	}

	if v, ok := getNestedValue(data, []string{"preshared-key"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return InterfaceWireguardPeerArgs{}, fmt.Errorf("parse preshared-key: %w", err)
		}
		args.PresharedKey = &s
	}

	if v, ok := getNestedValue(data, []string{"allowed-ips"}); ok {
		vals, err := parseMultiValue(v)
		if err != nil {
			return InterfaceWireguardPeerArgs{}, fmt.Errorf("parse allowed-ips: %w", err)
		}
		args.AllowedIps = vals
	}

	if v, ok := getNestedValue(data, []string{"address"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return InterfaceWireguardPeerArgs{}, fmt.Errorf("parse address: %w", err)
		}
		args.Address = &s
	}

	if v, ok := getNestedValue(data, []string{"host-name"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return InterfaceWireguardPeerArgs{}, fmt.Errorf("parse host-name: %w", err)
		}
		args.HostName = &s
	}

	if v, ok := getNestedValue(data, []string{"port"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return InterfaceWireguardPeerArgs{}, fmt.Errorf("parse port: %w", err)
		}
		args.Port = &n
	}

	if v, ok := getNestedValue(data, []string{"persistent-keepalive"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return InterfaceWireguardPeerArgs{}, fmt.Errorf("parse persistent-keepalive: %w", err)
		}
		args.PersistentKeepalive = &n
	}

	return args, nil
}
