// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
	"regexp"
	"strconv"
)

// VppNATNat44ExcludeRule manages a VyOS VppNATNat44ExcludeRule configuration.
type VppNATNat44ExcludeRule struct{}

// VppNATNat44ExcludeRuleArgs defines the inputs for the VppNATNat44ExcludeRule resource.
type VppNATNat44ExcludeRuleArgs struct {
	Name              string  `pulumi:"name"`
	LocalAddress      *string `pulumi:"localAddress,optional"`
	LocalPort         *int    `pulumi:"localPort,optional"`
	Protocol          *string `pulumi:"protocol,optional"`
	ExternalInterface *string `pulumi:"externalInterface,optional"`
	Description       *string `pulumi:"description,optional"`
}

// VppNATNat44ExcludeRuleState defines the outputs for the VppNATNat44ExcludeRule resource.
type VppNATNat44ExcludeRuleState struct {
	VppNATNat44ExcludeRuleArgs
}

// Annotate provides schema metadata for the resource.
func (*VppNATNat44ExcludeRule) Annotate(a infer.Annotator) {
	a.Describe(new(VppNATNat44ExcludeRule), "Manages a VyOS Rule number.")
}

// Annotate provides schema metadata for the inputs.
func (args *VppNATNat44ExcludeRuleArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.Name, "Rule number")
	a.Describe(&args.LocalAddress, "IP address of the internal (local) device")
	a.Describe(&args.LocalPort, "Port number used by connection on internal device")
	a.Describe(&args.Protocol, "Protocol")
	a.Describe(&args.ExternalInterface, "External interface")
	a.Describe(&args.Description, "Description")
}

var vppNATNat44ExcludeRuleProtocolRe = regexp.MustCompile(`^(?:` + "(tcp|udp|icmp|all)" + `)$`)
var vppNATNat44ExcludeRuleDescriptionRe = regexp.MustCompile(`^(?:` + ".{0,255}" + `)$`)

// Check validates the VppNATNat44ExcludeRule inputs.
func (VppNATNat44ExcludeRule) Check(
	ctx context.Context,
	req infer.CheckRequest,
) (infer.CheckResponse[VppNATNat44ExcludeRuleArgs], error) {
	inputs, failures, err := infer.DefaultCheck[VppNATNat44ExcludeRuleArgs](ctx, req.NewInputs)
	if err != nil {
		return infer.CheckResponse[VppNATNat44ExcludeRuleArgs]{}, err
	}
	if inputs.LocalPort != nil {
		if f := checkIntRange(int64(*inputs.LocalPort), 1, 65535, "localPort", "Port number must be in range 1 to 65535"); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.Protocol != nil {
		if f := checkRegex(*inputs.Protocol, vppNATNat44ExcludeRuleProtocolRe, "protocol", ""); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.Description != nil {
		if f := checkRegex(*inputs.Description, vppNATNat44ExcludeRuleDescriptionRe, "description", "Description too long (limit 255 characters)"); f != nil {
			failures = append(failures, *f)
		}
	}

	return infer.CheckResponse[VppNATNat44ExcludeRuleArgs]{Inputs: inputs, Failures: failures}, nil
}

func vppNATNat44ExcludeRuleBasePath(name string) []any {
	return []any{"vpp", "nat", "nat44", "exclude", "rule", name}
}

// Create sets up the VppNATNat44ExcludeRule on VyOS.
func (VppNATNat44ExcludeRule) Create(
	ctx context.Context,
	req infer.CreateRequest[VppNATNat44ExcludeRuleArgs],
) (infer.CreateResponse[VppNATNat44ExcludeRuleState], error) {
	if req.DryRun {
		return infer.CreateResponse[VppNATNat44ExcludeRuleState]{
			ID:     req.Inputs.Name,
			Output: VppNATNat44ExcludeRuleState{VppNATNat44ExcludeRuleArgs: req.Inputs},
		}, nil
	}

	ops := buildVppNATNat44ExcludeRuleOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[VppNATNat44ExcludeRuleState]{},
			fmt.Errorf("configure VppNATNat44ExcludeRule %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[VppNATNat44ExcludeRuleState]{
		ID:     req.Inputs.Name,
		Output: VppNATNat44ExcludeRuleState{VppNATNat44ExcludeRuleArgs: req.Inputs},
	}, nil
}

// Read fetches the current VppNATNat44ExcludeRule config from VyOS.
func (VppNATNat44ExcludeRule) Read(
	ctx context.Context,
	req infer.ReadRequest[VppNATNat44ExcludeRuleArgs, VppNATNat44ExcludeRuleState],
) (infer.ReadResponse[VppNATNat44ExcludeRuleArgs, VppNATNat44ExcludeRuleState], error) {
	client := getClient(ctx)
	base := vppNATNat44ExcludeRuleBasePath(req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := VppNATNat44ExcludeRuleArgs{Name: req.State.Name}
			state := VppNATNat44ExcludeRuleState{VppNATNat44ExcludeRuleArgs: args}
			return infer.ReadResponse[VppNATNat44ExcludeRuleArgs, VppNATNat44ExcludeRuleState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[VppNATNat44ExcludeRuleArgs, VppNATNat44ExcludeRuleState]{},
			fmt.Errorf("read VppNATNat44ExcludeRule %s: %w", req.State.Name, err)
	}

	args, err := parseVppNATNat44ExcludeRuleConfig(req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[VppNATNat44ExcludeRuleArgs, VppNATNat44ExcludeRuleState]{},
			fmt.Errorf("parse VppNATNat44ExcludeRule %s config: %w", req.State.Name, err)
	}

	state := VppNATNat44ExcludeRuleState{VppNATNat44ExcludeRuleArgs: args}
	return infer.ReadResponse[VppNATNat44ExcludeRuleArgs, VppNATNat44ExcludeRuleState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing VppNATNat44ExcludeRule configuration.
func (VppNATNat44ExcludeRule) Update(
	ctx context.Context,
	req infer.UpdateRequest[VppNATNat44ExcludeRuleArgs, VppNATNat44ExcludeRuleState],
) (infer.UpdateResponse[VppNATNat44ExcludeRuleState], error) {
	if req.DryRun {
		return infer.UpdateResponse[VppNATNat44ExcludeRuleState]{
			Output: VppNATNat44ExcludeRuleState{VppNATNat44ExcludeRuleArgs: req.Inputs},
		}, nil
	}

	ops := buildVppNATNat44ExcludeRuleUpdateOps(req.State.VppNATNat44ExcludeRuleArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[VppNATNat44ExcludeRuleState]{},
				fmt.Errorf("update VppNATNat44ExcludeRule %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[VppNATNat44ExcludeRuleState]{
		Output: VppNATNat44ExcludeRuleState{VppNATNat44ExcludeRuleArgs: req.Inputs},
	}, nil
}

// Delete removes the VppNATNat44ExcludeRule configuration from VyOS.
func (VppNATNat44ExcludeRule) Delete(
	ctx context.Context,
	req infer.DeleteRequest[VppNATNat44ExcludeRuleState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := vppNATNat44ExcludeRuleBasePath(req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete VppNATNat44ExcludeRule %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildVppNATNat44ExcludeRuleOps builds set operations for all non-nil fields.
func buildVppNATNat44ExcludeRuleOps(args VppNATNat44ExcludeRuleArgs) []vyosclient.Operation {
	base := vppNATNat44ExcludeRuleBasePath(args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}

	if args.LocalAddress != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "local-address"), Value: *args.LocalAddress})
	}

	if args.LocalPort != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "local-port"), Value: strconv.Itoa(*args.LocalPort)})
	}

	if args.Protocol != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "protocol"), Value: *args.Protocol})
	}

	if args.ExternalInterface != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "external-interface"), Value: *args.ExternalInterface})
	}

	if args.Description != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "description"), Value: *args.Description})
	}

	return ops
}

// buildVppNATNat44ExcludeRuleUpdateOps computes the diff between previous and current state.
func buildVppNATNat44ExcludeRuleUpdateOps(prev, cur VppNATNat44ExcludeRuleArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	base := vppNATNat44ExcludeRuleBasePath(cur.Name)

	ops = append(ops, diffStringField(base, []string{"local-address"}, prev.LocalAddress, cur.LocalAddress)...)

	ops = append(ops, diffIntField(base, []string{"local-port"}, prev.LocalPort, cur.LocalPort)...)

	ops = append(ops, diffStringField(base, []string{"protocol"}, prev.Protocol, cur.Protocol)...)

	ops = append(ops, diffStringField(base, []string{"external-interface"}, prev.ExternalInterface, cur.ExternalInterface)...)

	ops = append(ops, diffStringField(base, []string{"description"}, prev.Description, cur.Description)...)

	return ops
}

// parseVppNATNat44ExcludeRuleConfig unmarshals VyOS ShowConfig JSON.
func parseVppNATNat44ExcludeRuleConfig(name string, data json.RawMessage) (VppNATNat44ExcludeRuleArgs, error) {
	args := VppNATNat44ExcludeRuleArgs{
		Name: name,
	}

	if v, ok := getNestedValue(data, []string{"local-address"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return VppNATNat44ExcludeRuleArgs{}, fmt.Errorf("parse local-address: %w", err)
		}
		args.LocalAddress = &s
	}

	if v, ok := getNestedValue(data, []string{"local-port"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return VppNATNat44ExcludeRuleArgs{}, fmt.Errorf("parse local-port: %w", err)
		}
		args.LocalPort = &n
	}

	if v, ok := getNestedValue(data, []string{"protocol"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return VppNATNat44ExcludeRuleArgs{}, fmt.Errorf("parse protocol: %w", err)
		}
		args.Protocol = &s
	}

	if v, ok := getNestedValue(data, []string{"external-interface"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return VppNATNat44ExcludeRuleArgs{}, fmt.Errorf("parse external-interface: %w", err)
		}
		args.ExternalInterface = &s
	}

	if v, ok := getNestedValue(data, []string{"description"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return VppNATNat44ExcludeRuleArgs{}, fmt.Errorf("parse description: %w", err)
		}
		args.Description = &s
	}

	return args, nil
}
