// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
	"regexp"
)

// VppIpfixInterface manages a VyOS VppIpfixInterface configuration.
type VppIpfixInterface struct{}

// VppIpfixInterfaceArgs defines the inputs for the VppIpfixInterface resource.
type VppIpfixInterfaceArgs struct {
	Name        string  `pulumi:"name"`
	Direction   *string `pulumi:"direction,optional"`
	FlowVariant *string `pulumi:"flowVariant,optional"`
}

// VppIpfixInterfaceState defines the outputs for the VppIpfixInterface resource.
type VppIpfixInterfaceState struct {
	VppIpfixInterfaceArgs
}

// Annotate provides schema metadata for the resource.
func (*VppIpfixInterface) Annotate(a infer.Annotator) {
	a.Describe(new(VppIpfixInterface), "Manages a VyOS Interface.")
}

// Annotate provides schema metadata for the inputs.
func (args *VppIpfixInterfaceArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.Name, "Interface")
	a.Describe(&args.Direction, "Flow direction")
	a.Describe(&args.FlowVariant, "Flow variant")
}

var vppIpfixInterfaceDirectionRe = regexp.MustCompile(`^(?:` + "(rx|tx|both)" + `)$`)
var vppIpfixInterfaceFlowVariantRe = regexp.MustCompile(`^(?:` + "(l2|ipv4|ipv6)" + `)$`)

// Check validates the VppIpfixInterface inputs.
func (VppIpfixInterface) Check(
	ctx context.Context,
	req infer.CheckRequest,
) (infer.CheckResponse[VppIpfixInterfaceArgs], error) {
	inputs, failures, err := infer.DefaultCheck[VppIpfixInterfaceArgs](ctx, req.NewInputs)
	if err != nil {
		return infer.CheckResponse[VppIpfixInterfaceArgs]{}, err
	}
	if inputs.Direction != nil {
		if f := checkRegex(*inputs.Direction, vppIpfixInterfaceDirectionRe, "direction", ""); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.FlowVariant != nil {
		if f := checkRegex(*inputs.FlowVariant, vppIpfixInterfaceFlowVariantRe, "flowVariant", ""); f != nil {
			failures = append(failures, *f)
		}
	}

	return infer.CheckResponse[VppIpfixInterfaceArgs]{Inputs: inputs, Failures: failures}, nil
}

func vppIpfixInterfaceBasePath(name string) []any {
	return []any{"vpp", "ipfix", "interface", name}
}

// Create sets up the VppIpfixInterface on VyOS.
func (VppIpfixInterface) Create(
	ctx context.Context,
	req infer.CreateRequest[VppIpfixInterfaceArgs],
) (infer.CreateResponse[VppIpfixInterfaceState], error) {
	if req.DryRun {
		return infer.CreateResponse[VppIpfixInterfaceState]{
			ID:     req.Inputs.Name,
			Output: VppIpfixInterfaceState{VppIpfixInterfaceArgs: req.Inputs},
		}, nil
	}

	ops := buildVppIpfixInterfaceOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[VppIpfixInterfaceState]{},
			fmt.Errorf("configure VppIpfixInterface %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[VppIpfixInterfaceState]{
		ID:     req.Inputs.Name,
		Output: VppIpfixInterfaceState{VppIpfixInterfaceArgs: req.Inputs},
	}, nil
}

// Read fetches the current VppIpfixInterface config from VyOS.
func (VppIpfixInterface) Read(
	ctx context.Context,
	req infer.ReadRequest[VppIpfixInterfaceArgs, VppIpfixInterfaceState],
) (infer.ReadResponse[VppIpfixInterfaceArgs, VppIpfixInterfaceState], error) {
	client := getClient(ctx)
	base := vppIpfixInterfaceBasePath(req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := VppIpfixInterfaceArgs{Name: req.State.Name}
			state := VppIpfixInterfaceState{VppIpfixInterfaceArgs: args}
			return infer.ReadResponse[VppIpfixInterfaceArgs, VppIpfixInterfaceState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[VppIpfixInterfaceArgs, VppIpfixInterfaceState]{},
			fmt.Errorf("read VppIpfixInterface %s: %w", req.State.Name, err)
	}

	args, err := parseVppIpfixInterfaceConfig(req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[VppIpfixInterfaceArgs, VppIpfixInterfaceState]{},
			fmt.Errorf("parse VppIpfixInterface %s config: %w", req.State.Name, err)
	}

	state := VppIpfixInterfaceState{VppIpfixInterfaceArgs: args}
	return infer.ReadResponse[VppIpfixInterfaceArgs, VppIpfixInterfaceState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing VppIpfixInterface configuration.
func (VppIpfixInterface) Update(
	ctx context.Context,
	req infer.UpdateRequest[VppIpfixInterfaceArgs, VppIpfixInterfaceState],
) (infer.UpdateResponse[VppIpfixInterfaceState], error) {
	if req.DryRun {
		return infer.UpdateResponse[VppIpfixInterfaceState]{
			Output: VppIpfixInterfaceState{VppIpfixInterfaceArgs: req.Inputs},
		}, nil
	}

	ops := buildVppIpfixInterfaceUpdateOps(req.State.VppIpfixInterfaceArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[VppIpfixInterfaceState]{},
				fmt.Errorf("update VppIpfixInterface %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[VppIpfixInterfaceState]{
		Output: VppIpfixInterfaceState{VppIpfixInterfaceArgs: req.Inputs},
	}, nil
}

// Delete removes the VppIpfixInterface configuration from VyOS.
func (VppIpfixInterface) Delete(
	ctx context.Context,
	req infer.DeleteRequest[VppIpfixInterfaceState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := vppIpfixInterfaceBasePath(req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete VppIpfixInterface %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildVppIpfixInterfaceOps builds set operations for all non-nil fields.
func buildVppIpfixInterfaceOps(args VppIpfixInterfaceArgs) []vyosclient.Operation {
	base := vppIpfixInterfaceBasePath(args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}

	if args.Direction != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "direction"), Value: *args.Direction})
	}

	if args.FlowVariant != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "flow-variant"), Value: *args.FlowVariant})
	}

	return ops
}

// buildVppIpfixInterfaceUpdateOps computes the diff between previous and current state.
func buildVppIpfixInterfaceUpdateOps(prev, cur VppIpfixInterfaceArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	base := vppIpfixInterfaceBasePath(cur.Name)

	ops = append(ops, diffStringField(base, []string{"direction"}, prev.Direction, cur.Direction)...)

	ops = append(ops, diffStringField(base, []string{"flow-variant"}, prev.FlowVariant, cur.FlowVariant)...)

	return ops
}

// parseVppIpfixInterfaceConfig unmarshals VyOS ShowConfig JSON.
func parseVppIpfixInterfaceConfig(name string, data json.RawMessage) (VppIpfixInterfaceArgs, error) {
	args := VppIpfixInterfaceArgs{
		Name: name,
	}

	if v, ok := getNestedValue(data, []string{"direction"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return VppIpfixInterfaceArgs{}, fmt.Errorf("parse direction: %w", err)
		}
		args.Direction = &s
	}

	if v, ok := getNestedValue(data, []string{"flow-variant"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return VppIpfixInterfaceArgs{}, fmt.Errorf("parse flow-variant: %w", err)
		}
		args.FlowVariant = &s
	}

	return args, nil
}
