// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
	"strconv"
)

// ProtocolMPLSLdpNeighbor manages a VyOS ProtocolMPLSLdpNeighbor configuration.
type ProtocolMPLSLdpNeighbor struct{}

// ProtocolMPLSLdpNeighborArgs defines the inputs for the ProtocolMPLSLdpNeighbor resource.
type ProtocolMPLSLdpNeighborArgs struct {
	Name            string  `pulumi:"name"`
	Password        *string `pulumi:"password,optional"`
	TTLSecurity     *string `pulumi:"ttlSecurity,optional"`
	SessionHoldtime *int    `pulumi:"sessionHoldtime,optional"`
}

// ProtocolMPLSLdpNeighborState defines the outputs for the ProtocolMPLSLdpNeighbor resource.
type ProtocolMPLSLdpNeighborState struct {
	ProtocolMPLSLdpNeighborArgs
}

// Annotate provides schema metadata for the resource.
func (*ProtocolMPLSLdpNeighbor) Annotate(a infer.Annotator) {
	a.Describe(new(ProtocolMPLSLdpNeighbor), "Manages a VyOS LDP neighbor parameters.")
}

// Annotate provides schema metadata for the inputs.
func (args *ProtocolMPLSLdpNeighborArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.Name, "LDP neighbor parameters")
	a.Describe(&args.Password, "Neighbor password")
	a.Describe(&args.TTLSecurity, "Neighbor TTL security")
	a.Describe(&args.SessionHoldtime, "Session IPv4 hold time")
}

// Check validates the ProtocolMPLSLdpNeighbor inputs.
func (ProtocolMPLSLdpNeighbor) Check(
	ctx context.Context,
	req infer.CheckRequest,
) (infer.CheckResponse[ProtocolMPLSLdpNeighborArgs], error) {
	inputs, failures, err := infer.DefaultCheck[ProtocolMPLSLdpNeighborArgs](ctx, req.NewInputs)
	if err != nil {
		return infer.CheckResponse[ProtocolMPLSLdpNeighborArgs]{}, err
	}
	if inputs.SessionHoldtime != nil {
		if f := checkIntRange(int64(*inputs.SessionHoldtime), 15, 65535, "sessionHoldtime", ""); f != nil {
			failures = append(failures, *f)
		}
	}

	return infer.CheckResponse[ProtocolMPLSLdpNeighborArgs]{Inputs: inputs, Failures: failures}, nil
}

func protocolMPLSLdpNeighborBasePath(name string) []any {
	return []any{"protocols", "mpls", "ldp", "neighbor", name}
}

// Create sets up the ProtocolMPLSLdpNeighbor on VyOS.
func (ProtocolMPLSLdpNeighbor) Create(
	ctx context.Context,
	req infer.CreateRequest[ProtocolMPLSLdpNeighborArgs],
) (infer.CreateResponse[ProtocolMPLSLdpNeighborState], error) {
	if req.DryRun {
		return infer.CreateResponse[ProtocolMPLSLdpNeighborState]{
			ID:     req.Inputs.Name,
			Output: ProtocolMPLSLdpNeighborState{ProtocolMPLSLdpNeighborArgs: req.Inputs},
		}, nil
	}

	ops := buildProtocolMPLSLdpNeighborOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[ProtocolMPLSLdpNeighborState]{},
			fmt.Errorf("configure ProtocolMPLSLdpNeighbor %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[ProtocolMPLSLdpNeighborState]{
		ID:     req.Inputs.Name,
		Output: ProtocolMPLSLdpNeighborState{ProtocolMPLSLdpNeighborArgs: req.Inputs},
	}, nil
}

// Read fetches the current ProtocolMPLSLdpNeighbor config from VyOS.
func (ProtocolMPLSLdpNeighbor) Read(
	ctx context.Context,
	req infer.ReadRequest[ProtocolMPLSLdpNeighborArgs, ProtocolMPLSLdpNeighborState],
) (infer.ReadResponse[ProtocolMPLSLdpNeighborArgs, ProtocolMPLSLdpNeighborState], error) {
	client := getClient(ctx)
	base := protocolMPLSLdpNeighborBasePath(req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := ProtocolMPLSLdpNeighborArgs{Name: req.State.Name}
			state := ProtocolMPLSLdpNeighborState{ProtocolMPLSLdpNeighborArgs: args}
			return infer.ReadResponse[ProtocolMPLSLdpNeighborArgs, ProtocolMPLSLdpNeighborState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[ProtocolMPLSLdpNeighborArgs, ProtocolMPLSLdpNeighborState]{},
			fmt.Errorf("read ProtocolMPLSLdpNeighbor %s: %w", req.State.Name, err)
	}

	args, err := parseProtocolMPLSLdpNeighborConfig(req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[ProtocolMPLSLdpNeighborArgs, ProtocolMPLSLdpNeighborState]{},
			fmt.Errorf("parse ProtocolMPLSLdpNeighbor %s config: %w", req.State.Name, err)
	}

	state := ProtocolMPLSLdpNeighborState{ProtocolMPLSLdpNeighborArgs: args}
	return infer.ReadResponse[ProtocolMPLSLdpNeighborArgs, ProtocolMPLSLdpNeighborState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing ProtocolMPLSLdpNeighbor configuration.
func (ProtocolMPLSLdpNeighbor) Update(
	ctx context.Context,
	req infer.UpdateRequest[ProtocolMPLSLdpNeighborArgs, ProtocolMPLSLdpNeighborState],
) (infer.UpdateResponse[ProtocolMPLSLdpNeighborState], error) {
	if req.DryRun {
		return infer.UpdateResponse[ProtocolMPLSLdpNeighborState]{
			Output: ProtocolMPLSLdpNeighborState{ProtocolMPLSLdpNeighborArgs: req.Inputs},
		}, nil
	}

	ops := buildProtocolMPLSLdpNeighborUpdateOps(req.State.ProtocolMPLSLdpNeighborArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[ProtocolMPLSLdpNeighborState]{},
				fmt.Errorf("update ProtocolMPLSLdpNeighbor %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[ProtocolMPLSLdpNeighborState]{
		Output: ProtocolMPLSLdpNeighborState{ProtocolMPLSLdpNeighborArgs: req.Inputs},
	}, nil
}

// Delete removes the ProtocolMPLSLdpNeighbor configuration from VyOS.
func (ProtocolMPLSLdpNeighbor) Delete(
	ctx context.Context,
	req infer.DeleteRequest[ProtocolMPLSLdpNeighborState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := protocolMPLSLdpNeighborBasePath(req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete ProtocolMPLSLdpNeighbor %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildProtocolMPLSLdpNeighborOps builds set operations for all non-nil fields.
func buildProtocolMPLSLdpNeighborOps(args ProtocolMPLSLdpNeighborArgs) []vyosclient.Operation {
	base := protocolMPLSLdpNeighborBasePath(args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}

	if args.Password != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "password"), Value: *args.Password})
	}

	if args.TTLSecurity != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "ttl-security"), Value: *args.TTLSecurity})
	}

	if args.SessionHoldtime != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "session-holdtime"), Value: strconv.Itoa(*args.SessionHoldtime)})
	}

	return ops
}

// buildProtocolMPLSLdpNeighborUpdateOps computes the diff between previous and current state.
func buildProtocolMPLSLdpNeighborUpdateOps(prev, cur ProtocolMPLSLdpNeighborArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	base := protocolMPLSLdpNeighborBasePath(cur.Name)

	ops = append(ops, diffStringField(base, []string{"password"}, prev.Password, cur.Password)...)

	ops = append(ops, diffStringField(base, []string{"ttl-security"}, prev.TTLSecurity, cur.TTLSecurity)...)

	ops = append(ops, diffIntField(base, []string{"session-holdtime"}, prev.SessionHoldtime, cur.SessionHoldtime)...)

	return ops
}

// parseProtocolMPLSLdpNeighborConfig unmarshals VyOS ShowConfig JSON.
func parseProtocolMPLSLdpNeighborConfig(name string, data json.RawMessage) (ProtocolMPLSLdpNeighborArgs, error) {
	args := ProtocolMPLSLdpNeighborArgs{
		Name: name,
	}

	if v, ok := getNestedValue(data, []string{"password"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return ProtocolMPLSLdpNeighborArgs{}, fmt.Errorf("parse password: %w", err)
		}
		args.Password = &s
	}

	if v, ok := getNestedValue(data, []string{"ttl-security"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return ProtocolMPLSLdpNeighborArgs{}, fmt.Errorf("parse ttl-security: %w", err)
		}
		args.TTLSecurity = &s
	}

	if v, ok := getNestedValue(data, []string{"session-holdtime"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return ProtocolMPLSLdpNeighborArgs{}, fmt.Errorf("parse session-holdtime: %w", err)
		}
		args.SessionHoldtime = &n
	}

	return args, nil
}
