// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
	"strconv"
)

// InterfacePseudoEthernetVifPd manages a VyOS InterfacePseudoEthernetVifPd configuration.
type InterfacePseudoEthernetVifPd struct{}

// InterfacePseudoEthernetVifPdArgs defines the inputs for the InterfacePseudoEthernetVifPd resource.
type InterfacePseudoEthernetVifPdArgs struct {
	VifName string `pulumi:"vifName"`
	Name    string `pulumi:"name"`
	Length  *int   `pulumi:"length,optional"`
}

// InterfacePseudoEthernetVifPdState defines the outputs for the InterfacePseudoEthernetVifPd resource.
type InterfacePseudoEthernetVifPdState struct {
	InterfacePseudoEthernetVifPdArgs
}

// Annotate provides schema metadata for the resource.
func (*InterfacePseudoEthernetVifPd) Annotate(a infer.Annotator) {
	a.Describe(new(InterfacePseudoEthernetVifPd), "Manages a VyOS DHCPv6 prefix delegation interface statement.")
}

// Annotate provides schema metadata for the inputs.
func (args *InterfacePseudoEthernetVifPdArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.VifName, "Parent tag node key")
	a.Describe(&args.Name, "DHCPv6 prefix delegation interface statement")
	a.Describe(&args.Length, "Request IPv6 prefix length from peer")
}

// Check validates the InterfacePseudoEthernetVifPd inputs.
func (InterfacePseudoEthernetVifPd) Check(
	ctx context.Context,
	req infer.CheckRequest,
) (infer.CheckResponse[InterfacePseudoEthernetVifPdArgs], error) {
	inputs, failures, err := infer.DefaultCheck[InterfacePseudoEthernetVifPdArgs](ctx, req.NewInputs)
	if err != nil {
		return infer.CheckResponse[InterfacePseudoEthernetVifPdArgs]{}, err
	}
	if inputs.Length != nil {
		if f := checkIntRange(int64(*inputs.Length), 32, 64, "length", ""); f != nil {
			failures = append(failures, *f)
		}
	}

	return infer.CheckResponse[InterfacePseudoEthernetVifPdArgs]{Inputs: inputs, Failures: failures}, nil
}

func interfacePseudoEthernetVifPdBasePath(vifName, name string) []any {
	return []any{"interfaces", "pseudo-ethernet", "vif", vifName, "pd", name}
}

// Create sets up the InterfacePseudoEthernetVifPd on VyOS.
func (InterfacePseudoEthernetVifPd) Create(
	ctx context.Context,
	req infer.CreateRequest[InterfacePseudoEthernetVifPdArgs],
) (infer.CreateResponse[InterfacePseudoEthernetVifPdState], error) {
	if req.DryRun {
		return infer.CreateResponse[InterfacePseudoEthernetVifPdState]{
			ID:     req.Inputs.Name,
			Output: InterfacePseudoEthernetVifPdState{InterfacePseudoEthernetVifPdArgs: req.Inputs},
		}, nil
	}

	ops := buildInterfacePseudoEthernetVifPdOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[InterfacePseudoEthernetVifPdState]{},
			fmt.Errorf("configure InterfacePseudoEthernetVifPd %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[InterfacePseudoEthernetVifPdState]{
		ID:     req.Inputs.Name,
		Output: InterfacePseudoEthernetVifPdState{InterfacePseudoEthernetVifPdArgs: req.Inputs},
	}, nil
}

// Read fetches the current InterfacePseudoEthernetVifPd config from VyOS.
func (InterfacePseudoEthernetVifPd) Read(
	ctx context.Context,
	req infer.ReadRequest[InterfacePseudoEthernetVifPdArgs, InterfacePseudoEthernetVifPdState],
) (infer.ReadResponse[InterfacePseudoEthernetVifPdArgs, InterfacePseudoEthernetVifPdState], error) {
	client := getClient(ctx)
	base := interfacePseudoEthernetVifPdBasePath(req.State.VifName, req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := InterfacePseudoEthernetVifPdArgs{VifName: req.State.VifName, Name: req.State.Name}
			state := InterfacePseudoEthernetVifPdState{InterfacePseudoEthernetVifPdArgs: args}
			return infer.ReadResponse[InterfacePseudoEthernetVifPdArgs, InterfacePseudoEthernetVifPdState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[InterfacePseudoEthernetVifPdArgs, InterfacePseudoEthernetVifPdState]{},
			fmt.Errorf("read InterfacePseudoEthernetVifPd %s: %w", req.State.Name, err)
	}

	args, err := parseInterfacePseudoEthernetVifPdConfig(req.State.VifName, req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[InterfacePseudoEthernetVifPdArgs, InterfacePseudoEthernetVifPdState]{},
			fmt.Errorf("parse InterfacePseudoEthernetVifPd %s config: %w", req.State.Name, err)
	}

	state := InterfacePseudoEthernetVifPdState{InterfacePseudoEthernetVifPdArgs: args}
	return infer.ReadResponse[InterfacePseudoEthernetVifPdArgs, InterfacePseudoEthernetVifPdState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing InterfacePseudoEthernetVifPd configuration.
func (InterfacePseudoEthernetVifPd) Update(
	ctx context.Context,
	req infer.UpdateRequest[InterfacePseudoEthernetVifPdArgs, InterfacePseudoEthernetVifPdState],
) (infer.UpdateResponse[InterfacePseudoEthernetVifPdState], error) {
	if req.DryRun {
		return infer.UpdateResponse[InterfacePseudoEthernetVifPdState]{
			Output: InterfacePseudoEthernetVifPdState{InterfacePseudoEthernetVifPdArgs: req.Inputs},
		}, nil
	}

	ops := buildInterfacePseudoEthernetVifPdUpdateOps(req.State.InterfacePseudoEthernetVifPdArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[InterfacePseudoEthernetVifPdState]{},
				fmt.Errorf("update InterfacePseudoEthernetVifPd %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[InterfacePseudoEthernetVifPdState]{
		Output: InterfacePseudoEthernetVifPdState{InterfacePseudoEthernetVifPdArgs: req.Inputs},
	}, nil
}

// Delete removes the InterfacePseudoEthernetVifPd configuration from VyOS.
func (InterfacePseudoEthernetVifPd) Delete(
	ctx context.Context,
	req infer.DeleteRequest[InterfacePseudoEthernetVifPdState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := interfacePseudoEthernetVifPdBasePath(req.State.VifName, req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete InterfacePseudoEthernetVifPd %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildInterfacePseudoEthernetVifPdOps builds set operations for all non-nil fields.
func buildInterfacePseudoEthernetVifPdOps(args InterfacePseudoEthernetVifPdArgs) []vyosclient.Operation {
	base := interfacePseudoEthernetVifPdBasePath(args.VifName, args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}

	if args.Length != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "length"), Value: strconv.Itoa(*args.Length)})
	}

	return ops
}

// buildInterfacePseudoEthernetVifPdUpdateOps computes the diff between previous and current state.
func buildInterfacePseudoEthernetVifPdUpdateOps(prev, cur InterfacePseudoEthernetVifPdArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	base := interfacePseudoEthernetVifPdBasePath(cur.VifName, cur.Name)

	ops = append(ops, diffIntField(base, []string{"length"}, prev.Length, cur.Length)...)

	return ops
}

// parseInterfacePseudoEthernetVifPdConfig unmarshals VyOS ShowConfig JSON.
func parseInterfacePseudoEthernetVifPdConfig(vifName, name string, data json.RawMessage) (InterfacePseudoEthernetVifPdArgs, error) {
	args := InterfacePseudoEthernetVifPdArgs{
		VifName: vifName,
		Name:    name,
	}

	if v, ok := getNestedValue(data, []string{"length"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return InterfacePseudoEthernetVifPdArgs{}, fmt.Errorf("parse length: %w", err)
		}
		args.Length = &n
	}

	return args, nil
}
