// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
	"regexp"
)

// SystemIPProtocol manages a VyOS SystemIPProtocol configuration.
type SystemIPProtocol struct{}

// SystemIPProtocolArgs defines the inputs for the SystemIPProtocol resource.
type SystemIPProtocolArgs struct {
	Name     string  `pulumi:"name"`
	RouteMap *string `pulumi:"routeMap,optional"`
}

// SystemIPProtocolState defines the outputs for the SystemIPProtocol resource.
type SystemIPProtocolState struct {
	SystemIPProtocolArgs
}

// Annotate provides schema metadata for the resource.
func (*SystemIPProtocol) Annotate(a infer.Annotator) {
	a.Describe(new(SystemIPProtocol), "Manages a VyOS Filter routing info exchanged between routing protocol and zebra.")
}

// Annotate provides schema metadata for the inputs.
func (args *SystemIPProtocolArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.Name, "Filter routing info exchanged between routing protocol and zebra")
	a.Describe(&args.RouteMap, "Specify route-map name to use")
}

var systemIPProtocolNameRe = regexp.MustCompile(`^(?:` + "(any|babel|bgp|eigrp|isis|ospf|rip|static)" + `)$`)
var systemIPProtocolRouteMapRe = regexp.MustCompile(`^(?:` + "[-_a-zA-Z0-9][\\w\\-\\.\\+]*" + `)$`)

// Check validates the SystemIPProtocol inputs.
func (SystemIPProtocol) Check(
	ctx context.Context,
	req infer.CheckRequest,
) (infer.CheckResponse[SystemIPProtocolArgs], error) {
	inputs, failures, err := infer.DefaultCheck[SystemIPProtocolArgs](ctx, req.NewInputs)
	if err != nil {
		return infer.CheckResponse[SystemIPProtocolArgs]{}, err
	}
	if f := checkRegex(inputs.Name, systemIPProtocolNameRe, "name", ""); f != nil {
		failures = append(failures, *f)
	}
	if inputs.RouteMap != nil {
		if f := checkRegex(*inputs.RouteMap, systemIPProtocolRouteMapRe, "routeMap", "Name of route-map can only contain alpha-numeric letters, hyphen and underscores"); f != nil {
			failures = append(failures, *f)
		}
	}

	return infer.CheckResponse[SystemIPProtocolArgs]{Inputs: inputs, Failures: failures}, nil
}

func systemIPProtocolBasePath(name string) []any {
	return []any{"system", "ip", "protocol", name}
}

// Create sets up the SystemIPProtocol on VyOS.
func (SystemIPProtocol) Create(
	ctx context.Context,
	req infer.CreateRequest[SystemIPProtocolArgs],
) (infer.CreateResponse[SystemIPProtocolState], error) {
	if req.DryRun {
		return infer.CreateResponse[SystemIPProtocolState]{
			ID:     req.Inputs.Name,
			Output: SystemIPProtocolState{SystemIPProtocolArgs: req.Inputs},
		}, nil
	}

	ops := buildSystemIPProtocolOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[SystemIPProtocolState]{},
			fmt.Errorf("configure SystemIPProtocol %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[SystemIPProtocolState]{
		ID:     req.Inputs.Name,
		Output: SystemIPProtocolState{SystemIPProtocolArgs: req.Inputs},
	}, nil
}

// Read fetches the current SystemIPProtocol config from VyOS.
func (SystemIPProtocol) Read(
	ctx context.Context,
	req infer.ReadRequest[SystemIPProtocolArgs, SystemIPProtocolState],
) (infer.ReadResponse[SystemIPProtocolArgs, SystemIPProtocolState], error) {
	client := getClient(ctx)
	base := systemIPProtocolBasePath(req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := SystemIPProtocolArgs{Name: req.State.Name}
			state := SystemIPProtocolState{SystemIPProtocolArgs: args}
			return infer.ReadResponse[SystemIPProtocolArgs, SystemIPProtocolState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[SystemIPProtocolArgs, SystemIPProtocolState]{},
			fmt.Errorf("read SystemIPProtocol %s: %w", req.State.Name, err)
	}

	args, err := parseSystemIPProtocolConfig(req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[SystemIPProtocolArgs, SystemIPProtocolState]{},
			fmt.Errorf("parse SystemIPProtocol %s config: %w", req.State.Name, err)
	}

	state := SystemIPProtocolState{SystemIPProtocolArgs: args}
	return infer.ReadResponse[SystemIPProtocolArgs, SystemIPProtocolState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing SystemIPProtocol configuration.
func (SystemIPProtocol) Update(
	ctx context.Context,
	req infer.UpdateRequest[SystemIPProtocolArgs, SystemIPProtocolState],
) (infer.UpdateResponse[SystemIPProtocolState], error) {
	if req.DryRun {
		return infer.UpdateResponse[SystemIPProtocolState]{
			Output: SystemIPProtocolState{SystemIPProtocolArgs: req.Inputs},
		}, nil
	}

	ops := buildSystemIPProtocolUpdateOps(req.State.SystemIPProtocolArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[SystemIPProtocolState]{},
				fmt.Errorf("update SystemIPProtocol %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[SystemIPProtocolState]{
		Output: SystemIPProtocolState{SystemIPProtocolArgs: req.Inputs},
	}, nil
}

// Delete removes the SystemIPProtocol configuration from VyOS.
func (SystemIPProtocol) Delete(
	ctx context.Context,
	req infer.DeleteRequest[SystemIPProtocolState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := systemIPProtocolBasePath(req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete SystemIPProtocol %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildSystemIPProtocolOps builds set operations for all non-nil fields.
func buildSystemIPProtocolOps(args SystemIPProtocolArgs) []vyosclient.Operation {
	base := systemIPProtocolBasePath(args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}

	if args.RouteMap != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "route-map"), Value: *args.RouteMap})
	}

	return ops
}

// buildSystemIPProtocolUpdateOps computes the diff between previous and current state.
func buildSystemIPProtocolUpdateOps(prev, cur SystemIPProtocolArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	base := systemIPProtocolBasePath(cur.Name)

	ops = append(ops, diffStringField(base, []string{"route-map"}, prev.RouteMap, cur.RouteMap)...)

	return ops
}

// parseSystemIPProtocolConfig unmarshals VyOS ShowConfig JSON.
func parseSystemIPProtocolConfig(name string, data json.RawMessage) (SystemIPProtocolArgs, error) {
	args := SystemIPProtocolArgs{
		Name: name,
	}

	if v, ok := getNestedValue(data, []string{"route-map"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return SystemIPProtocolArgs{}, fmt.Errorf("parse route-map: %w", err)
		}
		args.RouteMap = &s
	}

	return args, nil
}
