// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
	"strconv"
)

// ProtocolOSPFAreaRange manages a VyOS ProtocolOSPFAreaRange configuration.
type ProtocolOSPFAreaRange struct{}

// ProtocolOSPFAreaRangeArgs defines the inputs for the ProtocolOSPFAreaRange resource.
type ProtocolOSPFAreaRangeArgs struct {
	AreaName     string  `pulumi:"areaName"`
	Name         string  `pulumi:"name"`
	Cost         *int    `pulumi:"cost,optional"`
	NotAdvertise *bool   `pulumi:"notAdvertise,optional"`
	Substitute   *string `pulumi:"substitute,optional"`
}

// ProtocolOSPFAreaRangeState defines the outputs for the ProtocolOSPFAreaRange resource.
type ProtocolOSPFAreaRangeState struct {
	ProtocolOSPFAreaRangeArgs
}

// Annotate provides schema metadata for the resource.
func (*ProtocolOSPFAreaRange) Annotate(a infer.Annotator) {
	a.Describe(new(ProtocolOSPFAreaRange), "Manages a VyOS Summarize routes matching a prefix (border routers only).")
}

// Annotate provides schema metadata for the inputs.
func (args *ProtocolOSPFAreaRangeArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.AreaName, "Parent tag node key")
	a.Describe(&args.Name, "Summarize routes matching a prefix (border routers only)")
	a.Describe(&args.Cost, "Metric for this range")
	a.Describe(&args.NotAdvertise, "Do not advertise this range")
	a.Describe(&args.Substitute, "Advertise area range as another prefix")
}

// Check validates the ProtocolOSPFAreaRange inputs.
func (ProtocolOSPFAreaRange) Check(
	ctx context.Context,
	req infer.CheckRequest,
) (infer.CheckResponse[ProtocolOSPFAreaRangeArgs], error) {
	inputs, failures, err := infer.DefaultCheck[ProtocolOSPFAreaRangeArgs](ctx, req.NewInputs)
	if err != nil {
		return infer.CheckResponse[ProtocolOSPFAreaRangeArgs]{}, err
	}
	if inputs.Cost != nil {
		if f := checkIntRange(int64(*inputs.Cost), 0, 16777215, "cost", ""); f != nil {
			failures = append(failures, *f)
		}
	}

	return infer.CheckResponse[ProtocolOSPFAreaRangeArgs]{Inputs: inputs, Failures: failures}, nil
}

func protocolOSPFAreaRangeBasePath(areaName, name string) []any {
	return []any{"protocols", "ospf", "area", areaName, "range", name}
}

// Create sets up the ProtocolOSPFAreaRange on VyOS.
func (ProtocolOSPFAreaRange) Create(
	ctx context.Context,
	req infer.CreateRequest[ProtocolOSPFAreaRangeArgs],
) (infer.CreateResponse[ProtocolOSPFAreaRangeState], error) {
	if req.DryRun {
		return infer.CreateResponse[ProtocolOSPFAreaRangeState]{
			ID:     req.Inputs.Name,
			Output: ProtocolOSPFAreaRangeState{ProtocolOSPFAreaRangeArgs: req.Inputs},
		}, nil
	}

	ops := buildProtocolOSPFAreaRangeOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[ProtocolOSPFAreaRangeState]{},
			fmt.Errorf("configure ProtocolOSPFAreaRange %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[ProtocolOSPFAreaRangeState]{
		ID:     req.Inputs.Name,
		Output: ProtocolOSPFAreaRangeState{ProtocolOSPFAreaRangeArgs: req.Inputs},
	}, nil
}

// Read fetches the current ProtocolOSPFAreaRange config from VyOS.
func (ProtocolOSPFAreaRange) Read(
	ctx context.Context,
	req infer.ReadRequest[ProtocolOSPFAreaRangeArgs, ProtocolOSPFAreaRangeState],
) (infer.ReadResponse[ProtocolOSPFAreaRangeArgs, ProtocolOSPFAreaRangeState], error) {
	client := getClient(ctx)
	base := protocolOSPFAreaRangeBasePath(req.State.AreaName, req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := ProtocolOSPFAreaRangeArgs{AreaName: req.State.AreaName, Name: req.State.Name}
			state := ProtocolOSPFAreaRangeState{ProtocolOSPFAreaRangeArgs: args}
			return infer.ReadResponse[ProtocolOSPFAreaRangeArgs, ProtocolOSPFAreaRangeState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[ProtocolOSPFAreaRangeArgs, ProtocolOSPFAreaRangeState]{},
			fmt.Errorf("read ProtocolOSPFAreaRange %s: %w", req.State.Name, err)
	}

	args, err := parseProtocolOSPFAreaRangeConfig(req.State.AreaName, req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[ProtocolOSPFAreaRangeArgs, ProtocolOSPFAreaRangeState]{},
			fmt.Errorf("parse ProtocolOSPFAreaRange %s config: %w", req.State.Name, err)
	}

	state := ProtocolOSPFAreaRangeState{ProtocolOSPFAreaRangeArgs: args}
	return infer.ReadResponse[ProtocolOSPFAreaRangeArgs, ProtocolOSPFAreaRangeState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing ProtocolOSPFAreaRange configuration.
func (ProtocolOSPFAreaRange) Update(
	ctx context.Context,
	req infer.UpdateRequest[ProtocolOSPFAreaRangeArgs, ProtocolOSPFAreaRangeState],
) (infer.UpdateResponse[ProtocolOSPFAreaRangeState], error) {
	if req.DryRun {
		return infer.UpdateResponse[ProtocolOSPFAreaRangeState]{
			Output: ProtocolOSPFAreaRangeState{ProtocolOSPFAreaRangeArgs: req.Inputs},
		}, nil
	}

	ops := buildProtocolOSPFAreaRangeUpdateOps(req.State.ProtocolOSPFAreaRangeArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[ProtocolOSPFAreaRangeState]{},
				fmt.Errorf("update ProtocolOSPFAreaRange %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[ProtocolOSPFAreaRangeState]{
		Output: ProtocolOSPFAreaRangeState{ProtocolOSPFAreaRangeArgs: req.Inputs},
	}, nil
}

// Delete removes the ProtocolOSPFAreaRange configuration from VyOS.
func (ProtocolOSPFAreaRange) Delete(
	ctx context.Context,
	req infer.DeleteRequest[ProtocolOSPFAreaRangeState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := protocolOSPFAreaRangeBasePath(req.State.AreaName, req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete ProtocolOSPFAreaRange %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildProtocolOSPFAreaRangeOps builds set operations for all non-nil fields.
func buildProtocolOSPFAreaRangeOps(args ProtocolOSPFAreaRangeArgs) []vyosclient.Operation {
	base := protocolOSPFAreaRangeBasePath(args.AreaName, args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}

	if args.Cost != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "cost"), Value: strconv.Itoa(*args.Cost)})
	}

	if args.NotAdvertise != nil && *args.NotAdvertise {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "not-advertise")})
	}

	if args.Substitute != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "substitute"), Value: *args.Substitute})
	}

	return ops
}

// buildProtocolOSPFAreaRangeUpdateOps computes the diff between previous and current state.
func buildProtocolOSPFAreaRangeUpdateOps(prev, cur ProtocolOSPFAreaRangeArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	base := protocolOSPFAreaRangeBasePath(cur.AreaName, cur.Name)

	ops = append(ops, diffIntField(base, []string{"cost"}, prev.Cost, cur.Cost)...)

	ops = append(ops, diffBoolField(base, []string{"not-advertise"}, prev.NotAdvertise, cur.NotAdvertise)...)

	ops = append(ops, diffStringField(base, []string{"substitute"}, prev.Substitute, cur.Substitute)...)

	return ops
}

// parseProtocolOSPFAreaRangeConfig unmarshals VyOS ShowConfig JSON.
func parseProtocolOSPFAreaRangeConfig(areaName, name string, data json.RawMessage) (ProtocolOSPFAreaRangeArgs, error) {
	args := ProtocolOSPFAreaRangeArgs{
		AreaName: areaName,
		Name:     name,
	}

	if v, ok := getNestedValue(data, []string{"cost"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return ProtocolOSPFAreaRangeArgs{}, fmt.Errorf("parse cost: %w", err)
		}
		args.Cost = &n
	}

	if _, ok := getNestedValue(data, []string{"not-advertise"}); ok {
		t := true
		args.NotAdvertise = &t
	}

	if v, ok := getNestedValue(data, []string{"substitute"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return ProtocolOSPFAreaRangeArgs{}, fmt.Errorf("parse substitute: %w", err)
		}
		args.Substitute = &s
	}

	return args, nil
}
