// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
)

// ServiceStunnelClientPsk manages a VyOS ServiceStunnelClientPsk configuration.
type ServiceStunnelClientPsk struct{}

// ServiceStunnelClientPskArgs defines the inputs for the ServiceStunnelClientPsk resource.
type ServiceStunnelClientPskArgs struct {
	ClientName string  `pulumi:"clientName"`
	Name       string  `pulumi:"name"`
	IDValue    *string `pulumi:"idValue,optional"`
	Secret     *string `pulumi:"secret,optional"`
}

// ServiceStunnelClientPskState defines the outputs for the ServiceStunnelClientPsk resource.
type ServiceStunnelClientPskState struct {
	ServiceStunnelClientPskArgs
}

// Annotate provides schema metadata for the resource.
func (*ServiceStunnelClientPsk) Annotate(a infer.Annotator) {
	a.Describe(new(ServiceStunnelClientPsk), "Manages a VyOS Pre-shared key name.")
}

// Annotate provides schema metadata for the inputs.
func (args *ServiceStunnelClientPskArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.ClientName, "Parent tag node key")
	a.Describe(&args.Name, "Pre-shared key name")
	a.Describe(&args.IDValue, "ID for authentication")
	a.Describe(&args.Secret, "pre-shared secret key")
}

func serviceStunnelClientPskBasePath(clientName, name string) []any {
	return []any{"service", "stunnel", "client", clientName, "psk", name}
}

// Create sets up the ServiceStunnelClientPsk on VyOS.
func (ServiceStunnelClientPsk) Create(
	ctx context.Context,
	req infer.CreateRequest[ServiceStunnelClientPskArgs],
) (infer.CreateResponse[ServiceStunnelClientPskState], error) {
	if req.DryRun {
		return infer.CreateResponse[ServiceStunnelClientPskState]{
			ID:     req.Inputs.Name,
			Output: ServiceStunnelClientPskState{ServiceStunnelClientPskArgs: req.Inputs},
		}, nil
	}

	ops := buildServiceStunnelClientPskOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[ServiceStunnelClientPskState]{},
			fmt.Errorf("configure ServiceStunnelClientPsk %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[ServiceStunnelClientPskState]{
		ID:     req.Inputs.Name,
		Output: ServiceStunnelClientPskState{ServiceStunnelClientPskArgs: req.Inputs},
	}, nil
}

// Read fetches the current ServiceStunnelClientPsk config from VyOS.
func (ServiceStunnelClientPsk) Read(
	ctx context.Context,
	req infer.ReadRequest[ServiceStunnelClientPskArgs, ServiceStunnelClientPskState],
) (infer.ReadResponse[ServiceStunnelClientPskArgs, ServiceStunnelClientPskState], error) {
	client := getClient(ctx)
	base := serviceStunnelClientPskBasePath(req.State.ClientName, req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := ServiceStunnelClientPskArgs{ClientName: req.State.ClientName, Name: req.State.Name}
			state := ServiceStunnelClientPskState{ServiceStunnelClientPskArgs: args}
			return infer.ReadResponse[ServiceStunnelClientPskArgs, ServiceStunnelClientPskState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[ServiceStunnelClientPskArgs, ServiceStunnelClientPskState]{},
			fmt.Errorf("read ServiceStunnelClientPsk %s: %w", req.State.Name, err)
	}

	args, err := parseServiceStunnelClientPskConfig(req.State.ClientName, req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[ServiceStunnelClientPskArgs, ServiceStunnelClientPskState]{},
			fmt.Errorf("parse ServiceStunnelClientPsk %s config: %w", req.State.Name, err)
	}

	state := ServiceStunnelClientPskState{ServiceStunnelClientPskArgs: args}
	return infer.ReadResponse[ServiceStunnelClientPskArgs, ServiceStunnelClientPskState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing ServiceStunnelClientPsk configuration.
func (ServiceStunnelClientPsk) Update(
	ctx context.Context,
	req infer.UpdateRequest[ServiceStunnelClientPskArgs, ServiceStunnelClientPskState],
) (infer.UpdateResponse[ServiceStunnelClientPskState], error) {
	if req.DryRun {
		return infer.UpdateResponse[ServiceStunnelClientPskState]{
			Output: ServiceStunnelClientPskState{ServiceStunnelClientPskArgs: req.Inputs},
		}, nil
	}

	ops := buildServiceStunnelClientPskUpdateOps(req.State.ServiceStunnelClientPskArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[ServiceStunnelClientPskState]{},
				fmt.Errorf("update ServiceStunnelClientPsk %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[ServiceStunnelClientPskState]{
		Output: ServiceStunnelClientPskState{ServiceStunnelClientPskArgs: req.Inputs},
	}, nil
}

// Delete removes the ServiceStunnelClientPsk configuration from VyOS.
func (ServiceStunnelClientPsk) Delete(
	ctx context.Context,
	req infer.DeleteRequest[ServiceStunnelClientPskState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := serviceStunnelClientPskBasePath(req.State.ClientName, req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete ServiceStunnelClientPsk %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildServiceStunnelClientPskOps builds set operations for all non-nil fields.
func buildServiceStunnelClientPskOps(args ServiceStunnelClientPskArgs) []vyosclient.Operation {
	base := serviceStunnelClientPskBasePath(args.ClientName, args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}

	if args.IDValue != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "id"), Value: *args.IDValue})
	}

	if args.Secret != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "secret"), Value: *args.Secret})
	}

	return ops
}

// buildServiceStunnelClientPskUpdateOps computes the diff between previous and current state.
func buildServiceStunnelClientPskUpdateOps(prev, cur ServiceStunnelClientPskArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	base := serviceStunnelClientPskBasePath(cur.ClientName, cur.Name)

	ops = append(ops, diffStringField(base, []string{"id"}, prev.IDValue, cur.IDValue)...)

	ops = append(ops, diffStringField(base, []string{"secret"}, prev.Secret, cur.Secret)...)

	return ops
}

// parseServiceStunnelClientPskConfig unmarshals VyOS ShowConfig JSON.
func parseServiceStunnelClientPskConfig(clientName, name string, data json.RawMessage) (ServiceStunnelClientPskArgs, error) {
	args := ServiceStunnelClientPskArgs{
		ClientName: clientName,
		Name:       name,
	}

	if v, ok := getNestedValue(data, []string{"id"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return ServiceStunnelClientPskArgs{}, fmt.Errorf("parse id: %w", err)
		}
		args.IDValue = &s
	}

	if v, ok := getNestedValue(data, []string{"secret"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return ServiceStunnelClientPskArgs{}, fmt.Errorf("parse secret: %w", err)
		}
		args.Secret = &s
	}

	return args, nil
}
