// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
	"regexp"
)

// PolicyAsPathListRule manages a VyOS PolicyAsPathListRule configuration.
type PolicyAsPathListRule struct{}

// PolicyAsPathListRuleArgs defines the inputs for the PolicyAsPathListRule resource.
type PolicyAsPathListRuleArgs struct {
	AsPathListName string  `pulumi:"asPathListName"`
	Name           string  `pulumi:"name"`
	Action         *string `pulumi:"action,optional"`
	Description    *string `pulumi:"description,optional"`
	Regex          *string `pulumi:"regex,optional"`
}

// PolicyAsPathListRuleState defines the outputs for the PolicyAsPathListRule resource.
type PolicyAsPathListRuleState struct {
	PolicyAsPathListRuleArgs
}

// Annotate provides schema metadata for the resource.
func (*PolicyAsPathListRule) Annotate(a infer.Annotator) {
	a.Describe(new(PolicyAsPathListRule), "Manages a VyOS Rule for this as-path-list.")
}

// Annotate provides schema metadata for the inputs.
func (args *PolicyAsPathListRuleArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.AsPathListName, "Parent tag node key")
	a.Describe(&args.Name, "Rule for this as-path-list")
	a.Describe(&args.Action, "Action to take on entries matching this rule")
	a.Describe(&args.Description, "Description")
	a.Describe(&args.Regex, "Regular expression to match against an AS path")
}

var policyAsPathListRuleActionRe = regexp.MustCompile(`^(?:` + "(permit|deny)" + `)$`)
var policyAsPathListRuleDescriptionRe = regexp.MustCompile(`^(?:` + ".{0,255}" + `)$`)

// Check validates the PolicyAsPathListRule inputs.
func (PolicyAsPathListRule) Check(
	ctx context.Context,
	req infer.CheckRequest,
) (infer.CheckResponse[PolicyAsPathListRuleArgs], error) {
	inputs, failures, err := infer.DefaultCheck[PolicyAsPathListRuleArgs](ctx, req.NewInputs)
	if err != nil {
		return infer.CheckResponse[PolicyAsPathListRuleArgs]{}, err
	}
	if inputs.Action != nil {
		if f := checkRegex(*inputs.Action, policyAsPathListRuleActionRe, "action", ""); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.Description != nil {
		if f := checkRegex(*inputs.Description, policyAsPathListRuleDescriptionRe, "description", "Description too long (limit 255 characters)"); f != nil {
			failures = append(failures, *f)
		}
	}

	return infer.CheckResponse[PolicyAsPathListRuleArgs]{Inputs: inputs, Failures: failures}, nil
}

func policyAsPathListRuleBasePath(asPathListName, name string) []any {
	return []any{"policy", "as-path-list", asPathListName, "rule", name}
}

// Create sets up the PolicyAsPathListRule on VyOS.
func (PolicyAsPathListRule) Create(
	ctx context.Context,
	req infer.CreateRequest[PolicyAsPathListRuleArgs],
) (infer.CreateResponse[PolicyAsPathListRuleState], error) {
	if req.DryRun {
		return infer.CreateResponse[PolicyAsPathListRuleState]{
			ID:     req.Inputs.Name,
			Output: PolicyAsPathListRuleState{PolicyAsPathListRuleArgs: req.Inputs},
		}, nil
	}

	ops := buildPolicyAsPathListRuleOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[PolicyAsPathListRuleState]{},
			fmt.Errorf("configure PolicyAsPathListRule %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[PolicyAsPathListRuleState]{
		ID:     req.Inputs.Name,
		Output: PolicyAsPathListRuleState{PolicyAsPathListRuleArgs: req.Inputs},
	}, nil
}

// Read fetches the current PolicyAsPathListRule config from VyOS.
func (PolicyAsPathListRule) Read(
	ctx context.Context,
	req infer.ReadRequest[PolicyAsPathListRuleArgs, PolicyAsPathListRuleState],
) (infer.ReadResponse[PolicyAsPathListRuleArgs, PolicyAsPathListRuleState], error) {
	client := getClient(ctx)
	base := policyAsPathListRuleBasePath(req.State.AsPathListName, req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := PolicyAsPathListRuleArgs{AsPathListName: req.State.AsPathListName, Name: req.State.Name}
			state := PolicyAsPathListRuleState{PolicyAsPathListRuleArgs: args}
			return infer.ReadResponse[PolicyAsPathListRuleArgs, PolicyAsPathListRuleState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[PolicyAsPathListRuleArgs, PolicyAsPathListRuleState]{},
			fmt.Errorf("read PolicyAsPathListRule %s: %w", req.State.Name, err)
	}

	args, err := parsePolicyAsPathListRuleConfig(req.State.AsPathListName, req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[PolicyAsPathListRuleArgs, PolicyAsPathListRuleState]{},
			fmt.Errorf("parse PolicyAsPathListRule %s config: %w", req.State.Name, err)
	}

	state := PolicyAsPathListRuleState{PolicyAsPathListRuleArgs: args}
	return infer.ReadResponse[PolicyAsPathListRuleArgs, PolicyAsPathListRuleState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing PolicyAsPathListRule configuration.
func (PolicyAsPathListRule) Update(
	ctx context.Context,
	req infer.UpdateRequest[PolicyAsPathListRuleArgs, PolicyAsPathListRuleState],
) (infer.UpdateResponse[PolicyAsPathListRuleState], error) {
	if req.DryRun {
		return infer.UpdateResponse[PolicyAsPathListRuleState]{
			Output: PolicyAsPathListRuleState{PolicyAsPathListRuleArgs: req.Inputs},
		}, nil
	}

	ops := buildPolicyAsPathListRuleUpdateOps(req.State.PolicyAsPathListRuleArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[PolicyAsPathListRuleState]{},
				fmt.Errorf("update PolicyAsPathListRule %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[PolicyAsPathListRuleState]{
		Output: PolicyAsPathListRuleState{PolicyAsPathListRuleArgs: req.Inputs},
	}, nil
}

// Delete removes the PolicyAsPathListRule configuration from VyOS.
func (PolicyAsPathListRule) Delete(
	ctx context.Context,
	req infer.DeleteRequest[PolicyAsPathListRuleState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := policyAsPathListRuleBasePath(req.State.AsPathListName, req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete PolicyAsPathListRule %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildPolicyAsPathListRuleOps builds set operations for all non-nil fields.
func buildPolicyAsPathListRuleOps(args PolicyAsPathListRuleArgs) []vyosclient.Operation {
	base := policyAsPathListRuleBasePath(args.AsPathListName, args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}

	if args.Action != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "action"), Value: *args.Action})
	}

	if args.Description != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "description"), Value: *args.Description})
	}

	if args.Regex != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "regex"), Value: *args.Regex})
	}

	return ops
}

// buildPolicyAsPathListRuleUpdateOps computes the diff between previous and current state.
func buildPolicyAsPathListRuleUpdateOps(prev, cur PolicyAsPathListRuleArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	base := policyAsPathListRuleBasePath(cur.AsPathListName, cur.Name)

	ops = append(ops, diffStringField(base, []string{"action"}, prev.Action, cur.Action)...)

	ops = append(ops, diffStringField(base, []string{"description"}, prev.Description, cur.Description)...)

	ops = append(ops, diffStringField(base, []string{"regex"}, prev.Regex, cur.Regex)...)

	return ops
}

// parsePolicyAsPathListRuleConfig unmarshals VyOS ShowConfig JSON.
func parsePolicyAsPathListRuleConfig(asPathListName, name string, data json.RawMessage) (PolicyAsPathListRuleArgs, error) {
	args := PolicyAsPathListRuleArgs{
		AsPathListName: asPathListName,
		Name:           name,
	}

	if v, ok := getNestedValue(data, []string{"action"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return PolicyAsPathListRuleArgs{}, fmt.Errorf("parse action: %w", err)
		}
		args.Action = &s
	}

	if v, ok := getNestedValue(data, []string{"description"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return PolicyAsPathListRuleArgs{}, fmt.Errorf("parse description: %w", err)
		}
		args.Description = &s
	}

	if v, ok := getNestedValue(data, []string{"regex"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return PolicyAsPathListRuleArgs{}, fmt.Errorf("parse regex: %w", err)
		}
		args.Regex = &s
	}

	return args, nil
}
