// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
)

// VpnIpsecRemoteAccessConnectionUsername manages a VyOS VpnIpsecRemoteAccessConnectionUsername configuration.
type VpnIpsecRemoteAccessConnectionUsername struct{}

// VpnIpsecRemoteAccessConnectionUsernameArgs defines the inputs for the VpnIpsecRemoteAccessConnectionUsername resource.
type VpnIpsecRemoteAccessConnectionUsernameArgs struct {
	ConnectionName string  `pulumi:"connectionName"`
	Name           string  `pulumi:"name"`
	Disable        *bool   `pulumi:"disable,optional"`
	Password       *string `pulumi:"password,optional"`
}

// VpnIpsecRemoteAccessConnectionUsernameState defines the outputs for the VpnIpsecRemoteAccessConnectionUsername resource.
type VpnIpsecRemoteAccessConnectionUsernameState struct {
	VpnIpsecRemoteAccessConnectionUsernameArgs
}

// Annotate provides schema metadata for the resource.
func (*VpnIpsecRemoteAccessConnectionUsername) Annotate(a infer.Annotator) {
	a.Describe(new(VpnIpsecRemoteAccessConnectionUsername), "Manages a VyOS Username used for authentication.")
}

// Annotate provides schema metadata for the inputs.
func (args *VpnIpsecRemoteAccessConnectionUsernameArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.ConnectionName, "Parent tag node key")
	a.Describe(&args.Name, "Username used for authentication")
	a.Describe(&args.Disable, "Disable instance")
	a.Describe(&args.Password, "Password used for authentication")
}

func vpnIpsecRemoteAccessConnectionUsernameBasePath(connectionName, name string) []any {
	return []any{"vpn", "ipsec", "remote-access", "connection", connectionName, "username", name}
}

// Create sets up the VpnIpsecRemoteAccessConnectionUsername on VyOS.
func (VpnIpsecRemoteAccessConnectionUsername) Create(
	ctx context.Context,
	req infer.CreateRequest[VpnIpsecRemoteAccessConnectionUsernameArgs],
) (infer.CreateResponse[VpnIpsecRemoteAccessConnectionUsernameState], error) {
	if req.DryRun {
		return infer.CreateResponse[VpnIpsecRemoteAccessConnectionUsernameState]{
			ID:     req.Inputs.Name,
			Output: VpnIpsecRemoteAccessConnectionUsernameState{VpnIpsecRemoteAccessConnectionUsernameArgs: req.Inputs},
		}, nil
	}

	ops := buildVpnIpsecRemoteAccessConnectionUsernameOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[VpnIpsecRemoteAccessConnectionUsernameState]{},
			fmt.Errorf("configure VpnIpsecRemoteAccessConnectionUsername %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[VpnIpsecRemoteAccessConnectionUsernameState]{
		ID:     req.Inputs.Name,
		Output: VpnIpsecRemoteAccessConnectionUsernameState{VpnIpsecRemoteAccessConnectionUsernameArgs: req.Inputs},
	}, nil
}

// Read fetches the current VpnIpsecRemoteAccessConnectionUsername config from VyOS.
func (VpnIpsecRemoteAccessConnectionUsername) Read(
	ctx context.Context,
	req infer.ReadRequest[VpnIpsecRemoteAccessConnectionUsernameArgs, VpnIpsecRemoteAccessConnectionUsernameState],
) (infer.ReadResponse[VpnIpsecRemoteAccessConnectionUsernameArgs, VpnIpsecRemoteAccessConnectionUsernameState], error) {
	client := getClient(ctx)
	base := vpnIpsecRemoteAccessConnectionUsernameBasePath(req.State.ConnectionName, req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := VpnIpsecRemoteAccessConnectionUsernameArgs{ConnectionName: req.State.ConnectionName, Name: req.State.Name}
			state := VpnIpsecRemoteAccessConnectionUsernameState{VpnIpsecRemoteAccessConnectionUsernameArgs: args}
			return infer.ReadResponse[VpnIpsecRemoteAccessConnectionUsernameArgs, VpnIpsecRemoteAccessConnectionUsernameState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[VpnIpsecRemoteAccessConnectionUsernameArgs, VpnIpsecRemoteAccessConnectionUsernameState]{},
			fmt.Errorf("read VpnIpsecRemoteAccessConnectionUsername %s: %w", req.State.Name, err)
	}

	args, err := parseVpnIpsecRemoteAccessConnectionUsernameConfig(req.State.ConnectionName, req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[VpnIpsecRemoteAccessConnectionUsernameArgs, VpnIpsecRemoteAccessConnectionUsernameState]{},
			fmt.Errorf("parse VpnIpsecRemoteAccessConnectionUsername %s config: %w", req.State.Name, err)
	}

	state := VpnIpsecRemoteAccessConnectionUsernameState{VpnIpsecRemoteAccessConnectionUsernameArgs: args}
	return infer.ReadResponse[VpnIpsecRemoteAccessConnectionUsernameArgs, VpnIpsecRemoteAccessConnectionUsernameState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing VpnIpsecRemoteAccessConnectionUsername configuration.
func (VpnIpsecRemoteAccessConnectionUsername) Update(
	ctx context.Context,
	req infer.UpdateRequest[VpnIpsecRemoteAccessConnectionUsernameArgs, VpnIpsecRemoteAccessConnectionUsernameState],
) (infer.UpdateResponse[VpnIpsecRemoteAccessConnectionUsernameState], error) {
	if req.DryRun {
		return infer.UpdateResponse[VpnIpsecRemoteAccessConnectionUsernameState]{
			Output: VpnIpsecRemoteAccessConnectionUsernameState{VpnIpsecRemoteAccessConnectionUsernameArgs: req.Inputs},
		}, nil
	}

	ops := buildVpnIpsecRemoteAccessConnectionUsernameUpdateOps(req.State.VpnIpsecRemoteAccessConnectionUsernameArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[VpnIpsecRemoteAccessConnectionUsernameState]{},
				fmt.Errorf("update VpnIpsecRemoteAccessConnectionUsername %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[VpnIpsecRemoteAccessConnectionUsernameState]{
		Output: VpnIpsecRemoteAccessConnectionUsernameState{VpnIpsecRemoteAccessConnectionUsernameArgs: req.Inputs},
	}, nil
}

// Delete removes the VpnIpsecRemoteAccessConnectionUsername configuration from VyOS.
func (VpnIpsecRemoteAccessConnectionUsername) Delete(
	ctx context.Context,
	req infer.DeleteRequest[VpnIpsecRemoteAccessConnectionUsernameState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := vpnIpsecRemoteAccessConnectionUsernameBasePath(req.State.ConnectionName, req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete VpnIpsecRemoteAccessConnectionUsername %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildVpnIpsecRemoteAccessConnectionUsernameOps builds set operations for all non-nil fields.
func buildVpnIpsecRemoteAccessConnectionUsernameOps(args VpnIpsecRemoteAccessConnectionUsernameArgs) []vyosclient.Operation {
	base := vpnIpsecRemoteAccessConnectionUsernameBasePath(args.ConnectionName, args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}

	if args.Disable != nil && *args.Disable {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "disable")})
	}

	if args.Password != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "password"), Value: *args.Password})
	}

	return ops
}

// buildVpnIpsecRemoteAccessConnectionUsernameUpdateOps computes the diff between previous and current state.
func buildVpnIpsecRemoteAccessConnectionUsernameUpdateOps(prev, cur VpnIpsecRemoteAccessConnectionUsernameArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	base := vpnIpsecRemoteAccessConnectionUsernameBasePath(cur.ConnectionName, cur.Name)

	ops = append(ops, diffBoolField(base, []string{"disable"}, prev.Disable, cur.Disable)...)

	ops = append(ops, diffStringField(base, []string{"password"}, prev.Password, cur.Password)...)

	return ops
}

// parseVpnIpsecRemoteAccessConnectionUsernameConfig unmarshals VyOS ShowConfig JSON.
func parseVpnIpsecRemoteAccessConnectionUsernameConfig(connectionName, name string, data json.RawMessage) (VpnIpsecRemoteAccessConnectionUsernameArgs, error) {
	args := VpnIpsecRemoteAccessConnectionUsernameArgs{
		ConnectionName: connectionName,
		Name:           name,
	}

	if _, ok := getNestedValue(data, []string{"disable"}); ok {
		t := true
		args.Disable = &t
	}

	if v, ok := getNestedValue(data, []string{"password"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return VpnIpsecRemoteAccessConnectionUsernameArgs{}, fmt.Errorf("parse password: %w", err)
		}
		args.Password = &s
	}

	return args, nil
}
