// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
	"regexp"
)

// VpnPptpRemoteAccessClientIPv6Pool manages a VyOS VpnPptpRemoteAccessClientIPv6Pool configuration.
type VpnPptpRemoteAccessClientIPv6Pool struct{}

// VpnPptpRemoteAccessClientIPv6PoolArgs defines the inputs for the VpnPptpRemoteAccessClientIPv6Pool resource.
type VpnPptpRemoteAccessClientIPv6PoolArgs struct {
	Name string `pulumi:"name"`
}

// VpnPptpRemoteAccessClientIPv6PoolState defines the outputs for the VpnPptpRemoteAccessClientIPv6Pool resource.
type VpnPptpRemoteAccessClientIPv6PoolState struct {
	VpnPptpRemoteAccessClientIPv6PoolArgs
}

// Annotate provides schema metadata for the resource.
func (*VpnPptpRemoteAccessClientIPv6Pool) Annotate(a infer.Annotator) {
	a.Describe(new(VpnPptpRemoteAccessClientIPv6Pool), "Manages a VyOS Pool of client IPv6 addresses.")
}

// Annotate provides schema metadata for the inputs.
func (args *VpnPptpRemoteAccessClientIPv6PoolArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.Name, "Pool of client IPv6 addresses")
}

var vpnPptpRemoteAccessClientIPv6PoolNameRe = regexp.MustCompile(`^(?:` + "[-_a-zA-Z0-9][\\w\\-\\.\\+]*" + `)$`)

// Check validates the VpnPptpRemoteAccessClientIPv6Pool inputs.
func (VpnPptpRemoteAccessClientIPv6Pool) Check(
	ctx context.Context,
	req infer.CheckRequest,
) (infer.CheckResponse[VpnPptpRemoteAccessClientIPv6PoolArgs], error) {
	inputs, failures, err := infer.DefaultCheck[VpnPptpRemoteAccessClientIPv6PoolArgs](ctx, req.NewInputs)
	if err != nil {
		return infer.CheckResponse[VpnPptpRemoteAccessClientIPv6PoolArgs]{}, err
	}
	if f := checkRegex(inputs.Name, vpnPptpRemoteAccessClientIPv6PoolNameRe, "name", ""); f != nil {
		failures = append(failures, *f)
	}

	return infer.CheckResponse[VpnPptpRemoteAccessClientIPv6PoolArgs]{Inputs: inputs, Failures: failures}, nil
}

func vpnPptpRemoteAccessClientIPv6PoolBasePath(name string) []any {
	return []any{"vpn", "pptp", "remote-access", "client-ipv6-pool", name}
}

// Create sets up the VpnPptpRemoteAccessClientIPv6Pool on VyOS.
func (VpnPptpRemoteAccessClientIPv6Pool) Create(
	ctx context.Context,
	req infer.CreateRequest[VpnPptpRemoteAccessClientIPv6PoolArgs],
) (infer.CreateResponse[VpnPptpRemoteAccessClientIPv6PoolState], error) {
	if req.DryRun {
		return infer.CreateResponse[VpnPptpRemoteAccessClientIPv6PoolState]{
			ID:     req.Inputs.Name,
			Output: VpnPptpRemoteAccessClientIPv6PoolState{VpnPptpRemoteAccessClientIPv6PoolArgs: req.Inputs},
		}, nil
	}

	ops := buildVpnPptpRemoteAccessClientIPv6PoolOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[VpnPptpRemoteAccessClientIPv6PoolState]{},
			fmt.Errorf("configure VpnPptpRemoteAccessClientIPv6Pool %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[VpnPptpRemoteAccessClientIPv6PoolState]{
		ID:     req.Inputs.Name,
		Output: VpnPptpRemoteAccessClientIPv6PoolState{VpnPptpRemoteAccessClientIPv6PoolArgs: req.Inputs},
	}, nil
}

// Read fetches the current VpnPptpRemoteAccessClientIPv6Pool config from VyOS.
func (VpnPptpRemoteAccessClientIPv6Pool) Read(
	ctx context.Context,
	req infer.ReadRequest[VpnPptpRemoteAccessClientIPv6PoolArgs, VpnPptpRemoteAccessClientIPv6PoolState],
) (infer.ReadResponse[VpnPptpRemoteAccessClientIPv6PoolArgs, VpnPptpRemoteAccessClientIPv6PoolState], error) {
	client := getClient(ctx)
	base := vpnPptpRemoteAccessClientIPv6PoolBasePath(req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := VpnPptpRemoteAccessClientIPv6PoolArgs{Name: req.State.Name}
			state := VpnPptpRemoteAccessClientIPv6PoolState{VpnPptpRemoteAccessClientIPv6PoolArgs: args}
			return infer.ReadResponse[VpnPptpRemoteAccessClientIPv6PoolArgs, VpnPptpRemoteAccessClientIPv6PoolState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[VpnPptpRemoteAccessClientIPv6PoolArgs, VpnPptpRemoteAccessClientIPv6PoolState]{},
			fmt.Errorf("read VpnPptpRemoteAccessClientIPv6Pool %s: %w", req.State.Name, err)
	}

	args, err := parseVpnPptpRemoteAccessClientIPv6PoolConfig(req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[VpnPptpRemoteAccessClientIPv6PoolArgs, VpnPptpRemoteAccessClientIPv6PoolState]{},
			fmt.Errorf("parse VpnPptpRemoteAccessClientIPv6Pool %s config: %w", req.State.Name, err)
	}

	state := VpnPptpRemoteAccessClientIPv6PoolState{VpnPptpRemoteAccessClientIPv6PoolArgs: args}
	return infer.ReadResponse[VpnPptpRemoteAccessClientIPv6PoolArgs, VpnPptpRemoteAccessClientIPv6PoolState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing VpnPptpRemoteAccessClientIPv6Pool configuration.
func (VpnPptpRemoteAccessClientIPv6Pool) Update(
	ctx context.Context,
	req infer.UpdateRequest[VpnPptpRemoteAccessClientIPv6PoolArgs, VpnPptpRemoteAccessClientIPv6PoolState],
) (infer.UpdateResponse[VpnPptpRemoteAccessClientIPv6PoolState], error) {
	if req.DryRun {
		return infer.UpdateResponse[VpnPptpRemoteAccessClientIPv6PoolState]{
			Output: VpnPptpRemoteAccessClientIPv6PoolState{VpnPptpRemoteAccessClientIPv6PoolArgs: req.Inputs},
		}, nil
	}

	ops := buildVpnPptpRemoteAccessClientIPv6PoolUpdateOps(req.State.VpnPptpRemoteAccessClientIPv6PoolArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[VpnPptpRemoteAccessClientIPv6PoolState]{},
				fmt.Errorf("update VpnPptpRemoteAccessClientIPv6Pool %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[VpnPptpRemoteAccessClientIPv6PoolState]{
		Output: VpnPptpRemoteAccessClientIPv6PoolState{VpnPptpRemoteAccessClientIPv6PoolArgs: req.Inputs},
	}, nil
}

// Delete removes the VpnPptpRemoteAccessClientIPv6Pool configuration from VyOS.
func (VpnPptpRemoteAccessClientIPv6Pool) Delete(
	ctx context.Context,
	req infer.DeleteRequest[VpnPptpRemoteAccessClientIPv6PoolState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := vpnPptpRemoteAccessClientIPv6PoolBasePath(req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete VpnPptpRemoteAccessClientIPv6Pool %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildVpnPptpRemoteAccessClientIPv6PoolOps builds set operations for all non-nil fields.
func buildVpnPptpRemoteAccessClientIPv6PoolOps(args VpnPptpRemoteAccessClientIPv6PoolArgs) []vyosclient.Operation {
	base := vpnPptpRemoteAccessClientIPv6PoolBasePath(args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}
	return ops
}

// buildVpnPptpRemoteAccessClientIPv6PoolUpdateOps computes the diff between previous and current state.
func buildVpnPptpRemoteAccessClientIPv6PoolUpdateOps(prev, cur VpnPptpRemoteAccessClientIPv6PoolArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	return ops
}

// parseVpnPptpRemoteAccessClientIPv6PoolConfig unmarshals VyOS ShowConfig JSON.
func parseVpnPptpRemoteAccessClientIPv6PoolConfig(name string, data json.RawMessage) (VpnPptpRemoteAccessClientIPv6PoolArgs, error) {
	args := VpnPptpRemoteAccessClientIPv6PoolArgs{
		Name: name,
	}

	return args, nil
}
