// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
	"regexp"
	"strconv"
)

// ProtocolBGPAddressFamilyIPv6UnicastNetwork manages a VyOS ProtocolBGPAddressFamilyIPv6UnicastNetwork configuration.
type ProtocolBGPAddressFamilyIPv6UnicastNetwork struct{}

// ProtocolBGPAddressFamilyIPv6UnicastNetworkArgs defines the inputs for the ProtocolBGPAddressFamilyIPv6UnicastNetwork resource.
type ProtocolBGPAddressFamilyIPv6UnicastNetworkArgs struct {
	Name      string  `pulumi:"name"`
	PathLimit *int    `pulumi:"pathLimit,optional"`
	RouteMap  *string `pulumi:"routeMap,optional"`
}

// ProtocolBGPAddressFamilyIPv6UnicastNetworkState defines the outputs for the ProtocolBGPAddressFamilyIPv6UnicastNetwork resource.
type ProtocolBGPAddressFamilyIPv6UnicastNetworkState struct {
	ProtocolBGPAddressFamilyIPv6UnicastNetworkArgs
}

// Annotate provides schema metadata for the resource.
func (*ProtocolBGPAddressFamilyIPv6UnicastNetwork) Annotate(a infer.Annotator) {
	a.Describe(new(ProtocolBGPAddressFamilyIPv6UnicastNetwork), "Manages a VyOS BGP network.")
}

// Annotate provides schema metadata for the inputs.
func (args *ProtocolBGPAddressFamilyIPv6UnicastNetworkArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.Name, "BGP network")
	a.Describe(&args.PathLimit, "AS-path hopcount limit")
	a.Describe(&args.RouteMap, "Specify route-map name to use")
}

var protocolBGPAddressFamilyIPv6UnicastNetworkRouteMapRe = regexp.MustCompile(`^(?:` + "[-_a-zA-Z0-9][\\w\\-\\.\\+]*" + `)$`)

// Check validates the ProtocolBGPAddressFamilyIPv6UnicastNetwork inputs.
func (ProtocolBGPAddressFamilyIPv6UnicastNetwork) Check(
	ctx context.Context,
	req infer.CheckRequest,
) (infer.CheckResponse[ProtocolBGPAddressFamilyIPv6UnicastNetworkArgs], error) {
	inputs, failures, err := infer.DefaultCheck[ProtocolBGPAddressFamilyIPv6UnicastNetworkArgs](ctx, req.NewInputs)
	if err != nil {
		return infer.CheckResponse[ProtocolBGPAddressFamilyIPv6UnicastNetworkArgs]{}, err
	}
	if inputs.PathLimit != nil {
		if f := checkIntRange(int64(*inputs.PathLimit), 0, 255, "pathLimit", ""); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.RouteMap != nil {
		if f := checkRegex(*inputs.RouteMap, protocolBGPAddressFamilyIPv6UnicastNetworkRouteMapRe, "routeMap", "Name of route-map can only contain alpha-numeric letters, hyphen and underscores"); f != nil {
			failures = append(failures, *f)
		}
	}

	return infer.CheckResponse[ProtocolBGPAddressFamilyIPv6UnicastNetworkArgs]{Inputs: inputs, Failures: failures}, nil
}

func protocolBGPAddressFamilyIPv6UnicastNetworkBasePath(name string) []any {
	return []any{"protocols", "bgp", "address-family", "ipv6-unicast", "network", name}
}

// Create sets up the ProtocolBGPAddressFamilyIPv6UnicastNetwork on VyOS.
func (ProtocolBGPAddressFamilyIPv6UnicastNetwork) Create(
	ctx context.Context,
	req infer.CreateRequest[ProtocolBGPAddressFamilyIPv6UnicastNetworkArgs],
) (infer.CreateResponse[ProtocolBGPAddressFamilyIPv6UnicastNetworkState], error) {
	if req.DryRun {
		return infer.CreateResponse[ProtocolBGPAddressFamilyIPv6UnicastNetworkState]{
			ID:     req.Inputs.Name,
			Output: ProtocolBGPAddressFamilyIPv6UnicastNetworkState{ProtocolBGPAddressFamilyIPv6UnicastNetworkArgs: req.Inputs},
		}, nil
	}

	ops := buildProtocolBGPAddressFamilyIPv6UnicastNetworkOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[ProtocolBGPAddressFamilyIPv6UnicastNetworkState]{},
			fmt.Errorf("configure ProtocolBGPAddressFamilyIPv6UnicastNetwork %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[ProtocolBGPAddressFamilyIPv6UnicastNetworkState]{
		ID:     req.Inputs.Name,
		Output: ProtocolBGPAddressFamilyIPv6UnicastNetworkState{ProtocolBGPAddressFamilyIPv6UnicastNetworkArgs: req.Inputs},
	}, nil
}

// Read fetches the current ProtocolBGPAddressFamilyIPv6UnicastNetwork config from VyOS.
func (ProtocolBGPAddressFamilyIPv6UnicastNetwork) Read(
	ctx context.Context,
	req infer.ReadRequest[ProtocolBGPAddressFamilyIPv6UnicastNetworkArgs, ProtocolBGPAddressFamilyIPv6UnicastNetworkState],
) (infer.ReadResponse[ProtocolBGPAddressFamilyIPv6UnicastNetworkArgs, ProtocolBGPAddressFamilyIPv6UnicastNetworkState], error) {
	client := getClient(ctx)
	base := protocolBGPAddressFamilyIPv6UnicastNetworkBasePath(req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := ProtocolBGPAddressFamilyIPv6UnicastNetworkArgs{Name: req.State.Name}
			state := ProtocolBGPAddressFamilyIPv6UnicastNetworkState{ProtocolBGPAddressFamilyIPv6UnicastNetworkArgs: args}
			return infer.ReadResponse[ProtocolBGPAddressFamilyIPv6UnicastNetworkArgs, ProtocolBGPAddressFamilyIPv6UnicastNetworkState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[ProtocolBGPAddressFamilyIPv6UnicastNetworkArgs, ProtocolBGPAddressFamilyIPv6UnicastNetworkState]{},
			fmt.Errorf("read ProtocolBGPAddressFamilyIPv6UnicastNetwork %s: %w", req.State.Name, err)
	}

	args, err := parseProtocolBGPAddressFamilyIPv6UnicastNetworkConfig(req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[ProtocolBGPAddressFamilyIPv6UnicastNetworkArgs, ProtocolBGPAddressFamilyIPv6UnicastNetworkState]{},
			fmt.Errorf("parse ProtocolBGPAddressFamilyIPv6UnicastNetwork %s config: %w", req.State.Name, err)
	}

	state := ProtocolBGPAddressFamilyIPv6UnicastNetworkState{ProtocolBGPAddressFamilyIPv6UnicastNetworkArgs: args}
	return infer.ReadResponse[ProtocolBGPAddressFamilyIPv6UnicastNetworkArgs, ProtocolBGPAddressFamilyIPv6UnicastNetworkState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing ProtocolBGPAddressFamilyIPv6UnicastNetwork configuration.
func (ProtocolBGPAddressFamilyIPv6UnicastNetwork) Update(
	ctx context.Context,
	req infer.UpdateRequest[ProtocolBGPAddressFamilyIPv6UnicastNetworkArgs, ProtocolBGPAddressFamilyIPv6UnicastNetworkState],
) (infer.UpdateResponse[ProtocolBGPAddressFamilyIPv6UnicastNetworkState], error) {
	if req.DryRun {
		return infer.UpdateResponse[ProtocolBGPAddressFamilyIPv6UnicastNetworkState]{
			Output: ProtocolBGPAddressFamilyIPv6UnicastNetworkState{ProtocolBGPAddressFamilyIPv6UnicastNetworkArgs: req.Inputs},
		}, nil
	}

	ops := buildProtocolBGPAddressFamilyIPv6UnicastNetworkUpdateOps(req.State.ProtocolBGPAddressFamilyIPv6UnicastNetworkArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[ProtocolBGPAddressFamilyIPv6UnicastNetworkState]{},
				fmt.Errorf("update ProtocolBGPAddressFamilyIPv6UnicastNetwork %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[ProtocolBGPAddressFamilyIPv6UnicastNetworkState]{
		Output: ProtocolBGPAddressFamilyIPv6UnicastNetworkState{ProtocolBGPAddressFamilyIPv6UnicastNetworkArgs: req.Inputs},
	}, nil
}

// Delete removes the ProtocolBGPAddressFamilyIPv6UnicastNetwork configuration from VyOS.
func (ProtocolBGPAddressFamilyIPv6UnicastNetwork) Delete(
	ctx context.Context,
	req infer.DeleteRequest[ProtocolBGPAddressFamilyIPv6UnicastNetworkState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := protocolBGPAddressFamilyIPv6UnicastNetworkBasePath(req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete ProtocolBGPAddressFamilyIPv6UnicastNetwork %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildProtocolBGPAddressFamilyIPv6UnicastNetworkOps builds set operations for all non-nil fields.
func buildProtocolBGPAddressFamilyIPv6UnicastNetworkOps(args ProtocolBGPAddressFamilyIPv6UnicastNetworkArgs) []vyosclient.Operation {
	base := protocolBGPAddressFamilyIPv6UnicastNetworkBasePath(args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}

	if args.PathLimit != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "path-limit"), Value: strconv.Itoa(*args.PathLimit)})
	}

	if args.RouteMap != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "route-map"), Value: *args.RouteMap})
	}

	return ops
}

// buildProtocolBGPAddressFamilyIPv6UnicastNetworkUpdateOps computes the diff between previous and current state.
func buildProtocolBGPAddressFamilyIPv6UnicastNetworkUpdateOps(prev, cur ProtocolBGPAddressFamilyIPv6UnicastNetworkArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	base := protocolBGPAddressFamilyIPv6UnicastNetworkBasePath(cur.Name)

	ops = append(ops, diffIntField(base, []string{"path-limit"}, prev.PathLimit, cur.PathLimit)...)

	ops = append(ops, diffStringField(base, []string{"route-map"}, prev.RouteMap, cur.RouteMap)...)

	return ops
}

// parseProtocolBGPAddressFamilyIPv6UnicastNetworkConfig unmarshals VyOS ShowConfig JSON.
func parseProtocolBGPAddressFamilyIPv6UnicastNetworkConfig(name string, data json.RawMessage) (ProtocolBGPAddressFamilyIPv6UnicastNetworkArgs, error) {
	args := ProtocolBGPAddressFamilyIPv6UnicastNetworkArgs{
		Name: name,
	}

	if v, ok := getNestedValue(data, []string{"path-limit"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return ProtocolBGPAddressFamilyIPv6UnicastNetworkArgs{}, fmt.Errorf("parse path-limit: %w", err)
		}
		args.PathLimit = &n
	}

	if v, ok := getNestedValue(data, []string{"route-map"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return ProtocolBGPAddressFamilyIPv6UnicastNetworkArgs{}, fmt.Errorf("parse route-map: %w", err)
		}
		args.RouteMap = &s
	}

	return args, nil
}
