// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
	"strconv"
)

// InterfaceBondingVifSVifCPd manages a VyOS InterfaceBondingVifSVifCPd configuration.
type InterfaceBondingVifSVifCPd struct{}

// InterfaceBondingVifSVifCPdArgs defines the inputs for the InterfaceBondingVifSVifCPd resource.
type InterfaceBondingVifSVifCPdArgs struct {
	VifCName string `pulumi:"vifCName"`
	Name     string `pulumi:"name"`
	Length   *int   `pulumi:"length,optional"`
}

// InterfaceBondingVifSVifCPdState defines the outputs for the InterfaceBondingVifSVifCPd resource.
type InterfaceBondingVifSVifCPdState struct {
	InterfaceBondingVifSVifCPdArgs
}

// Annotate provides schema metadata for the resource.
func (*InterfaceBondingVifSVifCPd) Annotate(a infer.Annotator) {
	a.Describe(new(InterfaceBondingVifSVifCPd), "Manages a VyOS DHCPv6 prefix delegation interface statement.")
}

// Annotate provides schema metadata for the inputs.
func (args *InterfaceBondingVifSVifCPdArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.VifCName, "Parent tag node key")
	a.Describe(&args.Name, "DHCPv6 prefix delegation interface statement")
	a.Describe(&args.Length, "Request IPv6 prefix length from peer")
}

// Check validates the InterfaceBondingVifSVifCPd inputs.
func (InterfaceBondingVifSVifCPd) Check(
	ctx context.Context,
	req infer.CheckRequest,
) (infer.CheckResponse[InterfaceBondingVifSVifCPdArgs], error) {
	inputs, failures, err := infer.DefaultCheck[InterfaceBondingVifSVifCPdArgs](ctx, req.NewInputs)
	if err != nil {
		return infer.CheckResponse[InterfaceBondingVifSVifCPdArgs]{}, err
	}
	if inputs.Length != nil {
		if f := checkIntRange(int64(*inputs.Length), 32, 64, "length", ""); f != nil {
			failures = append(failures, *f)
		}
	}

	return infer.CheckResponse[InterfaceBondingVifSVifCPdArgs]{Inputs: inputs, Failures: failures}, nil
}

func interfaceBondingVifSVifCPdBasePath(vifCName, name string) []any {
	return []any{"interfaces", "bonding", "vif-s", "vif-c", vifCName, "pd", name}
}

// Create sets up the InterfaceBondingVifSVifCPd on VyOS.
func (InterfaceBondingVifSVifCPd) Create(
	ctx context.Context,
	req infer.CreateRequest[InterfaceBondingVifSVifCPdArgs],
) (infer.CreateResponse[InterfaceBondingVifSVifCPdState], error) {
	if req.DryRun {
		return infer.CreateResponse[InterfaceBondingVifSVifCPdState]{
			ID:     req.Inputs.Name,
			Output: InterfaceBondingVifSVifCPdState{InterfaceBondingVifSVifCPdArgs: req.Inputs},
		}, nil
	}

	ops := buildInterfaceBondingVifSVifCPdOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[InterfaceBondingVifSVifCPdState]{},
			fmt.Errorf("configure InterfaceBondingVifSVifCPd %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[InterfaceBondingVifSVifCPdState]{
		ID:     req.Inputs.Name,
		Output: InterfaceBondingVifSVifCPdState{InterfaceBondingVifSVifCPdArgs: req.Inputs},
	}, nil
}

// Read fetches the current InterfaceBondingVifSVifCPd config from VyOS.
func (InterfaceBondingVifSVifCPd) Read(
	ctx context.Context,
	req infer.ReadRequest[InterfaceBondingVifSVifCPdArgs, InterfaceBondingVifSVifCPdState],
) (infer.ReadResponse[InterfaceBondingVifSVifCPdArgs, InterfaceBondingVifSVifCPdState], error) {
	client := getClient(ctx)
	base := interfaceBondingVifSVifCPdBasePath(req.State.VifCName, req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := InterfaceBondingVifSVifCPdArgs{VifCName: req.State.VifCName, Name: req.State.Name}
			state := InterfaceBondingVifSVifCPdState{InterfaceBondingVifSVifCPdArgs: args}
			return infer.ReadResponse[InterfaceBondingVifSVifCPdArgs, InterfaceBondingVifSVifCPdState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[InterfaceBondingVifSVifCPdArgs, InterfaceBondingVifSVifCPdState]{},
			fmt.Errorf("read InterfaceBondingVifSVifCPd %s: %w", req.State.Name, err)
	}

	args, err := parseInterfaceBondingVifSVifCPdConfig(req.State.VifCName, req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[InterfaceBondingVifSVifCPdArgs, InterfaceBondingVifSVifCPdState]{},
			fmt.Errorf("parse InterfaceBondingVifSVifCPd %s config: %w", req.State.Name, err)
	}

	state := InterfaceBondingVifSVifCPdState{InterfaceBondingVifSVifCPdArgs: args}
	return infer.ReadResponse[InterfaceBondingVifSVifCPdArgs, InterfaceBondingVifSVifCPdState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing InterfaceBondingVifSVifCPd configuration.
func (InterfaceBondingVifSVifCPd) Update(
	ctx context.Context,
	req infer.UpdateRequest[InterfaceBondingVifSVifCPdArgs, InterfaceBondingVifSVifCPdState],
) (infer.UpdateResponse[InterfaceBondingVifSVifCPdState], error) {
	if req.DryRun {
		return infer.UpdateResponse[InterfaceBondingVifSVifCPdState]{
			Output: InterfaceBondingVifSVifCPdState{InterfaceBondingVifSVifCPdArgs: req.Inputs},
		}, nil
	}

	ops := buildInterfaceBondingVifSVifCPdUpdateOps(req.State.InterfaceBondingVifSVifCPdArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[InterfaceBondingVifSVifCPdState]{},
				fmt.Errorf("update InterfaceBondingVifSVifCPd %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[InterfaceBondingVifSVifCPdState]{
		Output: InterfaceBondingVifSVifCPdState{InterfaceBondingVifSVifCPdArgs: req.Inputs},
	}, nil
}

// Delete removes the InterfaceBondingVifSVifCPd configuration from VyOS.
func (InterfaceBondingVifSVifCPd) Delete(
	ctx context.Context,
	req infer.DeleteRequest[InterfaceBondingVifSVifCPdState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := interfaceBondingVifSVifCPdBasePath(req.State.VifCName, req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete InterfaceBondingVifSVifCPd %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildInterfaceBondingVifSVifCPdOps builds set operations for all non-nil fields.
func buildInterfaceBondingVifSVifCPdOps(args InterfaceBondingVifSVifCPdArgs) []vyosclient.Operation {
	base := interfaceBondingVifSVifCPdBasePath(args.VifCName, args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}

	if args.Length != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "length"), Value: strconv.Itoa(*args.Length)})
	}

	return ops
}

// buildInterfaceBondingVifSVifCPdUpdateOps computes the diff between previous and current state.
func buildInterfaceBondingVifSVifCPdUpdateOps(prev, cur InterfaceBondingVifSVifCPdArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	base := interfaceBondingVifSVifCPdBasePath(cur.VifCName, cur.Name)

	ops = append(ops, diffIntField(base, []string{"length"}, prev.Length, cur.Length)...)

	return ops
}

// parseInterfaceBondingVifSVifCPdConfig unmarshals VyOS ShowConfig JSON.
func parseInterfaceBondingVifSVifCPdConfig(vifCName, name string, data json.RawMessage) (InterfaceBondingVifSVifCPdArgs, error) {
	args := InterfaceBondingVifSVifCPdArgs{
		VifCName: vifCName,
		Name:     name,
	}

	if v, ok := getNestedValue(data, []string{"length"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return InterfaceBondingVifSVifCPdArgs{}, fmt.Errorf("parse length: %w", err)
		}
		args.Length = &n
	}

	return args, nil
}
