// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
	"strconv"
)

// ProtocolStaticMrouteNextHop manages a VyOS ProtocolStaticMrouteNextHop configuration.
type ProtocolStaticMrouteNextHop struct{}

// ProtocolStaticMrouteNextHopArgs defines the inputs for the ProtocolStaticMrouteNextHop resource.
type ProtocolStaticMrouteNextHopArgs struct {
	MrouteName string `pulumi:"mrouteName"`
	Name       string `pulumi:"name"`
	Disable    *bool  `pulumi:"disable,optional"`
	Distance   *int   `pulumi:"distance,optional"`
}

// ProtocolStaticMrouteNextHopState defines the outputs for the ProtocolStaticMrouteNextHop resource.
type ProtocolStaticMrouteNextHopState struct {
	ProtocolStaticMrouteNextHopArgs
}

// Annotate provides schema metadata for the resource.
func (*ProtocolStaticMrouteNextHop) Annotate(a infer.Annotator) {
	a.Describe(new(ProtocolStaticMrouteNextHop), "Manages a VyOS Next-hop IPv4 router address.")
}

// Annotate provides schema metadata for the inputs.
func (args *ProtocolStaticMrouteNextHopArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.MrouteName, "Parent tag node key")
	a.Describe(&args.Name, "Next-hop IPv4 router address")
	a.Describe(&args.Disable, "Disable instance")
	a.Describe(&args.Distance, "Distance for this route")
}

// Check validates the ProtocolStaticMrouteNextHop inputs.
func (ProtocolStaticMrouteNextHop) Check(
	ctx context.Context,
	req infer.CheckRequest,
) (infer.CheckResponse[ProtocolStaticMrouteNextHopArgs], error) {
	inputs, failures, err := infer.DefaultCheck[ProtocolStaticMrouteNextHopArgs](ctx, req.NewInputs)
	if err != nil {
		return infer.CheckResponse[ProtocolStaticMrouteNextHopArgs]{}, err
	}
	if inputs.Distance != nil {
		if f := checkIntRange(int64(*inputs.Distance), 1, 255, "distance", ""); f != nil {
			failures = append(failures, *f)
		}
	}

	return infer.CheckResponse[ProtocolStaticMrouteNextHopArgs]{Inputs: inputs, Failures: failures}, nil
}

func protocolStaticMrouteNextHopBasePath(mrouteName, name string) []any {
	return []any{"protocols", "static", "mroute", mrouteName, "next-hop", name}
}

// Create sets up the ProtocolStaticMrouteNextHop on VyOS.
func (ProtocolStaticMrouteNextHop) Create(
	ctx context.Context,
	req infer.CreateRequest[ProtocolStaticMrouteNextHopArgs],
) (infer.CreateResponse[ProtocolStaticMrouteNextHopState], error) {
	if req.DryRun {
		return infer.CreateResponse[ProtocolStaticMrouteNextHopState]{
			ID:     req.Inputs.Name,
			Output: ProtocolStaticMrouteNextHopState{ProtocolStaticMrouteNextHopArgs: req.Inputs},
		}, nil
	}

	ops := buildProtocolStaticMrouteNextHopOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[ProtocolStaticMrouteNextHopState]{},
			fmt.Errorf("configure ProtocolStaticMrouteNextHop %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[ProtocolStaticMrouteNextHopState]{
		ID:     req.Inputs.Name,
		Output: ProtocolStaticMrouteNextHopState{ProtocolStaticMrouteNextHopArgs: req.Inputs},
	}, nil
}

// Read fetches the current ProtocolStaticMrouteNextHop config from VyOS.
func (ProtocolStaticMrouteNextHop) Read(
	ctx context.Context,
	req infer.ReadRequest[ProtocolStaticMrouteNextHopArgs, ProtocolStaticMrouteNextHopState],
) (infer.ReadResponse[ProtocolStaticMrouteNextHopArgs, ProtocolStaticMrouteNextHopState], error) {
	client := getClient(ctx)
	base := protocolStaticMrouteNextHopBasePath(req.State.MrouteName, req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := ProtocolStaticMrouteNextHopArgs{MrouteName: req.State.MrouteName, Name: req.State.Name}
			state := ProtocolStaticMrouteNextHopState{ProtocolStaticMrouteNextHopArgs: args}
			return infer.ReadResponse[ProtocolStaticMrouteNextHopArgs, ProtocolStaticMrouteNextHopState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[ProtocolStaticMrouteNextHopArgs, ProtocolStaticMrouteNextHopState]{},
			fmt.Errorf("read ProtocolStaticMrouteNextHop %s: %w", req.State.Name, err)
	}

	args, err := parseProtocolStaticMrouteNextHopConfig(req.State.MrouteName, req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[ProtocolStaticMrouteNextHopArgs, ProtocolStaticMrouteNextHopState]{},
			fmt.Errorf("parse ProtocolStaticMrouteNextHop %s config: %w", req.State.Name, err)
	}

	state := ProtocolStaticMrouteNextHopState{ProtocolStaticMrouteNextHopArgs: args}
	return infer.ReadResponse[ProtocolStaticMrouteNextHopArgs, ProtocolStaticMrouteNextHopState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing ProtocolStaticMrouteNextHop configuration.
func (ProtocolStaticMrouteNextHop) Update(
	ctx context.Context,
	req infer.UpdateRequest[ProtocolStaticMrouteNextHopArgs, ProtocolStaticMrouteNextHopState],
) (infer.UpdateResponse[ProtocolStaticMrouteNextHopState], error) {
	if req.DryRun {
		return infer.UpdateResponse[ProtocolStaticMrouteNextHopState]{
			Output: ProtocolStaticMrouteNextHopState{ProtocolStaticMrouteNextHopArgs: req.Inputs},
		}, nil
	}

	ops := buildProtocolStaticMrouteNextHopUpdateOps(req.State.ProtocolStaticMrouteNextHopArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[ProtocolStaticMrouteNextHopState]{},
				fmt.Errorf("update ProtocolStaticMrouteNextHop %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[ProtocolStaticMrouteNextHopState]{
		Output: ProtocolStaticMrouteNextHopState{ProtocolStaticMrouteNextHopArgs: req.Inputs},
	}, nil
}

// Delete removes the ProtocolStaticMrouteNextHop configuration from VyOS.
func (ProtocolStaticMrouteNextHop) Delete(
	ctx context.Context,
	req infer.DeleteRequest[ProtocolStaticMrouteNextHopState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := protocolStaticMrouteNextHopBasePath(req.State.MrouteName, req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete ProtocolStaticMrouteNextHop %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildProtocolStaticMrouteNextHopOps builds set operations for all non-nil fields.
func buildProtocolStaticMrouteNextHopOps(args ProtocolStaticMrouteNextHopArgs) []vyosclient.Operation {
	base := protocolStaticMrouteNextHopBasePath(args.MrouteName, args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}

	if args.Disable != nil && *args.Disable {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "disable")})
	}

	if args.Distance != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "distance"), Value: strconv.Itoa(*args.Distance)})
	}

	return ops
}

// buildProtocolStaticMrouteNextHopUpdateOps computes the diff between previous and current state.
func buildProtocolStaticMrouteNextHopUpdateOps(prev, cur ProtocolStaticMrouteNextHopArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	base := protocolStaticMrouteNextHopBasePath(cur.MrouteName, cur.Name)

	ops = append(ops, diffBoolField(base, []string{"disable"}, prev.Disable, cur.Disable)...)

	ops = append(ops, diffIntField(base, []string{"distance"}, prev.Distance, cur.Distance)...)

	return ops
}

// parseProtocolStaticMrouteNextHopConfig unmarshals VyOS ShowConfig JSON.
func parseProtocolStaticMrouteNextHopConfig(mrouteName, name string, data json.RawMessage) (ProtocolStaticMrouteNextHopArgs, error) {
	args := ProtocolStaticMrouteNextHopArgs{
		MrouteName: mrouteName,
		Name:       name,
	}

	if _, ok := getNestedValue(data, []string{"disable"}); ok {
		t := true
		args.Disable = &t
	}

	if v, ok := getNestedValue(data, []string{"distance"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return ProtocolStaticMrouteNextHopArgs{}, fmt.Errorf("parse distance: %w", err)
		}
		args.Distance = &n
	}

	return args, nil
}
