// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
)

// SystemSysctlParameter manages a VyOS SystemSysctlParameter configuration.
type SystemSysctlParameter struct{}

// SystemSysctlParameterArgs defines the inputs for the SystemSysctlParameter resource.
type SystemSysctlParameterArgs struct {
	Name  string  `pulumi:"name"`
	Value *string `pulumi:"value,optional"`
}

// SystemSysctlParameterState defines the outputs for the SystemSysctlParameter resource.
type SystemSysctlParameterState struct {
	SystemSysctlParameterArgs
}

// Annotate provides schema metadata for the resource.
func (*SystemSysctlParameter) Annotate(a infer.Annotator) {
	a.Describe(new(SystemSysctlParameter), "Manages a VyOS Sysctl key name.")
}

// Annotate provides schema metadata for the inputs.
func (args *SystemSysctlParameterArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.Name, "Sysctl key name")
	a.Describe(&args.Value, "Sysctl configuration value")
}

func systemSysctlParameterBasePath(name string) []any {
	return []any{"system", "sysctl", "parameter", name}
}

// Create sets up the SystemSysctlParameter on VyOS.
func (SystemSysctlParameter) Create(
	ctx context.Context,
	req infer.CreateRequest[SystemSysctlParameterArgs],
) (infer.CreateResponse[SystemSysctlParameterState], error) {
	if req.DryRun {
		return infer.CreateResponse[SystemSysctlParameterState]{
			ID:     req.Inputs.Name,
			Output: SystemSysctlParameterState{SystemSysctlParameterArgs: req.Inputs},
		}, nil
	}

	ops := buildSystemSysctlParameterOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[SystemSysctlParameterState]{},
			fmt.Errorf("configure SystemSysctlParameter %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[SystemSysctlParameterState]{
		ID:     req.Inputs.Name,
		Output: SystemSysctlParameterState{SystemSysctlParameterArgs: req.Inputs},
	}, nil
}

// Read fetches the current SystemSysctlParameter config from VyOS.
func (SystemSysctlParameter) Read(
	ctx context.Context,
	req infer.ReadRequest[SystemSysctlParameterArgs, SystemSysctlParameterState],
) (infer.ReadResponse[SystemSysctlParameterArgs, SystemSysctlParameterState], error) {
	client := getClient(ctx)
	base := systemSysctlParameterBasePath(req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := SystemSysctlParameterArgs{Name: req.State.Name}
			state := SystemSysctlParameterState{SystemSysctlParameterArgs: args}
			return infer.ReadResponse[SystemSysctlParameterArgs, SystemSysctlParameterState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[SystemSysctlParameterArgs, SystemSysctlParameterState]{},
			fmt.Errorf("read SystemSysctlParameter %s: %w", req.State.Name, err)
	}

	args, err := parseSystemSysctlParameterConfig(req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[SystemSysctlParameterArgs, SystemSysctlParameterState]{},
			fmt.Errorf("parse SystemSysctlParameter %s config: %w", req.State.Name, err)
	}

	state := SystemSysctlParameterState{SystemSysctlParameterArgs: args}
	return infer.ReadResponse[SystemSysctlParameterArgs, SystemSysctlParameterState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing SystemSysctlParameter configuration.
func (SystemSysctlParameter) Update(
	ctx context.Context,
	req infer.UpdateRequest[SystemSysctlParameterArgs, SystemSysctlParameterState],
) (infer.UpdateResponse[SystemSysctlParameterState], error) {
	if req.DryRun {
		return infer.UpdateResponse[SystemSysctlParameterState]{
			Output: SystemSysctlParameterState{SystemSysctlParameterArgs: req.Inputs},
		}, nil
	}

	ops := buildSystemSysctlParameterUpdateOps(req.State.SystemSysctlParameterArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[SystemSysctlParameterState]{},
				fmt.Errorf("update SystemSysctlParameter %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[SystemSysctlParameterState]{
		Output: SystemSysctlParameterState{SystemSysctlParameterArgs: req.Inputs},
	}, nil
}

// Delete removes the SystemSysctlParameter configuration from VyOS.
func (SystemSysctlParameter) Delete(
	ctx context.Context,
	req infer.DeleteRequest[SystemSysctlParameterState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := systemSysctlParameterBasePath(req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete SystemSysctlParameter %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildSystemSysctlParameterOps builds set operations for all non-nil fields.
func buildSystemSysctlParameterOps(args SystemSysctlParameterArgs) []vyosclient.Operation {
	base := systemSysctlParameterBasePath(args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}

	if args.Value != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "value"), Value: *args.Value})
	}

	return ops
}

// buildSystemSysctlParameterUpdateOps computes the diff between previous and current state.
func buildSystemSysctlParameterUpdateOps(prev, cur SystemSysctlParameterArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	base := systemSysctlParameterBasePath(cur.Name)

	ops = append(ops, diffStringField(base, []string{"value"}, prev.Value, cur.Value)...)

	return ops
}

// parseSystemSysctlParameterConfig unmarshals VyOS ShowConfig JSON.
func parseSystemSysctlParameterConfig(name string, data json.RawMessage) (SystemSysctlParameterArgs, error) {
	args := SystemSysctlParameterArgs{
		Name: name,
	}

	if v, ok := getNestedValue(data, []string{"value"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return SystemSysctlParameterArgs{}, fmt.Errorf("parse value: %w", err)
		}
		args.Value = &s
	}

	return args, nil
}
