// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
	"regexp"
)

// SystemLoginUserPublicKeys manages a VyOS SystemLoginUserPublicKeys configuration.
type SystemLoginUserPublicKeys struct{}

// SystemLoginUserPublicKeysArgs defines the inputs for the SystemLoginUserPublicKeys resource.
type SystemLoginUserPublicKeysArgs struct {
	UserName string  `pulumi:"userName"`
	Name     string  `pulumi:"name"`
	Key      *string `pulumi:"key,optional"`
	Options  *string `pulumi:"options,optional"`
	Type     *string `pulumi:"type,optional"`
}

// SystemLoginUserPublicKeysState defines the outputs for the SystemLoginUserPublicKeys resource.
type SystemLoginUserPublicKeysState struct {
	SystemLoginUserPublicKeysArgs
}

// Annotate provides schema metadata for the resource.
func (*SystemLoginUserPublicKeys) Annotate(a infer.Annotator) {
	a.Describe(new(SystemLoginUserPublicKeys), "Manages a VyOS Remote access public keys.")
}

// Annotate provides schema metadata for the inputs.
func (args *SystemLoginUserPublicKeysArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.UserName, "Parent tag node key")
	a.Describe(&args.Name, "Remote access public keys")
	a.Describe(&args.Key, "Public key value (Base64 encoded)")
	a.Describe(&args.Options, "Optional public key options")
	a.Describe(&args.Type, "SSH public key type")
}

var systemLoginUserPublicKeysTypeRe = regexp.MustCompile(`^(?:` + "(ssh-dss|ssh-rsa|ecdsa-sha2-nistp256|ecdsa-sha2-nistp384|ecdsa-sha2-nistp521|ssh-ed25519|sk-ecdsa-sha2-nistp256@openssh.com|sk-ssh-ed25519@openssh.com)" + `)$`)

// Check validates the SystemLoginUserPublicKeys inputs.
func (SystemLoginUserPublicKeys) Check(
	ctx context.Context,
	req infer.CheckRequest,
) (infer.CheckResponse[SystemLoginUserPublicKeysArgs], error) {
	inputs, failures, err := infer.DefaultCheck[SystemLoginUserPublicKeysArgs](ctx, req.NewInputs)
	if err != nil {
		return infer.CheckResponse[SystemLoginUserPublicKeysArgs]{}, err
	}
	if inputs.Type != nil {
		if f := checkRegex(*inputs.Type, systemLoginUserPublicKeysTypeRe, "type", ""); f != nil {
			failures = append(failures, *f)
		}
	}

	return infer.CheckResponse[SystemLoginUserPublicKeysArgs]{Inputs: inputs, Failures: failures}, nil
}

func systemLoginUserPublicKeysBasePath(userName, name string) []any {
	return []any{"system", "login", "user", userName, "public-keys", name}
}

// Create sets up the SystemLoginUserPublicKeys on VyOS.
func (SystemLoginUserPublicKeys) Create(
	ctx context.Context,
	req infer.CreateRequest[SystemLoginUserPublicKeysArgs],
) (infer.CreateResponse[SystemLoginUserPublicKeysState], error) {
	if req.DryRun {
		return infer.CreateResponse[SystemLoginUserPublicKeysState]{
			ID:     req.Inputs.Name,
			Output: SystemLoginUserPublicKeysState{SystemLoginUserPublicKeysArgs: req.Inputs},
		}, nil
	}

	ops := buildSystemLoginUserPublicKeysOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[SystemLoginUserPublicKeysState]{},
			fmt.Errorf("configure SystemLoginUserPublicKeys %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[SystemLoginUserPublicKeysState]{
		ID:     req.Inputs.Name,
		Output: SystemLoginUserPublicKeysState{SystemLoginUserPublicKeysArgs: req.Inputs},
	}, nil
}

// Read fetches the current SystemLoginUserPublicKeys config from VyOS.
func (SystemLoginUserPublicKeys) Read(
	ctx context.Context,
	req infer.ReadRequest[SystemLoginUserPublicKeysArgs, SystemLoginUserPublicKeysState],
) (infer.ReadResponse[SystemLoginUserPublicKeysArgs, SystemLoginUserPublicKeysState], error) {
	client := getClient(ctx)
	base := systemLoginUserPublicKeysBasePath(req.State.UserName, req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := SystemLoginUserPublicKeysArgs{UserName: req.State.UserName, Name: req.State.Name}
			state := SystemLoginUserPublicKeysState{SystemLoginUserPublicKeysArgs: args}
			return infer.ReadResponse[SystemLoginUserPublicKeysArgs, SystemLoginUserPublicKeysState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[SystemLoginUserPublicKeysArgs, SystemLoginUserPublicKeysState]{},
			fmt.Errorf("read SystemLoginUserPublicKeys %s: %w", req.State.Name, err)
	}

	args, err := parseSystemLoginUserPublicKeysConfig(req.State.UserName, req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[SystemLoginUserPublicKeysArgs, SystemLoginUserPublicKeysState]{},
			fmt.Errorf("parse SystemLoginUserPublicKeys %s config: %w", req.State.Name, err)
	}

	state := SystemLoginUserPublicKeysState{SystemLoginUserPublicKeysArgs: args}
	return infer.ReadResponse[SystemLoginUserPublicKeysArgs, SystemLoginUserPublicKeysState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing SystemLoginUserPublicKeys configuration.
func (SystemLoginUserPublicKeys) Update(
	ctx context.Context,
	req infer.UpdateRequest[SystemLoginUserPublicKeysArgs, SystemLoginUserPublicKeysState],
) (infer.UpdateResponse[SystemLoginUserPublicKeysState], error) {
	if req.DryRun {
		return infer.UpdateResponse[SystemLoginUserPublicKeysState]{
			Output: SystemLoginUserPublicKeysState{SystemLoginUserPublicKeysArgs: req.Inputs},
		}, nil
	}

	ops := buildSystemLoginUserPublicKeysUpdateOps(req.State.SystemLoginUserPublicKeysArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[SystemLoginUserPublicKeysState]{},
				fmt.Errorf("update SystemLoginUserPublicKeys %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[SystemLoginUserPublicKeysState]{
		Output: SystemLoginUserPublicKeysState{SystemLoginUserPublicKeysArgs: req.Inputs},
	}, nil
}

// Delete removes the SystemLoginUserPublicKeys configuration from VyOS.
func (SystemLoginUserPublicKeys) Delete(
	ctx context.Context,
	req infer.DeleteRequest[SystemLoginUserPublicKeysState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := systemLoginUserPublicKeysBasePath(req.State.UserName, req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete SystemLoginUserPublicKeys %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildSystemLoginUserPublicKeysOps builds set operations for all non-nil fields.
func buildSystemLoginUserPublicKeysOps(args SystemLoginUserPublicKeysArgs) []vyosclient.Operation {
	base := systemLoginUserPublicKeysBasePath(args.UserName, args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}

	if args.Key != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "key"), Value: *args.Key})
	}

	if args.Options != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "options"), Value: *args.Options})
	}

	if args.Type != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "type"), Value: *args.Type})
	}

	return ops
}

// buildSystemLoginUserPublicKeysUpdateOps computes the diff between previous and current state.
func buildSystemLoginUserPublicKeysUpdateOps(prev, cur SystemLoginUserPublicKeysArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	base := systemLoginUserPublicKeysBasePath(cur.UserName, cur.Name)

	ops = append(ops, diffStringField(base, []string{"key"}, prev.Key, cur.Key)...)

	ops = append(ops, diffStringField(base, []string{"options"}, prev.Options, cur.Options)...)

	ops = append(ops, diffStringField(base, []string{"type"}, prev.Type, cur.Type)...)

	return ops
}

// parseSystemLoginUserPublicKeysConfig unmarshals VyOS ShowConfig JSON.
func parseSystemLoginUserPublicKeysConfig(userName, name string, data json.RawMessage) (SystemLoginUserPublicKeysArgs, error) {
	args := SystemLoginUserPublicKeysArgs{
		UserName: userName,
		Name:     name,
	}

	if v, ok := getNestedValue(data, []string{"key"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return SystemLoginUserPublicKeysArgs{}, fmt.Errorf("parse key: %w", err)
		}
		args.Key = &s
	}

	if v, ok := getNestedValue(data, []string{"options"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return SystemLoginUserPublicKeysArgs{}, fmt.Errorf("parse options: %w", err)
		}
		args.Options = &s
	}

	if v, ok := getNestedValue(data, []string{"type"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return SystemLoginUserPublicKeysArgs{}, fmt.Errorf("parse type: %w", err)
		}
		args.Type = &s
	}

	return args, nil
}
