// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
	"regexp"
)

// InterfaceMacsecPeer manages a VyOS InterfaceMacsecPeer configuration.
type InterfaceMacsecPeer struct{}

// InterfaceMacsecPeerArgs defines the inputs for the InterfaceMacsecPeer resource.
type InterfaceMacsecPeerArgs struct {
	MacsecName string  `pulumi:"macsecName"`
	Name       string  `pulumi:"name"`
	Disable    *bool   `pulumi:"disable,optional"`
	MAC        *string `pulumi:"mac,optional"`
	Key        *string `pulumi:"key,optional"`
}

// InterfaceMacsecPeerState defines the outputs for the InterfaceMacsecPeer resource.
type InterfaceMacsecPeerState struct {
	InterfaceMacsecPeerArgs
}

// Annotate provides schema metadata for the resource.
func (*InterfaceMacsecPeer) Annotate(a infer.Annotator) {
	a.Describe(new(InterfaceMacsecPeer), "Manages a VyOS MACsec peer name.")
}

// Annotate provides schema metadata for the inputs.
func (args *InterfaceMacsecPeerArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.MacsecName, "Parent tag node key")
	a.Describe(&args.Name, "MACsec peer name")
	a.Describe(&args.Disable, "Disable instance")
	a.Describe(&args.MAC, "Media Access Control (MAC) address")
	a.Describe(&args.Key, "MACsec static key")
}

var interfaceMacsecPeerKeyRe = regexp.MustCompile(`^(?:` + "[A-Fa-f0-9]{32}|[A-Fa-f0-9]{64}" + `)$`)

// Check validates the InterfaceMacsecPeer inputs.
func (InterfaceMacsecPeer) Check(
	ctx context.Context,
	req infer.CheckRequest,
) (infer.CheckResponse[InterfaceMacsecPeerArgs], error) {
	inputs, failures, err := infer.DefaultCheck[InterfaceMacsecPeerArgs](ctx, req.NewInputs)
	if err != nil {
		return infer.CheckResponse[InterfaceMacsecPeerArgs]{}, err
	}
	if inputs.Key != nil {
		if f := checkRegex(*inputs.Key, interfaceMacsecPeerKeyRe, "key", ""); f != nil {
			failures = append(failures, *f)
		}
	}

	return infer.CheckResponse[InterfaceMacsecPeerArgs]{Inputs: inputs, Failures: failures}, nil
}

func interfaceMacsecPeerBasePath(macsecName, name string) []any {
	return []any{"interfaces", "macsec", macsecName, "peer", name}
}

// Create sets up the InterfaceMacsecPeer on VyOS.
func (InterfaceMacsecPeer) Create(
	ctx context.Context,
	req infer.CreateRequest[InterfaceMacsecPeerArgs],
) (infer.CreateResponse[InterfaceMacsecPeerState], error) {
	if req.DryRun {
		return infer.CreateResponse[InterfaceMacsecPeerState]{
			ID:     req.Inputs.Name,
			Output: InterfaceMacsecPeerState{InterfaceMacsecPeerArgs: req.Inputs},
		}, nil
	}

	ops := buildInterfaceMacsecPeerOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[InterfaceMacsecPeerState]{},
			fmt.Errorf("configure InterfaceMacsecPeer %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[InterfaceMacsecPeerState]{
		ID:     req.Inputs.Name,
		Output: InterfaceMacsecPeerState{InterfaceMacsecPeerArgs: req.Inputs},
	}, nil
}

// Read fetches the current InterfaceMacsecPeer config from VyOS.
func (InterfaceMacsecPeer) Read(
	ctx context.Context,
	req infer.ReadRequest[InterfaceMacsecPeerArgs, InterfaceMacsecPeerState],
) (infer.ReadResponse[InterfaceMacsecPeerArgs, InterfaceMacsecPeerState], error) {
	client := getClient(ctx)
	base := interfaceMacsecPeerBasePath(req.State.MacsecName, req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := InterfaceMacsecPeerArgs{MacsecName: req.State.MacsecName, Name: req.State.Name}
			state := InterfaceMacsecPeerState{InterfaceMacsecPeerArgs: args}
			return infer.ReadResponse[InterfaceMacsecPeerArgs, InterfaceMacsecPeerState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[InterfaceMacsecPeerArgs, InterfaceMacsecPeerState]{},
			fmt.Errorf("read InterfaceMacsecPeer %s: %w", req.State.Name, err)
	}

	args, err := parseInterfaceMacsecPeerConfig(req.State.MacsecName, req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[InterfaceMacsecPeerArgs, InterfaceMacsecPeerState]{},
			fmt.Errorf("parse InterfaceMacsecPeer %s config: %w", req.State.Name, err)
	}

	state := InterfaceMacsecPeerState{InterfaceMacsecPeerArgs: args}
	return infer.ReadResponse[InterfaceMacsecPeerArgs, InterfaceMacsecPeerState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing InterfaceMacsecPeer configuration.
func (InterfaceMacsecPeer) Update(
	ctx context.Context,
	req infer.UpdateRequest[InterfaceMacsecPeerArgs, InterfaceMacsecPeerState],
) (infer.UpdateResponse[InterfaceMacsecPeerState], error) {
	if req.DryRun {
		return infer.UpdateResponse[InterfaceMacsecPeerState]{
			Output: InterfaceMacsecPeerState{InterfaceMacsecPeerArgs: req.Inputs},
		}, nil
	}

	ops := buildInterfaceMacsecPeerUpdateOps(req.State.InterfaceMacsecPeerArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[InterfaceMacsecPeerState]{},
				fmt.Errorf("update InterfaceMacsecPeer %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[InterfaceMacsecPeerState]{
		Output: InterfaceMacsecPeerState{InterfaceMacsecPeerArgs: req.Inputs},
	}, nil
}

// Delete removes the InterfaceMacsecPeer configuration from VyOS.
func (InterfaceMacsecPeer) Delete(
	ctx context.Context,
	req infer.DeleteRequest[InterfaceMacsecPeerState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := interfaceMacsecPeerBasePath(req.State.MacsecName, req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete InterfaceMacsecPeer %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildInterfaceMacsecPeerOps builds set operations for all non-nil fields.
func buildInterfaceMacsecPeerOps(args InterfaceMacsecPeerArgs) []vyosclient.Operation {
	base := interfaceMacsecPeerBasePath(args.MacsecName, args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}

	if args.Disable != nil && *args.Disable {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "disable")})
	}

	if args.MAC != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "mac"), Value: *args.MAC})
	}

	if args.Key != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "key"), Value: *args.Key})
	}

	return ops
}

// buildInterfaceMacsecPeerUpdateOps computes the diff between previous and current state.
func buildInterfaceMacsecPeerUpdateOps(prev, cur InterfaceMacsecPeerArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	base := interfaceMacsecPeerBasePath(cur.MacsecName, cur.Name)

	ops = append(ops, diffBoolField(base, []string{"disable"}, prev.Disable, cur.Disable)...)

	ops = append(ops, diffStringField(base, []string{"mac"}, prev.MAC, cur.MAC)...)

	ops = append(ops, diffStringField(base, []string{"key"}, prev.Key, cur.Key)...)

	return ops
}

// parseInterfaceMacsecPeerConfig unmarshals VyOS ShowConfig JSON.
func parseInterfaceMacsecPeerConfig(macsecName, name string, data json.RawMessage) (InterfaceMacsecPeerArgs, error) {
	args := InterfaceMacsecPeerArgs{
		MacsecName: macsecName,
		Name:       name,
	}

	if _, ok := getNestedValue(data, []string{"disable"}); ok {
		t := true
		args.Disable = &t
	}

	if v, ok := getNestedValue(data, []string{"mac"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return InterfaceMacsecPeerArgs{}, fmt.Errorf("parse mac: %w", err)
		}
		args.MAC = &s
	}

	if v, ok := getNestedValue(data, []string{"key"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return InterfaceMacsecPeerArgs{}, fmt.Errorf("parse key: %w", err)
		}
		args.Key = &s
	}

	return args, nil
}
