// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
	"regexp"
)

// PolicyRouteMap manages a VyOS PolicyRouteMap configuration.
type PolicyRouteMap struct{}

// PolicyRouteMapArgs defines the inputs for the PolicyRouteMap resource.
type PolicyRouteMapArgs struct {
	Name        string  `pulumi:"name"`
	Description *string `pulumi:"description,optional"`
}

// PolicyRouteMapState defines the outputs for the PolicyRouteMap resource.
type PolicyRouteMapState struct {
	PolicyRouteMapArgs
}

// Annotate provides schema metadata for the resource.
func (*PolicyRouteMap) Annotate(a infer.Annotator) {
	a.Describe(new(PolicyRouteMap), "Manages a VyOS IP route-map.")
}

// Annotate provides schema metadata for the inputs.
func (args *PolicyRouteMapArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.Name, "IP route-map")
	a.Describe(&args.Description, "Description")
}

var policyRouteMapNameRe = regexp.MustCompile(`^(?:` + "[-_a-zA-Z0-9][\\w\\-\\.\\+]*" + `)$`)
var policyRouteMapDescriptionRe = regexp.MustCompile(`^(?:` + ".{0,255}" + `)$`)

// Check validates the PolicyRouteMap inputs.
func (PolicyRouteMap) Check(
	ctx context.Context,
	req infer.CheckRequest,
) (infer.CheckResponse[PolicyRouteMapArgs], error) {
	inputs, failures, err := infer.DefaultCheck[PolicyRouteMapArgs](ctx, req.NewInputs)
	if err != nil {
		return infer.CheckResponse[PolicyRouteMapArgs]{}, err
	}
	if f := checkRegex(inputs.Name, policyRouteMapNameRe, "name", "Name of route-map can only contain alpha-numeric letters, hyphen and underscores"); f != nil {
		failures = append(failures, *f)
	}
	if inputs.Description != nil {
		if f := checkRegex(*inputs.Description, policyRouteMapDescriptionRe, "description", "Description too long (limit 255 characters)"); f != nil {
			failures = append(failures, *f)
		}
	}

	return infer.CheckResponse[PolicyRouteMapArgs]{Inputs: inputs, Failures: failures}, nil
}

func policyRouteMapBasePath(name string) []any {
	return []any{"policy", "route-map", name}
}

// Create sets up the PolicyRouteMap on VyOS.
func (PolicyRouteMap) Create(
	ctx context.Context,
	req infer.CreateRequest[PolicyRouteMapArgs],
) (infer.CreateResponse[PolicyRouteMapState], error) {
	if req.DryRun {
		return infer.CreateResponse[PolicyRouteMapState]{
			ID:     req.Inputs.Name,
			Output: PolicyRouteMapState{PolicyRouteMapArgs: req.Inputs},
		}, nil
	}

	ops := buildPolicyRouteMapOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[PolicyRouteMapState]{},
			fmt.Errorf("configure PolicyRouteMap %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[PolicyRouteMapState]{
		ID:     req.Inputs.Name,
		Output: PolicyRouteMapState{PolicyRouteMapArgs: req.Inputs},
	}, nil
}

// Read fetches the current PolicyRouteMap config from VyOS.
func (PolicyRouteMap) Read(
	ctx context.Context,
	req infer.ReadRequest[PolicyRouteMapArgs, PolicyRouteMapState],
) (infer.ReadResponse[PolicyRouteMapArgs, PolicyRouteMapState], error) {
	client := getClient(ctx)
	base := policyRouteMapBasePath(req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := PolicyRouteMapArgs{Name: req.State.Name}
			state := PolicyRouteMapState{PolicyRouteMapArgs: args}
			return infer.ReadResponse[PolicyRouteMapArgs, PolicyRouteMapState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[PolicyRouteMapArgs, PolicyRouteMapState]{},
			fmt.Errorf("read PolicyRouteMap %s: %w", req.State.Name, err)
	}

	args, err := parsePolicyRouteMapConfig(req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[PolicyRouteMapArgs, PolicyRouteMapState]{},
			fmt.Errorf("parse PolicyRouteMap %s config: %w", req.State.Name, err)
	}

	state := PolicyRouteMapState{PolicyRouteMapArgs: args}
	return infer.ReadResponse[PolicyRouteMapArgs, PolicyRouteMapState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing PolicyRouteMap configuration.
func (PolicyRouteMap) Update(
	ctx context.Context,
	req infer.UpdateRequest[PolicyRouteMapArgs, PolicyRouteMapState],
) (infer.UpdateResponse[PolicyRouteMapState], error) {
	if req.DryRun {
		return infer.UpdateResponse[PolicyRouteMapState]{
			Output: PolicyRouteMapState{PolicyRouteMapArgs: req.Inputs},
		}, nil
	}

	ops := buildPolicyRouteMapUpdateOps(req.State.PolicyRouteMapArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[PolicyRouteMapState]{},
				fmt.Errorf("update PolicyRouteMap %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[PolicyRouteMapState]{
		Output: PolicyRouteMapState{PolicyRouteMapArgs: req.Inputs},
	}, nil
}

// Delete removes the PolicyRouteMap configuration from VyOS.
func (PolicyRouteMap) Delete(
	ctx context.Context,
	req infer.DeleteRequest[PolicyRouteMapState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := policyRouteMapBasePath(req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete PolicyRouteMap %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildPolicyRouteMapOps builds set operations for all non-nil fields.
func buildPolicyRouteMapOps(args PolicyRouteMapArgs) []vyosclient.Operation {
	base := policyRouteMapBasePath(args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}

	if args.Description != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "description"), Value: *args.Description})
	}

	return ops
}

// buildPolicyRouteMapUpdateOps computes the diff between previous and current state.
func buildPolicyRouteMapUpdateOps(prev, cur PolicyRouteMapArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	base := policyRouteMapBasePath(cur.Name)

	ops = append(ops, diffStringField(base, []string{"description"}, prev.Description, cur.Description)...)

	return ops
}

// parsePolicyRouteMapConfig unmarshals VyOS ShowConfig JSON.
func parsePolicyRouteMapConfig(name string, data json.RawMessage) (PolicyRouteMapArgs, error) {
	args := PolicyRouteMapArgs{
		Name: name,
	}

	if v, ok := getNestedValue(data, []string{"description"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return PolicyRouteMapArgs{}, fmt.Errorf("parse description: %w", err)
		}
		args.Description = &s
	}

	return args, nil
}
