// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
	"regexp"
)

// ProtocolRIPInterface manages a VyOS ProtocolRIPInterface configuration.
type ProtocolRIPInterface struct{}

// ProtocolRIPInterfaceArgs defines the inputs for the ProtocolRIPInterface resource.
type ProtocolRIPInterfaceArgs struct {
	Name                            string  `pulumi:"name"`
	AuthenticationPlaintextPassword *string `pulumi:"authenticationPlaintextPassword,optional"`
	ReceiveVersion                  *string `pulumi:"receiveVersion,optional"`
	SendVersion                     *string `pulumi:"sendVersion,optional"`
}

// ProtocolRIPInterfaceState defines the outputs for the ProtocolRIPInterface resource.
type ProtocolRIPInterfaceState struct {
	ProtocolRIPInterfaceArgs
}

// Annotate provides schema metadata for the resource.
func (*ProtocolRIPInterface) Annotate(a infer.Annotator) {
	a.Describe(new(ProtocolRIPInterface), "Manages a VyOS .")
}

// Annotate provides schema metadata for the inputs.
func (args *ProtocolRIPInterfaceArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.Name, "")
	a.Describe(&args.AuthenticationPlaintextPassword, "Plain text password")
	a.Describe(&args.ReceiveVersion, "Limit RIP protocol version")
	a.Describe(&args.SendVersion, "Limit RIP protocol version")
}

var protocolRIPInterfaceAuthenticationPlaintextPasswordRe = regexp.MustCompile(`^(?:` + "[^[:space:]]{1,16}" + `)$`)

// Check validates the ProtocolRIPInterface inputs.
func (ProtocolRIPInterface) Check(
	ctx context.Context,
	req infer.CheckRequest,
) (infer.CheckResponse[ProtocolRIPInterfaceArgs], error) {
	inputs, failures, err := infer.DefaultCheck[ProtocolRIPInterfaceArgs](ctx, req.NewInputs)
	if err != nil {
		return infer.CheckResponse[ProtocolRIPInterfaceArgs]{}, err
	}
	if inputs.AuthenticationPlaintextPassword != nil {
		if f := checkRegex(*inputs.AuthenticationPlaintextPassword, protocolRIPInterfaceAuthenticationPlaintextPasswordRe, "authenticationPlaintextPassword", "Password must be 16 characters or less"); f != nil {
			failures = append(failures, *f)
		}
	}

	return infer.CheckResponse[ProtocolRIPInterfaceArgs]{Inputs: inputs, Failures: failures}, nil
}

func protocolRIPInterfaceBasePath(name string) []any {
	return []any{"protocols", "rip", "interface", name}
}

// Create sets up the ProtocolRIPInterface on VyOS.
func (ProtocolRIPInterface) Create(
	ctx context.Context,
	req infer.CreateRequest[ProtocolRIPInterfaceArgs],
) (infer.CreateResponse[ProtocolRIPInterfaceState], error) {
	if req.DryRun {
		return infer.CreateResponse[ProtocolRIPInterfaceState]{
			ID:     req.Inputs.Name,
			Output: ProtocolRIPInterfaceState{ProtocolRIPInterfaceArgs: req.Inputs},
		}, nil
	}

	ops := buildProtocolRIPInterfaceOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[ProtocolRIPInterfaceState]{},
			fmt.Errorf("configure ProtocolRIPInterface %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[ProtocolRIPInterfaceState]{
		ID:     req.Inputs.Name,
		Output: ProtocolRIPInterfaceState{ProtocolRIPInterfaceArgs: req.Inputs},
	}, nil
}

// Read fetches the current ProtocolRIPInterface config from VyOS.
func (ProtocolRIPInterface) Read(
	ctx context.Context,
	req infer.ReadRequest[ProtocolRIPInterfaceArgs, ProtocolRIPInterfaceState],
) (infer.ReadResponse[ProtocolRIPInterfaceArgs, ProtocolRIPInterfaceState], error) {
	client := getClient(ctx)
	base := protocolRIPInterfaceBasePath(req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := ProtocolRIPInterfaceArgs{Name: req.State.Name}
			state := ProtocolRIPInterfaceState{ProtocolRIPInterfaceArgs: args}
			return infer.ReadResponse[ProtocolRIPInterfaceArgs, ProtocolRIPInterfaceState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[ProtocolRIPInterfaceArgs, ProtocolRIPInterfaceState]{},
			fmt.Errorf("read ProtocolRIPInterface %s: %w", req.State.Name, err)
	}

	args, err := parseProtocolRIPInterfaceConfig(req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[ProtocolRIPInterfaceArgs, ProtocolRIPInterfaceState]{},
			fmt.Errorf("parse ProtocolRIPInterface %s config: %w", req.State.Name, err)
	}

	state := ProtocolRIPInterfaceState{ProtocolRIPInterfaceArgs: args}
	return infer.ReadResponse[ProtocolRIPInterfaceArgs, ProtocolRIPInterfaceState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing ProtocolRIPInterface configuration.
func (ProtocolRIPInterface) Update(
	ctx context.Context,
	req infer.UpdateRequest[ProtocolRIPInterfaceArgs, ProtocolRIPInterfaceState],
) (infer.UpdateResponse[ProtocolRIPInterfaceState], error) {
	if req.DryRun {
		return infer.UpdateResponse[ProtocolRIPInterfaceState]{
			Output: ProtocolRIPInterfaceState{ProtocolRIPInterfaceArgs: req.Inputs},
		}, nil
	}

	ops := buildProtocolRIPInterfaceUpdateOps(req.State.ProtocolRIPInterfaceArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[ProtocolRIPInterfaceState]{},
				fmt.Errorf("update ProtocolRIPInterface %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[ProtocolRIPInterfaceState]{
		Output: ProtocolRIPInterfaceState{ProtocolRIPInterfaceArgs: req.Inputs},
	}, nil
}

// Delete removes the ProtocolRIPInterface configuration from VyOS.
func (ProtocolRIPInterface) Delete(
	ctx context.Context,
	req infer.DeleteRequest[ProtocolRIPInterfaceState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := protocolRIPInterfaceBasePath(req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete ProtocolRIPInterface %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildProtocolRIPInterfaceOps builds set operations for all non-nil fields.
func buildProtocolRIPInterfaceOps(args ProtocolRIPInterfaceArgs) []vyosclient.Operation {
	base := protocolRIPInterfaceBasePath(args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}

	if args.AuthenticationPlaintextPassword != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "authentication", "plaintext-password"), Value: *args.AuthenticationPlaintextPassword})
	}

	if args.ReceiveVersion != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "receive", "version"), Value: *args.ReceiveVersion})
	}

	if args.SendVersion != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "send", "version"), Value: *args.SendVersion})
	}

	return ops
}

// buildProtocolRIPInterfaceUpdateOps computes the diff between previous and current state.
func buildProtocolRIPInterfaceUpdateOps(prev, cur ProtocolRIPInterfaceArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	base := protocolRIPInterfaceBasePath(cur.Name)

	ops = append(ops, diffStringField(base, []string{"authentication", "plaintext-password"}, prev.AuthenticationPlaintextPassword, cur.AuthenticationPlaintextPassword)...)

	ops = append(ops, diffStringField(base, []string{"receive", "version"}, prev.ReceiveVersion, cur.ReceiveVersion)...)

	ops = append(ops, diffStringField(base, []string{"send", "version"}, prev.SendVersion, cur.SendVersion)...)

	return ops
}

// parseProtocolRIPInterfaceConfig unmarshals VyOS ShowConfig JSON.
func parseProtocolRIPInterfaceConfig(name string, data json.RawMessage) (ProtocolRIPInterfaceArgs, error) {
	args := ProtocolRIPInterfaceArgs{
		Name: name,
	}

	if v, ok := getNestedValue(data, []string{"authentication", "plaintext-password"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return ProtocolRIPInterfaceArgs{}, fmt.Errorf("parse plaintext-password: %w", err)
		}
		args.AuthenticationPlaintextPassword = &s
	}

	if v, ok := getNestedValue(data, []string{"receive", "version"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return ProtocolRIPInterfaceArgs{}, fmt.Errorf("parse version: %w", err)
		}
		args.ReceiveVersion = &s
	}

	if v, ok := getNestedValue(data, []string{"send", "version"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return ProtocolRIPInterfaceArgs{}, fmt.Errorf("parse version: %w", err)
		}
		args.SendVersion = &s
	}

	return args, nil
}
