// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
	"regexp"
	"strconv"
)

// ProtocolRIPDistributeListInterface manages a VyOS ProtocolRIPDistributeListInterface configuration.
type ProtocolRIPDistributeListInterface struct{}

// ProtocolRIPDistributeListInterfaceArgs defines the inputs for the ProtocolRIPDistributeListInterface resource.
type ProtocolRIPDistributeListInterfaceArgs struct {
	Name          string  `pulumi:"name"`
	AccessListIn  *int    `pulumi:"accessListIn,optional"`
	AccessListOut *int    `pulumi:"accessListOut,optional"`
	PrefixListIn  *string `pulumi:"prefixListIn,optional"`
	PrefixListOut *string `pulumi:"prefixListOut,optional"`
}

// ProtocolRIPDistributeListInterfaceState defines the outputs for the ProtocolRIPDistributeListInterface resource.
type ProtocolRIPDistributeListInterfaceState struct {
	ProtocolRIPDistributeListInterfaceArgs
}

// Annotate provides schema metadata for the resource.
func (*ProtocolRIPDistributeListInterface) Annotate(a infer.Annotator) {
	a.Describe(new(ProtocolRIPDistributeListInterface), "Manages a VyOS Apply filtering to an interface.")
}

// Annotate provides schema metadata for the inputs.
func (args *ProtocolRIPDistributeListInterfaceArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.Name, "Apply filtering to an interface")
	a.Describe(&args.AccessListIn, "Access list to apply to input packets")
	a.Describe(&args.AccessListOut, "Access list to apply to output packets")
	a.Describe(&args.PrefixListIn, "Prefix-list to apply to input packets")
	a.Describe(&args.PrefixListOut, "Prefix-list to apply to output packets")
}

var protocolRIPDistributeListInterfaceNameRe = regexp.MustCompile(`^(?:` + "(bond|br|dum|en|ersp|eth|gnv|ifb|ipoe|lan|l2tp|l2tpeth|macsec|peth|ppp|pppoe|pptp|sstp|sstpc|tun|veth|vpptap|vpptun|vti|vtun|vxlan|wg|wlan|wwan)[0-9]+(.\\d+)?|pod-[-_a-zA-Z0-9]{1,11}|lo" + `)$`)

// Check validates the ProtocolRIPDistributeListInterface inputs.
func (ProtocolRIPDistributeListInterface) Check(
	ctx context.Context,
	req infer.CheckRequest,
) (infer.CheckResponse[ProtocolRIPDistributeListInterfaceArgs], error) {
	inputs, failures, err := infer.DefaultCheck[ProtocolRIPDistributeListInterfaceArgs](ctx, req.NewInputs)
	if err != nil {
		return infer.CheckResponse[ProtocolRIPDistributeListInterfaceArgs]{}, err
	}
	if f := checkRegex(inputs.Name, protocolRIPDistributeListInterfaceNameRe, "name", ""); f != nil {
		failures = append(failures, *f)
	}
	if inputs.AccessListIn != nil {
		if f := checkIntRange(int64(*inputs.AccessListIn), 0, 4294967295, "accessListIn", ""); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.AccessListOut != nil {
		if f := checkIntRange(int64(*inputs.AccessListOut), 0, 4294967295, "accessListOut", ""); f != nil {
			failures = append(failures, *f)
		}
	}

	return infer.CheckResponse[ProtocolRIPDistributeListInterfaceArgs]{Inputs: inputs, Failures: failures}, nil
}

func protocolRIPDistributeListInterfaceBasePath(name string) []any {
	return []any{"protocols", "rip", "distribute-list", "interface", name}
}

// Create sets up the ProtocolRIPDistributeListInterface on VyOS.
func (ProtocolRIPDistributeListInterface) Create(
	ctx context.Context,
	req infer.CreateRequest[ProtocolRIPDistributeListInterfaceArgs],
) (infer.CreateResponse[ProtocolRIPDistributeListInterfaceState], error) {
	if req.DryRun {
		return infer.CreateResponse[ProtocolRIPDistributeListInterfaceState]{
			ID:     req.Inputs.Name,
			Output: ProtocolRIPDistributeListInterfaceState{ProtocolRIPDistributeListInterfaceArgs: req.Inputs},
		}, nil
	}

	ops := buildProtocolRIPDistributeListInterfaceOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[ProtocolRIPDistributeListInterfaceState]{},
			fmt.Errorf("configure ProtocolRIPDistributeListInterface %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[ProtocolRIPDistributeListInterfaceState]{
		ID:     req.Inputs.Name,
		Output: ProtocolRIPDistributeListInterfaceState{ProtocolRIPDistributeListInterfaceArgs: req.Inputs},
	}, nil
}

// Read fetches the current ProtocolRIPDistributeListInterface config from VyOS.
func (ProtocolRIPDistributeListInterface) Read(
	ctx context.Context,
	req infer.ReadRequest[ProtocolRIPDistributeListInterfaceArgs, ProtocolRIPDistributeListInterfaceState],
) (infer.ReadResponse[ProtocolRIPDistributeListInterfaceArgs, ProtocolRIPDistributeListInterfaceState], error) {
	client := getClient(ctx)
	base := protocolRIPDistributeListInterfaceBasePath(req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := ProtocolRIPDistributeListInterfaceArgs{Name: req.State.Name}
			state := ProtocolRIPDistributeListInterfaceState{ProtocolRIPDistributeListInterfaceArgs: args}
			return infer.ReadResponse[ProtocolRIPDistributeListInterfaceArgs, ProtocolRIPDistributeListInterfaceState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[ProtocolRIPDistributeListInterfaceArgs, ProtocolRIPDistributeListInterfaceState]{},
			fmt.Errorf("read ProtocolRIPDistributeListInterface %s: %w", req.State.Name, err)
	}

	args, err := parseProtocolRIPDistributeListInterfaceConfig(req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[ProtocolRIPDistributeListInterfaceArgs, ProtocolRIPDistributeListInterfaceState]{},
			fmt.Errorf("parse ProtocolRIPDistributeListInterface %s config: %w", req.State.Name, err)
	}

	state := ProtocolRIPDistributeListInterfaceState{ProtocolRIPDistributeListInterfaceArgs: args}
	return infer.ReadResponse[ProtocolRIPDistributeListInterfaceArgs, ProtocolRIPDistributeListInterfaceState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing ProtocolRIPDistributeListInterface configuration.
func (ProtocolRIPDistributeListInterface) Update(
	ctx context.Context,
	req infer.UpdateRequest[ProtocolRIPDistributeListInterfaceArgs, ProtocolRIPDistributeListInterfaceState],
) (infer.UpdateResponse[ProtocolRIPDistributeListInterfaceState], error) {
	if req.DryRun {
		return infer.UpdateResponse[ProtocolRIPDistributeListInterfaceState]{
			Output: ProtocolRIPDistributeListInterfaceState{ProtocolRIPDistributeListInterfaceArgs: req.Inputs},
		}, nil
	}

	ops := buildProtocolRIPDistributeListInterfaceUpdateOps(req.State.ProtocolRIPDistributeListInterfaceArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[ProtocolRIPDistributeListInterfaceState]{},
				fmt.Errorf("update ProtocolRIPDistributeListInterface %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[ProtocolRIPDistributeListInterfaceState]{
		Output: ProtocolRIPDistributeListInterfaceState{ProtocolRIPDistributeListInterfaceArgs: req.Inputs},
	}, nil
}

// Delete removes the ProtocolRIPDistributeListInterface configuration from VyOS.
func (ProtocolRIPDistributeListInterface) Delete(
	ctx context.Context,
	req infer.DeleteRequest[ProtocolRIPDistributeListInterfaceState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := protocolRIPDistributeListInterfaceBasePath(req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete ProtocolRIPDistributeListInterface %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildProtocolRIPDistributeListInterfaceOps builds set operations for all non-nil fields.
func buildProtocolRIPDistributeListInterfaceOps(args ProtocolRIPDistributeListInterfaceArgs) []vyosclient.Operation {
	base := protocolRIPDistributeListInterfaceBasePath(args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}

	if args.AccessListIn != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "access-list", "in"), Value: strconv.Itoa(*args.AccessListIn)})
	}

	if args.AccessListOut != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "access-list", "out"), Value: strconv.Itoa(*args.AccessListOut)})
	}

	if args.PrefixListIn != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "prefix-list", "in"), Value: *args.PrefixListIn})
	}

	if args.PrefixListOut != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "prefix-list", "out"), Value: *args.PrefixListOut})
	}

	return ops
}

// buildProtocolRIPDistributeListInterfaceUpdateOps computes the diff between previous and current state.
func buildProtocolRIPDistributeListInterfaceUpdateOps(prev, cur ProtocolRIPDistributeListInterfaceArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	base := protocolRIPDistributeListInterfaceBasePath(cur.Name)

	ops = append(ops, diffIntField(base, []string{"access-list", "in"}, prev.AccessListIn, cur.AccessListIn)...)

	ops = append(ops, diffIntField(base, []string{"access-list", "out"}, prev.AccessListOut, cur.AccessListOut)...)

	ops = append(ops, diffStringField(base, []string{"prefix-list", "in"}, prev.PrefixListIn, cur.PrefixListIn)...)

	ops = append(ops, diffStringField(base, []string{"prefix-list", "out"}, prev.PrefixListOut, cur.PrefixListOut)...)

	return ops
}

// parseProtocolRIPDistributeListInterfaceConfig unmarshals VyOS ShowConfig JSON.
func parseProtocolRIPDistributeListInterfaceConfig(name string, data json.RawMessage) (ProtocolRIPDistributeListInterfaceArgs, error) {
	args := ProtocolRIPDistributeListInterfaceArgs{
		Name: name,
	}

	if v, ok := getNestedValue(data, []string{"access-list", "in"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return ProtocolRIPDistributeListInterfaceArgs{}, fmt.Errorf("parse in: %w", err)
		}
		args.AccessListIn = &n
	}

	if v, ok := getNestedValue(data, []string{"access-list", "out"}); ok {
		n, err := parseIntFromJSON(v)
		if err != nil {
			return ProtocolRIPDistributeListInterfaceArgs{}, fmt.Errorf("parse out: %w", err)
		}
		args.AccessListOut = &n
	}

	if v, ok := getNestedValue(data, []string{"prefix-list", "in"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return ProtocolRIPDistributeListInterfaceArgs{}, fmt.Errorf("parse in: %w", err)
		}
		args.PrefixListIn = &s
	}

	if v, ok := getNestedValue(data, []string{"prefix-list", "out"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return ProtocolRIPDistributeListInterfaceArgs{}, fmt.Errorf("parse out: %w", err)
		}
		args.PrefixListOut = &s
	}

	return args, nil
}
