// Code generated by pulumi-vyos codegen. DO NOT EDIT. Regenerate with: make generate

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jaydoubleu/pulumi-vyos/provider/vyosclient"
	"github.com/pulumi/pulumi-go-provider/infer"
	"regexp"
)

// NATCgnatRule manages a VyOS NATCgnatRule configuration.
type NATCgnatRule struct{}

// NATCgnatRuleArgs defines the inputs for the NATCgnatRule resource.
type NATCgnatRuleArgs struct {
	Name            string  `pulumi:"name"`
	SourcePool      *string `pulumi:"sourcePool,optional"`
	TranslationPool *string `pulumi:"translationPool,optional"`
}

// NATCgnatRuleState defines the outputs for the NATCgnatRule resource.
type NATCgnatRuleState struct {
	NATCgnatRuleArgs
}

// Annotate provides schema metadata for the resource.
func (*NATCgnatRule) Annotate(a infer.Annotator) {
	a.Describe(new(NATCgnatRule), "Manages a VyOS Rule.")
}

// Annotate provides schema metadata for the inputs.
func (args *NATCgnatRuleArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.Name, "Rule")
	a.Describe(&args.SourcePool, "Source internal pool")
	a.Describe(&args.TranslationPool, "Translation external pool")
}

var natCgnatRuleSourcePoolRe = regexp.MustCompile(`^(?:` + "[-_a-zA-Z0-9][\\w\\-\\.\\+]*" + `)$`)
var natCgnatRuleTranslationPoolRe = regexp.MustCompile(`^(?:` + "[-_a-zA-Z0-9][\\w\\-\\.\\+]*" + `)$`)

// Check validates the NATCgnatRule inputs.
func (NATCgnatRule) Check(
	ctx context.Context,
	req infer.CheckRequest,
) (infer.CheckResponse[NATCgnatRuleArgs], error) {
	inputs, failures, err := infer.DefaultCheck[NATCgnatRuleArgs](ctx, req.NewInputs)
	if err != nil {
		return infer.CheckResponse[NATCgnatRuleArgs]{}, err
	}
	if inputs.SourcePool != nil {
		if f := checkRegex(*inputs.SourcePool, natCgnatRuleSourcePoolRe, "sourcePool", "Name of pool can only contain alpha-numeric letters, hyphen and underscores"); f != nil {
			failures = append(failures, *f)
		}
	}
	if inputs.TranslationPool != nil {
		if f := checkRegex(*inputs.TranslationPool, natCgnatRuleTranslationPoolRe, "translationPool", "Name of pool can only contain alpha-numeric letters, hyphen and underscores"); f != nil {
			failures = append(failures, *f)
		}
	}

	return infer.CheckResponse[NATCgnatRuleArgs]{Inputs: inputs, Failures: failures}, nil
}

func natCgnatRuleBasePath(name string) []any {
	return []any{"nat", "cgnat", "rule", name}
}

// Create sets up the NATCgnatRule on VyOS.
func (NATCgnatRule) Create(
	ctx context.Context,
	req infer.CreateRequest[NATCgnatRuleArgs],
) (infer.CreateResponse[NATCgnatRuleState], error) {
	if req.DryRun {
		return infer.CreateResponse[NATCgnatRuleState]{
			ID:     req.Inputs.Name,
			Output: NATCgnatRuleState{NATCgnatRuleArgs: req.Inputs},
		}, nil
	}

	ops := buildNATCgnatRuleOps(req.Inputs)
	client := getClient(ctx)
	if err := client.BatchConfigure(ctx, ops); err != nil {
		return infer.CreateResponse[NATCgnatRuleState]{},
			fmt.Errorf("configure NATCgnatRule %s: %w", req.Inputs.Name, err)
	}
	saveIfEnabled(ctx)

	return infer.CreateResponse[NATCgnatRuleState]{
		ID:     req.Inputs.Name,
		Output: NATCgnatRuleState{NATCgnatRuleArgs: req.Inputs},
	}, nil
}

// Read fetches the current NATCgnatRule config from VyOS.
func (NATCgnatRule) Read(
	ctx context.Context,
	req infer.ReadRequest[NATCgnatRuleArgs, NATCgnatRuleState],
) (infer.ReadResponse[NATCgnatRuleArgs, NATCgnatRuleState], error) {
	client := getClient(ctx)
	base := natCgnatRuleBasePath(req.State.Name)

	data, err := client.ShowConfig(ctx, pathToStrings(base))
	if err != nil {
		if isEmptyConfigError(err) {
			// Tag node exists but has no child properties. Return minimal state.
			args := NATCgnatRuleArgs{Name: req.State.Name}
			state := NATCgnatRuleState{NATCgnatRuleArgs: args}
			return infer.ReadResponse[NATCgnatRuleArgs, NATCgnatRuleState]{
				ID:     req.State.Name,
				Inputs: args,
				State:  state,
			}, nil
		}
		return infer.ReadResponse[NATCgnatRuleArgs, NATCgnatRuleState]{},
			fmt.Errorf("read NATCgnatRule %s: %w", req.State.Name, err)
	}

	args, err := parseNATCgnatRuleConfig(req.State.Name, data)
	if err != nil {
		return infer.ReadResponse[NATCgnatRuleArgs, NATCgnatRuleState]{},
			fmt.Errorf("parse NATCgnatRule %s config: %w", req.State.Name, err)
	}

	state := NATCgnatRuleState{NATCgnatRuleArgs: args}
	return infer.ReadResponse[NATCgnatRuleArgs, NATCgnatRuleState]{
		ID:     req.State.Name,
		Inputs: args,
		State:  state,
	}, nil
}

// Update modifies an existing NATCgnatRule configuration.
func (NATCgnatRule) Update(
	ctx context.Context,
	req infer.UpdateRequest[NATCgnatRuleArgs, NATCgnatRuleState],
) (infer.UpdateResponse[NATCgnatRuleState], error) {
	if req.DryRun {
		return infer.UpdateResponse[NATCgnatRuleState]{
			Output: NATCgnatRuleState{NATCgnatRuleArgs: req.Inputs},
		}, nil
	}

	ops := buildNATCgnatRuleUpdateOps(req.State.NATCgnatRuleArgs, req.Inputs)
	if len(ops) > 0 {
		client := getClient(ctx)
		if err := client.BatchConfigure(ctx, ops); err != nil {
			return infer.UpdateResponse[NATCgnatRuleState]{},
				fmt.Errorf("update NATCgnatRule %s: %w", req.Inputs.Name, err)
		}
		saveIfEnabled(ctx)
	}

	return infer.UpdateResponse[NATCgnatRuleState]{
		Output: NATCgnatRuleState{NATCgnatRuleArgs: req.Inputs},
	}, nil
}

// Delete removes the NATCgnatRule configuration from VyOS.
func (NATCgnatRule) Delete(
	ctx context.Context,
	req infer.DeleteRequest[NATCgnatRuleState],
) (infer.DeleteResponse, error) {
	client := getClient(ctx)
	base := natCgnatRuleBasePath(req.State.Name)
	if err := client.Delete(ctx, pathToStrings(base)); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("delete NATCgnatRule %s: %w", req.State.Name, err)
	}
	saveIfEnabled(ctx)
	return infer.DeleteResponse{}, nil
}

// buildNATCgnatRuleOps builds set operations for all non-nil fields.
func buildNATCgnatRuleOps(args NATCgnatRuleArgs) []vyosclient.Operation {
	base := natCgnatRuleBasePath(args.Name)
	ops := []vyosclient.Operation{
		{Op: "set", Path: base},
	}

	if args.SourcePool != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "source", "pool"), Value: *args.SourcePool})
	}

	if args.TranslationPool != nil {
		ops = append(ops, vyosclient.Operation{Op: "set", Path: appendPath(base, "translation", "pool"), Value: *args.TranslationPool})
	}

	return ops
}

// buildNATCgnatRuleUpdateOps computes the diff between previous and current state.
func buildNATCgnatRuleUpdateOps(prev, cur NATCgnatRuleArgs) []vyosclient.Operation {
	var ops []vyosclient.Operation
	base := natCgnatRuleBasePath(cur.Name)

	ops = append(ops, diffStringField(base, []string{"source", "pool"}, prev.SourcePool, cur.SourcePool)...)

	ops = append(ops, diffStringField(base, []string{"translation", "pool"}, prev.TranslationPool, cur.TranslationPool)...)

	return ops
}

// parseNATCgnatRuleConfig unmarshals VyOS ShowConfig JSON.
func parseNATCgnatRuleConfig(name string, data json.RawMessage) (NATCgnatRuleArgs, error) {
	args := NATCgnatRuleArgs{
		Name: name,
	}

	if v, ok := getNestedValue(data, []string{"source", "pool"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return NATCgnatRuleArgs{}, fmt.Errorf("parse pool: %w", err)
		}
		args.SourcePool = &s
	}

	if v, ok := getNestedValue(data, []string{"translation", "pool"}); ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return NATCgnatRuleArgs{}, fmt.Errorf("parse pool: %w", err)
		}
		args.TranslationPool = &s
	}

	return args, nil
}
